// ═══════════════════════════════════════════════════════════
//  Confettis & Cake — Crémaillère / Premier appart / Coloc
// ═══════════════════════════════════════════════════════════

export interface CremaillereMessage {
  id: string;
  text: string;
}

export interface CremaillereSubGroup {
  id: string;
  title: string;
  emoji: string;
  messages: CremaillereMessage[];
}

// ── S1 : Bienvenue chez toi — c'est officiel ─────────────
const S1: CremaillereMessage[] = [
  { id: 'cr_s1_001', text: `"Bienvenue chez toi. C'est officiel. T'as un chez-toi."\nPas chez tes parents. Pas chez quelqu'un d'autre. Chez toi. Avec ton nom sur la boîte aux lettres. Avec tes clés. Avec tes trucs dedans. Cette réalité-là elle est nouvelle. Elle est concrète. Elle est à toi. Bienvenue, [Prénom].\nAvec solennité appropriée pour l'officialisation de ton chez-toi,\n— quelqu'un qui pense que ce moment mérite d'être reconnu pour ce qu'il est 🔑` },
  { id: 'cr_s1_002', text: `"T'as un appart. C'est ton espace. Personne peut t'en déloger."\nEnfin légalement. Avec un bail. Avec des droits. Cet espace est le tien. Tu décides de la déco. De l'organisation. Des horaires. De qui entre et qui n'entre pas. Cette souveraineté-là c'est quelque chose. Bienvenue chez toi, [Prénom].\nAvec célébration de ta souveraineté nouvellement acquise sur ton espace,\n— quelqu'un qui pense que la souveraineté sur son espace est une des meilleures choses de la vie adulte 🏛️` },
  { id: 'cr_s1_003', text: `"Félicitations pour le nouvel appart. T'as trouvé un endroit qui va devenir toi."\nLes murs vont absorber ta façon d'être. L'espace va se configurer selon toi. Les habitudes vont s'installer. Les souvenirs vont s'accumuler. Cet appart va progressivement devenir l'extension de ta personnalité. C'est un processus beau. Bienvenue, [Prénom].\nAvec perspective sur le processus par lequel un appart devient progressivement soi,\n— quelqu'un qui est curieux de voir ce que tu vas faire de cet espace 🎨` },
  { id: 'cr_s1_004', text: `"T'as un chez-toi. C'est le plus beau mot de la langue française."\nChez toi. Deux mots. Qui contiennent tout. La sécurité. La liberté. L'appartenance. L'intimité. Le refuge. Ces deux mots sont maintenant les tiens dans un sens concret et légal. Bienvenue chez toi, [Prénom].\nAvec déclaration que chez toi est le plus beau mot et justification de cette position,\n— quelqu'un qui pense que rien ne vaut le sentiment d'avoir un chez-soi 🏠` },
  { id: 'cr_s1_005', text: `"Bienvenue chez toi. Là où tu peux être exactement toi sans explication."\nSans avoir à justifier tes horaires. Tes habitudes. Ta façon de ranger ou de pas ranger. Ta musique. Ton désordre ou ton ordre. Chez toi t'es toi sans avoir à négocier. Cette liberté-là est précieuse. Bienvenue, [Prénom].\nAvec célébration de la liberté d'être soi sans explication dans son propre espace,\n— quelqu'un qui pense que cette liberté est une des grandes joies de la vie adulte 🌿` },
  { id: 'cr_s1_006', text: `"T'as des clés. Ces clés ouvrent quelque chose qui t'appartient. C'est pas rien."\nCes clés. Ce métal. Ce truc qu'on porte dans sa poche. Qui ouvre une porte. Qui mène à un espace. Qui est à toi. Ces clés sont un symbole. Elles disent que t'as un endroit sur terre qui est le tien. Bienvenue chez toi, [Prénom].\nAvec éloge des clés comme symbole de l'appartenance à un espace,\n— quelqu'un qui pense que les clés d'un premier appart méritent d'être reconnues pour ce qu'elles représentent 🗝️` },
  { id: 'cr_s1_007', text: `"Félicitations pour le nouvel espace. Et bienvenue dans la version de toi qui a son propre espace."\nParce que cette version est différente. Avoir son propre espace change quelque chose. Dans la façon d'être. De se voir. De se projeter. Tu vas découvrir des trucs sur toi que t'aurais pas découverts autrement. Bienvenue, [Prénom].\nAvec anticipation des découvertes sur soi que l'espace propre va permettre,\n— quelqu'un qui est impatient de voir qui tu vas devenir dans cet espace 🔭` },
  { id: 'cr_s1_008', text: `"T'as un chez-toi. Maintenant tu peux inviter les gens chez toi."\nCe truc simple. Pouvoir dire viens chez moi. Et que chez moi ça veuille dire quelque chose de précis. Un endroit. Ton endroit. Avec ta porte. Ta cuisine. Ton canapé. Cette capacité à accueillir dans son propre espace c'est une forme de maturité. Bienvenue chez toi, [Prénom].\nAvec identification de la capacité à accueillir chez soi comme marqueur de maturité,\n— quelqu'un qui attend l'invitation avec impatience 🎉` },
  { id: 'cr_s1_009', text: `"Bienvenue chez toi. L'endroit où tout commence et où tout revient."\nLes matins qui commencent là. Les soirs qui finissent là. Les retours après des journées difficiles. Les retrouvailles avec soi-même. Ton chez-toi va devenir l'ancre de ta vie. Le point fixe autour duquel tout s'organise. Bienvenue, [Prénom].\nAvec perspective sur le rôle central que va jouer ton chez-toi dans ta vie,\n— quelqu'un qui pense que l'ancre d'une vie mérite d'être bien choisie 🌊` },
  { id: 'cr_s1_010', text: `"T'as un appart. T'as un chez-toi. T'as un endroit sur terre qui est le tien."\nUn endroit sur cette planète. Parmi tous les endroits possibles. Celui-là est le tien. Avec ton adresse. Ton nom dessus. Ta vie dedans. Cette réalité géographique et affective à la fois. Bienvenue chez toi, [Prénom].\nAvec mise en perspective géographique et affective de ton chez-toi,\n— quelqu'un qui pense que tout le monde mérite un endroit qui est le sien 🌍` },
  { id: 'cr_s1_011', text: `"Félicitations. Ton appart va voir ta vie se construire."\nLes matins difficiles. Les soirées réussies. Les périodes de doute. Les moments de fierté. Les amitiés qui se renforcent. Les projets qui se concrétisent. Tout ça va se passer là. Dans cet espace. Qui va tout absorber. Bienvenue, [Prénom].\nAvec anticipation de tout ce que ton appart va voir se construire,\n— quelqu'un qui espère être invité à certains de ces moments 🌱` },
  { id: 'cr_s1_012', text: `"T'as un chez-toi. Maintenant t'as un refuge."\nUn endroit où aller quand ça va pas. Où fermer la porte sur le reste. Où reprendre son souffle. Où se reconstruire entre deux rounds. Ce refuge-là il est à toi. Tu peux y aller quand tu veux. T'en avais peut-être besoin depuis longtemps. Bienvenue chez toi, [Prénom].\nAvec reconnaissance de la valeur du refuge que représente un chez-soi,\n— quelqu'un qui pense que tout le monde a besoin d'un endroit où fermer la porte sur le reste 🚪` },
  { id: 'cr_s1_013', text: `"Bienvenue chez toi. Là où tes règles s'appliquent."\nTes règles. Sur les horaires. Sur le bruit. Sur la propreté ou son absence. Sur les gens qu'on invite. Sur la façon de vivre l'espace. Ces règles sont les tiennes. Personne d'autre les définit. T'as cette souveraineté. Bienvenue, [Prénom].\nAvec célébration de ta souveraineté réglementaire dans ton propre espace,\n— quelqu'un qui espère que tes règles sont raisonnables si il vient te rendre visite 😄` },
  { id: 'cr_s1_014', text: `"T'as un appart. C'est ton territoire. Définis-le à ton image."\nLa déco. L'organisation. Les odeurs. La lumière. L'atmosphère. Tout ça tu peux le définir. L'ajuster. Le changer. Le faire évoluer. Jusqu'à ce que l'espace te ressemble vraiment. Jusqu'à ce qu'un étranger qui entre comprenne quelque chose sur toi. Bienvenue, [Prénom].\nAvec invitation à définir ton territoire à ton image,\n— quelqu'un qui est curieux de voir l'image que tu vas choisir 🖼️` },
  { id: 'cr_s1_015', text: `"Félicitations pour le nouvel appart. Et pour tout ce qu'il représente."\nL'indépendance. La responsabilité. La liberté. La charge aussi. Le loyer. Les charges. Les trucs à gérer. Le tout ensemble. Ce tout c'est la vie adulte dans ton propre espace. Et tu l'as choisi. Bienvenue dedans, [Prénom].\nAvec reconnaissance de tout ce que l'appart représente au-delà des murs,\n— quelqu'un qui sait que le tout c'est beaucoup et qui te félicite d'y être entré 🌟` },
  { id: 'cr_s1_016', text: `"Bienvenue chez toi. L'endroit où tu vas apprendre à te connaître autrement."\nVivre seul ou avec des gens qu'on a choisis. Ça apprend des trucs. Sur ses habitudes. Ses besoins. Ses limites. Sa façon d'occuper l'espace. Ses rituels. Ses inconforts. Ton appart va être un miroir particulier. Bienvenue, [Prénom].\nAvec anticipation de ce que ton appart va t'apprendre sur toi-même,\n— quelqu'un qui pense que vivre dans son propre espace est une des meilleures formations qui soit 🪞` },
  { id: 'cr_s1_017', text: `"T'as un chez-toi. C'est officiel. Et c'est mérité."\nT'as travaillé pour ça. T'as cherché. T'as visité. T'as signé. T'as organisé. T'as porté des cartons peut-être. T'as mis de l'énergie pour que cet espace devienne le tien. Ce chez-toi est mérité. Bienvenue, [Prénom].\nAvec reconnaissance que ce chez-toi est le résultat d'un effort réel,\n— quelqu'un qui sait que rien n'arrive tout seul et qui salue ton effort 💪` },
  { id: 'cr_s1_018', text: `"Félicitations pour le nouvel espace. Fais-en quelque chose qui te ressemble."\nPas quelque chose de parfait pour Instagram. Quelque chose de vrai pour toi. Confortable pour toi. Fonctionnel pour toi. Beau selon tes critères à toi. L'espace est une extension de soi. Fais-en une bonne extension. Bienvenue, [Prénom].\nAvec conseil amical de faire de l'espace quelque chose de vrai plutôt que de parfait,\n— quelqu'un qui pense que l'authenticité de son espace dit beaucoup sur soi 🎨` },
  { id: 'cr_s1_019', text: `"Bienvenue chez toi. Les meilleures choses vont se passer là."\nPas toutes. Certaines choses se passeront dehors. Dans le monde. Dans les voyages. Dans les aventures. Mais certaines des meilleures. Les soirées qui finissent tard. Les conversations importantes. Les matins lents. Les moments de paix. Ces choses-là vont se passer chez toi. Bienvenue, [Prénom].\nAvec perspective sur les meilleures choses qui vont se passer dans cet espace,\n— quelqu'un qui espère être présent pour certaines d'entre elles 🌟` },
  { id: 'cr_s1_020', text: `"T'as un chez-toi. Bienvenue dedans. Et bienvenue dans cette version de ta vie."\nCette version. Avec un chez-toi. Avec des clés. Avec un espace qui est le tien. Cette version est différente. Elle est plus grande. Plus responsable. Plus libre aussi. Bienvenue dans cette version, [Prénom].\nAvec accueil solennel dans cette nouvelle version de ta vie avec un chez-toi,\n— quelqu'un qui pense que cette version est une des meilleures qui soit ❤️` },
];

// ── S2 : T'as un appart et c'est chelou et bien en même temps ────────────────
const S2: CremaillereMessage[] = [
  { id: 'cr_s2_001', text: `"T'as un appart. C'est chelou. C'est bien. Les deux en même temps."\nChelou parce que c'est nouveau. Chelou parce que c'est réel. Chelou parce que y'a ton nom sur un bail et des charges à payer et des trucs à gérer. Et bien parce que c'est à toi. Et bien parce que c'est la liberté. Et bien parce que tu l'as voulu et tu l'as. Bienvenue, [Prénom].\nAvec validation de la chelou-ité et de la bien-ité simultanées de ce moment,\n— quelqu'un qui confirme que les deux coexistent et que c'est normal 🌀` },
  { id: 'cr_s2_002', text: `"C'est chelou d'avoir son propre appart. Et c'est une des meilleures chelou-ités qui soit."\nParmi les trucs chelous de la vie adulte. Avoir son propre appart c'est dans la catégorie des bons chelous. Pas le chelou stressant. Le chelou satisfaisant. Celui qui donne envie de regarder autour de soi et de se dire vraiment c'est à moi. Bienvenue, [Prénom].\nAvec classement de ce chelou dans la catégorie des meilleurs,\n— quelqu'un qui pense que le bon chelou mérite d'être savouré 😄` },
  { id: 'cr_s2_003', text: `"T'as signé un bail. C'est chelou d'avoir signé un bail. Et c'est bien d'avoir signé un bail."\nCe document. Ces pages. Ta signature. Qui dit que cet espace est le tien pour une durée déterminée. Chelou parce que c'est un engagement. Bien parce que c'est une fondation. Les deux à la fois. Bienvenue, [Prénom].\nAvec reconnaissance de la double nature du bail comme chelou et bien simultanément,\n— quelqu'un qui pense que les engagements qui font un peu peur sont souvent les meilleurs 📄` },
  { id: 'cr_s2_004', text: `"C'est chelou de rentrer chez soi dans un endroit qu'on connaît pas encore."\nLes premiers jours. Où l'espace est encore inconnu. Où on cherche l'interrupteur. Où les bruits sont nouveaux. Où l'appart sent différemment. Et progressivement il devient familier. Il devient chez soi. Bienvenue dans ce processus, [Prénom].\nAvec description du processus de familiarisation avec un nouveau chez-soi,\n— quelqu'un qui sait que ce processus est court et que l'appart deviendra vite vraiment chez toi 🏠` },
  { id: 'cr_s2_005', text: `"T'as un appart. C'est chelou d'avoir à gérer tout ça. Et c'est bien d'être celui qui gère."\nLes courses. Le ménage. Les charges. Les trucs qui marchent pas. Les voisins. Tout ça c'est à toi maintenant. C'est chelou parce que c'est beaucoup. C'est bien parce que c'est toi qui décides comment tout ça se gère. Bienvenue dans la gestion, [Prénom].\nAvec reconnaissance de la chelou-ité de la gestion et de la satisfaction d'en être le décideur,\n— quelqu'un qui sait que gérer son propre espace est épuisant et libérateur en même temps ⚖️` },
  { id: 'cr_s2_006', text: `"C'est chelou d'avoir une adresse qui est vraiment la sienne."\nCe truc. Ton adresse. Que tu peux donner. Qui existe sur une carte. Où des gens peuvent venir te voir. Où des lettres arrivent à ton nom. Cette adresse c'est ton ancrage géographique dans le monde. C'est chelou à réaliser. Et c'est bien. Bienvenue, [Prénom].\nAvec reconnaissance de la chelou-ité satisfaisante d'avoir une adresse qui est vraiment la sienne,\n— quelqu'un qui pense que l'adresse est une des choses les plus concrètes de l'identité adulte 📬` },
  { id: 'cr_s2_007', text: `"T'as un appart. C'est chelou de pas avoir quelqu'un qui vérifie si t'as rangé."\nCette liberté nouvelle. De laisser les trucs comme tu veux. De pas ranger si t'as pas envie. De ranger quand tu le décides. Sans regard extérieur. Sans commentaire. Sans attente. C'est chelou au début. Et puis c'est juste bien. Bienvenue, [Prénom].\nAvec célébration de la liberté de ranger ou pas ranger sans regard extérieur,\n— quelqu'un qui espère que t'en profiteras avec modération 😄` },
  { id: 'cr_s2_008', text: `"C'est chelou d'être responsable de son propre espace. Et c'est exactement ce qu'il fallait."\nCette responsabilité. De maintenir un espace. De le gérer. De prendre soin de ce qui est à toi. C'est chelou parce que c'est nouveau. Et c'est exactement ce qu'il te fallait pour cette étape. Bienvenue dedans, [Prénom].\nAvec identification de la responsabilité de son espace comme exactement ce qu'il fallait à ce stade,\n— quelqu'un qui pense que t'étais prêt pour ça même si tu sais pas encore 💪` },
  { id: 'cr_s2_009', text: `"T'as un appart. C'est chelou de décider de tout. C'est bien de décider de tout."\nLa température. La musique. Les horaires. Les invités. La déco. Les priorités. Tout. T'es le décideur de tout dans cet espace. C'est vertigineux. C'est exaltant. Les deux ensemble. Bienvenue dans le vertige exaltant, [Prénom].\nAvec description du vertige exaltant de décider de tout dans son propre espace,\n— quelqu'un qui pense que ce vertige est une des meilleures sensations de la vie adulte 🎢` },
  { id: 'cr_s2_010', text: `"C'est chelou de réaliser que personne va plus s'occuper des trucs à ta place."\nCes trucs. Qui se réglaient. Magiquement. Que quelqu'un gérait. Et qui maintenant attendent que ce soit toi. Le loyer. Les courses. L'ampoule grillée. Le ménage. Tout ça c'est toi maintenant. C'est chelou. Et c'est la vie adulte. Bienvenue, [Prénom].\nAvec accueil dans la réalité que personne va plus s'occuper des trucs à ta place,\n— quelqu'un qui est passé par là et qui confirme que ça devient vite automatique 🔧` },
  { id: 'cr_s2_011', text: `"T'as un appart. C'est chelou d'avoir un chez-toi à décorer selon ses propres goûts."\nSans compromis. Sans négociation avec d'autres. Juste toi et tes goûts. Et si tes goûts sont discutables c'est ton droit le plus absolu. Bienvenue dans la liberté décorative totale, [Prénom].\nAvec célébration de la liberté décorative totale et sans jugement sur les goûts,\n— quelqu'un qui viendra voir le résultat avec curiosité et bienveillance 🖼️` },
  { id: 'cr_s2_012', text: `"C'est chelou de rentrer dans un silence qui est le sien."\nCe silence. Celui de ton appart quand t'arrives. Qui t'appartient. Qui te connaît. Qui t'attend. Pas le silence inconfortable d'un endroit étranger. Le silence familier de ton chez-toi. Ce silence-là devient précieux très vite. Bienvenue, [Prénom].\nAvec description du silence familier de son propre espace comme quelque chose qui devient précieux,\n— quelqu'un qui pense que le silence de chez soi est une des choses les plus réconfortantes 🌿` },
  { id: 'cr_s2_013', text: `"T'as un appart. C'est chelou d'être propriétaire de ses propres erreurs de déco."\nCes choix. Ce tableau. Cette couleur. Ce meuble. Qui semblaient bien. Qui semblent moins bien maintenant. Qui sont quand même là. Parce que c'est chez toi. Et que chez toi tes erreurs de déco t'appartiennent. C'est chelou et libérateur. Bienvenue, [Prénom].\nAvec éloge de la propriété exclusive de ses propres erreurs de déco,\n— quelqu'un qui a les siennes et qui confirme qu'on y prend goût 😄` },
  { id: 'cr_s2_014', text: `"C'est chelou de réaliser que ton chez-toi va avoir son odeur à lui."\nL'odeur d'un chez-soi. Ce mélange unique. De ta cuisine. De tes produits. De ton quotidien. Qui se forme progressivement. Et qui devient l'odeur de chez toi. Celle que les gens reconnaissent en entrant. Celle qui te manque quand tu voyages. Bienvenue, [Prénom].\nAvec anticipation de l'odeur unique que ton chez-toi va développer,\n— quelqu'un qui trouve les odeurs de chez-soi parmi les plus réconfortantes qui soient 👃` },
  { id: 'cr_s2_015', text: `"T'as un appart. C'est chelou de payer un loyer. Et c'est bien de payer pour quelque chose qui est à toi."\nLe loyer. Cette somme mensuelle. Qui part. Et qui revient sous forme d'un espace. D'un refuge. D'un chez-toi. Ce troc-là est chelou à accepter au début. Et puis on comprend ce qu'on paie. Et on paie pour ça. Bienvenue, [Prénom].\nAvec perspective sur le loyer comme paiement pour quelque chose de concret et précieux,\n— quelqu'un qui pense que comprendre ce pour quoi on paie change tout 💶` },
  { id: 'cr_s2_016', text: `"C'est chelou de réaliser que ton appart va voir tous tes états."\nTes bons jours. Tes mauvais jours. Tes matins difficiles. Tes soirées réussies. Tes moments de doute. Tes moments de fierté. Ton appart va tout voir. Et il gardera ça. Dans ses murs. Dans son atmosphère. Bienvenue, [Prénom].\nAvec perspective sur ton appart comme témoin de tous tes états,\n— quelqu'un qui pense que les murs d'un chez-soi absorbent quelque chose de la vie qu'on y vit 🌊` },
  { id: 'cr_s2_017', text: `"T'as un appart. C'est chelou d'avoir un endroit à soi dans le monde."\nDans ce monde grand et agité. T'as un endroit. Précis. Géographiquement localisé. Qui est le tien. Où tu peux aller. Où tu peux revenir. Où tu peux exister à ta façon. Cet endroit c'est une fondation. Bienvenue dans ta fondation, [Prénom].\nAvec mise en perspective de ton appart comme fondation dans le monde grand et agité,\n— quelqu'un qui pense que tout le monde a besoin de sa fondation 🌍` },
  { id: 'cr_s2_018', text: `"C'est chelou de décider de ses propres rituels de chez-soi."\nCes rituels qui se forment. La façon de commencer la journée. La façon de rentrer le soir. Les trucs qu'on fait automatiquement dans son propre espace. Ces rituels vont se former. Ils vont devenir les tiens. Et ils diront quelque chose sur toi. Bienvenue, [Prénom].\nAvec anticipation des rituels de chez-soi qui vont se former et ce qu'ils diront sur toi,\n— quelqu'un qui est curieux de voir quels rituels tu vas développer 🔄` },
  { id: 'cr_s2_019', text: `"T'as un appart. C'est chelou et bien et les deux ensemble c'est exactement ce que c'est."\nPas l'un ou l'autre. Les deux simultanément. C'est la définition exacte de ce moment. Ce chelou bien particulier. Cette étape qui fait peur et qui réjouit en même temps. Bienvenue dedans, [Prénom].\nAvec définition exacte du moment comme chelou et bien simultanément et indissociablement,\n— quelqu'un qui pense que cette définition est la plus honnête qui soit 🎯` },
  { id: 'cr_s2_020', text: `"C'est chelou d'avoir un appart. Et t'as un appart. Bienvenue dans le chelou bien."\nLe chelou bien. Cette catégorie spéciale. Des trucs qui sont chelous et bien en même temps. Qui font peur et qui réjouissent. Qui sont nouveaux et qui deviennent vite normaux. Ton appart en fait partie. Bienvenue, [Prénom].\nAvec création de la catégorie officielle du chelou bien et placement de ton appart dedans,\n— quelqu'un qui pense que la vie est pleine de chelou bien et que c'est une bonne chose ❤️` },
];

// ── S3 : No cap t'assures dans la vie d'adulte ───────────
const S3: CremaillereMessage[] = [
  { id: 'cr_s3_001', text: `"No cap t'assures dans la vie d'adulte. T'as un appart et tu gères."\nPas juste l'avoir. Le gérer. Le loyer payé. Les charges comprises. L'espace maintenu. Les trucs organisés. Cette gestion quotidienne de son propre espace c'est de la vie adulte concrète. Et tu le fais. No cap. Bienvenue, [Prénom].\nAvec constat sincère de ta gestion adulte de ton propre espace,\n— quelqu'un qui observe ta vie adulte avec satisfaction 🌟` },
  { id: 'cr_s3_002', text: `"T'as trouvé un appart dans ce marché immobilier. No cap t'assures."\nLe marché immobilier c'est pas simple. Les visites. Les dossiers. La concurrence. Les refus. Et t'as trouvé. T'as navigué dans tout ça et t'as trouvé. C'est une victoire réelle dans un contexte difficile. Bienvenue chez toi, [Prénom].\nAvec reconnaissance de ta victoire dans un marché immobilier particulièrement difficile,\n— quelqu'un qui sait ce que ça demande et qui te félicite pour ça 🏆` },
  { id: 'cr_s3_003', text: `"No cap t'assures dans ta façon de t'installer."\nCette façon d'organiser l'espace. De faire des choix. De prioriser. De transformer un endroit vide en quelque chose qui te ressemble. Cette capacité à s'installer c'est une compétence. Et la tienne est bonne. Bienvenue, [Prénom].\nAvec éloge de ta capacité à t'installer comme compétence réelle,\n— quelqu'un qui a hâte de voir le résultat de ton installation 🎨` },
  { id: 'cr_s3_004', text: `"T'assures dans ta façon de gérer les trucs pratiques de l'appart."\nL'état des lieux. L'assurance. Les abonnements. L'électricité. Internet. Ces trucs administratifs qui arrivent en masse quand on emménage. T'as géré tout ça. Sans te noyer. En faisant ce qu'il fallait faire. No cap t'assures. Bienvenue, [Prénom].\nAvec respect pour ta gestion des trucs administratifs qui arrivent en masse à l'emménagement,\n— quelqu'un qui sait que cette gestion administrative est souvent plus difficile que prévu 📋` },
  { id: 'cr_s3_005', text: `"No cap t'as montré que t'étais prêt pour cette étape."\nPas juste envie. Prêt. T'as les compétences. La maturité. La capacité à gérer ce que ça demande. Cette étape c'est pas pour tout le monde au même moment. Toi t'y étais. Bienvenue chez toi, [Prénom].\nAvec confirmation que t'étais prêt pour cette étape,\n— quelqu'un qui était dans l'équipe de ceux qui savaient que t'étais prêt 🎯` },
  { id: 'cr_s3_006', text: `"T'assures dans ta façon de vivre seul ou en coloc."\nQue ce soit seul ou avec des gens. T'as trouvé une façon de fonctionner. De t'organiser. De gérer l'espace partagé ou non. Cette capacité à habiter son espace avec intelligence c'est quelque chose qui se développe. Et tu le développes bien. Bienvenue, [Prénom].\nAvec admiration pour ta façon d'habiter ton espace avec intelligence,\n— quelqu'un qui pense que bien habiter son espace est une forme d'intelligence de vie 🏠` },
  { id: 'cr_s3_007', text: `"No cap t'assures dans ta façon d'être indépendant."\nCette indépendance. Qui se voit dans les petits trucs. Dans ta façon de gérer. De décider. De te débrouiller. De pas attendre que quelqu'un d'autre prenne en charge. Cette indépendance-là est une qualité. Et la tienne est réelle. Bienvenue, [Prénom].\nAvec reconnaissance de ton indépendance réelle comme qualité visible dans les petits trucs,\n— quelqu'un qui observe ton indépendance avec satisfaction 🌿` },
  { id: 'cr_s3_008', text: `"T'assures dans les trucs que personne t'a appris."\nParce que l'école apprend pas à gérer un appart. À négocier un bail. À comprendre une quittance de loyer. À dealer avec un propriétaire. Ces compétences tu les as acquises sur le tas. Et tu te débrouilles. No cap. Bienvenue, [Prénom].\nAvec respect pour ton acquisition autodidacte des compétences de gestion d'un appart,\n— quelqu'un qui pense que ces compétences sont parmi les plus précieuses de la vie adulte 🔧` },
  { id: 'cr_s3_009', text: `"No cap t'as fait quelque chose de concret. T'as un chez-toi."\nConcret dans le sens tangible. Réel. Qu'on peut toucher. Visiter. Habiter. T'as construit quelque chose de réel dans ta vie. Pas un projet. Pas une intention. Un chez-toi. Bienvenue dedans, [Prénom].\nAvec célébration du caractère concret et tangible de ce que t'as construit,\n— quelqu'un qui pense que les trucs concrets dans une vie méritent d'être célébrés 🏗️` },
  { id: 'cr_s3_010', text: `"T'assures dans ta façon de faire de cet espace le tien."\nDe l'appropriation. De la personnalisation. De la mise en vie d'un espace. Cette façon de rendre un endroit neutre en quelque chose qui te ressemble. C'est une compétence créative et pratique à la fois. Et tu la fais bien. Bienvenue, [Prénom].\nAvec éloge de ta capacité à t'approprier un espace et en faire le tien,\n— quelqu'un qui est impatient de voir ce que tu en fais 🎨` },
  { id: 'cr_s3_011', text: `"No cap t'assures dans ta façon d'assumer la charge mentale du chez-soi."\nCette charge. Invisible. Permanente. De penser à tout. De rien oublier. De gérer les trucs avant qu'ils deviennent des problèmes. T'as commencé à développer ça. Et c'est une des compétences les plus précieuses de la vie adulte. Bienvenue, [Prénom].\nAvec reconnaissance de la charge mentale du chez-soi comme compétence précieuse en développement,\n— quelqu'un qui sait que cette charge est réelle et qui te félicite de la gérer 🧠` },
  { id: 'cr_s3_012', text: `"T'assures et ton appart le prouve."\nL'appart c'est la preuve. La preuve que t'as fait des démarches. Que t'as signé des trucs. Que t'as pris des responsabilités. Que t'as géré. Le résultat visible de tout ça c'est cet espace. Qui est à toi. No cap. Bienvenue, [Prénom].\nAvec identification de l'appart comme preuve tangible de ton sérieux et de ta gestion,\n— quelqu'un qui lit la preuve et qui est convaincu 📊` },
  { id: 'cr_s3_013', text: `"No cap t'as géré l'emménagement. C'est pas rien."\nLes cartons. Les meubles à monter. Les trucs à brancher. Les trucs à installer. Les trucs à trouver une place pour. Tout ça c'est de la gestion physique et logistique réelle. Et t'as traversé ça. Bienvenue de l'autre côté, [Prénom].\nAvec respect pour la gestion physique et logistique de l'emménagement,\n— quelqu'un qui sait que les cartons c'est épuisant et qui te félicite d'être de l'autre côté 📦` },
  { id: 'cr_s3_014', text: `"T'assures dans ta façon d'être autonome pour vrai."\nPas l'autonomie de façade. L'autonomie réelle. Celle qui se voit dans les actes. Dans les décisions. Dans la gestion. Dans la façon de se débrouiller sans filet. T'as cette autonomie. Elle est réelle. No cap. Bienvenue, [Prénom].\nAvec distinction entre l'autonomie de façade et l'autonomie réelle que tu as,\n— quelqu'un qui voit la différence et qui confirme que la tienne est réelle 🌱` },
  { id: 'cr_s3_015', text: `"No cap t'assures dans la vie d'adulte et ton appart en est la preuve."\nLa preuve numéro un. Visible. Concrète. Que t'as fait quelque chose. Que t'as avancé. Que t'as construit quelque chose dans ta vie d'adulte. Cette preuve-là elle est là. Dans tes murs. Dans tes clés. Dans ton adresse. Bienvenue, [Prénom].\nAvec identification de l'appart comme preuve numéro un de ta réussite dans la vie adulte,\n— quelqu'un qui reconnaît la preuve et qui te félicite pour elle 🌟` },
  { id: 'cr_s3_016', text: `"T'assures dans ta façon de gérer les imprévus du chez-soi."\nLa chaudière qui fait un bruit bizarre. L'ampoule grillée. Le robinet qui fuit. Ces imprévus. Qui arrivent toujours. Et t'as une façon de les gérer. De trouver une solution. De dealer avec. Sans paniquer. C'est de la gestion adulte réelle. Bienvenue, [Prénom].\nAvec respect pour ta gestion des imprévus du chez-soi sans paniquer,\n— quelqu'un qui sait que les imprévus arrivent toujours et qui confirme que ta gestion est bonne 🔧` },
  { id: 'cr_s3_017', text: `"No cap t'assures dans ta façon d'habiter ta vie."\nPas juste l'appart. Ta vie. T'as un chez-toi. T'as une façon d'être dans le monde. T'as des fondations. T'as des trucs qui sont à toi. Cette façon d'habiter sa vie c'est quelque chose. Et la tienne est bien habitée. Bienvenue, [Prénom].\nAvec éloge de ta façon d'habiter ta vie au-delà de l'appart,\n— quelqu'un qui trouve que ta vie est bien habitée et qui te le dit 🌍` },
  { id: 'cr_s3_018', text: `"T'assures et cet appart en est la preuve. Et on est fiers de toi."\nFiers dans le sens vraiment. Pas juste un mot. Vraiment fiers de voir où t'en es. De ce que t'as construit. De ce que tu gères. De qui tu deviens. Cet appart dit beaucoup sur toi. Et tout ça est bien. Bienvenue, [Prénom].\nAvec déclaration de fierté sincère et justifiée,\n— quelqu'un qui est vraiment fier et qui voulait te le dire clairement 💛` },
  { id: 'cr_s3_019', text: `"No cap t'assures. Et ton chez-toi t'attend pour que tu continues à assurer dedans."\nCe chez-toi. Qui t'attend. Qui sera là. Tous les soirs. Tous les matins. Et dans lequel tu vas continuer à construire. À grandir. À assurer. Il est prêt pour ça. Et toi aussi. Bienvenue, [Prénom].\nAvec perspective sur tout ce que tu vas continuer à construire dans cet espace,\n— quelqu'un qui est impatient de voir ce que tu vas faire de tout ça 🚀` },
  { id: 'cr_s3_020', text: `"No cap t'assures dans la vie d'adulte. Ton appart est là pour le prouver. Point."\nPas besoin d'en dire plus. La preuve est là. Visible. Concrète. T'assures. Ton appart le prouve. Point. Bienvenue chez toi, [Prénom].\nAvec économie de mots totale parce que parfois la preuve parle d'elle-même,\n— quelqu'un qui pense que les faits suffisent et qui les laisse parler ✅` },
];
// ── S4 : C'est pas le move d'avoir autant de cartons mais on t'aime ──────────
const S4: CremaillereMessage[] = [
  { id: 'cr_s4_001', text: `"Bienvenue chez toi. C'est pas le move d'avoir autant de cartons. On t'aime quand même."\nCes cartons. Ces piles. Ce chaos organisé ou pas. Cette façon que les affaires ont de prendre de la place quand on déménage. C'est pas le move. C'est inévitable. Et on t'aime dans le chaos des cartons. Bienvenue, [Prénom].\nAvec amour inconditionnel pour toi dans le chaos inévitable des cartons,\n— quelqu'un qui a vu tes cartons et qui t'aime quand même 📦` },
  { id: 'cr_s4_002', text: `"T'as gardé des trucs que tu garderas jamais. C'est pas le move. On t'aime."\nCes objets. Que t'as mis dans des cartons. Que tu te souviens pas d'avoir. Que tu sais pas trop pourquoi tu as gardés. Qui ont quand même voyagé jusqu'ici. C'est pas le move de les avoir gardés. Et on t'aime avec tes trucs incompréhensibles. Bienvenue, [Prénom].\nAvec amour pour toi et tes objets mystérieux qu'on garde sans savoir pourquoi,\n— quelqu'un qui a aussi ces objets et qui ne juge absolument pas 🗃️` },
  { id: 'cr_s4_003', text: `"C'est pas le move de monter les meubles en mode IKEA à 23h. On t'aime."\nCes moments. Ces instructions. Ces pièces qui semblent en trop. Ces vis qu'on sait pas où elles vont. Ce meuble qui penche légèrement. C'est pas le move. C'est un rite de passage. Bienvenue, [Prénom].\nAvec solidarité pour le rite de passage IKEA à 23h et amour malgré le meuble qui penche,\n— quelqu'un qui est passé par là et qui confirme que le meuble penché est universel 🪑` },
  { id: 'cr_s4_004', text: `"T'as déménagé avec des sacs poubelle en plus des cartons. C'est pas le move. On t'aime."\nLes sacs poubelle de déménagement. Cette méthode. Ces affaires mal emballées. Ces trucs qui se retrouvent dans un sac poubelle parce que les cartons étaient pleins. C'est pas le move. C'est universel. Bienvenue, [Prénom].\nAvec solidarité pour les sacs poubelle de déménagement comme méthode universelle et pas le move,\n— quelqu'un qui a aussi utilisé des sacs poubelle et qui n'en parle pas assez 🛍️` },
  { id: 'cr_s4_005', text: `"C'est pas le move d'avoir autant d'affaires. Mais t'as un chez-toi pour les mettre. On t'aime."\nCes affaires. Ces objets. Ces trucs accumulés. Qui remplissent les cartons. Qui débordent des placards. C'est pas le move d'en avoir autant. Et maintenant t'as un espace pour tout ça. Bienvenue, [Prénom].\nAvec amour pour toi et tes affaires nombreuses maintenant logées dans ton propre espace,\n— quelqu'un qui pense que t'as probablement trop de choses mais qui ne dira rien 😌` },
  { id: 'cr_s4_006', text: `"T'as un appart pas encore rangé. C'est pas le move. C'est normal. On t'aime."\nCes premières semaines. Où l'appart est en transit. Entre le chaos de l'emménagement et l'ordre du chez-soi. Où les cartons traînent encore. C'est normal. C'est une phase. Bienvenue dans la phase, [Prénom].\nAvec validation de la phase de chaos post-emménagement comme normale et temporaire,\n— quelqu'un qui sait que cette phase passe et qui t'aime pendant qu'elle dure 🌀` },
  { id: 'cr_s4_007', text: `"C'est pas le move d'avoir acheté ce meuble qui rentre pas. On t'aime quand même."\nCe meuble. Que t'as aimé. Que t'as acheté. Qui est arrivé à la maison. Et qui rentre pas tout à fait où tu voulais le mettre. C'est pas le move. C'est de l'expérience acquise. Bienvenue, [Prénom].\nAvec amour pour toi et ton meuble qui rentre pas tout à fait comme prévu,\n— quelqu'un qui a aussi acheté un meuble qui rentrait pas et qui compatit pleinement 🪚` },
  { id: 'cr_s4_008', text: `"T'as demandé de l'aide pour déménager et t'as pas eu de pizza pour remercier. C'est pas le move."\nLa pizza. Le code non écrit du déménagement. Ceux qui t'ont aidé à porter les cartons méritaient la pizza. Si t'as pas eu la pizza c'est un move discutable. Bienvenue, [Prénom].\nAvec rappel du code non écrit de la pizza pour ceux qui aident à déménager,\n— quelqu'un qui espère que la pizza était au rendez-vous et qui t'aime dans les deux cas 🍕` },
  { id: 'cr_s4_009', text: `"C'est pas le move d'avoir des cartons non déballés depuis trois semaines. On t'aime."\nCes cartons. Qui attendent. Dans un coin. Fermés. Que t'ouvriras quand tu seras prêt. Ou peut-être jamais. C'est pas le move. C'est universel. Et on t'aime avec tes cartons en attente. Bienvenue, [Prénom].\nAvec amour et solidarité pour les cartons non déballés qui attendent dans un coin,\n— quelqu'un qui a encore un carton non déballé de son dernier déménagement et qui ne juge pas 📦` },
  { id: 'cr_s4_010', text: `"T'as fait confiance à tes muscles pour un déménagement. C'est pas toujours le move."\nCes moments. Où on pense pouvoir porter quelque chose seul. Où le dos proteste. Où on réalise qu'on aurait dû demander de l'aide. C'est une leçon universelle. T'es pas le premier. Bienvenue, [Prénom].\nAvec solidarité pour la leçon universelle du dos après avoir sous-estimé un meuble,\n— quelqu'un qui a appris cette leçon lui aussi et qui t'aime quand même 💪` },
  { id: 'cr_s4_011', text: `"C'est pas le move de pas avoir mesuré avant d'acheter. On t'aime avec ton canapé trop grand."\nCe canapé. Qui était parfait dans le magasin. Qui est trop grand dans l'appart. C'est pas le move de pas avoir mesuré. Et on t'aime avec ton canapé trop grand. Bienvenue, [Prénom].\nAvec amour pour toi et ton canapé trop grand qui domine désormais le salon,\n— quelqu'un qui a hâte de s'y asseoir quand même 🛋️` },
  { id: 'cr_s4_012', text: `"T'as un appart. T'as des cartons. C'est pas le move d'avoir les deux trop longtemps. On t'aime."\nCette cohabitation. Entre l'appart et les cartons. Qui doit être temporaire. Le jour où les cartons disparaissent arrive toujours. Bienvenue dans l'attente, [Prénom].\nAvec amour pour toi dans la cohabitation appart-cartons en attendant la disparition des cartons,\n— quelqu'un qui te fait confiance pour que ce jour arrive bientôt 📅` },
  { id: 'cr_s4_013', text: `"C'est pas le move d'avoir perdu quelque chose pendant le déménagement. On t'aime."\nCette chose. Que t'as cherchée. Qui était là avant le déménagement. Qui est plus là après. Quelque part dans les cartons peut-être. C'est le mystère du déménagement. Bienvenue, [Prénom].\nAvec solidarité pour les objets perdus dans le déménagement et amour malgré la perte,\n— quelqu'un qui a aussi perdu quelque chose dans un déménagement et qui ne l'a jamais retrouvé 🔍` },
  { id: 'cr_s4_014', text: `"T'as sous-estimé le nombre de cartons nécessaires. C'est pas le move. C'est universel."\nTout le monde pense avoir besoin de moins de cartons qu'il n'en faut vraiment. Tout le monde se retrouve à improviser à mi-chemin. C'est une loi de la physique du déménagement. Bienvenue, [Prénom].\nAvec validation de la loi universelle de la sous-estimation des cartons nécessaires,\n— quelqu'un qui a contribué à ce phénomène lors de ses propres déménagements 📦` },
  { id: 'cr_s4_015', text: `"C'est pas le move d'avoir des affaires dans un appart pas encore organisé. On t'aime dedans."\nCe chaos temporaire. Cet appart en construction. Qui n'est pas encore tout à fait chez toi mais qui est en train de le devenir. On t'aime dans ce processus. Bienvenue, [Prénom].\nAvec amour pour toi dans le processus de construction de ton chez-toi,\n— quelqu'un qui sait que le processus est temporaire et le résultat permanent 🏗️` },
  { id: 'cr_s4_016', text: `"T'as réalisé pendant le déménagement que t'avais trop d'affaires. C'est pas le move. C'est la vérité."\nCette révélation. Au moment de mettre les affaires dans les cartons. Que t'as trop de trucs. Que Marie Kondo avait peut-être raison. C'est pas le move. C'est la vérité. Bienvenue, [Prénom].\nAvec validation de la révélation déménagement que t'as trop d'affaires,\n— quelqu'un qui a eu la même révélation et qui ne s'y est pas forcément conformé 🗂️` },
  { id: 'cr_s4_017', text: `"C'est pas le move d'avoir monté une étagère à l'envers. On t'aime avec ton étagère."\nCette étagère. Montée. Avec effort. Et retournée à l'envers. Ou penchée. Ou avec une pièce manquante. C'est pas le move. C'est le rite de passage du mobilier en kit. Bienvenue, [Prénom].\nAvec amour pour toi et ton étagère montée dans la mauvaise direction,\n— quelqu'un qui te propose de l'aide la prochaine fois mais qui vient quand même s'asseoir dessous 😄` },
  { id: 'cr_s4_018', text: `"T'as un chez-toi. Avec des cartons. C'est chelou et bien et pas le move tout en même temps. On t'aime."\nToutes les dimensions à la fois. Le chelou. Le bien. Le pas le move. Tout ça ensemble dans ton appart avec tes cartons. Et on t'aime dans toutes ces dimensions. Bienvenue, [Prénom].\nAvec amour pour toi dans toutes les dimensions simultanées de ce moment,\n— quelqu'un qui t'aime dans le chelou le bien et le pas le move en même temps ❤️` },
  { id: 'cr_s4_019', text: `"C'est pas le move d'avoir autant de cartons. T'as quand même un chez-toi. On t'aime les deux."\nLes deux ensemble. Les cartons pas le move. Le chez-toi bien. On t'aime avec les deux. Sans jugement sur les cartons. Avec joie pour le chez-toi. Bienvenue, [Prénom].\nAvec amour sans jugement pour les cartons et joie sincère pour le chez-toi,\n— quelqu'un qui accepte le package complet avec enthousiasme 📦🏠` },
  { id: 'cr_s4_020', text: `"C'est pas le move d'avoir autant de cartons. On t'aime. Bienvenue chez toi quand même."\nMalgré les cartons. Avec les cartons. À travers les cartons. Bienvenue chez toi. Ce chez-toi qui est là sous les cartons. Qui sera beau quand les cartons auront disparu. Bienvenue, [Prénom].\nAvec bienvenue sincère malgré et avec et à travers tous les cartons,\n— quelqu'un qui voit le chez-toi sous les cartons et qui est content pour toi ❤️` },
];

// ── S5 : La suite fait un peu peur mais ton appart est à toi ──────────────────
const S5: CremaillereMessage[] = [
  { id: 'cr_s5_001', text: `"La suite fait un peu peur. Ton appart est à toi. Ces deux vérités coexistent."\nLa peur de la suite. Le loyer à payer chaque mois. Les responsabilités. Et en même temps cet appart. Ce chez-toi. Ces deux vérités sont vraies en même temps. Bienvenue dedans, [Prénom].\nAvec validation de la coexistence de la peur et de la certitude du chez-toi,\n— quelqu'un qui pense que les deux peuvent coexister sans que l'un annule l'autre 🌀` },
  { id: 'cr_s5_002', text: `"T'as un chez-toi. La suite peut faire peur. Ton chez-toi sera là quand même."\nQuoi qu'il arrive. Ton chez-toi sera là. Comme ancre. Comme refuge. Comme point fixe. La suite peut être incertaine. Ton chez-toi est certain. Bienvenue, [Prénom].\nAvec identification de ton chez-toi comme point fixe dans une suite incertaine,\n— quelqu'un qui pense que l'ancre d'un chez-soi change tout face à l'incertitude 🌊` },
  { id: 'cr_s5_003', text: `"La suite fait peur. Le loyer fait peur. Ton appart est quand même à toi."\nCes peurs concrètes. Le loyer chaque mois. Les charges. Les imprévus. Et malgré tout ça. Ton appart est à toi. Cette certitude-là tient. Bienvenue, [Prénom].\nAvec validation des peurs concrètes et insistance sur la certitude du chez-toi malgré tout,\n— quelqu'un qui sait que ces peurs sont réelles et que ton chez-toi l'est aussi 💶` },
  { id: 'cr_s5_004', text: `"T'as signé pour une vie avec plus de responsabilités. Ton appart en vaut la peine."\nCes responsabilités. Ces engagements. Ce prix à payer pour avoir son propre espace. Est-ce que ça vaut la peine. Oui. Ton appart en vaut la peine. Bienvenue, [Prénom].\nAvec réponse ferme à la question de si les responsabilités en valent la peine,\n— quelqu'un qui pense que oui et qui le dit sans ambiguïté 🎯` },
  { id: 'cr_s5_005', text: `"La coloc peut faire peur. Les colocataires peuvent être chelous. Ton espace est quand même là."\nSi c'est une coloc. Avec des gens. Et la peur de comment ça va se passer. Des habitudes différentes. Malgré tout ça ton espace est là. Bienvenue, [Prénom].\nAvec validation des peurs de la coloc et insistance sur la présence de ton espace malgré tout,\n— quelqu'un qui a vécu en coloc et qui a des stories à raconter 🤝` },
  { id: 'cr_s5_006', text: `"La suite fait peur. Mais t'as un endroit où rentrer. Et ça change tout."\nTout. Littéralement. Avoir un endroit où rentrer. Un chez-soi qui attend. La suite fait moins peur quand on sait qu'on a un endroit où rentrer. Bienvenue, [Prénom].\nAvec identification de l'endroit où rentrer comme ce qui change tout face à la peur de la suite,\n— quelqu'un qui pense que cette certitude est une des plus précieuses qui soit 🏠` },
  { id: 'cr_s5_007', text: `"T'as un appart. La suite est incertaine. L'appart ne l'est pas."\nCette certitude au milieu de l'incertitude. Ton appart est là. Concret. Réel. Certain. Dans une vie adulte pleine d'incertitudes. Cette certitude-là est précieuse. Bienvenue, [Prénom].\nAvec éloge de la certitude de l'appart dans une vie pleine d'incertitudes,\n— quelqu'un qui pense que les certitudes concrètes sont de l'or dans la vie adulte 🌟` },
  { id: 'cr_s5_008', text: `"La suite fait peur. Les charges font peur. L'assurance fait peur. Ton chez-toi est là quand même."\nCette liste de trucs qui font peur. Qui arrivent avec un chez-soi. Et malgré tout ça ton chez-toi est là. Et il en vaut chacun de ces trucs qui font peur. Bienvenue, [Prénom].\nAvec liste honnête des peurs et affirmation que le chez-toi les vaut toutes,\n— quelqu'un qui pense que la liste des peurs est justifiée et que le chez-toi les dépasse toutes 📋` },
  { id: 'cr_s5_009', text: `"T'as peur de pas y arriver. Ton appart dit que t'y arrives déjà."\nCette peur de l'échec. De pas pouvoir gérer. Et la réalité. Que t'as déjà un appart. Que t'y arrives déjà. Ton appart est la preuve. Bienvenue, [Prénom].\nAvec utilisation de l'appart comme preuve que t'y arrives déjà malgré la peur,\n— quelqu'un qui pense que la preuve est là et que tu devrais te faire confiance 💡` },
  { id: 'cr_s5_010', text: `"La suite fait peur. Ton appart sera là toutes les nuits. C'est une ancre."\nToutes les nuits. Quoi qu'il se passe dans la journée. Ton appart sera là. Cette régularité nocturne. C'est une ancre dans la vie adulte. Bienvenue, [Prénom].\nAvec identification de la régularité nocturne de ton chez-soi comme ancre dans la vie adulte,\n— quelqu'un qui pense que rentrer chez soi tous les soirs est plus précieux qu'on ne le croit 🌙` },
  { id: 'cr_s5_011', text: `"T'as un chez-toi. La suite peut être difficile. Ton chez-toi sera ton point de départ à chaque fois."\nCe point de départ. Ton appart. D'où tu repars chaque matin. Ce point fixe à partir duquel la suite se construit. Même quand la suite est difficile. Bienvenue, [Prénom].\nAvec identification de ton appart comme point de départ permanent pour toute la suite,\n— quelqu'un qui pense que les points de départ solides sont fondamentaux 🏗️` },
  { id: 'cr_s5_012', text: `"La suite fait peur. Ton appart est à toi. Et ces deux trucs peuvent coexister longtemps."\nCette coexistence entre la peur de la suite et la certitude du chez-toi peut durer. Et c'est ok. On avance avec la peur. On s'appuie sur la certitude. Bienvenue, [Prénom].\nAvec permission de garder les deux longtemps sans que l'un doive effacer l'autre,\n— quelqu'un qui pense que la peur et la certitude peuvent cohabiter indéfiniment 🌿` },
  { id: 'cr_s5_013', text: `"T'as peur de la suite. Ton appart dit que t'as déjà commencé à la construire."\nTon appart c'est le premier bloc. Ce premier bloc est posé. La suite se construit bloc par bloc. Et t'as commencé. Bienvenue dans la construction, [Prénom].\nAvec perspective sur ton appart comme premier bloc de la construction de ta suite,\n— quelqu'un qui est impatient de voir ce que tu vas construire dessus 🏗️` },
  { id: 'cr_s5_014', text: `"La suite fait peur. Mais ton chez-toi sera là à chaque fois que tu en auras besoin."\nÀ chaque fois. Que la journée était difficile. Que les trucs allaient pas. Ton chez-toi sera là. Cette disponibilité permanente. C'est précieux. Bienvenue, [Prénom].\nAvec insistance sur la disponibilité permanente de ton chez-toi dans les moments difficiles,\n— quelqu'un qui pense que cette disponibilité est une des meilleures choses de la vie adulte 💛` },
  { id: 'cr_s5_015', text: `"T'as un appart. La suite est grande et incertaine. Ton appart est petit et certain. Tiens-toi à lui."\nCette certitude petite et concrète. Dans un monde grand et incertain. Tiens-toi à elle. Laisse-la te donner la stabilité dont tu as besoin pour affronter le reste. Bienvenue, [Prénom].\nAvec conseil de s'appuyer sur la petite certitude concrète dans le monde grand et incertain,\n— quelqu'un qui pense que les petites certitudes concrètes sont de l'or dans les grandes incertitudes 🌍` },
  { id: 'cr_s5_016', text: `"La suite fait peur. Ton appart sera là pour les bons moments aussi."\nPas juste les difficiles. Les bons aussi. Les soirées réussies. Les matins parfaits. Les moments de paix. Ton appart sera là pour tout ça. Bienvenue, [Prénom].\nAvec perspective sur tous les bons moments que ton appart va aussi accueillir,\n— quelqu'un qui est impatient d'être invité à certains d'entre eux 🎉` },
  { id: 'cr_s5_017', text: `"T'as un chez-toi. La suite peut être ce qu'elle veut. T'as un endroit à toi."\nQuoi que la suite apporte. Quels que soient les imprévus. T'as un endroit à toi. Cette certitude-là est indépendante de la suite. Bienvenue, [Prénom].\nAvec affirmation de la certitude du chez-toi comme indépendante de la suite,\n— quelqu'un qui pense que cette indépendance est une force 🌟` },
  { id: 'cr_s5_018', text: `"La suite fait peur. Ton appart dit que t'es prêt à y faire face."\nCet appart. Cette décision. Cette signature. Tout ça dit que t'es prêt. Prêt à commencer. Prêt à affronter la suite. Prêt à construire. Bienvenue, [Prénom].\nAvec lecture de ton appart comme preuve de ta préparation à affronter la suite,\n— quelqu'un qui voit ta préparation dans cet appart et qui te fait confiance 💪` },
  { id: 'cr_s5_019', text: `"La suite fait peur. Ton appart est là. Et on sera là aussi."\nLes deux. Ton chez-toi qui t'attend. Et les gens qui t'entourent. Ton appart et les gens autour. C'est une bonne fondation. Bienvenue, [Prénom].\nAvec rappel que ton chez-toi et les gens autour sont deux fondations complémentaires,\n— quelqu'un qui sera là pour la suite autant que pour la crémaillère 🫂` },
  { id: 'cr_s5_020', text: `"La suite fait un peu peur. Ton appart est à toi. Bienvenue chez toi. On gère ensemble."\nTout rassemblé. La peur de la suite. La certitude de ton chez-toi. Et la promesse qu'on est là. Pour la suite. Ensemble. Bienvenue, [Prénom].\nAvec tout rassemblé dans une bienvenue qui dit la peur la certitude et la solidarité,\n— quelqu'un qui sera là pour toute la suite de cette vie avec un chez-toi ❤️` },
];

// ── Export ────────────────────────────────────────────────
export const CREMAILLERE_GROUPS: CremaillereSubGroup[] = [
  { id: 'cr_s1', title: "Bienvenue chez toi — c'est officiel",                      emoji: '🔑', messages: S1 },
  { id: 'cr_s2', title: "T'as un appart et c'est chelou et bien en même temps",     emoji: '🤯', messages: S2 },
  { id: 'cr_s3', title: "No cap t'assures dans la vie d'adulte",                     emoji: '💪', messages: S3 },
  { id: 'cr_s4', title: "C'est pas le move d'avoir autant de cartons mais on t'aime",emoji: '📦', messages: S4 },
  { id: 'cr_s5', title: "La suite fait un peu peur mais ton appart est à toi",       emoji: '🌟', messages: S5 },
];
