// ═══════════════════════════════════════════════════════════
//  Confettis & Cake — Départ à l'étranger / Erasmus
// ═══════════════════════════════════════════════════════════

export interface DepartMessage {
  id: string;
  text: string;
}

export interface DepartSubGroup {
  id: string;
  title: string;
  emoji: string;
  messages: DepartMessage[];
}

// ── S1 : Tu pars et on est fiers et tristes en même temps ────────────────────
const S1: DepartMessage[] = [
  { id: 'dp_s1_001', text: `"Tu pars. On est fiers. On est tristes. Les trois sont vrais en même temps."\nFiers parce que t'as osé. Tristes parce que tu seras pas là. Et ces deux sentiments coexistent sans se contredire. On peut être fiers et tristes en même temps. C'est ça les départs des gens qui comptent. Bon voyage, [Prénom].\nAvec validation de la coexistence de la fierté et de la tristesse dans ce départ,\n— quelqu'un qui ressent les deux et qui pense que c'est honnête de le dire 🌍` },
  { id: 'dp_s1_002', text: `"T'as décidé de partir. On est fiers de cette décision. Et on va te manquer."\nPas tu vas nous manquer. On va te manquer. Parce que le manque c'est dans les deux sens. Ce manque mutuel c'est la preuve que ce qu'on a est réel. Bon voyage, [Prénom].\nAvec correction importante du sens du manque dans les deux directions,\n— quelqu'un qui pense que le manque mutuel est plus honnête que le manque unilatéral 💛` },
  { id: 'dp_s1_003', text: `"Tu pars à l'étranger. On est fiers de ton courage. Et on voudrait que tu restes."\nCes deux désirs simultanés. Te voir partir parce que c'est courageux et bien pour toi. Et te voir rester parce que c'est confortable pour nous. On gère ce conflit intérieur. Et on te dit bon voyage quand même. Bon voyage, [Prénom].\nAvec honnêteté sur le conflit entre la fierté et le désir égoïste que tu restes,\n— quelqu'un qui gère ce conflit et qui choisit la fierté malgré tout 🤝` },
  { id: 'dp_s1_004', text: `"T'as osé faire quelque chose que beaucoup rêvent et peu font. On est fiers. Et un peu jaloux."\nLa jalousie. Honnête. Cette envie de faire pareil. T'as fait ce que beaucoup imaginent. Et on t'admire pour ça. Et on est un peu jaloux. Et les deux sont normaux. Bon voyage, [Prénom].\nAvec aveu honnête de jalousie mêlée de fierté,\n— quelqu'un qui assume la jalousie comme forme d'admiration et qui t'envoie quand même avec joie ✈️` },
  { id: 'dp_s1_005', text: `"Tu pars. On est fiers. Et on sait pas trop comment dire au revoir."\nCes au revoir. Difficiles. Où on sait pas quoi dire. Où les mots semblent insuffisants. Ce message c'est une façon de combler ce manque. Bon voyage, [Prénom].\nAvec honnêteté sur la difficulté des au revoir et tentative de les combler avec ce message,\n— quelqu'un qui trouve les au revoir difficiles et qui t'écrit plutôt que de rater le sien 🚪` },
  { id: 'dp_s1_006', text: `"T'as pris une grande décision. On est fiers de ta façon de l'avoir prise."\nPas juste la décision. La façon. T'as réfléchi. T'as pesé. T'as décidé. Et t'as assumé ta décision. Cette façon de prendre de grandes décisions c'est quelque chose. Bon voyage, [Prénom].\nAvec éloge de ta façon de prendre la décision autant que de la décision elle-même,\n— quelqu'un qui pense que la façon de décider dit beaucoup sur qui on est 🎯` },
  { id: 'dp_s1_007', text: `"Tu pars. On reste. Et on est fiers de toi depuis d'ici."\nFiers depuis ici. Depuis là où on est. En te regardant partir. En pensant à ce que tu fais là-bas. Cette fierté à distance. Elle est réelle. Elle traverse la distance. Bon voyage, [Prénom].\nAvec description de la fierté à distance comme réelle et traversant les kilomètres,\n— quelqu'un qui sera fier de toi depuis ici pendant toute ta période là-bas 🌍` },
  { id: 'dp_s1_008', text: `"T'as choisi de partir. On aurait peut-être pas tous eu ce courage. Respect."\nCe courage. Honnêtement. De tout laisser. De partir dans l'inconnu. De s'exposer à une nouvelle langue. Une nouvelle culture. Ce courage n'est pas universel. T'as ce courage. Respect. Bon voyage, [Prénom].\nAvec respect sincère pour un courage qui n'est pas universel,\n— quelqu'un qui reconnaît honnêtement qu'il aurait peut-être pas eu ce courage lui-même 🦁` },
  { id: 'dp_s1_009', text: `"Tu pars. On est fiers et tristes. Et on sera là quand tu reviens."\nLa promesse. Simple. Claire. On sera là. Au retour. Pour entendre. Pour accueillir. Cette promesse-là on la tient. Bon voyage, [Prénom].\nAvec promesse simple et claire d'être là au retour,\n— quelqu'un qui tient ses promesses et qui tient celle-là particulièrement 🫂` },
  { id: 'dp_s1_010', text: `"T'as dit oui à quelque chose de grand. On est fiers de ton oui."\nCe oui. Cette décision. Cette ouverture vers quelque chose de plus grand. Dire oui à l'inconnu. Oui à la nouveauté. Oui à l'aventure. Ce oui mérite d'être célébré. Bon voyage, [Prénom].\nAvec célébration du oui comme acte courageux en soi,\n— quelqu'un qui pense que savoir dire oui aux grandes choses est une compétence rare 🌟` },
  { id: 'dp_s1_011', text: `"Tu pars. On va penser à toi. On est fiers de toi. Dans cet ordre et simultanément."\nCes sentiments. Qui arrivent ensemble. La pensée constante. La fierté permanente. La tristesse du vide que tu laisses. Tout ça ensemble. Bon voyage, [Prénom].\nAvec description de la simultanéité des sentiments du départ,\n— quelqu'un qui les vit tous en même temps et qui trouve ça normal et beau 💛` },
  { id: 'dp_s1_012', text: `"T'as fait quelque chose que tu te souviendras toujours d'avoir fait. On est là pour le marquer."\nCe départ. Cette décision. T'en souviendras toujours. Et on voulait marquer ça. Dire qu'on était là. Qu'on a vu. Que ce moment méritait d'être reconnu. Bon voyage, [Prénom].\nAvec intention de marquer ce moment mémorable pour qu'il soit reconnu,\n— quelqu'un qui voulait être présent à ce moment même sous forme de mots 📸` },
  { id: 'dp_s1_013', text: `"Tu pars à l'étranger. C'est courageux. C'est bien. Et on est tristes de te voir partir."\nCes trois choses. Vraies toutes les trois. Le courage. Le bien. La tristesse. Pas la honte de la tristesse. La tristesse honnête. Celle qui dit que tu comptes. Bon voyage, [Prénom].\nAvec honnêteté sur les trois vérités simultanées du départ,\n— quelqu'un qui ne cache pas sa tristesse parce qu'elle dit que tu comptes 💙` },
  { id: 'dp_s1_014', text: `"T'as osé. On est fiers. Et on t'envie un peu. Et on est tristes. Tout ça à la fois."\nFierté. Envie. Tristesse. Joie pour toi. Mélancolie pour nous. Admiration pour ton courage. Tout ça à la fois. C'est les émotions d'un vrai départ d'un vrai ami. Bon voyage, [Prénom].\nAvec inventaire honnête du mélange d'émotions d'un vrai départ d'un vrai ami,\n— quelqu'un qui ressent tout ça et qui pense que l'honnêteté sur les émotions est la meilleure façon de dire au revoir ✈️` },
  { id: 'dp_s1_015', text: `"Tu pars vers quelque chose de nouveau. On est fiers de ta curiosité."\nCette curiosité. Du monde. Des gens. Des cultures. Cette façon d'avoir envie de voir autre chose. Cette curiosité-là elle est belle et rare. On est fiers d'avoir un ami avec cette curiosité. Bon voyage, [Prénom].\nAvec éloge de ta curiosité du monde comme qualité belle et rare,\n— quelqu'un qui pense que la curiosité du monde est une des plus belles qualités 🔭` },
  { id: 'dp_s1_016', text: `"T'as une vie qui va changer là-bas. Et on est fiers d'être dans ta vie avant que ça change."\nAvant. Ce moment précis. On est là. Dans ta vie d'avant. Et on restera dans ta vie d'après. Mais on voulait marquer l'avant. Bon voyage, [Prénom].\nAvec marquage du moment d'avant le changement et promesse d'être dans l'après aussi,\n— quelqu'un qui veut exister dans ton avant et dans ton après 💛` },
  { id: 'dp_s1_017', text: `"Tu pars. On est fiers. Et on réalise pas encore vraiment que tu seras pas là."\nCette non-réalisation. Qui vient plus tard. Quand on veut t'appeler pour un truc. Quand on réalise que t'es pas au bout de la rue. En attendant on est juste fiers. Bon voyage, [Prénom].\nAvec honnêteté sur la non-réalisation du vide qui vient plus tard,\n— quelqu'un qui sait que la réalisation vient progressivement et qui profite de l'avant 🌀` },
  { id: 'dp_s1_018', text: `"T'as choisi l'aventure. On est fiers de ton choix. Et on sera là pour les histoires au retour."\nLes histoires. Que tu vas ramener. Que tu vas raconter. Qu'on attend déjà. Ces histoires d'un ailleurs. On attend ces histoires. Bon voyage, [Prénom].\nAvec anticipation des histoires que tu vas rapporter et impatience de les entendre,\n— quelqu'un qui attend tes histoires du retour avec beaucoup d'impatience 📖` },
  { id: 'dp_s1_019', text: `"Tu pars. On est fiers et tristes. Et c'est exactement comme ça devrait être."\nExactement. Les vrais départs des gens qui comptent produisent exactement ça. Fierté et tristesse mélangées. C'est la preuve que le départ est réel. Que la relation est réelle. Bon voyage, [Prénom].\nAvec validation que ce mélange de fierté et tristesse est exactement ce qui devrait être,\n— quelqu'un qui pense que les bons mélanges d'émotions disent les bons liens 💛` },
  { id: 'dp_s1_020', text: `"Tu pars. On est fiers. On est tristes. Et on t'aime. Bon voyage, [Prénom]."\nTout rassemblé. Le départ. La fierté. La tristesse. L'amour. Ces quatre vérités. Pour ce départ. Pour toi. Bon voyage, [Prénom].\nAvec tout rassemblé dans quatre vérités simples et directes,\n— quelqu'un qui dit tout en peu de mots parce que parfois c'est la meilleure façon ❤️` },
];

// ── S2 : T'as osé partir — no cap t'assures ──────────────────────────────────
const S2: DepartMessage[] = [
  { id: 'dp_s2_001', text: `"T'as osé partir. No cap t'assures."\nPas juste l'envie. L'acte. T'as décidé. T'as organisé. T'as signé. T'as dit au revoir. Et tu pars. Ce passage de l'envie à l'acte c'est là que beaucoup s'arrêtent. Toi t'as pas arrêté. No cap t'assures. Bon voyage, [Prénom].\nAvec identification du passage de l'envie à l'acte comme là où t'as fait la différence,\n— quelqu'un qui pense que c'est ce passage qui sépare ceux qui font de ceux qui veulent faire 🎯` },
  { id: 'dp_s2_002', text: `"No cap t'assures d'avoir choisi l'inconnu."\nL'inconnu. La nouvelle langue. Les nouvelles têtes. Les nouveaux codes. T'as choisi ça. Pas la sécurité. L'inconnu. Et choisir l'inconnu c'est une forme de courage que peu de gens ont. Bon voyage, [Prénom].\nAvec éloge de ton choix de l'inconnu comme forme rare de courage,\n— quelqu'un qui admire ta façon de choisir l'inconnu sur la sécurité 🌍` },
  { id: 'dp_s2_003', text: `"T'as tout organisé pour partir. No cap t'assures dans la logistique du départ."\nLes billets. Le logement. Les papiers. Les démarches. T'as géré tout ça. Cette logistique complexe. Sans te noyer. No cap. Bon voyage, [Prénom].\nAvec respect pour ta gestion de la logistique complexe du départ à l'étranger,\n— quelqu'un qui sait que cette logistique est bien plus compliquée qu'elle en a l'air 📋` },
  { id: 'dp_s2_004', text: `"T'as quitté ta zone de confort. No cap c'est le move le plus courageux."\nLa zone de confort. Confortable par définition. Difficile à quitter par définition. T'as quitté la tienne. Pour quelque chose de plus grand. Ce move-là est le plus courageux qui soit. Bon voyage, [Prénom].\nAvec identification de quitter sa zone de confort comme le move le plus courageux,\n— quelqu'un qui pense que ce move change les gens de façon durable 🦁` },
  { id: 'dp_s2_005', text: `"No cap t'assures d'avoir dit oui à cette opportunité."\nCette opportunité. À laquelle t'aurais pu dire non. Par peur. Par confort. T'as dit oui. Ce oui c'est un acte. Une décision. Une direction. No cap t'assures. Bon voyage, [Prénom].\nAvec éloge de ton oui à l'opportunité comme acte courageux,\n— quelqu'un qui pense que savoir dire oui aux bonnes opportunités est une compétence rare 🌟` },
  { id: 'dp_s2_006', text: `"T'as fait confiance à ce que tu pouvais vivre ailleurs. No cap t'assures."\nCette confiance. Dans ta capacité à t'adapter. À vivre dans un contexte différent. À trouver ta place ailleurs. No cap t'assures d'avoir eu cette confiance. Bon voyage, [Prénom].\nAvec éloge de ta confiance en ta capacité à vivre ailleurs,\n— quelqu'un qui partage cette confiance en toi et qui la trouve justifiée 💪` },
  { id: 'dp_s2_007', text: `"No cap t'assures d'avoir organisé ta vie autrement pour partir."\nTout ce que t'as réorganisé. Les trucs que t'as mis en pause. Pour que ce départ soit possible. Cette réorganisation de vie c'est un effort réel. No cap. Bon voyage, [Prénom].\nAvec respect pour la réorganisation de vie que le départ a demandé,\n— quelqu'un qui sait que réorganiser sa vie pour partir demande plus qu'il n'y paraît 🔄` },
  { id: 'dp_s2_008', text: `"T'as choisi de voir le monde. No cap c'est une des meilleures décisions qui soit."\nLe monde. T'as choisi d'aller le voir. Pas juste en touriste. En t'y installant. En y vivant. C'est une des meilleures décisions. No cap. Bon voyage, [Prénom].\nAvec affirmation que voir le monde en y vivant est une des meilleures décisions qui soit,\n— quelqu'un qui en est convaincu et qui te le dit sans ambiguïté 🌍` },
  { id: 'dp_s2_009', text: `"No cap t'assures d'avoir eu le courage de partir seul."\nSeul. Sans le filet habituel. Sans les repères habituels. Partir seul vers quelque chose de nouveau. C'est un courage particulier. Celui de faire confiance à soi-même dans l'inconnu. No cap. Bon voyage, [Prénom].\nAvec éloge particulier du courage de partir seul dans l'inconnu,\n— quelqu'un qui pense que partir seul est une des formes les plus pures du courage ✈️` },
  { id: 'dp_s2_010', text: `"T'as fait quelque chose que t'avais peut-être peur de faire. No cap t'assures."\nCette peur. Qui était là peut-être. Et tu l'as faite quand même. Cette capacité à faire malgré la peur. C'est la définition du courage. No cap. Bon voyage, [Prénom].\nAvec reconnaissance de ta capacité à faire malgré la peur comme définition du courage,\n— quelqu'un qui pense que faire malgré la peur est toujours plus courageux que faire sans 🎯` },
  { id: 'dp_s2_011', text: `"No cap t'assures d'avoir investi dans une expérience plutôt que dans des trucs."\nCet investissement en expérience. En vie. En rencontres. En apprentissages. Ces trucs-là valent plus que les trucs matériels. Et t'as choisi d'y investir. No cap. Bon voyage, [Prénom].\nAvec éloge de ton investissement en expérience sur les trucs matériels,\n— quelqu'un qui partage cette philosophie d'investissement et qui te felicite de l'avoir 💎` },
  { id: 'dp_s2_012', text: `"T'as osé et t'assures. Ces deux trucs vont souvent ensemble."\nCeux qui osent sont souvent ceux qui assurent. Parce que oser c'est une disposition d'esprit qui produit de bons résultats. T'as osé. T'assures. Bon voyage, [Prénom].\nAvec observation que oser et assurer vont souvent ensemble,\n— quelqu'un qui confirme cette corrélation dans ton cas 🔗` },
  { id: 'dp_s2_013', text: `"No cap t'assures d'avoir fait confiance à l'inconnu."\nL'inconnu auquel t'as fait confiance. Sans garantie. Juste une confiance dans le fait que l'inconnu pouvait être bon. Cette foi dans l'inconnu c'est remarquable. No cap. Bon voyage, [Prénom].\nAvec admiration pour ta foi dans l'inconnu comme quelque chose de remarquable,\n— quelqu'un qui pense que cette foi change les trajectoires de vie 🌟` },
  { id: 'dp_s2_014', text: `"T'as dit au revoir à du confort pour dire bonjour à de l'expérience. No cap t'assures."\nCe troc. Confort contre expérience. Familier contre nouveau. T'as fait ce troc. Et ce troc te va bien. No cap. Bon voyage, [Prénom].\nAvec éloge du troc confort-expérience que t'as fait,\n— quelqu'un qui pense que ce troc est toujours gagnant sur le long terme ⚖️` },
  { id: 'dp_s2_015', text: `"No cap t'assures d'avoir une vision de ce que tu veux vivre."\nCette vision. De vouloir vivre quelque chose de particulier. De pas juste subir la vie. De la choisir activement. No cap t'assures. Bon voyage, [Prénom].\nAvec éloge de ta vision active de ce que tu veux vivre,\n— quelqu'un qui pense que choisir activement sa vie est une des compétences les plus rares 🧭` },
  { id: 'dp_s2_016', text: `"T'as organisé ce départ dans un contexte pas toujours facile. No cap t'assures."\nParce que partir c'est jamais simple logistiquement. Financièrement parfois. Émotionnellement souvent. Et t'as navigué dans tout ça. Et tu pars. No cap. Bon voyage, [Prénom].\nAvec respect pour ta navigation dans les obstacles du départ,\n— quelqu'un qui sait que les obstacles du départ sont réels et qui te félicite de les avoir traversés 💪` },
  { id: 'dp_s2_017', text: `"No cap t'assures d'avoir choisi de grandir autrement."\nGrandir autrement. Dans l'ailleurs. Dans la différence. Dans l'adaptation. Dans la confrontation à autre chose que ce qu'on connaît. Cette façon de choisir de grandir c'est courageux et intelligent. No cap. Bon voyage, [Prénom].\nAvec éloge de ton choix de grandir autrement dans l'ailleurs,\n— quelqu'un qui pense que cette façon de grandir produit des gens plus riches 🌱` },
  { id: 'dp_s2_018', text: `"T'as osé partir. No cap c'est déjà une victoire avant même d'être parti."\nLa victoire du départ. Avant même d'arriver. Le fait d'avoir osé. D'avoir décidé. D'avoir organisé. C'est déjà une victoire. No cap. Bon voyage, [Prénom].\nAvec identification de la victoire dans l'acte de partir lui-même avant même l'arrivée,\n— quelqu'un qui pense que la victoire du départ mérite d'être célébrée en soi 🏆` },
  { id: 'dp_s2_019', text: `"No cap t'assures. Et là-bas tu continueras à assurer. On en est sûrs."\nLà-bas aussi. Dans le nouveau contexte. Tu continueras à assurer. Parce que l'assurance que t'as c'est pas lié au contexte. C'est toi. Bon voyage, [Prénom].\nAvec confiance dans la continuité de ton assurance dans le nouveau contexte,\n— quelqu'un qui sait que l'assurance vient de toi pas du contexte 🌍` },
  { id: 'dp_s2_020', text: `"T'as osé partir. No cap t'assures. Bon voyage, [Prénom]."\nSimple. Direct. L'essentiel. T'as osé. T'assures. Bon voyage. Tout le reste découle de ces trois vérités. Bon voyage, [Prénom].\nAvec économie de mots totale parce que parfois trois vérités disent tout,\n— quelqu'un qui pense que la concision est la forme suprême de l'expression ✈️` },
];

// ── S3 : Tu vas manquer mais c'est le bon move ────────────────────────────────
const S3: DepartMessage[] = [
  { id: 'dp_s3_001', text: `"Tu vas manquer. C'est le bon move. Les deux sont vrais."\nLe manque qui arrive. Réel. Concret. Et en même temps c'est le bon move. Ces deux vérités coexistent. Bon voyage, [Prénom].\nAvec validation de la coexistence du manque et du bon move,\n— quelqu'un qui ressent le manque et qui sait que c'est quand même le bon move 💛` },
  { id: 'dp_s3_002', text: `"Tu vas manquer mais le bon move c'est pas toujours le move confortable."\nLe move confortable c'est rester. Dans le connu. Avec les gens. Le bon move c'est partir. Même si ça fait manquer. Le bon move et le move confortable sont rarement le même. Bon voyage, [Prénom].\nAvec distinction importante entre le bon move et le move confortable,\n— quelqu'un qui sait que les meilleurs moves sont rarement les plus confortables 🎯` },
  { id: 'dp_s3_003', text: `"Tu vas nous manquer. Et on est contents pour toi en même temps. C'est compliqué."\nCompliqué. Honnêtement compliqué. Être contents pour quelqu'un qui part. Et tristes qu'il parte. Ces deux sentiments ensemble. Bon voyage, [Prénom].\nAvec honnêteté sur la complexité émotionnelle du départ d'un ami,\n— quelqu'un qui assume la complexité plutôt que de faire semblant que c'est simple 🌀` },
  { id: 'dp_s3_004', text: `"Tu vas manquer. Mais partir c'était ta bonne décision. Et on respecte tes bonnes décisions."\nMême quand elles nous arrangent pas. Même quand elles créent du manque. Tes bonnes décisions méritent le respect. Bon voyage, [Prénom].\nAvec respect pour tes bonnes décisions même celles qui créent du manque pour nous,\n— quelqu'un qui respecte tes décisions même quand elles l'arrangent pas 🤝` },
  { id: 'dp_s3_005', text: `"Tu vas manquer dans les moments précis. Ces moments qu'on aurait vécus ensemble."\nCes moments précis. Qui vont arriver. Et dans lesquels tu seras pas là. Ces soirées. Ces conversations. Ces trucs du quotidien. Tu vas manquer dans chacun d'eux. Mais c'est le bon move. Bon voyage, [Prénom].\nAvec description précise des moments dans lesquels le manque se fera sentir,\n— quelqu'un qui pense à ces moments d'avance et qui les accepte quand même 💙` },
  { id: 'dp_s3_006', text: `"Tu vas manquer. Et tu vas revenir enrichi. Et on attend les deux."\nL'absence d'abord. Avec le manque. Et le retour ensuite. Avec tout ce que tu auras vécu. On attend les deux. Le manque maintenant. L'enrichissement au retour. Bon voyage, [Prénom].\nAvec attente simultanée du manque maintenant et de l'enrichissement au retour,\n— quelqu'un qui est patient pour les deux 🌟` },
  { id: 'dp_s3_007', text: `"C'est le bon move même si ça fait un vide. Le vide dit que t'étais important."\nCe vide. Que tu vas laisser. Il est proportionnel à l'importance que tu avais. Un grand vide dit une grande importance. Bon voyage, [Prénom].\nAvec réinterprétation du vide comme preuve de l'importance de ta présence,\n— quelqu'un qui pense que la taille du vide est la meilleure mesure de l'importance de quelqu'un 📏` },
  { id: 'dp_s3_008', text: `"Tu vas manquer. Mais ton départ va t'apporter des trucs qu'on peut pas te donner ici."\nCes trucs. Que seul l'ailleurs peut donner. Des perspectives. Des rencontres. Des expériences. Ces trucs-là on peut pas te les donner ici. Là-bas peut. Alors vas-y. Bon voyage, [Prénom].\nAvec identification des trucs que seul l'ailleurs peut donner et que vous ne pouvez pas,\n— quelqu'un qui accepte ses limites et qui t'envoie là où elles sont compensées 🌍` },
  { id: 'dp_s3_009', text: `"Tu vas manquer et c'est le bon move. Ces deux vérités sont compatibles depuis toujours."\nLes bons départs font manquer. Les bonnes décisions créent parfois du manque. Ce n'est pas une contradiction. C'est la réalité des bons moves. Bon voyage, [Prénom].\nAvec insistance sur la compatibilité historique du manque et du bon move,\n— quelqu'un qui pense que cette compatibilité est une des vérités les plus importantes des relations 🌿` },
  { id: 'dp_s3_010', text: `"Tu vas manquer dans les petits trucs. Ces petits trucs quotidiens qu'on réalise pas qu'on partage."\nCes petits trucs. Qu'on partage sans y penser. Et dont l'absence crée un vide inattendu. Ces petits trucs-là on les réalisera quand tu seras parti. Bon voyage, [Prénom].\nAvec anticipation du vide inattendu des petits trucs quotidiens partagés sans y penser,\n— quelqu'un qui réalise déjà à quel point certains petits trucs vont manquer 💛` },
  { id: 'dp_s3_011', text: `"C'est le bon move. Et on te regardera de loin faire le bon move avec fierté."\nDe loin. Depuis ici. On te regardera. On suivra. On s'intéressera à ce que tu vis. Et on sera fiers. Bon voyage, [Prénom].\nAvec description de la façon d'être là de loin pendant ton voyage,\n— quelqu'un qui sera là de loin et qui compte être actif dans ce là de loin 👁️` },
  { id: 'dp_s3_012', text: `"Tu vas manquer. Et quelque part c'est beau que tu manques autant."\nBeau dans le sens. Que si tu manques autant c'est que ce qu'on a est réel. Le manque dit toujours quelque chose de beau sur ce qui est manqué. Bon voyage, [Prénom].\nAvec réinterprétation de l'intensité du manque comme quelque chose de beau,\n— quelqu'un qui trouve de la beauté dans le manque parce qu'il dit quelque chose sur la relation 🌸` },
  { id: 'dp_s3_013', text: `"C'est le bon move. Et les bons moves méritent d'être soutenus même quand ils font manquer."\nLe soutien. À ton bon move. Même si ce move crée du manque pour nous. On soutient ton bon move. Parce que c'est ça les bons amis. Bon voyage, [Prénom].\nAvec déclaration de soutien au bon move même quand il crée du manque,\n— quelqu'un qui pense que soutenir les bons moves de ses amis c'est la définition d'un bon ami 🤝` },
  { id: 'dp_s3_014', text: `"Tu vas manquer mais tu vas revenir. Et le retour sera bon."\nCette certitude. Du retour. Et de sa bonté. T'as pas parti pour toujours. Au bout de ce temps y'a un retour. Et ce retour sera bon. Bon voyage, [Prénom].\nAvec certitude du retour et anticipation de sa bonté,\n— quelqu'un qui attend le retour avec autant d'impatience que ton départ 🌅` },
  { id: 'dp_s3_015', text: `"Tu vas manquer. Et là-bas tu vas rencontrer des gens qui vont compter pour toi."\nDes gens nouveaux. Qui vont entrer dans ta vie. Qui vont compter. Et cette idée est belle. Que ton cercle va s'agrandir là-bas. Bon voyage, [Prénom].\nAvec anticipation joyeuse des rencontres à venir là-bas,\n— quelqu'un qui est content que tu rencontres de nouvelles personnes même si c'est ailleurs 🤝` },
  { id: 'dp_s3_016', text: `"C'est le bon move. Et les bons moves laissent parfois des vides temporaires."\nTemporaires. C'est le mot important. Les vides des bons moves sont temporaires. Le vide est temporaire. Le bien est permanent. Bon voyage, [Prénom].\nAvec insistance sur le caractère temporaire du vide et permanent du bien produit par le bon move,\n— quelqu'un qui pense que le rapport temporaire-permanent est toujours favorable dans les bons moves ⏳` },
  { id: 'dp_s3_017', text: `"Tu vas manquer dans nos conversations. T'étais quelqu'un qui comptait dans nos échanges."\nCes échanges. Où ta voix comptait. Où ton point de vue importait. Ces échanges seront différents sans toi. T'y manqueras. Bon voyage, [Prénom].\nAvec reconnaissance de ton importance dans les échanges collectifs,\n— quelqu'un qui sait que tes contributions aux conversations vont manquer 💬` },
  { id: 'dp_s3_018', text: `"Tu vas manquer. Et c'est normal de manquer quand on part pour les bonnes raisons."\nCeux qui partent pour les bonnes raisons manquent. Parce qu'ils avaient quelque chose de réel ici. Quelque chose qui méritait d'être manqué. T'as ça. Bon voyage, [Prénom].\nAvec normalisation du manque comme signe que le départ est pour les bonnes raisons,\n— quelqu'un qui pense que manquer est un signe de santé de la relation 🌿` },
  { id: 'dp_s3_019', text: `"Tu vas manquer. C'est le bon move. Et on t'aime assez pour te laisser partir."\nT'aimer assez pour laisser partir. C'est une forme d'amour. Pas la plus facile. On t'aime assez pour que ton bon move soit plus important que notre confort. Bon voyage, [Prénom].\nAvec identification de laisser partir comme forme d'amour,\n— quelqu'un qui pense que laisser partir ceux qu'on aime vers leurs bons moves est une des formes d'amour les plus nobles 💛` },
  { id: 'dp_s3_020', text: `"Tu vas manquer. C'est le bon move. Bon voyage, [Prénom]."\nTrois vérités. Ton absence future. La justesse de ta décision. Et le souhait sincère. Tout est dit. Bon voyage, [Prénom].\nAvec économie de mots totale parce que trois vérités suffisent,\n— quelqu'un qui dit tout en peu de mots et qui le pense vraiment ❤️` },
];

// ── S4 : C'est chelou de te voir partir mais c'est bien pour toi ──────────────
const S4: DepartMessage[] = [
  { id: 'dp_s4_001', text: `"C'est chelou de te voir partir. Et c'est bien pour toi. Les deux sont vrais."\nChelou parce que c'est inhabituel. Parce que tu seras pas là. Et bien pour toi parce que c'est ce que tu voulais. Ce que tu avais besoin. Les deux ensemble. Bon voyage, [Prénom].\nAvec validation de la chelou-ité et du bien simultanés de te voir partir,\n— quelqu'un qui ressent les deux et qui pense que c'est honnête 🌀` },
  { id: 'dp_s4_002', text: `"C'est chelou de réaliser que t'es quelqu'un qui part à l'étranger."\nT'es cette personne maintenant. Celle qui part. Celle qui va vivre ailleurs. C'est chelou à réaliser. Que t'es cette personne. Que c'est vraiment toi. Bon voyage, [Prénom].\nAvec description de la chelou-ité de réaliser que t'es vraiment cette personne qui part,\n— quelqu'un qui trouve ça chelou et impressionnant en même temps 😮` },
  { id: 'dp_s4_003', text: `"C'est chelou de te voir partir. Mais c'est bien pour toi et on s'accroche à ça."\nOn s'accroche à ça. Au bien pour toi. Quand le chelou devient trop fort. On revient à ça. C'est bien pour toi. Et ça suffit. Bon voyage, [Prénom].\nAvec description du bien pour toi comme ancre dans les moments où le chelou devient fort,\n— quelqu'un qui s'accroche à ça et qui te le dit pour que tu le saches 💙` },
  { id: 'dp_s4_004', text: `"C'est chelou de pas savoir exactement ce que tu vas vivre là-bas. Et c'est bien que toi tu saches pas non plus."\nPersonne sait exactement. Et c'est ça le beau. L'inconnu qui attend. Chelou de l'extérieur. Excitant de l'intérieur peut-être. Bon voyage, [Prénom].\nAvec réinterprétation de l'inconnu de ce qui attend comme quelque chose de bien,\n— quelqu'un qui pense que l'inconnu est souvent la meilleure partie 🌟` },
  { id: 'dp_s4_005', text: `"C'est chelou de te voir partir vers quelque chose qu'on connaît pas."\nCet ailleurs. Qu'on connaît pas. T'y vas toi. Et on reste ici avec notre pas connaissance. C'est chelou de rester avec ça. Et c'est bien pour toi. Bon voyage, [Prénom].\nAvec description de la chelou-ité de rester avec sa non-connaissance de l'ailleurs où tu pars,\n— quelqu'un qui va se former une image de là où tu es grâce à tes messages 📸` },
  { id: 'dp_s4_006', text: `"C'est chelou que la distance soit réelle maintenant."\nAvant la distance était abstraite. Maintenant elle sera concrète. Des kilomètres. Un décalage horaire peut-être. Un vol. Cette distance réelle c'est chelou à réaliser. Et c'est bien pour toi quand même. Bon voyage, [Prénom].\nAvec description de la chelou-ité de la distance qui devient réelle et concrète,\n— quelqu'un qui pense à cette distance et qui trouve ça chelou et acceptable à la fois ✈️` },
  { id: 'dp_s4_007', text: `"C'est chelou de te voir partir mais c'est bien de voir quelqu'un faire ce qu'il voulait faire."\nFaire ce qu'on voulait faire. T'as voulu partir. T'as fait partir. Cette cohérence entre ce qu'on veut et ce qu'on fait c'est pas toujours là. Toi t'as ça. Bon voyage, [Prénom].\nAvec éloge de ta cohérence entre ce que tu voulais et ce que tu fais,\n— quelqu'un qui trouve cette cohérence belle à voir 🌿` },
  { id: 'dp_s4_008', text: `"C'est chelou de réaliser qu'on va communiquer différemment maintenant."\nDifféremment. Pas plus rarement forcément. Mais différemment. Les messages. Les appels. C'est chelou à imaginer. Et c'est bien pour toi quand même. Bon voyage, [Prénom].\nAvec description de la chelou-ité de la communication qui va changer de forme,\n— quelqu'un qui s'engage à communiquer différemment et régulièrement 📱` },
  { id: 'dp_s4_009', text: `"C'est chelou que ce soit déjà le moment de partir. Et c'est bien que ce moment soit arrivé."\nLe moment. Qui était dans le futur. Et qui est maintenant. Ce glissement du futur au présent. Chelou à réaliser. Et bien à vivre. Bon voyage, [Prénom].\nAvec description du glissement du futur au présent comme quelque chose de chelou et de bien,\n— quelqu'un qui trouve ce glissement temporel à la fois vertigineux et satisfaisant 🕰️` },
  { id: 'dp_s4_010', text: `"C'est chelou de te voir partir vers une vie qu'on ne connaîtra pas directement."\nCette vie. Là-bas. Qu'on va pas partager directement. Qu'on connaîtra qu'à travers ce que tu raconteras. C'est chelou d'être en dehors de cette vie. Et c'est bien qu'elle soit pour toi. Bon voyage, [Prénom].\nAvec description de la chelou-ité d'être en dehors de ta vie là-bas,\n— quelqu'un qui suivra cette vie de l'extérieur avec beaucoup d'intérêt 👁️` },
  { id: 'dp_s4_011', text: `"C'est chelou et bien et on s'y fait pas vraiment à l'idée que tu pars."\nOn s'y fait pas. Vraiment. L'idée que tu pars. Qu'il est réel. On sait mais on s'y fait pas. Et c'est ok de pas s'y faire. Bon voyage quand même, [Prénom].\nAvec honnêteté sur la difficulté de vraiment s'y faire à l'idée du départ,\n— quelqu'un qui s'y fait pas et qui le dit honnêtement 🌀` },
  { id: 'dp_s4_012', text: `"C'est chelou de te voir partir mais c'est bien de voir quelqu'un qui sait ce qu'il veut."\nSavoir ce qu'on veut. Et l'obtenir. T'as voulu partir. T'as organisé pour partir. Tu pars. Cette clarté c'est admirable. Bon voyage, [Prénom].\nAvec admiration pour ta clarté sur ce que tu veux et ta capacité à l'obtenir,\n— quelqu'un qui admire cette combinaison et qui te le dit 🎯` },
  { id: 'dp_s4_013', text: `"C'est chelou que tu seras là-bas pendant que les trucs habituels continuent ici."\nCette simultanéité. Toi là-bas à vivre quelque chose de nouveau. Nous ici à continuer les trucs habituels. Ces deux réalités en même temps. C'est chelou à concevoir. Bon voyage, [Prénom].\nAvec description de la chelou-ité de deux réalités simultanées dans des endroits différents,\n— quelqu'un qui trouvera ça chelou chaque fois qu'il pensera à toi là-bas 🌍` },
  { id: 'dp_s4_014', text: `"C'est chelou de te voir partir. Et c'est bien pour toi. On choisit de se concentrer sur le deuxième."\nCe choix. Actif. De se concentrer sur le bien pour toi. Plutôt que sur le chelou de te voir partir. Ce choix est une façon de t'aimer. Bon voyage, [Prénom].\nAvec description du choix actif de se concentrer sur le bien pour toi,\n— quelqu'un qui fait ce choix consciemment et qui pense que c'est la meilleure façon de t'aimer 💛` },
  { id: 'dp_s4_015', text: `"C'est chelou d'imaginer ta vie là-bas. Et c'est bien de savoir que tu vas en avoir une."\nCette vie. Que tu vas construire là-bas. Que tu vas habiter. C'est chelou de l'imaginer de l'extérieur. Et bien de savoir que tu vas en avoir une. Pleine. Réelle. À toi. Bon voyage, [Prénom].\nAvec description de la chelou-ité d'imaginer ta vie là-bas et du bien de savoir que tu vas en avoir une,\n— quelqu'un qui est content que tu ailles avoir cette vie 🌟` },
  { id: 'dp_s4_016', text: `"C'est chelou de te voir partir. C'est bien pour toi. Et les deux vont rester vrais longtemps."\nLongtemps. Le chelou de ton absence. Et le bien pour toi. Ces deux vérités vont rester vraies en parallèle. Et on vivra avec les deux. Bon voyage, [Prénom].\nAvec perspective sur la durée pendant laquelle les deux vérités vont coexister,\n— quelqu'un qui s'engage à vivre avec les deux pendant toute ta période là-bas 🌿` },
  { id: 'dp_s4_017', text: `"C'est chelou de pas te voir dans les endroits habituels. Et c'est bien de te savoir ailleurs."\nCes endroits habituels. Où t'étais. Où tu seras pas. Et l'idée que tu seras ailleurs. Que tu vas découvrir. C'est chelou et bien en même temps. Bon voyage, [Prénom].\nAvec description du chelou de l'absence dans les endroits habituels et du bien d'être ailleurs,\n— quelqu'un qui pensera à toi dans ces endroits habituels et qui sera content que tu sois ailleurs 🗺️` },
  { id: 'dp_s4_018', text: `"C'est chelou de te voir partir mais c'est bien de te voir faire quelque chose de grand."\nQuelque chose de grand. Ce départ. Cette décision. Cette vie qui s'ouvre. C'est grand. Et chelou de voir quelqu'un qu'on connaît faire quelque chose de grand. Bon voyage, [Prénom].\nAvec éloge de la grandeur de ce que tu fais malgré la chelou-ité de te voir partir,\n— quelqu'un qui trouve grand ce que tu fais et qui est un peu impressionné 🌟` },
  { id: 'dp_s4_019', text: `"C'est chelou que ce soit maintenant. Et c'est bien que ce soit maintenant."\nLe timing. Maintenant. Pas plus tard. Maintenant. C'est chelou parce que c'est maintenant. Et c'est bien parce que c'est maintenant. Le bon timing est toujours chelou et bien à la fois. Bon voyage, [Prénom].\nAvec réflexion sur le timing comme à la fois chelou et bien,\n— quelqu'un qui pense que le bon timing est toujours les deux en même temps ⏰` },
  { id: 'dp_s4_020', text: `"C'est chelou de te voir partir. C'est bien pour toi. Bon voyage, [Prénom]."\nSimple. Direct. La chelou-ité. Le bien pour toi. Et le souhait sincère. Ces trois choses suffisent. Bon voyage, [Prénom].\nAvec économie de mots totale parce que trois choses suffisent parfois,\n— quelqu'un qui dit tout ce qu'il faut en peu de mots ❤️` },
];

// ── S5 : On sera là quand tu reviens — promis ─────────────────────────────────
const S5: DepartMessage[] = [
  { id: 'dp_s5_001', text: `"On sera là quand tu reviens. Promis."\nSimple. Direct. Sans fioritures. On sera là. Ta place sera là. Les gens seront là. La relation sera là. Peut-être différente. Certainement enrichie. Mais là. Bon voyage, [Prénom].\nAvec promesse simple directe et sans fioritures,\n— quelqu'un qui fait cette promesse et qui la tient 🫂` },
  { id: 'dp_s5_002', text: `"Tu pars. On reste. Et quand tu reviens on sera encore là."\nCette permanence. Dans l'impermanence du départ. On reste ici. On continue. Et quand tu reviens on sera encore là. Pas figés. Pas pareils peut-être. Mais là. Bon voyage, [Prénom].\nAvec description de la permanence dans l'impermanence,\n— quelqu'un qui sera là et qui le sait avec certitude 💛` },
  { id: 'dp_s5_003', text: `"On sera là au retour. Et on voudra tout entendre."\nTout. Chaque histoire. Chaque anecdote. Chaque rencontre. Chaque moment difficile. Chaque moment magnifique. On voudra tout. Prépare-toi à raconter. Bon voyage, [Prénom].\nAvec anticipation avide de tout entendre au retour,\n— quelqu'un qui prévoit d'être un public très attentif au retour 📖` },
  { id: 'dp_s5_004', text: `"Ta place sera là quand tu reviens."\nTa place. Dans les conversations. Dans les soirées. Dans la relation. Ta place sera là. Pas occupée par quelqu'un d'autre. Pas oubliée. Là. T'attendant. Bon voyage, [Prénom].\nAvec assurance que ta place sera gardée,\n— quelqu'un qui veille sur ta place pendant ton absence 🪑` },
  { id: 'dp_s5_005', text: `"On sera là au retour. Et on sera curieux de qui tu seras devenu."\nLa curiosité du retour. De qui tu seras. Comment tu auras changé. Ce que tu auras appris. Cette version de toi qu'on connaît pas encore. On est déjà curieux. Bon voyage, [Prénom].\nAvec anticipation curieuse de la version de toi qu'on va rencontrer au retour,\n— quelqu'un qui attend avec impatience de rencontrer la version enrichie de toi 🔭` },
  { id: 'dp_s5_006', text: `"On sera là quand tu reviens. Et les histoires qu'on aura à échanger seront bonnes."\nTes histoires de là-bas. Nos histoires d'ici. Ces échanges croisés du retour seront bons. On les attend. Bon voyage, [Prénom].\nAvec anticipation des échanges croisés du retour,\n— quelqu'un qui accumule déjà des histoires à te raconter pour le retour 📚` },
  { id: 'dp_s5_007', text: `"La relation sera là quand tu reviens. Elle traverse les distances."\nLes vraies relations traversent les distances. Elles survivent aux absences. Notre relation traverse ta distance. Elle sera là au retour. Bon voyage, [Prénom].\nAvec affirmation de la capacité de la relation à traverser la distance,\n— quelqu'un qui pense que les vraies relations survivent aux absences et parfois en ressortent plus fortes 🌊` },
  { id: 'dp_s5_008', text: `"On sera là au retour. Et on sera fiers de ce que tu auras fait là-bas."\nFiers. Déjà. Avant même que tu sois parti vraiment. Et encore plus fiers au retour. De ce que tu auras vécu. Cette fierté du retour on l'anticipe déjà. Bon voyage, [Prénom].\nAvec anticipation de la fierté du retour,\n— quelqu'un qui sera encore plus fier au retour qu'il l'est maintenant 🌟` },
  { id: 'dp_s5_009', text: `"Tu pars pour un temps. On sera là pour après."\nPour après. Ce mot. Ce moment. Qui viendra. Quand ton séjour sera terminé. On sera là pour après. Pour accueillir. Pour reprendre. Bon voyage, [Prénom].\nAvec engagement pour l'après du voyage,\n— quelqu'un qui pense à l'après autant qu'au maintenant 🌅` },
  { id: 'dp_s5_010', text: `"On sera là quand tu reviens. Et la vie reprendra autrement."\nAutrement. Parce que toi tu auras changé. Et nous on aura changé. Et ce qu'on va construire ensemble après sera enrichi de ce que tu auras vécu. La vie reprendra. Autrement. Et mieux peut-être. Bon voyage, [Prénom].\nAvec perspective sur la vie qui reprendra différemment et peut-être mieux après,\n— quelqu'un qui pense que l'autrement est souvent le mieux 🌱` },
  { id: 'dp_s5_011', text: `"On sera là quand tu reviens. Et on aura des trucs à se dire."\nDes trucs accumulés. Pendant l'absence. Des choses qui se sont passées. Des pensées qui se sont formées. Ces échanges-là seront bons. Le retour sera riche. Bon voyage, [Prénom].\nAvec anticipation de la richesse de l'échange au retour,\n— quelqu'un qui accumule déjà des trucs à te dire pour le retour 💬` },
  { id: 'dp_s5_012', text: `"Ta place dans nos vies sera là au retour. Non négociable."\nNon négociable. Cette place. Elle est là. Elle sera là. Pendant toute ton absence. Et au retour. C'est une promesse ferme. Non négociable. Bon voyage, [Prénom].\nAvec fermeté non négociable sur la permanence de ta place,\n— quelqu'un qui tient cette promesse avec conviction 🔒` },
  { id: 'dp_s5_013', text: `"On sera là quand tu reviens. Et on est fiers de toi depuis maintenant jusqu'au retour."\nDepuis maintenant. En continu. Pendant tout ton séjour. La fierté ne s'arrête pas au départ. Elle continue. Elle accompagne. Bon voyage, [Prénom].\nAvec fierté continue depuis le départ jusqu'au retour,\n— quelqu'un qui sera fier de toi en continu pendant toute ton absence 💛` },
  { id: 'dp_s5_014', text: `"Le retour sera bon. On sera là. Et on célébrera."\nOn célébrera. Ton retour. Ce que tu auras vécu. Qui tu seras revenu. On célébrera tout ça. Au retour. Bon voyage, [Prénom].\nAvec annonce de la célébration prévue au retour,\n— quelqu'un qui commence déjà à planifier l'accueil du retour 🎉` },
  { id: 'dp_s5_015', text: `"On sera là quand tu reviens. Et en attendant on pense à toi."\nEn attendant. Pendant toute l'absence. On pense à toi. On se demande comment ça va. On imagine ce que tu vis. Cette pensée continue pendant l'absence. Bon voyage, [Prénom].\nAvec description de la pensée continue pendant l'absence,\n— quelqu'un qui pensera à toi régulièrement pendant tout ton séjour 💭` },
  { id: 'dp_s5_016', text: `"Tu reviendras. On sera là. Et ce moment-là sera beau."\nCe moment du retour. Qu'on anticipe déjà. Qui sera beau. Parce que les retours sont souvent beaux. Surtout ceux des gens qui comptent. Bon voyage, [Prénom].\nAvec anticipation de la beauté du moment du retour,\n— quelqu'un qui pense que les retours des gens qui comptent sont parmi les plus beaux moments 🌸` },
  { id: 'dp_s5_017', text: `"On sera là au retour. Et entre temps on sera là aussi. À distance mais là."\nÀ distance mais là. Cette présence à distance. Qui existe. Qui est réelle. On est là maintenant et on sera là au retour et entre les deux on sera là à distance. Bon voyage, [Prénom].\nAvec description de la présence à distance comme réelle et continue,\n— quelqu'un qui sera présent à distance pendant tout le voyage et heureux de l'être 📱` },
  { id: 'dp_s5_018', text: `"On sera là quand tu reviens parce qu'on sera toujours là."\nToujours. Pas juste pour le retour. Toujours. C'est le sens de cette promesse. On est là. On sera là. Pendant l'absence. Au retour. Après. Toujours. Bon voyage, [Prénom].\nAvec extension de la promesse d'être là au-delà du retour vers le toujours,\n— quelqu'un qui fait la promesse du toujours et qui la tient 💛` },
  { id: 'dp_s5_019', text: `"Bon voyage. Et reviens. On sera là."\nTrois phrases. L'essentiel. Le souhait. La demande. La promesse. Tout en trois phrases. Bon voyage, [Prénom].\nAvec économie de mots maximale sur les trois choses les plus importantes,\n— quelqu'un qui pense que ces trois phrases contiennent tout ce qu'il faut dire 🎯` },
  { id: 'dp_s5_020', text: `"On sera là quand tu reviens. Promis. Bon voyage, [Prénom]."\nLa promesse. Directe. Ferme. Sincère. On sera là. Promis. Et bon voyage. Parce que parfois peu de mots suffisent pour dire tout ce qui compte. Bon voyage, [Prénom].\nAvec promesse ferme et souhait sincère en peu de mots,\n— quelqu'un qui tient ses promesses et qui te souhaite le meilleur des voyages ❤️` },
];

// ── Export ────────────────────────────────────────────────
export const DEPART_GROUPS: DepartSubGroup[] = [
  { id: 'dp_s1', title: 'Tu pars et on est fiers et tristes en même temps',      emoji: '🌍', messages: S1 },
  { id: 'dp_s2', title: "T'as osé partir — no cap t'assures",                   emoji: '✈️', messages: S2 },
  { id: 'dp_s3', title: "Tu vas manquer mais c'est le bon move",                emoji: '💛', messages: S3 },
  { id: 'dp_s4', title: "C'est chelou de te voir partir mais c'est bien pour toi", emoji: '🌀', messages: S4 },
  { id: 'dp_s5', title: 'On sera là quand tu reviens — promis',                 emoji: '🫂', messages: S5 },
];
