// ═══════════════════════════════════════════════════════════
//  Confettis & Cake — 18 ans (occasion à part entière)
// ═══════════════════════════════════════════════════════════

export interface DixHuitAnsMessage {
  id: string;
  text: string;
}

export interface DixHuitAnsSubGroup {
  id: string;
  title: string;
  emoji: string;
  messages: DixHuitAnsMessage[];
}

// ── S1 : T'es officiellement adulte — bonne chance ───────
const S1: DixHuitAnsMessage[] = [
  { id: 'dha_s1_001', text: `"T'es officiellement adulte. Bonne chance."\nC'est dit. Le statut est là. Officiel. Légal. Reconnu par tous les papiers qui vont maintenant te traiter différemment. Adulte. Avec tout ce que ça implique. De responsabilités. De libertés. De trucs à gérer. Bonne chance. Joyeux anniversaire, [Prénom].\nAvec solennité appropriée et bonne chance sincère,\n— quelqu'un qui pense que la bonne chance est le meilleur cadeau qu'on peut faire à un adulte 🎂` },
  { id: 'dha_s1_002', text: `"18 ans. T'es adulte. Et personne te demande si t'es prêt."\nC'est ça le truc. T'es adulte à 18 ans que t'y sois prêt ou pas. Le calendrier s'en fout. La société s'en fout. T'as 18 ans donc t'es adulte. Bonne chance avec cette transition forcée. Joyeux anniversaire, [Prénom].\nAvec honnêteté sur le caractère forcé de la transition à 18 ans,\n— quelqu'un qui pense qu'on aurait dû demander si t'étais prêt mais qui confirme que personne le fait 🎯` },
  { id: 'dha_s1_003', text: `"Joyeux anniversaire. T'as 18 ans. C'est une étape. Une vraie."\nPas comme les autres anniversaires. Celui-là change des trucs. Légalement. Socialement. Dans la façon dont le monde te regarde. Dans ce qui t'est accessible maintenant. C'est une vraie étape. Joyeux anniversaire, [Prénom].\nAvec distinction de cet anniversaire comme vraiment différent des autres,\n— quelqu'un qui pense que 18 ans mérite une reconnaissance particulière 🌟` },
  { id: 'dha_s1_004', text: `"T'as 18 ans. Officiellement adulte. Officieusement t'as encore des trucs à apprendre."\nOfficieusement. Parce que le papier dit adulte mais la vie dira encore autre chose pendant un moment. Et c'est normal. Et c'est bien. Être adulte ça s'apprend. Ça s'acquiert. Ça se construit. T'as commencé. Joyeux anniversaire, [Prénom].\nAvec distinction entre le adulte officiel et le adulte acquis progressivement,\n— quelqu'un qui pense que devenir adulte dure bien plus longtemps que le 18ème anniversaire 🎓` },
  { id: 'dha_s1_005', text: `"Joyeux anniversaire. T'es majeur. Le monde va te traiter différemment."\nLes contrats. Les votes. Les responsabilités légales. La façon dont les institutions te voient. Tout ça change. T'es majeur. Et le monde traite les majeurs différemment. Prépare-toi à ce changement de regard. Joyeux anniversaire, [Prénom].\nAvec préparation au changement de regard du monde sur toi maintenant que t'es majeur,\n— quelqu'un qui pense que ce changement est réel et mérite d'être anticipé 👁️` },
  { id: 'dha_s1_006', text: `"18 ans. Bonne chance. Et sache que tout le monde improvise."\nCe secret. Que les adultes ne disent pas toujours. Tout le monde improvise. Même les adultes qui semblent avoir tout compris. Improvisation généralisée. Bienvenue dans le club. Joyeux anniversaire, [Prénom].\nAvec révélation du grand secret de l'improvisation adulte à l'entrée dans le club,\n— quelqu'un qui improvise depuis des années et qui t'accueille avec solidarité 🎭` },
  { id: 'dha_s1_007', text: `"Joyeux anniversaire. T'es adulte. Et c'est à la fois excitant et un peu flippant."\nLes deux ensemble. L'excitation des nouvelles libertés. Le flippage des nouvelles responsabilités. Ces deux sensations simultanées. C'est exactement ce que ça fait d'avoir 18 ans. C'est normal. C'est bien même. Joyeux anniversaire, [Prénom].\nAvec validation de la coexistence de l'excitation et du flippage à 18 ans,\n— quelqu'un qui a vécu les deux et qui confirme que les deux sont normaux 🌀` },
  { id: 'dha_s1_008', text: `"T'as 18 ans. Les libertés arrivent avec les responsabilités. Le package est complet."\nLe package. Voté. Conduire peut-être. Signer des contrats. Être responsable légalement. Ces libertés et ces responsabilités arrivent ensemble. Le package est complet. Bienvenue dans le package. Joyeux anniversaire, [Prénom].\nAvec description du package complet libertés-responsabilités qui arrive à 18 ans,\n— quelqu'un qui pense que le package mérite d'être connu avant d'être ouvert 📦` },
  { id: 'dha_s1_009', text: `"Joyeux anniversaire. T'as 18 ans. Maintenant t'as le droit de voter. Utilise-le."\nCe droit. Qui arrive avec la majorité. Qui est précieux. Qui mérite d'être utilisé. Utilise-le. C'est le premier conseil de bienvenue dans l'âge adulte. Joyeux anniversaire, [Prénom].\nAvec premier conseil de bienvenue dans l'âge adulte sur le droit de vote,\n— quelqu'un qui pense que voter est une des premières responsabilités sérieuses de l'adulte 🗳️` },
  { id: 'dha_s1_010', text: `"T'as 18 ans. C'est officiel. Et c'est ta vie maintenant. Vraiment ta vie."\nTa vie. Vraiment. Avec tout ce que ça implique de choix. De responsabilités. De directions. Cette vie-là elle est à toi maintenant. Vraiment. Bienvenue dedans. Joyeux anniversaire, [Prénom].\nAvec accueil dans ta vraie vie maintenant vraiment la tienne,\n— quelqu'un qui pense que c'est une des plus belles choses qui soit d'avoir sa vie vraiment à soi 🌍` },
  { id: 'dha_s1_011', text: `"Joyeux anniversaire. Bonne chance. Et sache que les adultes sont souvent aussi perdus que toi."\nSouvent. Pas toujours. Mais souvent. Cette apparence d'avoir tout compris. C'est souvent une apparence. En dessous c'est souvent aussi flottant que ce que tu ressens. Tu n'es pas seul dans ce flottement. Joyeux anniversaire, [Prénom].\nAvec validation que le flottement que tu ressens est partagé par beaucoup d'adultes,\n— quelqu'un qui flotte encore parfois et qui te confirme que c'est normal 🌊` },
  { id: 'dha_s1_012', text: `"T'as 18 ans. Le monde t'appartient. Enfin légalement cette fois."\nLégalement. Vraiment. T'as accès à des trucs que t'avais pas avant. Des droits. Des responsabilités. Des possibilités. Le monde t'appartient légalement. Fais-en quelque chose. Joyeux anniversaire, [Prénom].\nAvec nuance importante que cette fois c'est légalement que le monde t'appartient,\n— quelqu'un qui pense que cette légalité change quelque chose dans la réalité 🌟` },
  { id: 'dha_s1_013', text: `"Joyeux anniversaire. 18 ans. Et maintenant t'as toute une vie adulte devant toi."\nDevant. Toute cette vie adulte. Qui commence maintenant. Qui va durer. Qui va être pleine. De bonnes choses. De moins bonnes. D'imprévus. De joies. De défis. C'est beaucoup. C'est bien. Joyeux anniversaire, [Prénom].\nAvec perspective sur toute la vie adulte qui commence maintenant,\n— quelqu'un qui pense que cette perspective est à la fois vertigineuse et exaltante 🚀` },
  { id: 'dha_s1_014', text: `"T'as 18 ans. Bonne chance. Et n'oublie pas que demander de l'aide c'est adulte."\nCe truc qu'on apprend souvent trop tard. Que demander de l'aide c'est pas de la faiblesse. C'est de la maturité. C'est adulte. Dès maintenant. Joyeux anniversaire, [Prénom].\nAvec conseil précoce sur le fait que demander de l'aide c'est adulte,\n— quelqu'un qui espère que tu apprendras ça plus vite qu'il ne l'a appris lui-même 🤝` },
  { id: 'dha_s1_015', text: `"Joyeux anniversaire. T'es adulte officiellement. Dans les faits c'est un processus."\nUn processus. Pas un bouton. Pas un interrupteur. Un processus. Long. Non linéaire. En cours chez tout le monde. T'as commencé le tien. Joyeux anniversaire, [Prénom].\nAvec description de l'adulte comme processus non linéaire plutôt qu'état soudain,\n— quelqu'un qui est encore dans ce processus et qui te confirme qu'il dure longtemps 🌱` },
  { id: 'dha_s1_016', text: `"18 ans. T'es adulte. Et les adultes mangent des légumes et dorment à des heures raisonnables."\nCe conseil. Pratique. Que tout le monde donne et que personne suit vraiment au début. Les légumes. Le sommeil. Ces bases. Que l'âge adulte demande. En théorie. Joyeux anniversaire quand même, [Prénom].\nAvec conseil pratique légèrement ironique sur les bases de l'âge adulte,\n— quelqu'un qui ne mange pas toujours ses légumes et qui le dit 😄` },
  { id: 'dha_s1_017', text: `"Joyeux anniversaire. T'as 18 ans. C'est ta fête. Profite avant que les responsabilités prennent trop de place."\nAvant. Ce moment avant. Où on peut encore profiter légèrement. Avant que le loyer. Les charges. Les impôts. Les trucs sérieux prennent trop de place. Profite maintenant. C'est un conseil sincère. Joyeux anniversaire, [Prénom].\nAvec conseil sincère de profiter avant que les responsabilités prennent trop de place,\n— quelqu'un qui regrette parfois de pas avoir assez profité avant 🌟` },
  { id: 'dha_s1_018', text: `"T'as 18 ans. Officiellement adulte. Et tout le monde autour de toi est là pour toi."\nLà. Dans cette transition. Dans cette étape. Tout le monde autour de toi est là. Pour accompagner. Pour soutenir. Pour aider quand c'est difficile. T'es adulte mais t'es pas seul. Joyeux anniversaire, [Prénom].\nAvec rappel que être adulte ne veut pas dire être seul,\n— quelqu'un qui sera là dans la vie adulte comme dans la vie d'avant 🫂` },
  { id: 'dha_s1_019', text: `"Joyeux anniversaire. 18 ans. La suite est grande. Et t'es prêt."\nPrêt. Peut-être pas pour tout. Mais prêt pour commencer. Pour entrer dans cette suite. Pour construire ce qui vient. T'as ce qu'il faut. La suite est grande. T'es prêt. Joyeux anniversaire, [Prénom].\nAvec affirmation que t'es prêt pour la suite même si pas pour tout,\n— quelqu'un qui pense que t'as ce qu'il faut et qui te le dit sans hésitation 💪` },
  { id: 'dha_s1_020', text: `"T'es officiellement adulte. Bonne chance. Et joyeux anniversaire, [Prénom]."\nSimple. Direct. Le statut. Le souhait. Et la célébration. Tout ce qu'il faut dans l'ordre qui convient. Bonne chance dans cette vie adulte. Et joyeux anniversaire. Joyeux anniversaire, [Prénom].\nAvec économie de mots totale parce que parfois la simplicité est la meilleure façon de marquer les grandes étapes,\n— quelqu'un qui te souhaite la meilleure des vies adultes ❤️` },
];

// ── S2 : No cap t'assures pour quelqu'un qui vient d'avoir 18 ans ─────────────
const S2: DixHuitAnsMessage[] = [
  { id: 'dha_s2_001', text: `"No cap t'assures pour quelqu'un qui vient d'avoir 18 ans."\nPour ton âge. Dans le contexte. T'as une maturité. Une façon d'être. Des trucs en place. Qui disent que l'adulte qui commence c'est quelqu'un de solide. No cap t'assures. Joyeux anniversaire, [Prénom].\nAvec constat sincère de ton niveau pour quelqu'un qui vient d'avoir 18 ans,\n— quelqu'un qui t'évalue dans le contexte et qui te met haut 📊` },
  { id: 'dha_s2_002', text: `"T'as 18 ans et t'as déjà des trucs en place que certains mettent des années à construire."\nCes trucs. Que t'as déjà. Cette maturité. Ces qualités. Que certains développent beaucoup plus tard. T'as commencé tôt. Et ça se voit. No cap. Joyeux anniversaire, [Prénom].\nAvec reconnaissance que t'as des trucs en place en avance sur beaucoup,\n— quelqu'un qui voit ces trucs et qui te confirme qu'ils sont là 🌱` },
  { id: 'dha_s2_003', text: `"No cap t'assures dans ta façon d'être toi à 18 ans."\nÊtre soi. À 18 ans. C'est pas si évident. Y'a des pressions. Des attentes. Des modèles. Et toi t'as une façon d'être toi qui est claire. Qui est assumée. No cap t'assures d'être toi. Joyeux anniversaire, [Prénom].\nAvec éloge de ta façon d'être toi à 18 ans comme quelque chose de pas si évident,\n— quelqu'un qui pense qu'être soi à 18 ans demande du courage 🌿` },
  { id: 'dha_s2_004', text: `"T'assures dans ta façon de gérer les trucs que 18 ans apporte."\nCes trucs nouveaux. Ces responsabilités. Ces libertés. Ces décisions. T'as une façon de gérer tout ça qui dit que tu vas t'en sortir. No cap. Joyeux anniversaire, [Prénom].\nAvec admiration pour ta façon de gérer ce que 18 ans apporte,\n— quelqu'un qui observe ta gestion avec satisfaction 💪` },
  { id: 'dha_s2_005', text: `"No cap t'assures d'avoir grandi comme t'as grandi."\nCette façon de grandir. Qui est la tienne. Avec ce que t'as traversé. Ce que t'as appris. Cette façon de grandir a produit quelqu'un de bien. No cap. Joyeux anniversaire, [Prénom].\nAvec éloge de ta façon spécifique de grandir et du résultat qu'elle a produit,\n— quelqu'un qui pense que ton chemin a produit quelqu'un de bien 🌟` },
  { id: 'dha_s2_006', text: `"T'as 18 ans et t'as déjà des valeurs qui tiennent. No cap t'assures."\nDes valeurs. À 18 ans. Qui sont là. Qui guident. Qui tiennent même sous la pression. Ces valeurs-là à ton âge c'est pas universel. No cap. Joyeux anniversaire, [Prénom].\nAvec reconnaissance de tes valeurs à 18 ans comme quelque chose de pas universel,\n— quelqu'un qui voit tes valeurs et qui les respecte 🧭` },
  { id: 'dha_s2_007', text: `"No cap t'assures dans ta relation aux autres pour quelqu'un qui a 18 ans."\nCette façon d'être avec les gens. De les traiter. De créer des liens. Cette intelligence relationnelle à 18 ans c'est pas donnée à tout le monde. La tienne est là. No cap. Joyeux anniversaire, [Prénom].\nAvec admiration pour ton intelligence relationnelle à 18 ans,\n— quelqu'un qui pense que cette intelligence est une des plus précieuses qui soit 🤝` },
  { id: 'dha_s2_008', text: `"T'assures dans ta façon de déjà savoir des trucs sur toi."\nCette connaissance de soi. À 18 ans. Tu sais des trucs sur toi. Tes besoins. Tes limites. Tes forces. Cette connaissance précoce c'est un avantage réel. No cap. Joyeux anniversaire, [Prénom].\nAvec éloge de ta connaissance de toi-même comme avantage réel à 18 ans,\n— quelqu'un qui pense que cette connaissance précoce va te servir toute ta vie 🪞` },
  { id: 'dha_s2_009', text: `"No cap t'assures d'avoir des projets à 18 ans."\nDes projets. Des envies. Des directions. Des trucs vers quoi tu avances. Cette orientation vers quelque chose. Ce n'est pas universel à 18 ans. Beaucoup flottent. Toi t'as des projets. No cap. Joyeux anniversaire, [Prénom].\nAvec éloge de tes projets à 18 ans comme quelque chose d'utile et pas universel,\n— quelqu'un qui trouve tes projets inspirants et qui veut en entendre plus 🚀` },
  { id: 'dha_s2_010', text: `"T'assures dans ta façon d'être quelqu'un de fiable à 18 ans."\nFiable. À 18 ans. Qui fait ce qu'il dit. Qui tient ses engagements. Cette fiabilité à cet âge c'est pas donnée. Et la tienne est réelle. No cap. Joyeux anniversaire, [Prénom].\nAvec reconnaissance de ta fiabilité à 18 ans comme quelque chose de pas universel,\n— quelqu'un qui a testé ta fiabilité et qui confirme qu'elle est là 🔒` },
  { id: 'dha_s2_011', text: `"No cap t'assures dans ta façon de gérer les trucs difficiles."\nCes trucs difficiles. Que la vie a déjà mis sur ton chemin. Que tu as traversés. À ta façon. Et qui t'ont construit. Ta façon de gérer le difficile dit quelque chose de bien sur toi. No cap. Joyeux anniversaire, [Prénom].\nAvec respect pour ta façon de gérer les trucs difficiles déjà rencontrés,\n— quelqu'un qui a vu certains de ces trucs difficiles et qui confirme que tu t'en es bien sorti 💪` },
  { id: 'dha_s2_012', text: `"T'as 18 ans et t'as déjà une façon d'être dans le monde qui est la tienne. No cap."\nDans le monde. Ta façon d'y être. Distincte. Reconnaissable. Toi. Pas une copie. T'as ça. À 18 ans. C'est quelque chose. No cap. Joyeux anniversaire, [Prénom].\nAvec éloge de ta façon distincte d'être dans le monde à 18 ans,\n— quelqu'un qui reconnaît ta façon d'être comme distinctement toi 🌍` },
  { id: 'dha_s2_013', text: `"No cap t'assures pour quelqu'un qui commence. Et t'imagines même pas à quel point t'iras loin."\nCe début. Et ce qu'il annonce. Pour quelqu'un qui commence comme tu commences. Avec ce que tu as déjà. Ce que tu vas construire. T'imagines même pas. No cap. Joyeux anniversaire, [Prénom].\nAvec anticipation de ce que tu vas devenir à partir de ce début,\n— quelqu'un qui pense que ton début dit de très bonnes choses sur la suite 🔭` },
  { id: 'dha_s2_014', text: `"T'assures dans ta façon d'être curieux du monde à 18 ans."\nCette curiosité. Du monde. Des gens. Des idées. À 18 ans. Cette ouverture à ce qui existe. Cette façon de vouloir comprendre. D'être intéressé. No cap t'assures d'avoir ça. Joyeux anniversaire, [Prénom].\nAvec éloge de ta curiosité du monde à 18 ans comme qualité précieuse,\n— quelqu'un qui pense que la curiosité est une des meilleures choses qu'on puisse avoir à n'importe quel âge 🔭` },
  { id: 'dha_s2_015', text: `"No cap t'assures. Et la vie adulte va te convenir."\nCette prédiction. Que la vie adulte va te convenir. Basée sur ce que tu es déjà. Sur tes qualités. Sur ta façon d'être. La vie adulte te conviendra parce que t'as les trucs pour. No cap. Joyeux anniversaire, [Prénom].\nAvec prédiction confiante que la vie adulte va te convenir,\n— quelqu'un qui base cette prédiction sur des observations réelles et qui la maintient 🌟` },
  { id: 'dha_s2_016', text: `"T'assures dans ta façon d'assumer ce que t'es à 18 ans."\nD'assumer. À un âge où la pression est forte. Et toi t'assumes. Ce que t'es. Sans trop de compromis. No cap. Joyeux anniversaire, [Prénom].\nAvec admiration pour ta façon d'assumer ce que t'es sous la pression de la conformité,\n— quelqu'un qui pense que s'assumer à 18 ans prend du courage 🌿` },
  { id: 'dha_s2_017', text: `"No cap t'assures et les gens autour de toi le voient."\nIls voient. Ceux qui te connaissent. Ceux qui t'observent. Ils voient que t'assures. Tu seras peut-être le dernier à le voir. Mais les autres le voient. No cap. Joyeux anniversaire, [Prénom].\nAvec invitation à voir ce que les autres voient de toi,\n— quelqu'un qui voit et qui te le dit parce que t'as besoin de le savoir 👁️` },
  { id: 'dha_s2_018', text: `"T'as 18 ans. T'assures. Et ça va continuer. On en est sûrs."\nCette continuité. Ce que t'as déjà va se développer. S'enrichir. Grandir avec toi. L'adulte que tu deviens va assurer. Parce que la base est bonne. No cap. Joyeux anniversaire, [Prénom].\nAvec confiance dans la continuité de ton assurance,\n— quelqu'un qui pense que la bonne base que t'as produit inévitablement de bonnes choses 💪` },
  { id: 'dha_s2_019', text: `"No cap t'assures pour quelqu'un qui vient d'avoir 18 ans. Et t'assures pour quelqu'un de n'importe quel âge."\nLa précision pour ton âge était courtoise. En réalité t'assures point. Sans restriction d'âge. T'assures. Et ça se voit. Joyeux anniversaire, [Prénom].\nAvec retrait de la restriction d'âge pour dire que t'assures point,\n— quelqu'un qui retire la nuance pour être plus direct sur le fond 🎯` },
  { id: 'dha_s2_020', text: `"No cap t'assures pour quelqu'un qui vient d'avoir 18 ans. Joyeux anniversaire, [Prénom]."\nSimple. Direct. L'essentiel. T'assures. Pour ton âge. Et au-delà. Joyeux anniversaire. Bon début dans la vie adulte. Joyeux anniversaire, [Prénom].\nAvec économie de mots totale sur l'essentiel,\n— quelqu'un qui pense que tu mérites cet anniversaire et tous ceux qui suivront ❤️` },
];

// ── S3 : 18 ans c'est chelou et bien en même temps ───────
const S3: DixHuitAnsMessage[] = [
  { id: 'dha_s3_001', text: `"18 ans. C'est chelou. C'est bien. Les deux ensemble."\nChelou parce que c'est nouveau. Chelou parce que l'étiquette adulte arrive d'un coup. Et bien parce que c'est une étape. Une vraie. Une nouvelle liberté. Un nouveau chapitre. Joyeux anniversaire, [Prénom].\nAvec validation de la chelou-ité et du bien de 18 ans simultanément,\n— quelqu'un qui confirme que les deux coexistent et que c'est normal 🌀` },
  { id: 'dha_s3_002', text: `"C'est chelou d'avoir 18 ans. Et c'est bien d'avoir 18 ans. Ces deux trucs sont vrais."\nPas l'un ou l'autre. Les deux. En même temps. C'est chelou parce que c'est un seuil. C'est bien parce que c'est un seuil. Le même seuil produit les deux. Joyeux anniversaire, [Prénom].\nAvec identification du seuil comme produisant simultanément le chelou et le bien,\n— quelqu'un qui pense que les seuils importants font toujours ça 🚪` },
  { id: 'dha_s3_003', text: `"18 ans c'est chelou d'être officiellement adulte sans se sentir forcément différent."\nCe décalage. Entre le statut officiel et la sensation interne. T'es adulte officiellement. Et tu te sens peut-être pas si différent qu'hier. C'est chelou ce décalage. Et c'est normal. Le sentiment vient après. Joyeux anniversaire, [Prénom].\nAvec validation du décalage chelou entre le statut officiel et la sensation interne,\n— quelqu'un qui se souvient de ce décalage et qui confirme que c'est universel 🌀` },
  { id: 'dha_s3_004', text: `"C'est chelou de réaliser que c'est maintenant qu'on est adulte."\nMaintenant. Ce moment précis. Où on réalise que c'est maintenant. Pas dans quelques années. Maintenant. C'est chelou à réaliser. Parce que maintenant ça fait beaucoup. Joyeux anniversaire, [Prénom].\nAvec description de la chelou-ité de la réalisation que c'est maintenant,\n— quelqu'un qui se souvient de cette réalisation et de son effet 🕰️` },
  { id: 'dha_s3_005', text: `"18 ans c'est chelou d'avoir plus d'obligations qu'avant."\nCes obligations nouvelles. Ces responsabilités légales. Ces trucs qui s'ajoutent. Ces droits qui viennent avec des devoirs. C'est chelou d'en avoir plus. Et c'est bien parce que ça dit que t'es quelqu'un à qui on fait confiance. Joyeux anniversaire, [Prénom].\nAvec réinterprétation des nouvelles obligations comme preuve de confiance accordée,\n— quelqu'un qui pense que la chelou-ité des obligations cache quelque chose de bien 🌱` },
  { id: 'dha_s3_006', text: `"C'est chelou et bien d'avoir 18 ans parce que personne t'explique vraiment comment ça marche."\nCe manque de mode d'emploi. Cette transition sans instructions. C'est chelou. Et c'est aussi bien parce que chacun construit son adulte à sa façon. Joyeux anniversaire, [Prénom].\nAvec identification de l'absence de mode d'emploi comme chelou et potentiellement bien,\n— quelqu'un qui pense que construire son adulte à sa façon est une liberté précieuse 🎨` },
  { id: 'dha_s3_007', text: `"18 ans c'est chelou d'avoir le droit de faire des trucs qu'on faisait peut-être déjà."\nCette ironie. Des droits qui légalisent ce qui existait peut-être déjà en pratique. C'est chelou que le droit arrive après la pratique parfois. Joyeux anniversaire, [Prénom].\nAvec observation légèrement ironique sur les droits qui arrivent parfois après la pratique,\n— quelqu'un qui fait cette observation avec bienveillance et sans jugement 😄` },
  { id: 'dha_s3_008', text: `"C'est chelou de réaliser que la société te considère maintenant comme responsable de tes actes."\nCette responsabilité légale. Qui arrive à 18 ans. C'est chelou à réaliser. Et c'est bien d'être traité comme quelqu'un de responsable. Joyeux anniversaire, [Prénom].\nAvec description de la chelou-ité et du bien d'être considéré comme responsable de ses actes,\n— quelqu'un qui pense que la responsabilité est chelou et digne à la fois 🎯` },
  { id: 'dha_s3_009', text: `"18 ans c'est chelou et bien d'être à l'entrée d'une vie qui est vraiment la tienne."\nL'entrée. Ce seuil. De cette vie qui est vraiment la tienne. Pas la vie que d'autres ont construite pour toi. La tienne. Que tu vas construire. C'est chelou ce seuil. Et c'est bien d'y être. Joyeux anniversaire, [Prénom].\nAvec identification du seuil de la vie vraiment sienne comme chelou et bien,\n— quelqu'un qui pense que ce seuil mérite d'être célébré 🌟` },
  { id: 'dha_s3_010', text: `"C'est chelou d'avoir 18 ans et de se demander si on est vraiment prêt."\nCette question. Suis-je prêt. Tout le monde se la pose à 18 ans. Personne n'est jamais vraiment prêt. Tout le monde devient adulte quand même. C'est chelou. Et c'est bien. Joyeux anniversaire, [Prénom].\nAvec validation que se demander si on est prêt à 18 ans est universel,\n— quelqu'un qui s'est posé cette question et qui confirme qu'on devient adulte quand même 🌊` },
  { id: 'dha_s3_011', text: `"18 ans c'est chelou de réaliser que les adultes qu'on regardait comme des modèles avaient notre âge un jour."\nCette réalisation. Que ces gens. Ces adultes. Ces modèles. Avaient 18 ans. Et ne savaient pas plus. Et sont devenus qui ils sont quand même. C'est chelou et rassurant. Joyeux anniversaire, [Prénom].\nAvec réalisation rassurante que tout le monde avait 18 ans un jour,\n— quelqu'un qui pense que cette réalisation est parmi les plus rassurantes 🌍` },
  { id: 'dha_s3_012', text: `"C'est chelou et bien d'avoir 18 ans dans ce monde-là."\nCe monde. Avec tout ce qu'il a. De difficile. De possible. D'avoir 18 ans dedans. C'est chelou. Et c'est bien. Et c'est maintenant. Joyeux anniversaire, [Prénom].\nAvec reconnaissance de la chelou-ité et du bien d'avoir 18 ans dans ce monde précis,\n— quelqu'un qui pense que ce monde avec tout ce qu'il a mérite d'être habité avec courage 🌍` },
  { id: 'dha_s3_013', text: `"18 ans c'est chelou d'être l'adulte qu'on voulait devenir enfant."\nCet adulte. Qu'on imaginait enfant. Qu'on voulait être. Et qu'on est maintenant. Officiellement. C'est chelou de se retrouver à cet endroit qu'on imaginait de loin. Joyeux anniversaire, [Prénom].\nAvec description de la chelou-ité d'être enfin l'adulte qu'on imaginait enfant,\n— quelqu'un qui trouve cette réalisation à la fois absurde et belle 🌸` },
  { id: 'dha_s3_014', text: `"C'est chelou de réaliser que les 18 ans c'était une date dans le futur et que c'est maintenant."\nLe futur qui devient maintenant. Cette date qu'on voyait de loin. Et qui est maintenant. Aujourd'hui. Ce glissement du futur au présent. C'est chelou et bien. Joyeux anniversaire, [Prénom].\nAvec description du glissement de la date abstraite au moment réel,\n— quelqu'un qui pense que ces glissements sont parmi les moments les plus chelous de la vie ⏰` },
  { id: 'dha_s3_015', text: `"18 ans c'est chelou d'avoir des droits et chelou d'avoir les responsabilités qui vont avec."\nLes deux côtés du même seuil. Les droits. Et les responsabilités. Qui arrivent ensemble. C'est chelou les deux. Et c'est bien les deux. Et les deux font l'adulte. Joyeux anniversaire, [Prénom].\nAvec reconnaissance que droits et responsabilités arrivent ensemble et sont chelous ensemble,\n— quelqu'un qui pense que comprendre le lien entre les deux est déjà de la maturité ⚖️` },
  { id: 'dha_s3_016', text: `"C'est chelou et bien d'avoir 18 ans parce que c'est un birthday qui change quelque chose."\nPas comme les autres. Pas juste un an de plus. Un birthday qui change le statut. Les droits. La façon dont le monde te voit. C'est chelou. C'est bien. Joyeux anniversaire, [Prénom].\nAvec distinction de ce birthday comme différent de tous les autres,\n— quelqu'un qui pense que ce birthday mérite une célébration à la hauteur de ce qu'il représente 🎂` },
  { id: 'dha_s3_017', text: `"18 ans c'est chelou d'avoir le sentiment que tout commence et que plein de choses finissent."\nCette double sensation. Quelque chose qui commence. L'âge adulte. Et quelque chose qui finit. Une certaine enfance. Une certaine irresponsabilité. Les deux à la fois. C'est chelou et c'est bien. Joyeux anniversaire, [Prénom].\nAvec validation de la double sensation de début et de fin à 18 ans,\n— quelqu'un qui a vécu les deux et qui confirme que les deux sont réels 🌀` },
  { id: 'dha_s3_018', text: `"C'est chelou d'avoir 18 ans et de pas encore savoir exactement qui on va être."\nCette incertitude. Sur soi. C'est chelou de pas savoir à 18 ans. Et c'est bien. Parce que ne pas savoir c'est rester ouvert. Et rester ouvert à 18 ans c'est la meilleure position. Joyeux anniversaire, [Prénom].\nAvec réhabilitation de ne pas savoir à 18 ans comme position ouverte et précieuse,\n— quelqu'un qui pense que l'ouverture à 18 ans est une ressource précieuse 🌿` },
  { id: 'dha_s3_019', text: `"18 ans c'est chelou et bien et on t'aime à cet âge comme à tous les autres."\nÀ cet âge. Avec sa chelou-ité. Avec son bien. On t'aime. Peut-être plus. Avec une fierté supplémentaire. Joyeux anniversaire, [Prénom].\nAvec déclaration d'amour à 18 ans comme à tous les autres âges,\n— quelqu'un qui t'aime à cet âge et à tous ceux qui suivront 💛` },
  { id: 'dha_s3_020', text: `"18 ans. Chelou. Bien. Joyeux anniversaire, [Prénom]."\nTrois mots. L'âge. Le chelou. Le bien. Et le souhait. Tout en peu. Joyeux anniversaire, [Prénom].\nAvec économie de mots maximale parce que parfois trois mots disent tout,\n— quelqu'un qui pense que la concision est honnête et que tu mérites cet anniversaire ❤️` },
];

// ── S4 : C'est pas le move d'être adulte mais on t'aime ──
const S4: DixHuitAnsMessage[] = [
  { id: 'dha_s4_001', text: `"Joyeux anniversaire. T'es adulte maintenant. C'est pas toujours le move d'être adulte. On t'aime quand même."\nParce que la vie adulte c'est pas que des bonnes choses. C'est des impôts. Des charges. Des responsabilités. Des trucs à gérer. C'est pas toujours le move. Et on t'aime dedans. Joyeux anniversaire, [Prénom].\nAvec honnêteté sur les aspects pas le move de la vie adulte et amour quand même,\n— quelqu'un qui pense que la vérité sur la vie adulte mérite d'être dite dès le départ 💙` },
  { id: 'dha_s4_002', text: `"T'as 18 ans. Le monde des adultes a des réunions inutiles et des impôts. On t'aime."\nBienvenue dans ce monde. Avec ses réunions. Ses impôts. Ses formulaires. Ses complexités. Ses absurdités. C'est pas toujours le move. Et on t'aime dans ce monde quand même. Joyeux anniversaire, [Prénom].\nAvec bienvenue honnête dans le monde des adultes avec ses aspects pas le move,\n— quelqu'un qui t'accueille dans ce monde avec solidarité et bienveillance 😅` },
  { id: 'dha_s4_003', text: `"C'est pas le move de payer des impôts. Bonne chance pour tes premiers. On t'aime."\nLes impôts. Ce premier contact avec la réalité fiscale. C'est pas le move. C'est inévitable. Et on t'aime dans cette inévitabilité. Joyeux anniversaire, [Prénom].\nAvec solidarité préventive pour les premiers impôts et amour dans l'inévitable,\n— quelqu'un qui paie ses impôts et qui partage cette solidarité fiscale avec toi 💶` },
  { id: 'dha_s4_004', text: `"Joyeux anniversaire. T'es adulte. Les adultes se plaignent beaucoup. C'est normal. On t'aime."\nCes plaintes. Sur le travail. Sur les prix. Sur la politique. C'est une activité adulte majeure. T'as maintenant l'âge officiel pour y participer. Bienvenue dans les plaintes collectives. Joyeux anniversaire, [Prénom].\nAvec bienvenue dans l'activité adulte majeure des plaintes collectives,\n— quelqu'un qui se plaint beaucoup et qui t'accueille dans ce rituel 😄` },
  { id: 'dha_s4_005', text: `"C'est pas le move d'avoir des responsabilités qui n'ont pas de mode d'emploi. On t'aime."\nCes responsabilités. Qui arrivent. Sans instructions. Sans formation. C'est pas le move d'avoir à les gérer sans mode d'emploi. Et c'est pourtant la réalité adulte. On t'aime dans cette réalité. Joyeux anniversaire, [Prénom].\nAvec solidarité pour les responsabilités sans mode d'emploi de la vie adulte,\n— quelqu'un qui a géré les siennes sans mode d'emploi et qui partage cette expérience 🔧` },
  { id: 'dha_s4_006', text: `"T'as 18 ans. Maintenant tu vas réaliser que les adultes que tu admirais improvisaient."\nCette révélation. Qui vient avec l'âge adulte. Que les adultes qu'on admirait improvisaient souvent. Toi aussi tu vas improviser. Et c'est pas le move mais c'est universel. On t'aime dans l'improvisation. Joyeux anniversaire, [Prénom].\nAvec révélation de l'improvisation adulte universelle et amour dans cette improvisation,\n— quelqu'un qui improvise encore et qui t'accueille dans le club 🎭` },
  { id: 'dha_s4_007', text: `"C'est pas le move de découvrir que la vie adulte c'est beaucoup de logistique. On t'aime."\nCette logistique. Permanente. De la vie adulte. Les rendez-vous. Les papiers. Les démarches. C'est pas le move. C'est la réalité. Et on t'aime dans cette réalité logistique. Joyeux anniversaire, [Prénom].\nAvec solidarité pour la logistique permanente de la vie adulte,\n— quelqu'un qui noie dans la logistique adulte et qui t'accueille avec compassion 📋` },
  { id: 'dha_s4_008', text: `"Joyeux anniversaire. T'es adulte. Parfois c'est fatigant. C'est pas le move. On t'aime."\nLa fatigue adulte. Ce truc particulier. Qui vient de la gestion de tout. C'est fatigant. C'est pas toujours le move. Et on t'aime fatigué aussi. Joyeux anniversaire, [Prénom].\nAvec validation de la fatigue adulte et amour dans la fatigue,\n— quelqu'un qui est fatigué aussi et qui partage cette fatigue avec solidarité 😴` },
  { id: 'dha_s4_009', text: `"C'est pas le move de réaliser que personne a vraiment les réponses. On t'aime."\nCette réalisation. Que les réponses que t'attendais. Que les adultes censés avoir. Sont souvent absentes. Personne a vraiment toutes les réponses. On t'aime dans cette découverte. Joyeux anniversaire, [Prénom].\nAvec solidarité pour la découverte que personne a vraiment les réponses,\n— quelqu'un qui n'a pas toutes les réponses et qui t'accueille dans ce club 💙` },
  { id: 'dha_s4_010', text: `"T'as 18 ans. Bienvenue dans le monde où on fait semblant d'avoir tout compris. On t'aime."\nCe monde. Où on fait semblant. Où on a des apparences d'adultes qui savent. T'es bienvenu dans ce monde. On t'aime dedans. Joyeux anniversaire, [Prénom].\nAvec bienvenue dans le monde du faire semblant d'avoir tout compris et amour dedans,\n— quelqu'un qui fait semblant depuis un moment et qui t'accueille avec honnêteté 🎭` },
  { id: 'dha_s4_011', text: `"C'est pas le move les nuits où on se demande si on fait les bons choix. On t'aime dans ces nuits-là."\nCes nuits. De doute. De questionnement. Est-ce que je fais les bons choix. Ces nuits arrivent dans la vie adulte. Et on t'aime dans ces nuits-là aussi. Joyeux anniversaire, [Prénom].\nAvec amour particulier pour les nuits de doute qui font partie de la vie adulte,\n— quelqu'un qui a ces nuits aussi et qui confirme qu'on s'en sort 💙` },
  { id: 'dha_s4_012', text: `"Joyeux anniversaire. T'es adulte. C'est parfois pas le move. Et t'auras des gens pour traverser le pas le move."\nCes gens. Qui seront là. Dans les moments pas le move. Pour traverser ensemble. On est ces gens. Joyeux anniversaire, [Prénom].\nAvec promesse d'être là dans les moments pas le move de la vie adulte,\n— quelqu'un qui sera là pour les pas le move et qui le dit clairement 🫂` },
  { id: 'dha_s4_013', text: `"C'est pas le move de réaliser que grandir c'est complexe. Mais on t'aime dans la complexité."\nLa complexité. De la vie adulte. Qui est rarement simple. Souvent nuancée. C'est pas le move cette complexité. Et on t'aime dedans. Joyeux anniversaire, [Prénom].\nAvec amour dans la complexité de la vie adulte,\n— quelqu'un qui vit dans la complexité depuis un moment et qui t'accueille avec bienveillance 🌿` },
  { id: 'dha_s4_014', text: `"T'as 18 ans. Parfois ça va pas être le move. Et on sera là. Toujours."\nToujours. Dans les pas le move. Dans les difficultés. Cette promesse de toujours. C'est le plus beau cadeau d'anniversaire possible. Joyeux anniversaire, [Prénom].\nAvec promesse de toujours être là dans les pas le move,\n— quelqu'un qui fait cette promesse et qui la tient 💛` },
  { id: 'dha_s4_015', text: `"C'est pas le move les surprises pas bonnes de la vie adulte. On t'aime dans les surprises."\nCes surprises. Pas toutes bonnes. Qui arrivent. Qui déstabilisent. Et on t'aime dans chacune d'entre elles. Joyeux anniversaire, [Prénom].\nAvec amour dans les surprises pas bonnes de la vie adulte,\n— quelqu'un qui a eu ses surprises et qui t'aime dans les tiennes 🌊` },
  { id: 'dha_s4_016', text: `"Joyeux anniversaire. 18 ans c'est pas toujours le move. Et c'est aussi souvent le move. On t'aime dans les deux."\nL'équilibre. Les moments pas le move et les moments le move. Les deux font partie de la vie adulte. Dans les deux on t'aime. Joyeux anniversaire, [Prénom].\nAvec amour dans les deux catégories de moments de la vie adulte,\n— quelqu'un qui t'aime dans le move et dans le pas le move 💛` },
  { id: 'dha_s4_017', text: `"C'est pas le move de réaliser qu'on a toujours des trucs à apprendre. On t'aime dans l'apprentissage."\nCes trucs. Qu'on réalise qu'on sait pas. Même adulte. Il y a toujours des trucs à apprendre. C'est pas le move de le réaliser parfois. Et c'est bien en même temps. Joyeux anniversaire, [Prénom].\nAvec amour dans l'apprentissage permanent qui ne s'arrête pas à 18 ans,\n— quelqu'un qui apprend encore et qui t'accueille dans cet apprentissage continu 📚` },
  { id: 'dha_s4_018', text: `"T'as 18 ans. Parfois la vie adulte c'est pas le move. Et on t'aime quand même dans chaque pas le move."\nDans chaque. Pas juste en général. Dans chaque moment pas le move spécifique. On t'aime. C'est une promesse précise. Joyeux anniversaire, [Prénom].\nAvec précision de l'amour dans chaque pas le move spécifique,\n— quelqu'un qui fait cette promesse précise et qui la tient 💙` },
  { id: 'dha_s4_019', text: `"C'est pas le move la vie adulte parfois. Et on est là pour les fois où c'est pas le move."\nPour ces fois. Ces moments. Ces jours. On est là. Disponibles. Présents. Pour traverser ensemble. Joyeux anniversaire, [Prénom].\nAvec promesse de présence spécifique dans les moments pas le move,\n— quelqu'un qui sera là pour ces moments-là comme pour les autres 🫂` },
  { id: 'dha_s4_020', text: `"C'est pas le move d'être adulte parfois. On t'aime. Joyeux anniversaire, [Prénom]."\nSimple. Direct. La vérité sur la vie adulte. L'amour malgré. Et le souhait. Tout en peu de mots. Joyeux anniversaire, [Prénom].\nAvec économie de mots totale sur les trois vérités essentielles,\n— quelqu'un qui t'aime dans tous les aspects de ta vie adulte qui commence ❤️` },
];

// ── S5 : La vraie vie commence — on gère ensemble ────────
const S5: DixHuitAnsMessage[] = [
  { id: 'dha_s5_001', text: `"La vraie vie commence. On gère ensemble. Joyeux anniversaire, [Prénom]."\nSimple. Direct. La vraie vie. Qui commence maintenant. Et le on gère ensemble. Qui dit que t'es pas seul. Joyeux anniversaire, [Prénom].\nAvec simplicité directe sur les deux vérités les plus importantes de ce moment,\n— quelqu'un qui sera là pour gérer ensemble toute la vraie vie 💛` },
  { id: 'dha_s5_002', text: `"La vraie vie commence à 18 ans. Et on sera là pour toute la vraie vie."\nToute. Pas juste le début. Les bonnes parties. Les difficiles. Les imprévues. Les magnifiques. On sera là pour toutes. Joyeux anniversaire, [Prénom].\nAvec promesse d'être là pour toute la vraie vie,\n— quelqu'un qui fait cette promesse et qui la tient dans toutes ses parties 🌟` },
  { id: 'dha_s5_003', text: `"Joyeux anniversaire. La vraie vie commence. T'as ce qu'il faut pour la vivre."\nCe qu'il faut. Pas tout. Mais ce qu'il faut pour commencer. Pour avancer. T'as ça. Et ça suffit pour commencer. Joyeux anniversaire, [Prénom].\nAvec affirmation que t'as ce qu'il faut pour commencer la vraie vie,\n— quelqu'un qui en est convaincu et qui te le dit sans hésitation 💪` },
  { id: 'dha_s5_004', text: `"La vraie vie commence. Et on gère ensemble les trucs difficiles."\nLes trucs difficiles. En particulier. Ceux-là on les gère ensemble. Pas seul. Avec les gens qui sont là. Joyeux anniversaire, [Prénom].\nAvec engagement particulier pour gérer ensemble les trucs difficiles,\n— quelqu'un qui sera là particulièrement pour les trucs difficiles 🫂` },
  { id: 'dha_s5_005', text: `"Joyeux anniversaire. La vraie vie commence. Et elle a l'air grande. C'est bien."\nGrande. Cette vraie vie. Pleine de possibilités. De directions. De choix. Grande ça fait peur et ça réjouit en même temps. Et c'est bien qu'elle soit grande. Joyeux anniversaire, [Prénom].\nAvec validation que la grandeur de la vraie vie est une bonne chose,\n— quelqu'un qui pense que les vies grandes valent mieux que les vies petites 🌍` },
  { id: 'dha_s5_006', text: `"La vraie vie commence. Et les gens autour de toi sont là pour ça."\nPour ça. Pour la vraie vie. Pour l'accompagner. Pour la partager. Pour être là dans les moments importants. Joyeux anniversaire, [Prénom].\nAvec rappel que les gens autour de toi sont là pour la vraie vie,\n— quelqu'un qui est dans ces gens-là et qui te le dit clairement 💛` },
  { id: 'dha_s5_007', text: `"Joyeux anniversaire. La vraie vie commence et on gère ensemble parce qu'on était là avant aussi."\nAvant la vraie vie. T'as eu des gens. Qui étaient là. Et qui seront là dans la vraie vie aussi. Cette continuité. C'est une richesse. Joyeux anniversaire, [Prénom].\nAvec mise en valeur de la continuité des gens de l'avant à la vraie vie,\n— quelqu'un qui était là avant et qui sera là dans la vraie vie avec la même constance 🌊` },
  { id: 'dha_s5_008', text: `"La vraie vie commence. Et on gère ensemble les bons moments aussi."\nPas juste les difficiles. Les bons aussi. Les réussites. Les célébrations. Les joies. On est là pour les fêter. Joyeux anniversaire, [Prénom].\nAvec engagement d'être là pour les bons moments autant que pour les difficiles,\n— quelqu'un qui sera là pour célébrer les bons moments avec autant d'enthousiasme 🎉` },
  { id: 'dha_s5_009', text: `"Joyeux anniversaire. La vraie vie commence. T'as pas à tout savoir maintenant."\nLe soulagement. T'as pas à tout savoir. Pas à tout avoir compris. T'as juste à commencer. Et commencer c'est déjà tout. Joyeux anniversaire, [Prénom].\nAvec soulagement de la pression de tout savoir maintenant,\n— quelqu'un qui pense que commencer c'est tout ce qu'il faut et que le reste vient en route 🌱` },
  { id: 'dha_s5_010', text: `"La vraie vie commence. Et on gère ensemble parce que personne la gère vraiment seul."\nPersonne. Vraiment seul. La vraie vie se gère avec des gens. Des soutiens. Des présences. Et toi t'as des gens. Joyeux anniversaire, [Prénom].\nAvec affirmation que personne ne gère vraiment la vraie vie seul,\n— quelqu'un qui confirme cette réalité de sa propre expérience 🤝` },
  { id: 'dha_s5_011', text: `"Joyeux anniversaire. La vraie vie commence. Et on sera là à chaque étape."\nÀ chaque. Pas juste aux grandes. Aux petites aussi. À toutes. On sera là. À chaque étape de la vraie vie. Joyeux anniversaire, [Prénom].\nAvec promesse de présence à chaque étape sans exception,\n— quelqu'un qui pense que les étapes petites méritent autant de présence que les grandes 🌟` },
  { id: 'dha_s5_012', text: `"La vraie vie commence. Et les questions sans réponse font partie de la vraie vie."\nCes questions. Qui n'ont pas de réponse. Qui restent. Qui font partie du paysage de la vraie vie. C'est pas grave de les avoir. Joyeux anniversaire, [Prénom].\nAvec validation des questions sans réponse comme partie normale de la vraie vie,\n— quelqu'un qui a ses propres questions sans réponse et qui te confirme que c'est ok 💭` },
  { id: 'dha_s5_013', text: `"Joyeux anniversaire. La vraie vie commence. T'as une bonne base pour la construire."\nCette base. Ce que t'as déjà. Ces qualités. Ces valeurs. C'est ta base pour construire la vraie vie. Et cette base est bonne. Joyeux anniversaire, [Prénom].\nAvec confirmation que ta base pour construire la vraie vie est bonne,\n— quelqu'un qui voit ta base et qui trouve qu'elle est solide 🏗️` },
  { id: 'dha_s5_014', text: `"La vraie vie commence. On gère ensemble les moments où on sait pas trop."\nLes moments où on sait pas trop. Où la direction est floue. Où l'incertitude est là. On gère ensemble ces moments-là aussi. Joyeux anniversaire, [Prénom].\nAvec engagement pour gérer ensemble les moments d'incertitude,\n— quelqu'un qui sera là particulièrement dans les moments où on sait pas trop 💙` },
  { id: 'dha_s5_015', text: `"Joyeux anniversaire. La vraie vie commence. Et elle vaut d'être vécue pleinement."\nPleinement. Pas à moitié. Avec ce qu'elle a de beau. De difficile. De riche. Tout ça mérite d'être vécu pleinement. Joyeux anniversaire, [Prénom].\nAvec invitation à vivre la vraie vie pleinement et pas à moitié,\n— quelqu'un qui pense que tu as ce qu'il faut pour la vivre vraiment pleinement 🌟` },
  { id: 'dha_s5_016', text: `"La vraie vie commence. Et on est fiers de toi qui la commence."\nFiers. De toi. Cette version de toi qui entre dans la vraie vie. On est fiers de cette version. Joyeux anniversaire, [Prénom].\nAvec fierté pour la version de toi qui entre dans la vraie vie,\n— quelqu'un qui est fier depuis maintenant et pour toute la vraie vie 💛` },
  { id: 'dha_s5_017', text: `"Joyeux anniversaire. La vraie vie commence. Et on t'aime dans toute cette vraie vie."\nDans toute. Pas juste dans les bons moments. Les bons. Les difficiles. Les chelous. Dans toute la vraie vie on t'aime. C'est une promesse complète. Joyeux anniversaire, [Prénom].\nAvec promesse d'amour dans toute la vraie vie sans exception de moment,\n— quelqu'un qui t'aime dans toute la vraie vie et qui le dit clairement ❤️` },
  { id: 'dha_s5_018', text: `"La vraie vie commence. Et elle commence bien parce que t'as des gens autour de toi."\nDes gens. Qui comptent. Qui sont là. Avoir des gens autour de soi pour commencer la vraie vie c'est une richesse. T'as cette richesse. Joyeux anniversaire, [Prénom].\nAvec identification des gens autour de toi comme richesse pour commencer la vraie vie,\n— quelqu'un qui est dans ces gens-là et qui en est content 💛` },
  { id: 'dha_s5_019', text: `"Joyeux anniversaire. La vraie vie commence. On gère ensemble. No cap."\nNo cap. Pour de vrai. Sans exagération. On gère ensemble. La vraie vie commence. Et on gère vraiment ensemble. Joyeux anniversaire, [Prénom].\nAvec affirmation no cap de la gestion ensemble de la vraie vie,\n— quelqu'un qui dit no cap et qui le pense vraiment 🎯` },
  { id: 'dha_s5_020', text: `"La vraie vie commence. On gère ensemble. Joyeux anniversaire et bienvenue dans la vraie vie, [Prénom]."\nBienvenue. Dans la vraie vie. Ce moment. Cette étape. Ce début. Bienvenue dedans. Avec tous les gens qui t'attendent de ce côté. Joyeux anniversaire, [Prénom].\nAvec bienvenue solennelle et sincère dans la vraie vie,\n— quelqu'un qui t'accueille dans la vraie vie avec joie et fierté ❤️` },
];

// ── Export ────────────────────────────────────────────────
export const DIX_HUIT_ANS_GROUPS: DixHuitAnsSubGroup[] = [
  { id: 'dha_s1', title: "T'es officiellement adulte — bonne chance",                    emoji: '🎂', messages: S1 },
  { id: 'dha_s2', title: "No cap t'assures pour quelqu'un qui vient d'avoir 18 ans",     emoji: '💪', messages: S2 },
  { id: 'dha_s3', title: '18 ans c\'est chelou et bien en même temps',                   emoji: '🌀', messages: S3 },
  { id: 'dha_s4', title: "C'est pas le move d'être adulte mais on t'aime",               emoji: '💙', messages: S4 },
  { id: 'dha_s5', title: 'La vraie vie commence — on gère ensemble',                     emoji: '🚀', messages: S5 },
];
