import type { Occasion } from '../stores/createStore';

type StarterSet = {
  tu: { court: string[]; moyen: string[]; long: string[] };
  vous: { court: string[]; moyen: string[]; long: string[] };
};

/**
 * Starters "À ma façon" — textes pré-écrits pour chaque occasion.
 * Le placeholder [Prénom] est remplacé côté client avec le prénom du destinataire.
 */
export const MANUAL_STARTERS: Partial<Record<Occasion, StarterSet>> = {
  birthday: {
    tu: {
      court: [
        'Joyeux anniversaire [Prénom] ! 🎉',
        'Bon anniversaire ! Profite bien de ta journée.',
        'Joyeux anniversaire ! Que cette journée soit belle.',
        'Un an de plus, plein de bonheur en plus !',
        'Très joyeux anniversaire !',
        'Passe une super journée !',
        'Joyeux anniversaire ! Plein de belles choses.',
        'Profite bien de ta journée, c\'est la tienne !',
        'Joyeux anniversaire ! 🎂',
        'Que cette journée soit pleine de joie !',
      ],
      moyen: [
        'Joyeux anniversaire [Prénom] ! 🎉 J\'espère que ta journée sera remplie de beaux moments. Je te souhaite une année pleine de bonheur.',
        'Bon anniversaire ! Profite bien de cette journée et entoure-toi de ceux que tu aimes. Que cette année t\'apporte de belles choses.',
        'Joyeux anniversaire [Prénom] ! Une nouvelle année commence, pleine de projets et de moments à savourer. Je te souhaite le meilleur.',
      ],
      long: [
        'Joyeux anniversaire [Prénom] ! 🎉 J\'espère que cette journée sera à ton image, remplie de joie et de belles surprises. Tu mérites une année pleine de bonheur et de moments précieux. Profite bien de chaque instant.',
        'Bon anniversaire ! Une nouvelle année commence pour toi, pleine de possibilités. Je te souhaite de réaliser tes projets et de vivre de beaux moments. Passe une excellente journée.',
        'Joyeux anniversaire [Prénom] ! Je te souhaite une année remplie de réussites et de petits bonheurs du quotidien. Que tout ce que tu entreprends te rende heureux(se).',
      ],
    },
    vous: {
      court: [
        'Joyeux anniversaire [Prénom] ! 🎉',
        'Bon anniversaire !',
        'Très joyeux anniversaire !',
        'Je vous souhaite une belle journée.',
        'Joyeux anniversaire !',
        'Excellente journée à vous.',
        'Très bon anniversaire !',
        'Que cette journée vous soit agréable.',
        'Joyeux anniversaire 🎂',
        'Tous mes vœux pour cette journée.',
      ],
      moyen: [
        'Joyeux anniversaire [Prénom] ! 🎉 Je vous souhaite une très belle journée remplie de moments agréables. Que cette année vous apporte bonheur et réussite.',
        'Bon anniversaire ! Profitez pleinement de cette journée. Je vous souhaite une année riche en projets et en joies.',
        'Joyeux anniversaire [Prénom] ! Une nouvelle année s\'ouvre à vous, pleine de possibilités. Je vous souhaite le meilleur.',
      ],
      long: [
        'Joyeux anniversaire [Prénom] ! 🎉 Je vous souhaite une journée remplie de joie et de beaux moments. Que cette nouvelle année vous apporte bonheur et réussite. Profitez pleinement de cette journée.',
        'Bon anniversaire ! Cette journée est l\'occasion de célébrer tout ce que vous êtes. Je vous souhaite une année pleine de réussites et de sérénité.',
        'Joyeux anniversaire [Prénom] ! Je vous souhaite une année riche en projets et en moments heureux. Que tous vos souhaits se réalisent.',
      ],
    },
  },

  nameday: {
    tu: {
      court: [
        'Bonne fête ! 🎉',
        'Que cette journée soit aussi joyeuse que toi !',
        'Profite bien de ta fête, tu le mérites.',
        'Bonne fête, et que le bonheur soit au rendez-vous !',
        'Une journée spéciale pour une personne spéciale. Bonne fête !',
        'Que cette fête soit inoubliable !',
        'Bonne fête, et que tous tes vœux se réalisent.',
        'C\'est ta journée : savoure-la à fond !',
        'Bonne fête, et que la joie t\'accompagne toute l\'année.',
        'Que cette fête soit aussi brillante que ton sourire !',
      ],
      moyen: [
        'Bonne fête [Prénom] ! Je pense bien à toi aujourd\'hui. Je te souhaite une belle journée pleine de douceur.',
        'Bonne fête ! Une belle occasion de te dire que je pense à toi. Profite bien de cette journée.',
        'Bonne fête [Prénom] ! J\'espère que cette journée sera remplie de joie et de beaux moments.',
      ],
      long: [
        'Bonne fête [Prénom] ! C\'est une belle occasion de te rappeler combien tu comptes. Je te souhaite une journée remplie de douceur et de moments agréables. Profite pleinement de cette journée.',
        'Bonne fête ! Je te souhaite une journée pleine de joie, de petits bonheurs et de moments précieux. Tu le mérites vraiment.',
        'Bonne fête [Prénom] ! Une journée spéciale pour une personne qui l\'est tout autant. Je te souhaite beaucoup de bonheur aujourd\'hui.',
      ],
    },
    vous: {
      court: [
        'Bonne fête !',
        'Que cette journée soit aussi joyeuse que vous.',
        'Profitez bien de votre fête, vous le méritez.',
        'Bonne fête, et que le bonheur soit au rendez-vous.',
        'Une journée spéciale pour une personne spéciale. Bonne fête !',
        'Que cette fête soit inoubliable.',
        'Bonne fête, et que tous vos vœux se réalisent.',
        'C\'est votre journée : savourez-la à fond.',
        'Bonne fête, et que la joie vous accompagne toute l\'année.',
        'Que cette fête soit aussi brillante que votre sourire.',
      ],
      moyen: [
        'Bonne fête [Prénom] ! Je vous souhaite une très belle journée pleine de moments agréables.',
        'Bonne fête ! Une pensée pour vous aujourd\'hui. Je vous souhaite une journée agréable.',
        'Bonne fête [Prénom] ! J\'espère que cette journée vous apportera de la joie.',
      ],
      long: [
        'Bonne fête [Prénom] ! Je vous souhaite une journée remplie de douceur et de beaux moments. Profitez pleinement de cette occasion.',
        'Bonne fête ! Je vous adresse mes meilleurs vœux pour cette journée particulière. Qu\'elle soit agréable et sereine.',
        'Bonne fête [Prénom] ! Une belle occasion de vous souhaiter une journée chaleureuse et pleine de bonheur.',
      ],
    },
  },

  wedding: {
    tu: {
      court: [
        'Félicitations pour ton mariage 💍',
        'Bravo [Prénom] !',
        'Tous mes vœux de bonheur',
        'Félicitations !',
        'Quelle belle union 💛',
        'Beaucoup de bonheur à vous deux',
        'Félicitations 🎉',
        'Une magnifique étape',
        'Tous mes vœux',
        'Félicitations pour cette belle journée',
      ],
      moyen: [
        'Félicitations pour ton mariage [Prénom] 💍 Je te souhaite beaucoup de bonheur dans cette nouvelle aventure.',
        'Bravo pour cette belle union ! Une magnifique étape commence.',
        'Félicitations ! Que cette journée soit remplie d\'émotion et de beaux souvenirs.',
        'Félicitations [Prénom] ! Je te souhaite une vie à deux pleine de bonheur.',
        'Félicitations pour ton mariage ! Une nouvelle vie commence pour vous.',
        'Bravo ! Je te souhaite beaucoup d\'amour et de complicité.',
        'Félicitations [Prénom] ! Une belle étape pleine de promesses.',
        'Félicitations pour cette union ! Je te souhaite le meilleur.',
        'Bravo ! Une journée unique à savourer pleinement.',
        'Félicitations [Prénom] 💛 Tous mes vœux de bonheur.',
      ],
      long: [
        'Félicitations pour ton mariage [Prénom] ! 💍 Cette journée marque le début d\'une belle aventure à deux. Je te souhaite beaucoup d\'amour, de complicité et de moments précieux à partager tout au long de cette nouvelle vie.',
        'Bravo pour cette belle union ! Aujourd\'hui est une journée unique, pleine d\'émotions, qui restera gravée. Je te souhaite une vie remplie de bonheur et de beaux projets à deux.',
        'Félicitations ! Construire une vie ensemble est une aventure incroyable, faite de moments forts et de souvenirs à créer. Je te souhaite tout le bonheur possible.',
        'Félicitations [Prénom] ! Une nouvelle étape commence, pleine de promesses et de projets. Je te souhaite une vie à deux riche en amour et en complicité.',
        'Félicitations pour ton mariage ! Cette journée est le début d\'un nouveau chapitre. Je te souhaite beaucoup de bonheur pour la suite.',
        'Bravo ! Une belle histoire continue de s\'écrire. Je te souhaite une vie pleine de joie et de moments précieux.',
        'Félicitations [Prénom] ! Une journée unique qui marque un engagement fort. Je te souhaite une vie heureuse à deux.',
        'Félicitations pour cette union ! Que votre histoire soit longue, belle et remplie d\'amour.',
        'Bravo pour ton mariage ! Une étape importante et pleine d\'émotions. Je te souhaite le meilleur.',
        'Félicitations [Prénom] 💛 Beaucoup de bonheur pour cette nouvelle aventure à deux.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour votre mariage 💍',
        'Bravo [Prénom] !',
        'Tous mes vœux de bonheur',
        'Félicitations !',
        'Quelle belle union',
        'Beaucoup de bonheur à vous deux',
        'Félicitations 🎉',
        'Une magnifique étape',
        'Tous mes vœux',
        'Félicitations pour cette belle journée',
      ],
      moyen: [
        'Félicitations pour votre mariage [Prénom] 💍 Je vous souhaite beaucoup de bonheur dans cette nouvelle étape.',
        'Bravo pour cette belle union ! Une magnifique étape commence.',
        'Félicitations ! Que cette journée soit remplie d\'émotion et de beaux souvenirs.',
        'Félicitations [Prénom] ! Je vous souhaite une vie à deux pleine de bonheur.',
        'Félicitations pour votre mariage ! Une nouvelle vie commence pour vous.',
        'Bravo ! Je vous souhaite beaucoup d\'amour et de complicité.',
        'Félicitations [Prénom] ! Une belle étape pleine de promesses.',
        'Félicitations pour cette union ! Je vous souhaite le meilleur.',
        'Bravo ! Une journée unique à savourer pleinement.',
        'Félicitations [Prénom] 💛 Tous mes vœux de bonheur.',
      ],
      long: [
        'Félicitations pour votre mariage [Prénom] ! 💍 Cette journée marque le début d\'une belle aventure à deux. Je vous souhaite beaucoup d\'amour, de complicité et de moments précieux à partager.',
        'Bravo pour cette belle union ! Aujourd\'hui est une journée unique, pleine d\'émotions. Je vous souhaite une vie remplie de bonheur et de beaux projets.',
        'Félicitations ! Construire une vie ensemble est une aventure précieuse. Je vous souhaite tout le bonheur possible.',
        'Félicitations [Prénom] ! Une nouvelle étape commence, pleine de promesses. Je vous souhaite beaucoup de bonheur.',
        'Félicitations pour votre mariage ! Cette journée marque le début d\'un nouveau chapitre. Je vous souhaite le meilleur.',
        'Bravo ! Une belle histoire commence. Je vous souhaite une vie pleine de joie.',
        'Félicitations [Prénom] ! Une journée importante et pleine d\'émotions. Je vous souhaite une vie heureuse à deux.',
        'Félicitations pour cette union ! Que votre histoire soit longue et heureuse.',
        'Bravo pour votre mariage ! Une étape importante dans votre vie. Je vous souhaite beaucoup de bonheur.',
        'Félicitations [Prénom] 💛 Tous mes vœux pour cette nouvelle aventure.',
      ],
    },
  },

  engagement: {
    tu: {
      court: [
        'Félicitations pour vos fiançailles ! 💍',
        'Très heureux(se) pour toi !',
        'Quelle belle nouvelle !',
        'Félicitations !',
        'Plein de bonheur à vous deux !',
        'Une belle étape commence !',
        'Félicitations 🎉',
        'Beaucoup de bonheur !',
        'Très belle nouvelle !',
        'Félicitations pour cette belle étape !',
      ],
      moyen: [
        'Félicitations pour tes fiançailles [Prénom] ! Une très belle étape commence. Je te souhaite beaucoup de bonheur.',
        'Félicitations ! Une nouvelle aventure à deux commence. Profite bien de cette belle période.',
        'Félicitations pour vos fiançailles ! Une belle histoire continue de s\'écrire. Je te souhaite le meilleur.',
      ],
      long: [
        'Félicitations pour tes fiançailles [Prénom] ! 💍 Une très belle étape commence pour vous deux. Je te souhaite beaucoup de bonheur, de complicité et de beaux projets. Profite pleinement de cette période.',
        'Félicitations ! Cette belle nouvelle marque le début d\'une nouvelle aventure. Je te souhaite une vie remplie d\'amour et de moments précieux.',
        'Félicitations pour vos fiançailles ! Une étape importante et pleine d\'émotion. Je te souhaite une relation remplie de bonheur et de projets.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour vos fiançailles ! 💍',
        'Très heureux pour vous !',
        'Quelle belle nouvelle !',
        'Félicitations !',
        'Beaucoup de bonheur à vous deux !',
        'Une belle étape commence !',
        'Félicitations 🎉',
        'Tous mes vœux de bonheur !',
        'Très belle annonce !',
        'Félicitations pour cette étape !',
      ],
      moyen: [
        'Félicitations pour vos fiançailles ! Je vous souhaite beaucoup de bonheur pour cette belle étape.',
        'Félicitations ! Une nouvelle aventure commence pour vous deux. Je vous souhaite le meilleur.',
        'Félicitations pour vos fiançailles ! Une belle histoire se poursuit. Je vous souhaite beaucoup de joie.',
      ],
      long: [
        'Toutes mes félicitations pour vos fiançailles ! 💍 Cette étape marque le début d\'une belle aventure. Je vous souhaite beaucoup de bonheur et de moments précieux.',
        'Félicitations pour vos fiançailles ! Une très belle nouvelle qui annonce de beaux moments à venir. Je vous souhaite une vie remplie d\'amour.',
        'Félicitations pour cette belle annonce ! Je vous souhaite une vie pleine de bonheur, de complicité et de projets partagés.',
      ],
    },
  },

  birth: {
    tu: {
      court: [
        'Félicitations pour cette naissance ! 👶',
        'Bienvenue à ce petit bout !',
        'Quelle belle nouvelle !',
        'Félicitations !',
        'Plein de bonheur à vous !',
        'Bienvenue à bébé 💛',
        'Une merveilleuse nouvelle !',
        'Félicitations 🎉',
        'Beaucoup de bonheur à vous trois !',
        'Quelle joie !',
      ],
      moyen: [
        'Félicitations pour cette naissance [Prénom] ! Bienvenue à ce petit bout. Je te souhaite beaucoup de bonheur.',
        'Quelle belle nouvelle ! Félicitations pour cette naissance. Je te souhaite plein de beaux moments.',
        'Félicitations ! Une nouvelle vie commence, pleine de moments précieux. Profite bien de chaque instant.',
      ],
      long: [
        'Félicitations pour cette naissance [Prénom] ! 👶 Bienvenue à ce petit être qui va remplir votre vie d\'amour. Je te souhaite beaucoup de bonheur dans cette nouvelle aventure. Profite de chaque instant.',
        'Quelle magnifique nouvelle ! Félicitations pour cette naissance. Je te souhaite beaucoup de joie, de douceur et de moments précieux avec ton bébé.',
        'Félicitations pour cette naissance ! Un petit être vient agrandir votre famille et apporter encore plus d\'amour. Je te souhaite beaucoup de bonheur et de sérénité.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour cette naissance ! 👶',
        'Bienvenue à ce petit être !',
        'Quelle belle nouvelle !',
        'Félicitations !',
        'Beaucoup de bonheur à vous !',
        'Bienvenue à bébé 💛',
        'Une merveilleuse nouvelle !',
        'Félicitations 🎉',
        'Tous mes vœux de bonheur !',
        'Quelle joie !',
      ],
      moyen: [
        'Toutes mes félicitations pour cette naissance [Prénom] ! Je vous souhaite beaucoup de bonheur.',
        'Félicitations pour cette belle nouvelle ! Une nouvelle aventure commence. Je vous souhaite beaucoup de joie.',
        'Félicitations pour cette naissance ! Une étape importante pleine d\'émotion. Je vous souhaite le meilleur.',
      ],
      long: [
        'Toutes mes félicitations pour cette naissance [Prénom] ! 👶 Bienvenue à ce petit être qui vient enrichir votre famille. Je vous souhaite beaucoup de bonheur dans cette nouvelle aventure.',
        'Félicitations pour cette belle nouvelle ! L\'arrivée de votre enfant marque le début d\'une nouvelle vie pleine d\'émotions. Je vous souhaite beaucoup de joie et de douceur.',
        'Félicitations pour cette naissance ! Un nouveau chapitre commence pour vous. Je vous souhaite beaucoup de bonheur et de moments précieux.',
      ],
    },
  },

  baptism: {
    tu: {
      court: [
        'Félicitations pour ce baptême ✨',
        'Très belle cérémonie !',
        'Une belle étape !',
        'Félicitations !',
        'Belle journée à toi !',
        'Un moment précieux !',
        'Félicitations 🎉',
        'Très belle occasion !',
        'Que du bonheur !',
        'Une journée spéciale !',
      ],
      moyen: [
        'Félicitations pour ce baptême [Prénom] ! Une très belle étape pleine de sens. Profite bien de cette journée.',
        'Félicitations pour cette belle cérémonie ! Un moment important entouré de tes proches. Je te souhaite beaucoup de joie.',
        'Félicitations pour ce baptême ! Une journée pleine d\'émotion et de partage. Profite bien de chaque instant.',
      ],
      long: [
        'Félicitations pour ce baptême [Prénom] ✨ Une très belle étape pleine de sens et d\'émotion. Je te souhaite une journée remplie de joie et de beaux souvenirs. Profite pleinement de cette occasion.',
        'Félicitations pour cette belle cérémonie ! Une journée importante entourée de ceux qui comptent. Je te souhaite beaucoup de bonheur et de douceur.',
        'Félicitations pour ce baptême ! Un moment unique et symbolique. Je te souhaite une journée agréable et pleine de beaux moments.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour ce baptême ✨',
        'Très belle cérémonie !',
        'Une belle étape !',
        'Félicitations !',
        'Belle journée à vous !',
        'Un moment précieux !',
        'Félicitations 🎉',
        'Très belle occasion !',
        'Tous mes vœux !',
        'Une journée spéciale !',
      ],
      moyen: [
        'Toutes mes félicitations pour ce baptême [Prénom] ! Je vous souhaite une très belle cérémonie.',
        'Félicitations pour cette belle célébration ! Une étape importante entourée de vos proches. Je vous souhaite beaucoup de joie.',
        'Félicitations pour ce baptême ! Une journée pleine de sens et de partage. Je vous souhaite de très beaux moments.',
      ],
      long: [
        'Toutes mes félicitations pour ce baptême [Prénom] ✨ Une belle cérémonie pleine de sens et d\'émotion. Je vous souhaite une journée remplie de joie et de beaux souvenirs.',
        'Félicitations pour cette belle célébration ! Une journée importante entourée de ceux qui comptent. Je vous souhaite beaucoup de bonheur et de sérénité.',
        'Félicitations pour ce baptême ! Une étape importante dans la vie. Je vous souhaite une très belle journée pleine de moments précieux.',
      ],
    },
  },

  communion: {
    tu: {
      court: [
        'Félicitations pour ta communion ✨',
        'Très belle cérémonie !',
        'Une belle étape !',
        'Félicitations !',
        'Belle journée à toi !',
        'Un moment précieux !',
        'Félicitations 🎉',
        'Très belle occasion !',
        'Que du bonheur !',
        'Une journée spéciale !',
      ],
      moyen: [
        'Félicitations pour ta communion [Prénom] ! Une très belle étape pleine de sens. Profite bien de cette journée.',
        'Félicitations pour cette belle célébration ! Un moment important entouré de tes proches. Je te souhaite beaucoup de joie.',
        'Félicitations pour cette communion ! Une journée pleine d\'émotion et de partage. Profite bien de chaque instant.',
      ],
      long: [
        'Félicitations pour ta communion [Prénom] ✨ Une très belle étape pleine de sens et d\'émotion. Je te souhaite une journée remplie de joie et de beaux souvenirs.',
        'Félicitations pour cette belle célébration ! Une journée importante entourée de ceux qui comptent. Je te souhaite beaucoup de bonheur et de douceur.',
        'Félicitations pour cette communion ! Un moment unique et symbolique. Je te souhaite une journée agréable et pleine de beaux moments.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour cette communion ✨',
        'Très belle cérémonie !',
        'Une belle étape !',
        'Félicitations !',
        'Belle journée à vous !',
        'Un moment précieux !',
        'Félicitations 🎉',
        'Très belle occasion !',
        'Tous mes vœux !',
        'Une journée spéciale !',
      ],
      moyen: [
        'Toutes mes félicitations pour cette communion [Prénom] ! Je vous souhaite une très belle cérémonie.',
        'Félicitations pour cette belle célébration ! Une étape importante entourée de vos proches. Je vous souhaite beaucoup de joie.',
        'Félicitations pour cette communion ! Une journée pleine de sens et de partage. Je vous souhaite de très beaux moments.',
      ],
      long: [
        'Toutes mes félicitations pour cette communion [Prénom] ✨ Une belle cérémonie pleine de sens et d\'émotion. Je vous souhaite une journée remplie de joie et de beaux souvenirs.',
        'Félicitations pour cette belle célébration ! Une journée importante entourée de ceux qui comptent. Je vous souhaite beaucoup de bonheur et de sérénité.',
        'Félicitations pour cette communion ! Une étape importante dans la vie. Je vous souhaite une très belle journée pleine de moments précieux.',
      ],
    },
  },

  graduation: {
    tu: {
      court: [
        'Félicitations pour ton diplôme ! 🎓',
        'Bravo pour ta réussite !',
        'Tu l\'as fait, bravo !',
        'Félicitations !',
        'Très belle réussite !',
        'Bravo 🎉',
        'Une étape franchie !',
        'Félicitations pour ce succès !',
        'Tu peux être fier(ère) !',
        'Bien joué !',
      ],
      moyen: [
        'Félicitations pour ton diplôme [Prénom] ! 🎓 Tu peux être fier(ère) de toi. Je te souhaite le meilleur pour la suite.',
        'Bravo pour cette belle réussite ! Une étape importante franchie. Que la suite t\'apporte encore plein de belles opportunités.',
        'Félicitations pour ton diplôme ! Un bel accomplissement qui ouvre de nouvelles perspectives. Je te souhaite beaucoup de réussite.',
      ],
      long: [
        'Félicitations pour ton diplôme [Prénom] ! 🎓 C\'est une belle récompense pour tout le travail accompli. Tu peux être fier(ère) de toi. Je te souhaite beaucoup de réussite pour la suite.',
        'Bravo pour cette réussite ! Cette étape marque un tournant important. Je te souhaite de continuer à réaliser tes projets et de vivre de belles expériences.',
        'Félicitations pour ton diplôme ! Un accomplissement important qui ouvre la voie à de nouvelles aventures. Je te souhaite beaucoup de succès et de belles opportunités.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour votre diplôme ! 🎓',
        'Bravo pour votre réussite !',
        'Très belle réussite !',
        'Félicitations !',
        'Bravo 🎉',
        'Une étape franchie !',
        'Félicitations pour ce succès !',
        'Vous pouvez être fier(ère) !',
        'Bien joué !',
        'Tous mes compliments !',
      ],
      moyen: [
        'Félicitations pour votre diplôme [Prénom] ! 🎓 C\'est une belle réussite. Je vous souhaite le meilleur pour la suite.',
        'Bravo pour cette belle réussite ! Une étape importante franchie avec succès. Je vous souhaite de belles opportunités.',
        'Félicitations pour votre diplôme ! Un bel accomplissement qui ouvre de nouvelles perspectives. Je vous souhaite beaucoup de réussite.',
      ],
      long: [
        'Félicitations pour votre diplôme [Prénom] ! 🎓 Ce résultat récompense votre travail et votre engagement. Vous pouvez être fier(ère) de ce que vous avez accompli. Je vous souhaite beaucoup de succès.',
        'Bravo pour cette réussite ! Cette étape marque un moment important de votre parcours. Je vous souhaite de poursuivre vos projets avec succès.',
        'Félicitations pour votre diplôme ! Un accomplissement qui ouvre la voie à de nouvelles perspectives. Je vous souhaite beaucoup de réussite et de belles opportunités.',
      ],
    },
  },

  promotion: {
    tu: {
      court: [
        'Félicitations pour ta promotion 🎉',
        'Bravo [Prénom] !',
        'Quelle belle réussite !',
        'Félicitations !',
        'Bien mérité 👏',
        'Bravo pour cette promotion',
        'Félicitations 🎉',
        'Une belle étape franchie',
        'Bravo !',
        'Félicitations pour cette évolution',
      ],
      moyen: [
        'Félicitations pour ta promotion [Prénom] 🎉 Tu peux être fier(ère) de toi.',
        'Bravo pour cette belle réussite ! Une étape importante franchie.',
        'Félicitations ! Cette promotion est bien méritée.',
        'Bravo [Prénom] ! Ton travail a payé.',
        'Félicitations pour ta promotion ! Une belle évolution.',
        'Bravo ! Je te souhaite beaucoup de réussite.',
        'Félicitations [Prénom] ! Une nouvelle étape commence.',
        'Bravo pour cette promotion ! Tu peux être fier(ère).',
        'Félicitations ! Une belle récompense pour ton travail.',
        'Bravo [Prénom] ! Je te souhaite le meilleur pour la suite.',
      ],
      long: [
        'Félicitations pour ta promotion [Prénom] 🎉 C\'est une belle reconnaissance de ton travail et de ton engagement. Tu peux être fier(ère) de ton parcours. Je te souhaite beaucoup de réussite pour la suite.',
        'Bravo pour cette belle réussite ! Cette promotion marque une étape importante et reflète tout ce que tu as accompli. Je te souhaite beaucoup de succès.',
        'Félicitations ! Une belle évolution qui récompense ton travail. Je te souhaite de t\'épanouir pleinement dans ce nouveau rôle.',
        'Bravo [Prénom] ! Cette promotion est le fruit de ton investissement. Je te souhaite beaucoup de réussite.',
        'Félicitations pour ta promotion ! Une nouvelle étape commence avec de belles opportunités.',
        'Bravo ! Ton travail a été reconnu, et c\'est amplement mérité.',
        'Félicitations [Prénom] ! Une étape importante dans ton parcours.',
        'Bravo pour cette promotion ! Je te souhaite beaucoup de réussite pour la suite.',
        'Félicitations ! Une belle reconnaissance de ton travail.',
        'Bravo [Prénom] ! Je te souhaite de continuer sur cette belle lancée.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour votre promotion 🎉',
        'Bravo [Prénom] !',
        'Quelle belle réussite !',
        'Félicitations !',
        'Bien mérité 👏',
        'Bravo pour cette promotion',
        'Félicitations 🎉',
        'Une belle étape franchie',
        'Bravo !',
        'Félicitations pour cette évolution',
      ],
      moyen: [
        'Félicitations pour votre promotion [Prénom] 🎉 Vous pouvez être fier(ère).',
        'Bravo pour cette belle réussite ! Une étape importante franchie.',
        'Félicitations ! Cette promotion est bien méritée.',
        'Bravo [Prénom] ! Votre travail a porté ses fruits.',
        'Félicitations pour votre promotion ! Une belle évolution.',
        'Bravo ! Je vous souhaite beaucoup de réussite.',
        'Félicitations [Prénom] ! Une nouvelle étape commence.',
        'Bravo pour cette promotion ! Vous pouvez être fier(ère).',
        'Félicitations ! Une belle récompense pour votre travail.',
        'Bravo [Prénom] ! Je vous souhaite le meilleur pour la suite.',
      ],
      long: [
        'Félicitations pour votre promotion [Prénom] 🎉 C\'est une belle reconnaissance de votre travail et de votre engagement. Je vous souhaite beaucoup de réussite pour la suite.',
        'Bravo pour cette belle réussite ! Cette promotion marque une étape importante dans votre parcours. Je vous souhaite beaucoup de succès.',
        'Félicitations ! Une belle évolution qui récompense votre travail. Je vous souhaite de vous épanouir dans ce nouveau rôle.',
        'Bravo [Prénom] ! Cette promotion est le fruit de votre investissement.',
        'Félicitations pour votre promotion ! Une nouvelle étape pleine d\'opportunités.',
        'Bravo ! Votre travail a été reconnu, et c\'est mérité.',
        'Félicitations [Prénom] ! Une étape importante dans votre parcours.',
        'Bravo pour cette promotion ! Je vous souhaite beaucoup de réussite.',
        'Félicitations ! Une belle reconnaissance de votre travail.',
        'Bravo [Prénom] ! Je vous souhaite de continuer sur cette lancée.',
      ],
    },
  },

  thanks: {
    tu: {
      court: [
        'Merci beaucoup ! 💛',
        'Un grand merci !',
        'Merci pour tout !',
        'Merci infiniment !',
        'Merci 🙏',
        'Vraiment merci !',
        'Merci à toi !',
        'Merci pour ton aide !',
        'Merci pour tout 💛',
        'Merci du fond du cœur !',
      ],
      moyen: [
        'Merci beaucoup [Prénom] 💛 Ton geste m\'a vraiment touché{E_EXP}. Ça compte beaucoup pour moi.',
        'Un grand merci ! Ce que tu as fait m\'a fait très plaisir. Je t\'en suis reconnaissant{E_EXP}.',
        'Merci pour tout ! Ta présence et ton attention ont vraiment compté pour moi.',
      ],
      long: [
        'Merci beaucoup [Prénom] 💛 Je voulais vraiment te remercier sincèrement. Ton geste m\'a profondément touché{E_EXP}. Je t\'en suis très reconnaissant{E_EXP}.',
        'Un grand merci ! Ce que tu as fait m\'a vraiment touché{E_EXP} et fait plaisir. Ta présence compte beaucoup pour moi.',
        'Merci pour tout ! Je voulais te dire combien j\'ai apprécié ton attention. Cela m\'a sincèrement touché{E_EXP}.',
      ],
    },
    vous: {
      court: [
        'Merci beaucoup !',
        'Un grand merci !',
        'Merci pour tout !',
        'Merci infiniment !',
        'Merci 🙏',
        'Je vous remercie !',
        'Merci à vous !',
        'Merci pour votre aide !',
        'Merci pour tout',
        'Merci sincèrement !',
      ],
      moyen: [
        'Je vous remercie sincèrement [Prénom] 💛 Votre geste m\'a beaucoup touché{E_EXP}.',
        'Un grand merci ! Votre attention a été très appréciée. Je vous en suis reconnaissant{E_EXP}.',
        'Merci pour tout ! Votre présence et votre geste ont beaucoup compté.',
      ],
      long: [
        'Je vous remercie sincèrement [Prénom] 💛 Je tenais à vous exprimer toute ma gratitude. Votre geste m\'a profondément touché{E_EXP}.',
        'Un grand merci ! Votre attention m\'a beaucoup touché{E_EXP} et fait plaisir. Je vous en suis très reconnaissant{E_EXP}.',
        'Merci pour tout ! Je voulais vous dire combien j\'ai apprécié votre soutien. Cela m\'a sincèrement touché{E_EXP}.',
      ],
    },
  },

  newyear: {
    tu: {
      court: [
        'Bonne année [Prénom] ! 🎉',
        'Très belle année !',
        'Bonne année !',
        'Tous mes vœux !',
        'Excellente année !',
        'Belle année à toi !',
        'Bonne année 🎉',
        'Que du bonheur !',
        'Meilleurs vœux !',
        'Très bonne année !',
      ],
      moyen: [
        'Bonne année [Prénom] ! 🎉 Je te souhaite une année pleine de bonheur et de réussite.',
        'Très belle année ! Que cette nouvelle année t\'apporte joie et beaux moments.',
        'Bonne année [Prénom] ! Une nouvelle page commence. Je te souhaite le meilleur.',
      ],
      long: [
        'Bonne année [Prénom] ! 🎉 Je te souhaite une année remplie de bonheur, de réussite et de beaux moments. Que tous tes projets se réalisent.',
        'Très belle année ! Une nouvelle année commence, pleine de possibilités. Je te souhaite de vivre de beaux moments.',
        'Bonne année [Prénom] ! Je te souhaite une année riche en projets, en réussites et en moments heureux.',
      ],
    },
    vous: {
      court: [
        'Bonne année [Prénom] ! 🎉',
        'Très belle année !',
        'Bonne année !',
        'Tous mes vœux !',
        'Excellente année !',
        'Belle année à vous !',
        'Bonne année 🎉',
        'Que du bonheur !',
        'Meilleurs vœux !',
        'Très bonne année !',
      ],
      moyen: [
        'Bonne année [Prénom] ! 🎉 Je vous souhaite une année pleine de bonheur et de réussite.',
        'Très belle année ! Que cette nouvelle année vous apporte joie et beaux moments.',
        'Bonne année [Prénom] ! Une nouvelle page commence. Je vous souhaite le meilleur.',
      ],
      long: [
        'Bonne année [Prénom] ! 🎉 Je vous souhaite une année remplie de bonheur, de réussite et de beaux moments.',
        'Très belle année ! Une nouvelle année commence, pleine de possibilités. Je vous souhaite de beaux projets.',
        'Bonne année [Prénom] ! Je vous souhaite une année riche en réussites et en moments heureux.',
      ],
    },
  },

  christmas: {
    tu: {
      court: [
        'Joyeux Noël [Prénom] ! 🎄',
        'Très joyeux Noël !',
        'Belles fêtes !',
        'Joyeux Noël !',
        'Profite bien des fêtes !',
        'Un très beau Noël !',
        'Joyeuses fêtes 🎄',
        'Que du bonheur !',
        'Très belles fêtes !',
        'Passe un bon Noël !',
      ],
      moyen: [
        'Joyeux Noël [Prénom] ! 🎄 Je te souhaite une journée pleine de douceur et de beaux moments.',
        'Joyeux Noël ! Profite de cette journée entouré{E_DEST} de ceux que tu aimes.',
        'Très joyeux Noël [Prénom] ! Une belle occasion de partager des moments précieux.',
      ],
      long: [
        'Joyeux Noël [Prénom] ! 🎄 Je te souhaite une journée remplie de joie, de douceur et de moments précieux avec ceux que tu aimes.',
        'Joyeux Noël ! Cette période est idéale pour se retrouver et partager de beaux moments. Je te souhaite beaucoup de bonheur.',
        'Très joyeux Noël [Prénom] ! Que cette journée soit pleine de chaleur, de bonheur et de souvenirs précieux.',
      ],
    },
    vous: {
      court: [
        'Joyeux Noël [Prénom] ! 🎄',
        'Très joyeux Noël !',
        'Belles fêtes !',
        'Joyeux Noël !',
        'Profitez bien des fêtes !',
        'Un très beau Noël !',
        'Joyeuses fêtes 🎄',
        'Que du bonheur !',
        'Très belles fêtes !',
        'Passez un bon Noël !',
      ],
      moyen: [
        'Je vous souhaite un joyeux Noël [Prénom] 🎄 et une belle journée.',
        'Joyeux Noël ! Je vous souhaite de beaux moments entouré{E_DEST} de vos proches.',
        'Très joyeux Noël [Prénom] ! Une belle occasion de partager des instants précieux.',
      ],
      long: [
        'Je vous souhaite un joyeux Noël [Prénom] 🎄 rempli de joie, de douceur et de moments partagés.',
        'Joyeux Noël ! Que cette période vous apporte bonheur, sérénité et beaux moments.',
        'Très joyeux Noël [Prénom] ! Que cette journée soit pleine de chaleur et de moments précieux.',
      ],
    },
  },

  easter: {
    tu: {
      court: [
        'Joyeuses Pâques [Prénom] 🐣',
        'Très joyeuses Pâques !',
        'Bonne fête de Pâques !',
        'Joyeuses Pâques !',
        'Profite bien !',
        'Belle journée !',
        'Pâques 🎉',
        'Que du bonheur !',
        'Bonne journée !',
        'Joyeuses Pâques !',
      ],
      moyen: [
        'Joyeuses Pâques [Prénom] 🐣 Je te souhaite une belle journée pleine de douceur.',
        'Joyeuses Pâques ! Profite de cette journée agréable et gourmande.',
        'Très joyeuses Pâques [Prénom] ! Une belle occasion de profiter.',
      ],
      long: [
        'Joyeuses Pâques [Prénom] 🐣 Je te souhaite une journée remplie de douceur, de joie et de moments agréables.',
        'Joyeuses Pâques ! Une belle journée pour se retrouver et profiter de bons moments.',
        'Très joyeuses Pâques [Prénom] ! Que cette journée soit pleine de bonheur et de sérénité.',
      ],
    },
    vous: {
      court: [
        'Joyeuses Pâques [Prénom] 🐣',
        'Très joyeuses Pâques !',
        'Bonne fête de Pâques !',
        'Joyeuses Pâques !',
        'Profitez bien !',
        'Belle journée !',
        'Pâques 🎉',
        'Que du bonheur !',
        'Bonne journée !',
        'Joyeuses Pâques !',
      ],
      moyen: [
        'Je vous souhaite de joyeuses Pâques [Prénom] 🐣 et une belle journée.',
        'Joyeuses Pâques ! Je vous souhaite une journée agréable.',
        'Très joyeuses Pâques [Prénom] ! Profitez bien de cette journée.',
      ],
      long: [
        'Je vous souhaite de joyeuses Pâques [Prénom] 🐣 remplies de douceur et de moments agréables.',
        'Joyeuses Pâques ! Une belle journée pour se retrouver et profiter de moments précieux.',
        'Très joyeuses Pâques [Prénom] ! Que cette journée soit pleine de sérénité et de bonheur.',
      ],
    },
  },

  valentines: {
    tu: {
      court: [
        'Joyeuse Saint-Valentin ❤️',
        'Je pense à toi 💛',
        'Avec tout mon amour ❤️',
        'Belle journée à toi !',
        'Je t\'aime ❤️',
        'Joyeuse Saint-Valentin !',
        'Une pensée pour toi',
        '❤️',
        'Très belle journée',
        'Pour toi 💛',
      ],
      moyen: [
        'Joyeuse Saint-Valentin [Prénom] ❤️ Je voulais te dire combien tu comptes pour moi.',
        'Joyeuse Saint-Valentin ! Une belle occasion de te dire que je tiens à toi.',
        'Joyeuse Saint-Valentin [Prénom] ! Je te souhaite une journée pleine de douceur.',
      ],
      long: [
        'Joyeuse Saint-Valentin [Prénom] ❤️ Je voulais te dire à quel point tu comptes pour moi. Je te souhaite une journée pleine de douceur et d\'amour.',
        'Joyeuse Saint-Valentin ! Une belle occasion de te rappeler combien tu es important{E_DEST} pour moi.',
        'Joyeuse Saint-Valentin [Prénom] ! Merci pour tout ce que tu apportes dans ma vie.',
      ],
    },
    vous: {
      court: [
        'Belle Saint-Valentin ❤️',
        'Une pensée pour vous',
        'Très belle journée',
        '❤️',
        'Avec toute mon attention',
        'Bonne Saint-Valentin',
        'Belle journée à vous',
        'Très belle fête',
        'Je pense à vous',
        'Belle occasion',
      ],
      moyen: [
        'Je vous souhaite une belle Saint-Valentin [Prénom] ❤️',
        'Joyeuse Saint-Valentin ! Une pensée pour vous aujourd\'hui.',
        'Très belle Saint-Valentin [Prénom] ! Je vous souhaite une agréable journée.',
      ],
      long: [
        'Je vous souhaite une très belle Saint-Valentin [Prénom] ❤️ pleine de douceur et de beaux moments.',
        'Joyeuse Saint-Valentin ! Une belle occasion de partager des moments agréables.',
        'Très belle Saint-Valentin [Prénom] ! Que cette journée vous apporte joie et sérénité.',
      ],
    },
  },

  mothersday: {
    tu: {
      court: [
        'Bonne fête maman 💛',
        'Bonne fête [Prénom] !',
        'Une très belle fête à toi',
        'Bonne fête !',
        'Je pense à toi aujourd\'hui 💛',
        'Belle fête des mères',
        'Bonne fête maman ❤️',
        'Profite bien de ta journée',
        'Bonne fête !',
        'Une pensée pour toi aujourd\'hui',
      ],
      moyen: [
        'Bonne fête maman 💛 Je te souhaite une très belle journée remplie de douceur.',
        'Bonne fête [Prénom] ! Merci pour tout ce que tu fais au quotidien.',
        'Bonne fête ! Une belle occasion de te dire merci.',
        'Bonne fête maman ❤️ Profite bien de ta journée.',
        'Bonne fête [Prénom] ! Je te souhaite beaucoup de bonheur aujourd\'hui.',
        'Bonne fête ! Une pensée pour toi en ce jour spécial.',
        'Bonne fête maman 💛 Merci pour ton amour.',
        'Bonne fête [Prénom] ! Je te souhaite une journée agréable.',
        'Bonne fête ! Profite bien de ce moment.',
        'Bonne fête maman ! Je te souhaite plein de beaux moments.',
      ],
      long: [
        'Bonne fête maman 💛 Je voulais prendre un moment pour te dire combien tu es importante pour moi. Merci pour tout ton amour et tout ce que tu fais. Je te souhaite une journée douce et pleine de bonheur.',
        'Bonne fête [Prénom] ! C\'est une belle occasion de te dire merci pour tout ce que tu apportes. Je te souhaite une très belle journée.',
        'Bonne fête ! Une journée spéciale pour te rappeler combien tu comptes. Je te souhaite beaucoup de bonheur.',
        'Bonne fête maman ❤️ Merci pour ton soutien et ta présence. Je te souhaite une journée pleine de douceur.',
        'Bonne fête [Prénom] ! Je te souhaite une journée remplie de moments agréables.',
        'Bonne fête ! Une pensée pour toi avec beaucoup d\'affection.',
        'Bonne fête maman 💛 Je te souhaite beaucoup de bonheur aujourd\'hui.',
        'Bonne fête [Prénom] ! Merci pour tout ce que tu fais.',
        'Bonne fête ! Une journée pour te faire plaisir.',
        'Bonne fête maman ! Je te souhaite une très belle journée.',
      ],
    },
    vous: {
      court: [
        'Bonne fête [Prénom] !',
        'Très belle fête à vous',
        'Bonne fête !',
        'Une pensée pour vous',
        'Belle fête des mères',
        'Bonne fête !',
        'Je vous souhaite une belle journée',
        'Bonne fête [Prénom]',
        'Profitez bien de cette journée',
        'Bonne fête !',
      ],
      moyen: [
        'Bonne fête [Prénom] ! Je vous souhaite une très belle journée.',
        'Bonne fête ! Une pensée pour vous aujourd\'hui.',
        'Bonne fête [Prénom] ! Merci pour tout ce que vous faites.',
        'Bonne fête ! Je vous souhaite beaucoup de bonheur.',
        'Bonne fête [Prénom] ! Profitez bien de cette journée.',
        'Bonne fête ! Je vous souhaite une journée agréable.',
        'Bonne fête [Prénom] ! Une belle journée à vous.',
        'Bonne fête ! Je vous adresse mes pensées.',
        'Bonne fête [Prénom] ! Je vous souhaite de beaux moments.',
        'Bonne fête ! Profitez bien de cette journée.',
      ],
      long: [
        'Bonne fête [Prénom] ! Je vous souhaite une très belle journée remplie de douceur et de moments agréables. Profitez pleinement de cette occasion.',
        'Bonne fête ! Une journée spéciale pour vous dire merci. Je vous souhaite beaucoup de bonheur.',
        'Bonne fête [Prénom] ! Je vous remercie pour tout ce que vous faites. Je vous souhaite une belle journée.',
        'Bonne fête ! Je vous adresse mes pensées en cette journée particulière.',
        'Bonne fête [Prénom] ! Je vous souhaite de beaux moments aujourd\'hui.',
        'Bonne fête ! Une belle journée à vous.',
        'Bonne fête [Prénom] ! Je vous souhaite une journée agréable.',
        'Bonne fête ! Profitez bien de cette journée.',
        'Bonne fête [Prénom] ! Je vous adresse mes meilleurs vœux.',
        'Bonne fête ! Je vous souhaite une très belle journée.',
      ],
    },
  },

  fathersday: {
    tu: {
      court: [
        'Bonne fête papa 💛',
        'Bonne fête [Prénom] !',
        'Une très belle fête à toi',
        'Bonne fête !',
        'Je pense à toi aujourd\'hui',
        'Belle fête des pères',
        'Bonne fête papa ❤️',
        'Profite bien de ta journée',
        'Bonne fête !',
        'Une pensée pour toi',
      ],
      moyen: [
        'Bonne fête papa 💛 Je te souhaite une très belle journée.',
        'Bonne fête [Prénom] ! Merci pour tout ce que tu fais.',
        'Bonne fête ! Une belle occasion de te dire merci.',
        'Bonne fête papa ❤️ Profite bien de ta journée.',
        'Bonne fête [Prénom] ! Je te souhaite beaucoup de bonheur.',
        'Bonne fête ! Une pensée pour toi aujourd\'hui.',
        'Bonne fête papa 💛 Merci pour ton soutien.',
        'Bonne fête [Prénom] ! Je te souhaite une belle journée.',
        'Bonne fête ! Profite bien de ce moment.',
        'Bonne fête papa ! Je te souhaite plein de beaux moments.',
      ],
      long: [
        'Bonne fête papa 💛 Je voulais te dire combien tu es important pour moi. Merci pour tout ce que tu fais et pour ton soutien. Je te souhaite une très belle journée.',
        'Bonne fête [Prénom] ! Une belle occasion de te remercier pour tout. Je te souhaite beaucoup de bonheur aujourd\'hui.',
        'Bonne fête ! Une journée spéciale pour te dire merci et te souhaiter une belle journée.',
        'Bonne fête papa ❤️ Merci pour ta présence et ton soutien. Je te souhaite une journée douce et agréable.',
        'Bonne fête [Prénom] ! Je te souhaite une journée remplie de moments agréables.',
        'Bonne fête ! Une pensée pour toi avec beaucoup d\'affection.',
        'Bonne fête papa 💛 Je te souhaite beaucoup de bonheur.',
        'Bonne fête [Prénom] ! Merci pour tout ce que tu fais.',
        'Bonne fête ! Une journée pour te faire plaisir.',
        'Bonne fête papa ! Je te souhaite une très belle journée.',
      ],
    },
    vous: {
      court: [
        'Bonne fête [Prénom] !',
        'Très belle fête à vous',
        'Bonne fête !',
        'Une pensée pour vous',
        'Belle fête des pères',
        'Bonne fête !',
        'Je vous souhaite une belle journée',
        'Bonne fête [Prénom]',
        'Profitez bien de cette journée',
        'Bonne fête !',
      ],
      moyen: [
        'Bonne fête [Prénom] ! Je vous souhaite une très belle journée.',
        'Bonne fête ! Une pensée pour vous aujourd\'hui.',
        'Bonne fête [Prénom] ! Merci pour tout ce que vous faites.',
        'Bonne fête ! Je vous souhaite beaucoup de bonheur.',
        'Bonne fête [Prénom] ! Profitez bien de cette journée.',
        'Bonne fête ! Je vous souhaite une journée agréable.',
        'Bonne fête [Prénom] ! Une belle journée à vous.',
        'Bonne fête ! Je vous adresse mes pensées.',
        'Bonne fête [Prénom] ! Je vous souhaite de beaux moments.',
        'Bonne fête ! Profitez bien de cette journée.',
      ],
      long: [
        'Bonne fête [Prénom] ! Je vous souhaite une très belle journée remplie de douceur et de moments agréables. Profitez pleinement de cette occasion.',
        'Bonne fête ! Une journée spéciale pour vous dire merci. Je vous souhaite beaucoup de bonheur.',
        'Bonne fête [Prénom] ! Je vous remercie pour tout ce que vous faites. Je vous souhaite une belle journée.',
        'Bonne fête ! Je vous adresse mes pensées en cette journée particulière.',
        'Bonne fête [Prénom] ! Je vous souhaite de beaux moments aujourd\'hui.',
        'Bonne fête ! Une belle journée à vous.',
        'Bonne fête [Prénom] ! Je vous souhaite une journée agréable.',
        'Bonne fête ! Profitez bien de cette journée.',
        'Bonne fête [Prénom] ! Je vous adresse mes meilleurs vœux.',
        'Bonne fête ! Je vous souhaite une très belle journée.',
      ],
    },
  },

  halloween: {
    tu: {
      court: [
        'Joyeux Halloween [Prénom] 🎃',
        'Bonne soirée d\'Halloween !',
        'Profite bien de cette soirée 🎃',
        'Joyeux Halloween !',
        'Une soirée pleine de frissons 😄',
        'Amuse-toi bien ce soir !',
        'Happy Halloween 🎃',
        'Une soirée fun en perspective !',
        'Profite de cette ambiance 👻',
        'Passe un super Halloween !',
      ],
      moyen: [
        'Joyeux Halloween [Prénom] 🎃 Profite bien de cette soirée pleine de surprises et de fun.',
        'Bonne soirée d\'Halloween ! J\'espère qu\'elle sera remplie de rires et de bons moments.',
        'Joyeux Halloween ! Une soirée parfaite pour s\'amuser et profiter.',
        'Très bon Halloween [Prénom] ! Que ta soirée soit agréable et pleine de surprises.',
        'Joyeux Halloween 🎃 Profite bien de cette ambiance unique.',
        'Bonne soirée ! Que ce Halloween soit fun et agréable.',
        'Joyeux Halloween [Prénom] ! Passe une excellente soirée.',
        'Une soirée spéciale pour s\'amuser ! Joyeux Halloween 🎃',
        'Profite bien de cette soirée pleine de surprises.',
        'Joyeux Halloween ! Passe un très bon moment.',
      ],
      long: [
        'Joyeux Halloween [Prénom] 🎃 Je te souhaite une soirée pleine de surprises, de rires et de moments amusants. Profite bien de cette ambiance unique et de tout ce qui rend cette soirée différente.',
        'Très bon Halloween ! C\'est l\'occasion parfaite pour s\'amuser et passer un bon moment. J\'espère que ta soirée sera remplie de rires et de bons souvenirs.',
        'Joyeux Halloween [Prénom] ! Que cette soirée soit à la fois amusante, surprenante et pleine de bons moments à partager.',
        'Joyeux Halloween 🎃 Une soirée différente pour profiter, s\'amuser et lâcher prise. Je te souhaite de passer un excellent moment.',
        'Très bon Halloween ! Profite de cette soirée pour t\'amuser et vivre de bons moments.',
        'Joyeux Halloween [Prénom] ! J\'espère que ta soirée sera pleine de surprises et de moments agréables.',
        'Joyeux Halloween 🎃 Une soirée idéale pour se détendre et profiter.',
        'Très bon Halloween ! Je te souhaite une soirée fun et pleine de rires.',
        'Joyeux Halloween [Prénom] ! Profite bien de cette ambiance et de cette soirée.',
        'Joyeux Halloween ! Passe une excellente soirée pleine de bons moments.',
      ],
    },
    vous: {
      court: [
        'Joyeux Halloween [Prénom] 🎃',
        'Bonne soirée d\'Halloween !',
        'Profitez bien de cette soirée 🎃',
        'Joyeux Halloween !',
        'Une soirée pleine de surprises',
        'Très bon Halloween !',
        'Happy Halloween 🎃',
        'Passez une belle soirée',
        'Profitez de cette ambiance 👻',
        'Excellent Halloween !',
      ],
      moyen: [
        'Joyeux Halloween [Prénom] 🎃 Je vous souhaite une soirée pleine de surprises et de bons moments.',
        'Bonne soirée d\'Halloween ! J\'espère qu\'elle sera agréable et festive.',
        'Joyeux Halloween ! Profitez pleinement de cette soirée.',
        'Très bon Halloween [Prénom] ! Que votre soirée soit réussie.',
        'Joyeux Halloween 🎃 Profitez bien de cette ambiance unique.',
        'Bonne soirée ! Que ce Halloween soit agréable.',
        'Joyeux Halloween [Prénom] ! Passez une excellente soirée.',
        'Une soirée spéciale pour profiter ! Joyeux Halloween 🎃',
        'Profitez bien de cette soirée pleine de surprises.',
        'Joyeux Halloween ! Je vous souhaite un bon moment.',
      ],
      long: [
        'Joyeux Halloween [Prénom] 🎃 Je vous souhaite une soirée pleine de surprises, de moments agréables et de bonne humeur. Profitez bien de cette ambiance particulière.',
        'Très bon Halloween ! C\'est une belle occasion de passer un moment agréable. Je vous souhaite une excellente soirée.',
        'Joyeux Halloween [Prénom] ! Que cette soirée soit plaisante et pleine de bons moments.',
        'Joyeux Halloween 🎃 Je vous souhaite une soirée agréable et réussie.',
        'Très bon Halloween ! Profitez bien de cette soirée.',
        'Joyeux Halloween [Prénom] ! J\'espère que votre soirée sera agréable.',
        'Joyeux Halloween 🎃 Une soirée pour profiter et se détendre.',
        'Très bon Halloween ! Je vous souhaite une soirée agréable.',
        'Joyeux Halloween [Prénom] ! Profitez bien de ce moment.',
        'Joyeux Halloween ! Passez une excellente soirée.',
      ],
    },
  },

  retirement: {
    tu: {
      court: [
        'Félicitations pour ta retraite ! 🎉',
        'Bravo pour cette étape !',
        'Une nouvelle vie commence !',
        'Profite bien !',
        'Félicitations !',
        'Place au repos !',
        'Bravo 🎉',
        'Que du bonheur !',
        'Profite à fond !',
        'Très belle retraite !',
      ],
      moyen: [
        'Félicitations pour ta retraite [Prénom] ! Une belle nouvelle étape commence. Profite bien.',
        'Félicitations ! Après tout ce travail, place au plaisir et aux projets.',
        'Félicitations [Prénom] ! Une nouvelle aventure commence. Profite bien.',
      ],
      long: [
        'Félicitations pour ta retraite [Prénom] ! 🎉 Une belle étape commence après un parcours bien rempli. Profite pleinement de cette nouvelle vie.',
        'Félicitations ! Il est temps de profiter de chaque moment et de réaliser tes envies. Je te souhaite une retraite épanouissante.',
        'Félicitations [Prénom] ! Une nouvelle aventure commence. Je te souhaite beaucoup de bonheur pour cette nouvelle vie.',
      ],
    },
    vous: {
      court: [
        'Félicitations pour votre retraite ! 🎉',
        'Bravo pour cette étape !',
        'Une nouvelle vie commence !',
        'Profitez bien !',
        'Félicitations !',
        'Place au repos !',
        'Bravo 🎉',
        'Que du bonheur !',
        'Profitez à fond !',
        'Très belle retraite !',
      ],
      moyen: [
        'Félicitations pour votre retraite [Prénom] ! Une nouvelle étape commence. Profitez pleinement.',
        'Félicitations ! Après votre parcours, place à une nouvelle vie.',
        'Félicitations [Prénom] ! Une nouvelle aventure s\'ouvre à vous.',
      ],
      long: [
        'Félicitations pour votre retraite [Prénom] ! 🎉 Une belle étape commence après un parcours riche. Profitez pleinement de cette nouvelle vie.',
        'Félicitations ! Il est temps de profiter de chaque moment et de vos projets. Je vous souhaite une retraite épanouissante.',
        'Félicitations [Prénom] ! Une nouvelle aventure commence. Je vous souhaite beaucoup de bonheur.',
      ],
    },
  },

  support: {
    tu: {
      court: [
        'Je pense à toi 💛',
        'Courage à toi',
        'Je suis là',
        'Toutes mes pensées',
        'Je pense fort à toi',
        'Prends soin de toi',
        'Beaucoup de courage',
        'Je suis avec toi',
        '💛',
        'Je t\'envoie du soutien',
      ],
      moyen: [
        'Je pense fort à toi [Prénom] 💛 Je suis là si tu en as besoin.',
        'Toutes mes pensées t\'accompagnent. Je t\'envoie beaucoup de courage.',
        'Je pense à toi [Prénom] dans ce moment difficile. Tu n\'es pas seul{E_DEST}.',
      ],
      long: [
        'Je pense très fort à toi [Prénom] 💛 Je sais que ce n\'est pas facile. Je suis là si tu en ressens le besoin.',
        'Toutes mes pensées t\'accompagnent. Prends le temps qu\'il te faut, je suis là.',
        'Je pense à toi [Prénom] dans cette période difficile. Je t\'envoie tout mon soutien.',
      ],
    },
    vous: {
      court: [
        'Je pense à vous',
        'Courage à vous',
        'Toutes mes pensées',
        'Je suis avec vous',
        'Soutien sincère',
        '💛',
        'Beaucoup de courage',
        'Je vous soutiens',
        'Pensées pour vous',
        'Prenez soin de vous',
      ],
      moyen: [
        'Je pense à vous [Prénom] dans cette période difficile. Je vous adresse tout mon soutien.',
        'Toutes mes pensées vous accompagnent. Je vous souhaite beaucoup de courage.',
        'Je pense à vous dans ce moment délicat. Je suis là si besoin.',
      ],
      long: [
        'Je pense sincèrement à vous [Prénom] dans cette période difficile. Je vous adresse tout mon soutien.',
        'Toutes mes pensées vous accompagnent. Je vous souhaite beaucoup de courage pour traverser cette épreuve.',
        'Je pense à vous [Prénom] dans ce moment délicat. Je reste disponible si besoin.',
      ],
    },
  },
};

/** Retourne n éléments aléatoires depuis un tableau */
export function pickRandom<T>(arr: T[], n = 3): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, n);
}
