export const DOG_BREEDS = [
  'Beagle',
  'Berger allemand',
  'Berger américain miniature',
  'Berger australien',
  'Berger belge Malinois',
  'Border Collie',
  'Bouledogue français',
  'Caniche',
  'Cane Corso',
  'Cavalier King Charles',
  'Chihuahua',
  'Cocker Spaniel anglais',
  'Golden Retriever',
  'Husky sibérien',
  'Jack Russell',
  'Labrador Retriever',
  'Rottweiler',
  'Spitz allemand / Poméranien',
  'Staffie',
  'Teckel',
  'Yorkshire Terrier',
  'Autre',
] as const;

export const CAT_BREEDS = [
  'Abyssin',
  'Angora',
  'Bengal',
  'Bleu russe',
  'British Shorthair',
  'Chartreux',
  'Devon Rex',
  'Européen (chat de gouttière)',
  'Exotic Shorthair',
  'Maine Coon',
  'Norvégien',
  'Oriental Shorthair',
  'Persan',
  'Ragdoll',
  'Sacré de Birmanie',
  'Savannah',
  'Scottish Fold',
  'Sibérien',
  'Siamois',
  'Sphynx',
  'Autre',
] as const;
