// ═══════════════════════════════════════════════════════════
//  Confettis & Cake — Timide qui ose (5 occasions)
// ═══════════════════════════════════════════════════════════

export type TimideOccasion = 'birthday' | 'nameday' | 'graduation' | 'departure' | 'cremaillere';

export interface TimideMessage {
  id: string;
  text: string;
}

export interface TimideGroup {
  id: TimideOccasion;
  label: string;
  emoji: string;
  cta: string;
  messages: TimideMessage[];
}

// ── Anniversaire ─────────────────────────────────────────
const BIRTHDAY: TimideMessage[] = [
  { id: 'tm_bday_001', text: `"Joyeux anniversaire. Je dis pas souvent des trucs. Là je dis quelque chose."\nC'est une exception. Pas dans mes habitudes. Pas dans ma façon d'être. Dire des trucs à voix haute. Ou même par message. Mais ton anniversaire m'a donné l'occasion. Et j'ai décidé de la prendre. Joyeux anniversaire, [Prénom].\nAvec aveu simple que dire des trucs c'est pas dans mes habitudes et que je le fais quand même,\n— quelqu'un qui t'écrit depuis un endroit inhabituel pour lui 🫣` },
  { id: 'tm_bday_002', text: `"Je suis pas du genre à écrire des trucs. Mais t'as un anniversaire et je voulais pas pas le marquer."\nNe pas pas le marquer. Cette double négation. C'est ça. Je voulais pas que ton anniversaire passe sans que je dise quelque chose. Alors voilà. Quelque chose. Joyeux anniversaire, [Prénom].\nAvec description de la motivation comme refus de ne pas marquer l'occasion,\n— quelqu'un qui a décidé que ne rien dire était pire que dire quelque chose de maladroit 💛` },
  { id: 'tm_bday_003', text: `"Joyeux anniversaire. Je te dis pas souvent les trucs que je pense sur toi. Là je le fais."\nCes trucs. Que je pense. Que je dis pas. Que je garde. Pas par manque de sentiment. Par manque de facilité avec les mots. Là je le fais quand même. Joyeux anniversaire, [Prénom].\nAvec explication que les trucs sont là mais les mots viennent pas facilement,\n— quelqu'un qui pense beaucoup de trucs bien sur toi et qui en dit un aujourd'hui 🌿` },
  { id: 'tm_bday_004', text: `"T'es quelqu'un qui compte pour moi. Je le dis pas souvent. Je le dis maintenant."\nMaintenant. Ton anniversaire. C'est le moment. Pas parfait. Pas le plus élégant peut-être. Mais un moment. Et j'ai choisi ce moment pour dire ce truc. Que t'es quelqu'un qui compte. Joyeux anniversaire, [Prénom].\nAvec choix de ce moment précis pour dire le truc important,\n— quelqu'un qui a attendu le bon moment et qui a décidé que c'était maintenant 💛` },
  { id: 'tm_bday_005', text: `"Joyeux anniversaire. J'aurais dû dire des trucs plus souvent. Aujourd'hui j'en dis un."\nAurais dû. Ce regret doux. D'avoir gardé trop longtemps trop de choses. Aujourd'hui j'en dis un. Un seul. Comme un début. Comme une pratique. Joyeux anniversaire, [Prénom].\nAvec regret doux de pas avoir dit assez et décision d'en dire un maintenant,\n— quelqu'un qui commence aujourd'hui à dire les trucs et qui espère continuer 🌱` },
  { id: 'tm_bday_006', text: `"Je suis timide avec les mots. Mais j'ai beaucoup de pensées sur toi. Et elles sont bien."\nBeaucoup. De pensées bien. Que je garde. Que je formule pas. Que tu reçois pas parce que mes mots s'arrêtent souvent avant d'arriver. Mais elles sont là. Et elles sont bien. Joyeux anniversaire, [Prénom].\nAvec révélation que les pensées bien existent même si les mots n'arrivent pas toujours,\n— quelqu'un dont les pensées sur toi sont plus nombreuses et meilleures que ce qu'il exprime 💙` },
  { id: 'tm_bday_007', text: `"Joyeux anniversaire. T'as compté pour moi cette année. Et je voulais que tu le saches."\nQue tu le saches. Pas juste que ce soit vrai. Que tu le saches. Que l'information passe. Ton anniversaire m'a donné l'occasion de te le faire passer. Joyeux anniversaire, [Prénom].\nAvec distinction entre que ça soit vrai et que tu le saches comme deux choses différentes,\n— quelqu'un qui voulait que l'information passe et qui a saisi l'occasion 📬` },
  { id: 'tm_bday_008', text: `"Je dis pas souvent les trucs bien sur les gens. Là je fais une exception pour toi."\nUne exception. Parce que tu le mérites. Parce que certaines personnes méritent qu'on surmonte sa timidité pour elles. T'es une de ces personnes. Joyeux anniversaire, [Prénom].\nAvec identification de toi comme méritant l'exception à sa timidité habituelle,\n— quelqu'un dont les exceptions sont rares et qui t'en accorde une aujourd'hui 🎯` },
  { id: 'tm_bday_009', text: `"Joyeux anniversaire. Je voulais juste que tu saches que je suis content que tu existes."\nCe truc simple. Et difficile à dire. Je suis content que tu existes. Dans ma vie. Dans le monde. Ça méritait d'être dit. Ton anniversaire c'est le bon moment. Joyeux anniversaire, [Prénom].\nAvec le truc simple et difficile à dire dit finalement,\n— quelqu'un qui est content que tu existes et qui a attendu un bon moment pour le dire 🌸` },
  { id: 'tm_bday_010', text: `"T'es quelqu'un de bien. Je le pense depuis longtemps. Je le dis maintenant."\nDepuis longtemps. Je le pensais. En silence. Sans que tu le saches. Et maintenant je le dis. Ton anniversaire a été plus fort que ma timidité. Joyeux anniversaire, [Prénom].\nAvec révélation que la pensée existait depuis longtemps mais que le dire vient maintenant,\n— quelqu'un dont la timidité a cédé face à ton anniversaire 💛` },
  { id: 'tm_bday_011', text: `"Joyeux anniversaire. Je suis pas très bon pour dire les trucs. Alors je dis juste ça."\nJuste ça. Ce peu. Qui représente beaucoup en fait. Parce que pour moi dire même ça c'est un effort. Et cet effort c'est pour toi. Joyeux anniversaire, [Prénom].\nAvec invitation à lire le peu comme représentant beaucoup venant de quelqu'un de peu expressif,\n— quelqu'un dont le peu vaut beaucoup et qui espère que tu le lis comme ça 🌊` },
  { id: 'tm_bday_012', text: `"J'observe plus que je parle. Et ce que j'observe sur toi c'est bien. Joyeux anniversaire."\nJ'observe. En silence. Ce que tu fais. Comment tu es. Et ce que j'observe est bien. Je l'ai pas dit souvent. Je le dis maintenant. Joyeux anniversaire, [Prénom].\nAvec révélation de l'observation silencieuse et positive qui existait depuis longtemps,\n— quelqu'un qui observe beaucoup et qui dit peu mais dont les observations sont attentives 👁️` },
  { id: 'tm_bday_013', text: `"Joyeux anniversaire. J'aurais voulu dire ça à voix haute. J'ai écrit à la place."\nCe compromis. Entre vouloir dire et pas arriver à le faire à voix haute. Écrire c'est plus facile. Moins immédiat. C'est ce que j'ai fait. Et c'est pour toi. Joyeux anniversaire, [Prénom].\nAvec description de l'écriture comme compromis accessible entre vouloir dire et pas pouvoir le dire à voix haute,\n— quelqu'un qui a trouvé le format qui lui permettait de dire le truc 💬` },
  { id: 'tm_bday_014', text: `"T'as fait des trucs bien pour les gens autour de toi. Je l'ai vu. Merci."\nMerci. Ce mot. Qu'on dit pas assez. Pour des trucs précis que t'as faits. Que j'ai vus. Ton anniversaire est l'occasion de rattraper ça. Joyeux anniversaire, [Prénom].\nAvec merci tardif mais sincère pour des trucs bien vus et pas assez mentionnés,\n— quelqu'un qui a observé les trucs bien et qui rattrape le retard du merci 🙏` },
  { id: 'tm_bday_015', text: `"Joyeux anniversaire. J'espère que tu sais combien tu comptes. Dans le doute je te le dis."\nDans le doute. Au cas où. Peut-être que tu le sais. Peut-être que non. Dans le doute je te le dis. Tu comptes. Pour moi. Joyeux anniversaire, [Prénom].\nAvec décision de dire le truc dans le doute plutôt que de supposer que tu le sais,\n— quelqu'un qui préfère dire dans le doute que supposer et se taire 💛` },
  { id: 'tm_bday_016', text: `"Je suis timide avec les mots. Mais pour toi j'ai fait l'effort."\nL'effort. Réel. De trouver les mots. De les écrire. De les envoyer. Cet effort c'est pour toi. Parce que tu le mérites. Joyeux anniversaire, [Prénom].\nAvec identification de l'effort comme cadeau en soi venant de quelqu'un de timide avec les mots,\n— quelqu'un qui espère que tu reçois l'effort comme le cadeau qu'il est 🎁` },
  { id: 'tm_bday_017', text: `"Joyeux anniversaire. Je te dis pas assez les trucs bien. Là j'en dis un."\nUn. Un seul. Mais un vrai. Pas vide. Pas de façade. Un vrai truc bien. Que je pense. Que je te dis maintenant. Joyeux anniversaire, [Prénom].\nAvec engagement sur la qualité d'un truc bien dit plutôt que sur la quantité,\n— quelqu'un qui dit peu mais dit vrai et qui espère que tu reçois ce vrai 🌟` },
  { id: 'tm_bday_018', text: `"T'as été là des fois où c'était important. Je l'ai pas assez dit. Je le dis maintenant."\nCes fois. Ces moments. Où t'étais là. Où ça comptait. Ton anniversaire est l'occasion de rattraper ce pas assez. Joyeux anniversaire, [Prénom].\nAvec rattrapage tardif de la reconnaissance pour les fois où t'étais là,\n— quelqu'un qui te doit des reconnaissances et qui commence à les rembourser 💙` },
  { id: 'tm_bday_019', text: `"Joyeux anniversaire. J'aurais voulu être meilleur pour dire les trucs. Là c'est comme je peux."\nComme je peux. Pas comme je voudrais. Pas parfaitement. Comme je peux. Et comme je peux c'est pour toi. C'est tout ce que j'ai. Et c'est sincère. Joyeux anniversaire, [Prénom].\nAvec honnêteté que c'est comme je peux et non comme je voudrais mais que c'est sincère,\n— quelqu'un qui fait de son mieux avec ce qu'il a et qui espère que c'est suffisant 🌿` },
  { id: 'tm_bday_020', text: `"Joyeux anniversaire. Je dis pas souvent des trucs. Aujourd'hui j'en dis. C'est pour toi."\nPour toi. C'est le point central. Tout ce message. Ce dépassement de ma timidité. Cet effort de trouver les mots. C'est pour toi. Parce que tu le mérites. Joyeux anniversaire, [Prénom].\nAvec identification de toi comme raison centrale de tout cet effort,\n— quelqu'un qui a fait tout cet effort pour toi et qui espère que tu le reçois bien ❤️` },
];

// ── Fête du prénom ───────────────────────────────────────
const NAMEDAY: TimideMessage[] = [
  { id: 'tm_name_001', text: `"Joyeuse fête. Je dis pas souvent des trucs. Ta fête du prénom m'a donné une excuse."\nUne excuse. Pour enfin dire quelque chose. Parce que sans occasion je trouve pas la façon de le faire. Mais là y'a une occasion. Et j'ai décidé d'en profiter. Joyeuse fête, [Prénom].\nAvec utilisation de ta fête du prénom comme excuse bienvenue pour dire enfin quelque chose,\n— quelqu'un qui avait besoin d'une excuse et qui est content d'en avoir trouvé une 🫣` },
  { id: 'tm_name_002', text: `"Joyeuse fête. J'aurais pu rien dire. T'aurais pas su que j'avais des trucs à dire. Mais là je le fais."\nCette décision. Active. De ne pas laisser passer cette occasion. De pas garder ces trucs pour moi cette fois. Joyeuse fête, [Prénom].\nAvec description de la décision active de ne pas laisser passer l'occasion,\n— quelqu'un qui a décidé que cette fois il allait pas garder les trucs pour lui 💛` },
  { id: 'tm_name_003', text: `"Joyeuse fête. Je suis quelqu'un qui dit pas facilement les trucs. Mais t'es quelqu'un pour qui j'essaie."\nJ'essaie. Ce verbe. Qui dit que c'est difficile. Que ça demande un effort. Et que je le fais quand même pour toi. Joyeuse fête, [Prénom].\nAvec identification de toi comme quelqu'un pour qui l'effort de dire les trucs vaut la peine,\n— quelqu'un qui essaie pour toi et qui espère que tu vois l'effort dans ce mot 🌿` },
  { id: 'tm_name_004', text: `"Joyeuse fête. Tu comptes pour moi. Je le dis pas assez. Ta fête du prénom c'est une occasion de rattraper."\nRattraper. Ce retard dans les trucs dits. Ta fête du prénom est l'occasion de rattraper au moins un peu ce retard. Joyeuse fête, [Prénom].\nAvec description de ta fête du prénom comme occasion de rattraper un retard dans les trucs dits,\n— quelqu'un qui a un retard à rattraper et qui commence maintenant 📮` },
  { id: 'tm_name_005', text: `"Joyeuse fête. Je pense souvent des trucs bien sur toi. Je les dis rarement. Là je le fais."\nLà. Ce moment précis. Ta fête du prénom. J'ai décidé de prendre cette occasion pour dire un truc bien que je pense souvent. Joyeuse fête, [Prénom].\nAvec identification de ta fête du prénom comme moment précis pour dire enfin le truc pensé souvent,\n— quelqu'un qui pense souvent des trucs bien sur toi et qui en dit un aujourd'hui 💙` },
  { id: 'tm_name_006', text: `"Joyeuse fête. J'ai du mal à dire les choses en face. Alors je les écris."\nEn face. Ce serait trop. Écrire c'est plus accessible. C'est une protection. Et ça permet quand même de dire. Joyeuse fête, [Prénom].\nAvec explication de l'écriture comme format accessible pour quelqu'un qui a du mal en face,\n— quelqu'un qui a trouvé son format et qui l'utilise pour toi 💬` },
  { id: 'tm_name_007', text: `"Joyeuse fête. T'as fait des trucs bien pour moi. Je le sais. Et je te le dis enfin."\nEnfin. Ce mot. Qui dit que ça devrait être venu avant. Ta fête du prénom c'est l'occasion de rattraper. Joyeuse fête, [Prénom].\nAvec enfin comme mot qui porte tout le retard rattrapé,\n— quelqu'un qui rattrape un retard et qui espère que c'est pas trop tard 🙏` },
  { id: 'tm_name_008', text: `"Joyeuse fête. Je suis timide avec les mots mais pas avec les sentiments. Ils sont là."\nIls sont là. Les sentiments. L'amitié. La reconnaissance. Tout ça est là. C'est juste les mots qui viennent pas facilement. Joyeuse fête, [Prénom].\nAvec distinction entre la timidité avec les mots et la présence réelle des sentiments,\n— quelqu'un dont les sentiments sont là même quand les mots ne suivent pas 💛` },
  { id: 'tm_name_009', text: `"Joyeuse fête. J'espère que tu sais à quel point tu comptes. Dans le doute je te le dis."\nDans le doute. Parce que peut-être que tu sais pas. Je dis pas assez. Dans le doute je te le dis. Tu comptes. Joyeuse fête, [Prénom].\nAvec décision de dire dans le doute plutôt que de supposer que tu le sais déjà,\n— quelqu'un qui préfère trop dire que pas assez pour une fois 💛` },
  { id: 'tm_name_010', text: `"Joyeuse fête. Je garde beaucoup pour moi. Là j'essaie de partager un peu."\nUn peu. Parmi tout ce que je garde. Un peu qui sort. Pour toi. Pour ta fête du prénom. Joyeuse fête, [Prénom].\nAvec invitation à recevoir le peu comme représentant le beaucoup gardé,\n— quelqu'un qui partage un peu de ce qu'il garde beaucoup et qui espère que ça dit quelque chose 🌊` },
  { id: 'tm_name_011', text: `"Joyeuse fête. T'es quelqu'un qu'on a de la chance d'avoir autour. Je le pense. Là je le dis."\nLà. Ta fête du prénom. Ce moment. Où j'ai décidé que le penser sans le dire c'était pas assez. Joyeuse fête, [Prénom].\nAvec décision que le penser sans dire n'était plus suffisant,\n— quelqu'un qui a décidé que l'information méritait de voyager jusqu'à toi 🌸` },
  { id: 'tm_name_012', text: `"Joyeuse fête. Je dis les trucs difficiles encore moins que les trucs faciles. Celui-là est difficile et je le dis."\nDifficile. Parce que c'est vrai. Et que le vrai c'est plus difficile à dire. Mais ta fête du prénom mérite le vrai. Joyeuse fête, [Prénom].\nAvec identification du truc difficile à dire et décision de le dire quand même,\n— quelqu'un qui choisit le vrai difficile sur le convenu facile pour toi 🎯` },
  { id: 'tm_name_013', text: `"Joyeuse fête. J'aurais voulu te dire des trucs en personne. J'arrive pas. Alors je t'écris."\nJ'arrive pas. À voix haute. Alors j'écris. C'est moins parfait que ce que je voudrais. Et c'est mieux que rien. Joyeuse fête, [Prénom].\nAvec honnêteté sur l'impossibilité de dire en personne et l'écriture comme solution imparfaite mais réelle,\n— quelqu'un qui trouve une façon de dire même si ce n'est pas la façon idéale 💙` },
  { id: 'tm_name_014', text: `"Joyeuse fête. T'as une façon d'être qui m'a marqué. Je l'ai pas dit. Je le dis maintenant."\nMarqué. Ce mot fort. Ce que tu as fait. Cette façon d'être. Qui a laissé une trace. Tu m'as marqué. Et je te le dis maintenant. Joyeuse fête, [Prénom].\nAvec révélation tardive mais sincère de l'impact de ta façon d'être,\n— quelqu'un qui a été marqué et qui te le dit enfin 🌟` },
  { id: 'tm_name_015', text: `"Joyeuse fête. Je voulais que tu saches que ton prénom c'est quelqu'un qui compte pour moi."\nTon prénom. Ce prénom fêté aujourd'hui. C'est toi. Et toi tu comptes. Pour moi. Joyeuse fête, [Prénom].\nAvec connexion poétique entre le prénom fêté et le fait que tu comptes,\n— quelqu'un qui a trouvé une façon originale de dire le truc important 🌿` },
  { id: 'tm_name_016', text: `"Joyeuse fête. J'ai souvent les mots dans la tête et pas dans la bouche. Là ils sont quelque part entre les deux."\nEntre les deux. Pas tout à fait à voix haute. Pas tout à fait gardés. Dans ce message. Joyeuse fête, [Prénom].\nAvec description de la zone intermédiaire entre les mots dans la tête et les mots dits,\n— quelqu'un qui habite cette zone intermédiaire et qui écrit depuis là 🌀` },
  { id: 'tm_name_017', text: `"Joyeuse fête. T'es quelqu'un de bien. Et ça méritait d'être dit. Même par quelqu'un comme moi."\nMême par quelqu'un comme moi. Qui dit pas facilement. Qui préfère souvent se taire. Ça méritait d'être dit. Joyeuse fête, [Prénom].\nAvec insistance que même quelqu'un de peu expressif comme lui méritait de le dire,\n— quelqu'un qui pense que certains trucs méritent d'être dits même par ceux qui disent peu 💛` },
  { id: 'tm_name_018', text: `"Joyeuse fête. Je dis rarement les trucs qui comptent. Là je fais une exception."\nUne exception. Rare. Précieuse. Parce que tu mérites une exception. Parce que ta fête du prénom mérite que je sorte de mes habitudes. Joyeuse fête, [Prénom].\nAvec identification de l'exception comme rare et précieuse pour cette occasion,\n— quelqu'un dont les exceptions sont rares et qui en fait une pour toi aujourd'hui 🌟` },
  { id: 'tm_name_019', text: `"Joyeuse fête. J'espère que tu reçois ce message comme ce qu'il est. Un effort sincère."\nUn effort. Sincère. C'est ce que c'est. Pas parfait. Peut-être pas élégant. Mais sincère. Joyeuse fête, [Prénom].\nAvec invitation à recevoir le message comme effort sincère plutôt que comme production littéraire,\n— quelqu'un qui espère que la sincérité passe malgré l'imperfection 💙` },
  { id: 'tm_name_020', text: `"Joyeuse fête. Je dis pas souvent des trucs. Là j'en dis. C'est pour toi. C'est tout."\nC'est tout. La conclusion simple. Je dis pas souvent. Là j'en dis. C'est pour toi. Rien de plus à ajouter. Joyeuse fête, [Prénom].\nAvec économie de mots finale parce que le reste a déjà été dit,\n— quelqu'un qui a dit ce qu'il avait à dire et qui s'arrête là ❤️` },
];

// ── Diplôme ──────────────────────────────────────────────
const GRADUATION: TimideMessage[] = [
  { id: 'tm_grad_001', text: `"Félicitations. Je dis pas souvent des trucs. Là j'en dis un. T'as réussi et je voulais que tu le saches."\nQue tu le saches. Que j'ai vu. Que j'ai remarqué. Que ça m'a touché. Ton diplôme méritait que je sorte de mes habitudes. Félicitations, [Prénom].\nAvec sortie des habitudes pour que l'information passe jusqu'à toi,\n— quelqu'un qui voulait que tu saches qu'il a vu et qui te le dit enfin 🌟` },
  { id: 'tm_grad_002', text: `"T'as eu ton diplôme. Je suis fier de toi. Je le dis pas souvent. Je le dis maintenant."\nFier. Ce mot. Que je garde souvent. Que je dis pas facilement. Là il sort. Pour toi. Pour ton diplôme. Félicitations, [Prénom].\nAvec le mot fier dit enfin pour une fois,\n— quelqu'un qui le ressent souvent et qui le dit rarement et qui fait l'exception maintenant 💛` },
  { id: 'tm_grad_003', text: `"Félicitations. Je voulais te dire quelque chose depuis un moment. Ton diplôme m'en donne l'occasion."\nDepuis un moment. Ces trucs qui attendent. Ton diplôme a créé ce moment. Et j'en profite. Félicitations, [Prénom].\nAvec utilisation du diplôme comme occasion pour dire quelque chose qui attendait depuis longtemps,\n— quelqu'un qui attendait le bon moment et qui a décidé que c'était maintenant 🎓` },
  { id: 'tm_grad_004', text: `"T'as réussi quelque chose de difficile. Je t'ai vu traverser ça. Et je voulais que tu saches que j'ai vu."\nJ'ai vu. Cette observation silencieuse. De ton effort. J'ai vu et j'ai rien dit. Là je dis. J'ai vu. Et c'était bien. Félicitations, [Prénom].\nAvec révélation de l'observation silencieuse qui existait et que tu ne savais peut-être pas,\n— quelqu'un qui a observé en silence et qui te le dit maintenant 👁️` },
  { id: 'tm_grad_005', text: `"Félicitations. T'as travaillé pour ça. J'ai du respect pour ce travail. Je le dis pas assez. Là je le dis."\nLà. Ce moment. Après ton diplôme. Pour que tu saches que le respect est là. Que le travail a été vu. Félicitations, [Prénom].\nAvec rattrapage du manque de dits et expression du respect pour ton travail,\n— quelqu'un qui rattrape maintenant ce qu'il aurait dû dire pendant 🙏` },
  { id: 'tm_grad_006', text: `"T'as eu ton diplôme. C'est une réussite. Et j'aurais dû te dire des trucs pendant que tu traversais. Je le fais maintenant."\nPendant. J'aurais dû. Pendant les révisions. Pendant les examens. J'aurais dû dire des trucs. J'ai pas. Je les dis maintenant. C'est mieux que jamais. Félicitations, [Prénom].\nAvec regret de pas avoir dit des trucs pendant et décision de les dire maintenant,\n— quelqu'un qui pense que maintenant c'est mieux que jamais 🌱` },
  { id: 'tm_grad_007', text: `"Félicitations. Je t'aurais bien dit des trucs en personne. J'arrive pas. Alors je t'écris."\nCette impossibilité. De dire en personne. Alors j'écris. C'est moins parfait. C'est ce que je peux faire. Et je le fais pour toi. Félicitations, [Prénom].\nAvec honnêteté sur l'impossibilité en personne et l'écriture comme alternative accessible,\n— quelqu'un qui fait ce qu'il peut pour que les trucs soient dits 💬` },
  { id: 'tm_grad_008', text: `"T'as réussi. Je le savais que tu allais réussir. J'aurais dû te le dire avant. C'est maintenant."\nAvant. J'aurais dû te dire que j'avais confiance. Ça t'aurait peut-être aidé. J'ai pas dit. Je le dis maintenant. Après. Félicitations, [Prénom].\nAvec confession de pas avoir dit la confiance avant et regret doux de ce manque,\n— quelqu'un qui regrette de pas avoir dit sa confiance avant et qui la dit maintenant 💙` },
  { id: 'tm_grad_009', text: `"Félicitations. Tu méritais ce diplôme. Et tu méritais que quelqu'un te le dise clairement."\nClairement. Sans ambiguïté. Tu méritais ce diplôme. Et tu méritais d'entendre ça. Je te le dis clairement. Félicitations, [Prénom].\nAvec décision de dire clairement ce que tu méritais d'entendre,\n— quelqu'un qui pense que la clarté sur ce qu'on mérite est un cadeau 🌟` },
  { id: 'tm_grad_010', text: `"T'as eu ton diplôme. C'est beau. Et j'avais du mal à trouver les mots pour le dire. Les voilà."\nLes voilà. Ces mots. Qui ont mis du temps à arriver. Mais qui sont là. C'est beau ce que tu as fait. Félicitations, [Prénom].\nAvec présentation des mots enfin trouvés après les avoir cherchés,\n— quelqu'un qui a cherché les mots et qui te les présente maintenant 🌸` },
  { id: 'tm_grad_011', text: `"Félicitations. Je suis content pour toi. Je le dis pas souvent. Là c'est dit."\nC'est dit. Ce constat simple. Que les mots ont voyagé. Qu'ils sont arrivés. Je suis content pour toi. C'est dit. Félicitations, [Prénom].\nAvec satisfaction que les mots soient enfin dits,\n— quelqu'un qui trouve une satisfaction particulière dans le fait que les mots soient dits 💛` },
  { id: 'tm_grad_012', text: `"T'as eu ton diplôme. C'est une belle étape. J'avais envie de le marquer même si c'est pas dans mes habitudes."\nPas dans mes habitudes. Mais ton diplôme m'a semblé mériter que je sorte de mes habitudes. Alors je les ai sorties. Félicitations, [Prénom].\nAvec sortie des habitudes comme acte volontaire pour marquer ton diplôme,\n— quelqu'un qui sort de ses habitudes pour toi et qui en est content 🎯` },
  { id: 'tm_grad_013', text: `"Félicitations. T'as galéré et tu l'as eu. Je t'ai vu galérer. Je t'en dis la valeur maintenant."\nLa valeur. De ta galère. De ton effort. Je t'ai vu. Et là je te dis la valeur de ce que j'ai vu. Elle est grande. Félicitations, [Prénom].\nAvec révélation tardive de la valeur que j'attribuais à ta galère,\n— quelqu'un qui attribuait une grande valeur à ton effort et qui te le dit maintenant 💪` },
  { id: 'tm_grad_014', text: `"T'as réussi quelque chose. Je voulais que tu saches que j'en suis fier. Même si je le dis rarement."\nMême si. Ce petit mot. Qui reconnaît ma limite. Et qui dit quand même. Même si je le dis rarement. Là je le dis. Pour toi. Félicitations, [Prénom].\nAvec le même si qui reconnaît la limite et qui dit quand même malgré elle,\n— quelqu'un qui dépasse sa limite pour te dire le truc important 🌿` },
  { id: 'tm_grad_015', text: `"Félicitations. Je voulais juste que tu saches que quelqu'un dans ta vie voit ce que tu fais et en est fier."\nQuelqu'un. Qui voit. En silence peut-être. Mais qui voit. Et qui est fier. Ce quelqu'un c'est moi. Félicitations, [Prénom].\nAvec révélation d'être ce quelqu'un qui voit et qui est fier en silence,\n— quelqu'un qui observe et qui est fier et qui te le dit enfin 👁️` },
  { id: 'tm_grad_016', text: `"T'as eu ton diplôme. Je suis content. Je le dis maintenant parce que je l'ai pas assez dit avant."\nParce que. Cette raison honnête. Je l'ai pas assez dit avant. Alors je le dis maintenant. Pour combler un peu. Félicitations, [Prénom].\nAvec honnêteté que le dire maintenant est en partie une façon de rattraper le passé,\n— quelqu'un qui rattrape maintenant et qui espère que ça compte quand même 💙` },
  { id: 'tm_grad_017', text: `"Félicitations. T'as fait quelque chose de difficile. Et j'aurais voulu être meilleur pour te le dire pendant. Là c'est après."\nAprès. C'est moins bien. Mais après c'est mieux que jamais. Et là c'est dit. Et ça compte quand même. Félicitations, [Prénom].\nAvec acceptation que le après est mieux que le jamais,\n— quelqu'un qui préfère le après imparfait au jamais propre 🌊` },
  { id: 'tm_grad_018', text: `"T'as eu ton diplôme. Quelque chose en moi voulait te le dire. J'ai laissé ce quelque chose parler."\nCe quelque chose. Cette impulsion. J'aurais pu l'étouffer comme d'habitude. Là je l'ai laissé parler. Et il t'a écrit ça. Félicitations, [Prénom].\nAvec description de l'impulsion laissée parler pour une fois,\n— quelqu'un qui a laissé l'impulsion parler au lieu de l'étouffer et qui en est content 🌱` },
  { id: 'tm_grad_019', text: `"Félicitations. J'espère que tu reçois ce message pour ce qu'il est. La preuve que quelqu'un a vu."\nLa preuve. Que j'ai vu. Que ton diplôme a été vu. Que ton effort a été vu. Par quelqu'un qui le dit rarement mais qui le dit là. Félicitations, [Prénom].\nAvec identification du message comme preuve que quelqu'un a vu,\n— quelqu'un qui a vu et qui te le prouve maintenant 💛` },
  { id: 'tm_grad_020', text: `"Félicitations. Je dis pas souvent des trucs. Pour ton diplôme j'en dis un. C'est pour toi."\nPour toi. C'est ça le point central. Ce message. Cet effort. Ce dépassement. C'est pour toi. Et parce que tu méritais que quelqu'un le dise. Félicitations, [Prénom].\nAvec identification de toi comme raison principale de tout cet effort,\n— quelqu'un qui a fait tout ça pour toi et qui espère que tu le reçois bien ❤️` },
];

// ── Départ ───────────────────────────────────────────────
const DEPARTURE: TimideMessage[] = [
  { id: 'tm_dep_001', text: `"Tu pars. Je dis pas souvent des trucs. Là je peux pas laisser partir sans dire quelque chose."\nPas laisser partir sans dire. Cette ligne. Que je me suis fixée. Parce que si tu pars sans que j'aie dit quelque chose je le regretterais. Alors je le dis. Même maladroitement. Bon voyage, [Prénom].\nAvec ligne tracée de ne pas laisser partir sans dire quelque chose,\n— quelqu'un qui pense que les départs méritent des mots même pour ceux qui en disent peu 🌍` },
  { id: 'tm_dep_002', text: `"Tu pars. J'aurais voulu te dire des trucs depuis longtemps. Ton départ crée une urgence."\nUne urgence. Que le départ crée. Ces trucs qui attendaient le bon moment. Et le bon moment qui s'éloigne avec toi. Alors l'urgence. Bon voyage, [Prénom].\nAvec description du départ comme créateur d'urgence pour les trucs qui attendaient,\n— quelqu'un que l'urgence a aidé à dire enfin ce qui attendait 💛` },
  { id: 'tm_dep_003', text: `"Tu pars. Je suis timide avec les mots. Mais là les mots doivent voyager avec toi."\nVoyager avec toi. Ces mots. Pas gardés. Envoyés. Qui t'accompagnent dans ton départ. Bon voyage, [Prénom].\nAvec image des mots qui voyagent avec toi malgré la timidité de l'émetteur,\n— quelqu'un qui envoie ses mots voyager avec toi ✈️` },
  { id: 'tm_dep_004', text: `"Je sais pas trop comment dire au revoir. Alors je dis un truc que je gardais."\nUn truc gardé. Qui sort maintenant. Parce qu'un au revoir c'est une occasion. Et les occasions méritent d'être saisies même par quelqu'un comme moi. Bon voyage, [Prénom].\nAvec saisie de l'occasion du départ pour sortir un truc gardé,\n— quelqu'un qui saisit l'occasion même si c'est pas dans ses habitudes 🚪` },
  { id: 'tm_dep_005', text: `"Tu pars. Et j'aurais voulu être meilleur pour dire les trucs. Là c'est comme je peux."\nComme je peux. Cette honnêteté. Que ce que je dis est imparfait. Mais que c'est sincère dans son imperfection. Bon voyage, [Prénom].\nAvec honnêteté sur l'imperfection de ce qui est dit et la sincérité dans cette imperfection,\n— quelqu'un qui fait de son mieux et qui espère que c'est suffisant 💙` },
  { id: 'tm_dep_006', text: `"Tu pars. T'as compté pour moi. Je te le dis maintenant parce que si je le dis pas maintenant je le dirai peut-être jamais."\nPeut-être jamais. Cette prise de conscience. Que le départ crée une dernière occasion. Alors je dis. Bon voyage, [Prénom].\nAvec prise de conscience que le départ est peut-être la dernière occasion,\n— quelqu'un qui refuse de laisser passer peut-être la dernière occasion 💛` },
  { id: 'tm_dep_007', text: `"Tu pars. Je voulais que tu emportes avec toi la certitude que quelqu'un ici te pense du bien."\nEmporter avec toi. Cette certitude. Que tu ne pars pas dans un vide. Que quelqu'un ici pense du bien de toi. Cette certitude comme bagage. Bon voyage, [Prénom].\nAvec idée de la certitude comme bagage à emporter,\n— quelqu'un qui voulait t'équiper de cette certitude pour le voyage 🎒` },
  { id: 'tm_dep_008', text: `"Tu pars. Je suis quelqu'un qui dit pas les trucs. Mais là je veux pas que tu penses que les trucs sont pas là."\nIls sont là. Les trucs. L'affection. La reconnaissance. Ils sont là même si je les dis pas. Et je veux pas que tu penses qu'ils sont absents. Bon voyage, [Prénom].\nAvec clarification que les trucs sont là même quand ils ne sont pas dits,\n— quelqu'un qui voulait que tu saches que le silence ne veut pas dire l'absence 🌿` },
  { id: 'tm_dep_009', text: `"Tu pars. Et je réalise que j'aurais dû dire des trucs avant. J'en dis un maintenant."\nUn. Un seul. Mais vrai. Pour que tu partes avec au moins un truc dit. Ce truc c'est que tu comptes. Bon voyage, [Prénom].\nAvec compensation partielle du silence d'avant par ce truc dit maintenant,\n— quelqu'un qui compense le silence d'avant et qui espère que ça suffit 💙` },
  { id: 'tm_dep_010', text: `"Tu pars vers quelque chose de nouveau. Et moi je vais dire quelque chose de nouveau aussi."\nQuelque chose de nouveau. Pour moi aussi. Dire les trucs. Ça c'est nouveau. T'as ton aventure. Moi j'ai ma petite aventure à moi. Bon voyage, [Prénom].\nAvec parallèle poétique entre ton aventure du départ et la mienne de dire les trucs,\n— quelqu'un qui trouve ce parallèle à la fois absurde et touchant 🌀` },
  { id: 'tm_dep_011', text: `"Tu pars. Je suis content pour toi. Triste aussi. Et je le dis parce que tu mérites de le savoir."\nTu mérites de le savoir. Que je suis content pour toi. Et triste aussi. Ces deux sentiments coexistent. Et tu mérites d'en être informé. Bon voyage, [Prénom].\nAvec transmission de l'information des deux sentiments parce que tu mérites de le savoir,\n— quelqu'un qui pense que tu mérites d'être informé de ses sentiments 💛` },
  { id: 'tm_dep_012', text: `"Tu pars. Je garde beaucoup. Là je lâche un peu. C'est pour toi avant ton départ."\nLâche un peu. Ce que je garde. Pour toi. Avant que tu partes. Parce que si je le lâche pas maintenant je le garderai peut-être toujours. Bon voyage, [Prénom].\nAvec décision de lâcher un peu de ce qu'on garde avant que le départ ne soit définitif,\n— quelqu'un qui lâche un peu pour toi et qui espère que ça arrive avant ton avion 🌸` },
  { id: 'tm_dep_013', text: `"Tu pars. T'as eu de l'impact sur moi. Je le gardais. Je te le dis avant ton départ."\nDe l'impact. Ce mot fort. Que j'aurais voulu dire depuis. Et ton départ crée l'urgence de le dire avant que tu disparaisses là-bas. Bon voyage, [Prénom].\nAvec révélation urgente de l'impact eu avant le départ,\n— quelqu'un qui ne voulait pas garder ça sans te le dire avant que tu partes 🌊` },
  { id: 'tm_dep_014', text: `"Tu pars. J'espère que tu emportes avec toi des trucs bons. J'essaie d'en ajouter un."\nUn truc bon. Que j'essaie d'ajouter. À ton bagage. Pas matériel. Émotionnel. Ce message. Cette affection. Bon voyage, [Prénom].\nAvec tentative d'ajouter un truc bon au bagage émotionnel du départ,\n— quelqu'un qui essaie d'ajouter un truc bon et qui espère y arriver 🎒` },
  { id: 'tm_dep_015', text: `"Tu pars. Et je réalise que les gens qui partent méritent qu'on leur dise des trucs avant."\nMéritent. Que tu mérites. Des trucs dits avant. Pas après. Avant. Pendant qu'il est encore temps. Là c'est encore temps. Bon voyage, [Prénom].\nAvec réalisation que les départs méritent des trucs dits avant pendant qu'il est encore temps,\n— quelqu'un qui a réalisé ça et qui agit en conséquence 🚪` },
  { id: 'tm_dep_016', text: `"Tu pars. Je veux que tu saches que tu vas être dans mes pensées là-bas."\nDans mes pensées. Là-bas. Quand tu seras parti. T'y seras. Même si je le dis pas à voix haute. Même si tu l'entends pas. T'y seras. Bon voyage, [Prénom].\nAvec révélation que tu seras dans les pensées même à distance,\n— quelqu'un qui pense à toi souvent et qui voulait que tu le saches avant de partir 💭` },
  { id: 'tm_dep_017', text: `"Tu pars. J'ai du mal à dire les trucs. Mais j'ai encore plus de mal à te laisser partir sans en dire un."\nEncore plus de mal. Cette comparaison. Entre la difficulté de dire et la difficulté de te laisser partir sans dire. La deuxième l'emporte. Alors je dis. Bon voyage, [Prénom].\nAvec comparaison des deux difficultés dont la deuxième l'emporte,\n— quelqu'un qui a pesé les deux difficultés et qui a choisi de dire 🎯` },
  { id: 'tm_dep_018', text: `"Tu pars. Je te dis pas souvent les trucs bien. Avant ton départ j'en dis un. Tu mérites ça."\nTu mérites ça. Ce truc dit. Cette exception à mes habitudes. Ton départ mérite que je te le donne. Bon voyage, [Prénom].\nAvec identification de ce que tu mérites comme raison de l'exception,\n— quelqu'un qui pense que tu mérites ce truc dit et qui le donne avant que tu partes 💛` },
  { id: 'tm_dep_019', text: `"Tu pars. Et je réalise que si je dis pas quelque chose maintenant ce sera une occasion ratée."\nUne occasion ratée. Ce que je voulais pas. J'ai vu l'occasion. J'ai pas voulu la rater. Alors je dis. Bon voyage, [Prénom].\nAvec refus de laisser passer l'occasion comme motivation principale,\n— quelqu'un qui ne voulait pas rater cette occasion et qui ne l'a pas ratée 🌟` },
  { id: 'tm_dep_020', text: `"Tu pars. Je dis pas souvent des trucs. Là j'en dis. Pour que tu partes avec ça. Bon voyage, [Prénom]."\nPour que tu partes avec ça. Ce truc dit. Ce message. Cette affection exprimée. Pour que ton bagage contienne aussi ça. Bon voyage, [Prénom].\nAvec intention que tu partes avec ce truc dit comme partie de ton bagage,\n— quelqu'un qui voulait que son truc fasse partie de ton voyage ❤️` },
];

// ── Crémaillère ──────────────────────────────────────────
const CREMAILLERE: TimideMessage[] = [
  { id: 'tm_crem_001', text: `"Bienvenue chez toi. Je dis pas souvent des trucs. Ta crémaillère m'en donne l'occasion."\nL'occasion. Créée par ta crémaillère. Par cet événement. Par ce nouveau chapitre. Qui mérite des mots. Même de la part de quelqu'un qui en dit peu. Bienvenue, [Prénom].\nAvec utilisation de la crémaillère comme occasion pour dire enfin quelque chose,\n— quelqu'un qui avait besoin d'une occasion et qui l'a trouvée 🏠` },
  { id: 'tm_crem_002', text: `"T'as un chez-toi. Je voulais marquer ça. Même si c'est pas dans mes habitudes."\nPas dans mes habitudes. Marquer. Célébrer. Dire des trucs. Mais ton chez-toi mérite ça. Mérite que je sorte de mes habitudes. Bienvenue, [Prénom].\nAvec sortie des habitudes pour marquer ce qui mérite de l'être,\n— quelqu'un qui sort de ses habitudes pour toi et pour ton chez-toi 🌟` },
  { id: 'tm_crem_003', text: `"Bienvenue chez toi. Je suis timide avec les mots. Mais je suis content pour toi. Et 'je suis content pour toi' méritait d'être dit."\nMéritait. Ce mot. Qui dit que l'information avait besoin de voyager. Que te la garder pour moi c'était pas assez. Que tu méritais de la recevoir. Je suis content pour toi. Bienvenue, [Prénom].\nAvec décision que l'information méritait de voyager jusqu'à toi,\n— quelqu'un qui a décidé que l'information méritait le trajet 💛` },
  { id: 'tm_crem_004', text: `"T'as un chez-toi. C'est une étape. J'ai voulu dire quelque chose pour marquer cette étape."\nVoulu. Ce verbe. Qui dit que c'était intentionnel. Que j'ai décidé. Que ça n'est pas arrivé par hasard. J'ai voulu. Et j'ai fait. Bienvenue, [Prénom].\nAvec identification du vouloir comme acte intentionnel,\n— quelqu'un qui a voulu et qui a fait et qui en est content 🎯` },
  { id: 'tm_crem_005', text: `"Bienvenue chez toi. Je voulais juste que tu saches que quelqu'un est content pour toi."\nQuelqu'un. Ce quelqu'un c'est moi. Content pour toi. Pour ton chez-toi. Pour cette étape. Et je voulais que tu le saches. Bienvenue, [Prénom].\nAvec révélation que le quelqu'un content pour toi c'est moi,\n— quelqu'un qui voulait que tu saches que tu as ce quelqu'un 💙` },
  { id: 'tm_crem_006', text: `"T'as un chez-toi. J'aurais voulu te le dire en personne. J'arrive pas. Alors je t'écris."\nJ'arrive pas. À voix haute. En te regardant. T'aurais vu ma gêne. Alors j'écris. C'est moins exposé. Et ça dit quand même ce que je veux dire. Bienvenue, [Prénom].\nAvec honnêteté sur l'impossibilité en personne et l'écriture comme alternative,\n— quelqu'un qui trouve dans l'écriture le format qui lui permet de dire 💬` },
  { id: 'tm_crem_007', text: `"Bienvenue chez toi. Je t'aurais bien dit des trucs depuis longtemps. Ton chez-toi me donne l'occasion."\nL'occasion créée par ton chez-toi. Ces trucs qui attendaient. Le bon moment. Qui arrive. Sous forme de crémaillère. Et j'en profite. Bienvenue, [Prénom].\nAvec utilisation de la crémaillère comme bon moment tant attendu,\n— quelqu'un qui attendait le bon moment et qui pense que celui-là en est un 🌸` },
  { id: 'tm_crem_008', text: `"T'as un chez-toi. C'est une belle étape dans ta vie. Je le pense. Là je le dis."\nLà. Ce maintenant. Ta crémaillère. L'occasion de dire ce que je pense. Ce que je gardais. Là je le dis. Bienvenue, [Prénom].\nAvec le là comme moment choisi pour dire ce qui était pensé depuis longtemps,\n— quelqu'un qui choisit ce là pour dire ce qui attendait 💛` },
  { id: 'tm_crem_009', text: `"Bienvenue chez toi. Je dis rarement les trucs. Là je dis un truc. C'est que je suis fier de où t'en es."\nFier. Ce mot. Que je garde souvent. Que je dis rarement. Là il sort. Pour ton chez-toi. Pour où t'en es. Pour qui tu es devenu. Je suis fier. Bienvenue, [Prénom].\nAvec le mot fier dit enfin pour ton chez-toi et où t'en es,\n— quelqu'un qui est fier depuis longtemps et qui le dit enfin maintenant 🌟` },
  { id: 'tm_crem_010', text: `"T'as un chez-toi. Et j'aurais dû te dire plus souvent les trucs bien. Là j'en dis un."\nUn. Pour commencer. Pour rattraper un peu. Pour que tu saches que les pensées bien existaient même quand les mots manquaient. Bienvenue, [Prénom].\nAvec rattrapage partiel des trucs bien pas assez dits,\n— quelqu'un qui commence à rattraper maintenant 🌱` },
  { id: 'tm_crem_011', text: `"Bienvenue chez toi. Je suis content que t'aies ce chez-toi. Et j'aurais voulu le dire plus vite."\nPlus vite. Dès que tu as eu les clés peut-être. Mais j'ai tardé. Et là c'est tardif. Et c'est quand même dit. Et c'est mieux que pas dit. Bienvenue, [Prénom].\nAvec aveu du retard et décision de dire quand même malgré le retard,\n— quelqu'un qui préfère le tardif au jamais 📮` },
  { id: 'tm_crem_012', text: `"T'as un chez-toi. J'espère que tu sais combien c'est bien. Dans le doute je te le dis."\nDans le doute. Au cas où. Dans le doute je le dis. C'est bien. Ce que tu as. C'est une vraie étape. Et tu devrais en être fier. Bienvenue, [Prénom].\nAvec décision de dire dans le doute ce que tu devrais savoir,\n— quelqu'un qui pense que dans le doute il vaut mieux dire 💛` },
  { id: 'tm_crem_013', text: `"Bienvenue chez toi. J'observe souvent. Je dis peu. Là j'observe que t'as fait quelque chose de bien."\nJ'observe. En silence. Ce que tu fais. Ce que tu construis. Et là j'observe que t'as fait quelque chose de bien. Et j'ai décidé de dire ce que j'observe. Bienvenue, [Prénom].\nAvec révélation que l'observation silencieuse a produit ce constat et cette décision de dire,\n— quelqu'un qui observe beaucoup et qui dit peu et qui dit là que c'est bien 👁️` },
  { id: 'tm_crem_014', text: `"T'as un chez-toi. Ça représente quelque chose. J'avais envie de marquer ça même si c'est pas facile pour moi."\nPas facile pour moi. Cette honnêteté. Que dire des trucs c'est pas facile. Et que je le fais quand même. Parce que ça mérite d'être marqué. Bienvenue, [Prénom].\nAvec honnêteté que c'est pas facile et décision de le faire quand même,\n— quelqu'un qui fait ce qui est pas facile pour lui parce que ça mérite d'être fait 💪` },
  { id: 'tm_crem_015', text: `"Bienvenue chez toi. Je pensais des trucs sur toi. Ta crémaillère m'a donné l'occasion de les dire."\nDonnée. Par ta crémaillère. Cette occasion. D'enfin exprimer les trucs pensés. Ces trucs qui attendaient. Le moment a trouvé sa forme. Bienvenue, [Prénom].\nAvec gratitude envers ta crémaillère pour avoir fourni l'occasion,\n— quelqu'un qui avait des trucs à dire et qui est content que l'occasion soit venue 🌸` },
  { id: 'tm_crem_016', text: `"T'as un chez-toi. Et quelque part j'en suis fier pour toi. Même si on est pas forcément proches de cette façon."\nMême si. Cette nuance. Qu'on exprime pas forcément les trucs. Et que quand même la fierté est là. Et que je voulais te le dire. Bienvenue, [Prénom].\nAvec fierté qui transcende les habitudes relationnelles habituelles,\n— quelqu'un dont la fierté pour toi existe même en dehors de ses habitudes d'expression 🌊` },
  { id: 'tm_crem_017', text: `"Bienvenue chez toi. Je suis quelqu'un qui dit peu. Mais là je voulais pas rater ça."\nRater ça. Ce moment. Cette occasion de marquer ton chez-toi. De te dire quelque chose. Je voulais pas rater. Bienvenue, [Prénom].\nAvec refus de rater ce moment comme motivation principale,\n— quelqu'un qui ne voulait pas rater ça et qui ne l'a pas raté 🎯` },
  { id: 'tm_crem_018', text: `"T'as un chez-toi. Je te le dis pas souvent mais tu comptes pour les gens autour de toi. Dont moi."\nDont moi. Ce ajout. Qui dit que je suis dans les gens pour qui tu comptes. Et je voulais que tu le saches. Pour ton chez-toi. Bienvenue, [Prénom].\nAvec ajout de soi-même dans les gens pour qui tu comptes,\n— quelqu'un qui voulait être explicitement inclus dans la liste des gens pour qui tu comptes 💛` },
  { id: 'tm_crem_019', text: `"Bienvenue chez toi. J'espère que ce message arrive jusqu'à toi comme ce qu'il est. Quelque chose de sincère de quelqu'un de peu expressif."\nQuelque chose de sincère. De quelqu'un de peu expressif. C'est sa définition. Ce message c'est ça. Et j'espère qu'il arrive jusqu'à toi tel quel. Bienvenue, [Prénom].\nAvec invitation à recevoir le message dans son authenticité de quelqu'un de peu expressif,\n— quelqu'un qui espère que l'authenticité passe malgré tout 💙` },
  { id: 'tm_crem_020', text: `"Bienvenue chez toi. Je dis pas souvent des trucs. Là j'en dis. C'est pour toi. Bienvenue, [Prénom]."\nPour toi. C'est le point central. Ce message. Cet effort. Ce dépassement de la timidité. C'est pour toi. Et pour ton chez-toi. Et parce que tu méritais que quelqu'un le dise. Bienvenue, [Prénom].\nAvec identification de toi comme raison principale de tout cet effort,\n— quelqu'un qui a fait tout ça pour toi et qui espère que tu le reçois bien ❤️` },
];

// ── Export ────────────────────────────────────────────────
export const TIMIDE_GROUPS: TimideGroup[] = [
  { id: 'birthday',    label: 'Anniversaire',    emoji: '🎂', cta: '🎂 Anniversaire',    messages: BIRTHDAY },
  { id: 'nameday',     label: 'Fête du prénom',  emoji: '🌸', cta: '🌸 Fête du prénom',  messages: NAMEDAY },
  { id: 'graduation',  label: 'Diplôme',         emoji: '🎓', cta: '🎓 Diplôme',         messages: GRADUATION },
  { id: 'departure',   label: 'Départ',          emoji: '✈️', cta: '✈️ Départ',          messages: DEPARTURE },
  { id: 'cremaillere', label: 'Crémaillère',     emoji: '🏠', cta: '🏠 Crémaillère',     messages: CREMAILLERE },
];
