// ═══════════════════════════════════════════════════════════════════
//  Confettis & Cake — Significations des prénoms
//  Généré automatiquement via Mistral AI (mistral-small-latest)
//  Format : "Prénom" → "signification courte"
// ═══════════════════════════════════════════════════════════════════

export const NAME_MEANINGS: Record<string, string> = {
  "Abel": "D'origine hébraïque, signifie 'souffle' ou 'vanité'. Symbole de douceur et de fragilité, souvent associé à la pureté dans la tradition biblique.",
  "Achille": "Du grec Akhilleus, signifiant 'celui qui a les lèvres d'un guerrier' ou 'douleur'. Héros légendaire de la guerre de Troie, symbole de force et de courage.",
  "Adeline": "D'origine germanique, dérivé de adal (noble) et lind (doux, tendre), ce prénom signifie noble douceur. Il évoque une personne à la fois distinguée et bienveillante.",
  "Adèle": "Issu du germanique adal (noble) et haid (forme, apparence), ce prénom signifie noble apparence. Il porte l'idée d'une élégance naturelle et d'une distinction innée.",
  "Adélaïde": "Formé du germanique adal (noble) et haid (forme), ce prénom signifie noble par la forme ou l'apparence. Il suggère une personne à la fois distinguée et harmonieuse.",
  "Agathe": "D'origine grecque, Agathé vient de agathos (bon, vertueux), signifiant la bonne ou la vertueuse. Ce prénom évoque une personne au cœur pur et à l'esprit bienveillant.",
  "Agnès": "Issu du grec hagnos (chaste, pur), ce prénom signifie la pureté ou la sainteté. Il évoque une personne innocente et intègre, souvent associée à la lumière spirituelle.",
  "Aimée": "Formé du latin amatus (aimé), ce prénom signifie celle qui est aimée. Il porte l'idée d'une personne chérie, entourée d'affection et de tendresse.",
  "Alain": "D'origine celtique, Alain vient de al (harmonie) et ano (doux), signifiant doux ou harmonieux. Ce prénom évoque une personne paisible et équilibrée.",
  "Albert": "Issu du germanique adal (noble) et berht (brillant), ce prénom signifie noble et brillant. Il suggère une personne à la fois distinguée et intelligente.",
  "Alexandre": "D'origine grecque, Alexandros vient de alexein (protéger) et anēr (homme), signifiant protecteur des hommes. Ce prénom évoque un leader courageux et généreux.",
  "Alexis": "Issu du grec alexein (protéger), ce prénom signifie le protecteur. Il porte l'idée d'une personne secourable et bienveillante envers autrui.",
  "Alix": "Variante d'Alice, d'origine germanique adal (noble) et haid (forme), ce prénom signifie noble par la forme. Il évoque une personne distinguée et élégante.",
  "Alphonse-Marie": "Composé de Alphonse (germanique adal (noble) et funs (prêt), signifiant prêt à servir) et Marie (hébreu Miryam, signifiant goutte de mer ou aimée de Dieu), ce prénom évoque un serviteur noble et pieux.",
  "Ambroise": "D'origine grecque ambrosios (immortel), ce prénom signifie celui qui est immortel ou divin. Il évoque une personne au destin exceptionnel ou à l'esprit intemporel.",
  "Amédée": "Formé du latin amatus (aimé) et Deus (Dieu), ce prénom signifie aimé de Dieu. Il porte l'idée d'une personne bénie et chérie par le divin.",
  "André": "Issu du grec anēr (homme, guerrier), ce prénom signifie viril ou courageux. Il évoque une personne forte, déterminée et protectrice.",
  "Angèle": "Du grec angelos (ἄγγελος), signifiant ange. Symbole de pureté et de protection, souvent associé à la douceur et à la bienveillance.",
  "Anne": "Le prénom Anne vient de l’hébreu Hannah, signifiant grâce ou faveur divine. En français, il évoque simplement la douceur et la bienveillance.",
  "Anselme": "D'origine germanique, Anselme vient de ans (dieu) et helm (casque, protection), signifiant littéralement \"protégé par Dieu\" ou \"celui qui a la protection divine\".",
  "Anthelme": "D'origine grecque, Anthelme vient de anthos (fleur) et helma (casque), signifiant littéralement celui qui porte la fleur comme un casque, ou plus poétiquement l'épanoui.",
  "Antoine": "Le prénom Antoine vient du latin Antonius, lui-même issu du grec Antōnios, d'origine incertaine mais peut-être étrusque. Il signifie littéralement celui qui est inestimable ou sans prix.",
  "Antoine-Marie": "Le prénom Antoine-Marie vient du latin Antonius, d'origine incertaine mais peut-être grecque (anthemon, fleur), et de Maria, d'origine hébraïque (Myriam, goutte de mer ou aimée de Dieu). Antoine signifie littéralement inestimable ou qui vaut le prix, et Marie signifie dame ou souveraine.",
  "Apolline": "Apolline vient du grec Apollon, dieu du soleil et des arts. Ce prénom signifie lumière, éclat ou beauté divine.",
  "Aristide": "Aristide vient du grec ancien Aristides, formé de aristos (le meilleur) et eidos (forme, apparence). Il signifie donc littéralement celui qui est le meilleur, l'excellent.",
  "Armand": "D'origine germanique, Armand vient de Herman (armée) et hard (dur, fort). Il signifie littéralement fort dans l'armée ou guerrier vaillant.",
  "Armel": "Originaire du breton, Armel vient de Arzhel ou Armel lui-même, formé de ar (devant, près de) et mael (prince). Il signifie donc littéralement prince noble ou chef illustre.",
  "Athanase": "Le prénom Athanase vient du grec ancien athanasios, formé de a- (privatif) et thanatos (la mort), ce qui signifie littéralement immortel.",
  "Auban": "D’origine germanique, Auban vient de Aubain, formé de ald (noble) et bald (audacieux). Il signifie littéralement noble et courageux.",
  "Aubin": "Le prénom Aubin vient du latin Albinus, dérivé de albus qui signifie blanc. Il évoque donc la pureté ou la blancheur.",
  "Aude": "D’origine germanique, Aude vient de ald (ancien haut allemand) signifiant noble ou ancienne. Ce prénom évoque aussi la richesse et la sagesse.",
  "Auguste": "Issu du latin augustus, dérivé de augere (augmenter), Auguste signifie littéralement celui qui est vénérable ou majestueux.",
  "Augustin": "D'origine latine, issu de Augustinus, dérivé d'Augustus signifiant 'venerable' ou 'sacré'. Il évoque la grandeur et la majesté, souvent associé à la sagesse et à la piété.",
  "Aurèle": "Issu du latin aureus, Aurèle signifie littéralement or ou doré, évoquant la richesse et la lumière. Ce prénom renvoie aussi à la noblesse et à la clarté.",
  "Barbe": "D’origine latine, Barbe vient de barba, qui signifie littéralement barbe. C’est un prénom ancien, souvent associé à la force ou à la sagesse dans les traditions populaires.",
  "Barnabé": "Le prénom Barnabé vient de l'hébreu Bar-Navé, signifiant fils de la consolation ou fils de l'encouragement. En français, il évoque simplement un caractère apaisant et bienveillant.",
  "Barthélemy": "Le prénom Barthélemy vient de l'hébreu Bar-Talmay, signifiant fils de Talmay. En français, il évoque simplement l'idée de fils fertile ou de terre fertile.",
  "Basile": "Originaire du grec ancien Basileios, ce prénom vient de basileus, qui signifie roi. Il évoque donc la royauté ou la noblesse.",
  "Benjamin": "Issu de l’hébreu Binyamin, Benjamin signifie littéralement fils de la droite ou fils du sud. En français, il évoque aussi l’idée de chance ou de bénédiction.",
  "Benoît": "Le prénom Benoît vient du latin Benedictus, issu du verbe benedicere (bénir). Il signifie littéralement celui qui est béni ou béni par Dieu.",
  "Benoît-Joseph": "Du latin Benedictus (béni) et Joseph (hébreu, Yosef, Dieu ajoute). Signifie 'béni par Dieu' ou 'ajouté à la bénédiction', évoquant la grâce divine et l'abondance.",
  "Bernadette": "D'origine germanique, Bernadette vient de Bernhard : bernhard signifie force (bern) et hardi (hard). En français, il évoque la force et la bravoure.",
  "Bernard": "D'origine germanique, Bernard vient de bernhard signifiant 'fort comme un ours'. Ce prénom évoque la force et la protection, souvent associé à la sagesse et à la générosité.",
  "Bernardin": "Forme diminutive de Bernard, ce prénom germanique signifie 'petit ours fort'. Il porte l'idée de douceur et de force tranquille, comme un protecteur discret.",
  "Bertille": "D'origine germanique, Bertille vient de berht (brillant) et hild (combat). Ce prénom évoque une personne à la fois lumineuse et courageuse, pleine de vitalité.",
  "Bertrand": "D'origine germanique, Bertrand signifie 'brillant corbeau'. Ce prénom associe l'intelligence (le corbeau) à la lumière, symbolisant une pensée claire et perçante.",
  "Bibiane": "D'origine latine, Bibiane dérive de Viviana, lié à vivus (vivant). Ce prénom évoque la vitalité, la joie de vivre et une énergie contagieuse.",
  "Bienvenue": "D'origine latine, Bienvenue signifie 'bien venu' ou 'accueilli avec joie'. Ce prénom rare porte un message de chaleur et d'hospitalité naturelle.",
  "Blaise": "D'origine latine, Blaise vient de blaesus (bègue) ou blasius (doux). Ce prénom évoque à la fois la douceur et une parole parfois hésitante mais toujours sincère.",
  "Blandine": "D'origine latine, Blandine vient de blandus (doux, caressant). Ce prénom évoque une personne au tempérament apaisant, douce et enjôleuse.",
  "Bonaventure": "D'origine latine, Bonaventure signifie 'bonheur à venir'. Ce prénom porte l'espoir d'une vie prospère et épanouie, comme un présage heureux.",
  "Boniface": "D'origine latine, Boniface signifie 'celui qui fait le bien'. Ce prénom reflète une nature généreuse, tournée vers l'aide et la justice.",
  "Boris": "D'origine slave, Boris vient de bor (combat) et slav (gloire). Ce prénom évoque un guerrier glorieux, à la fois fort et noble d'esprit.",
  "Brice": "D'origine celtique, Brice vient de brigos (force). Ce prénom court et percutant symbolise une énergie inépuisable et une détermination sans faille.",
  "Brigitte": "D'origine celtique, Brigitte vient de brigh (force, puissance). Ce prénom évoque une femme forte, protectrice et dotée d'un charisme naturel.",
  "Bruno": "D'origine germanique, Bruno vient de brun (brun, sombre). Ce prénom évoque une personne discrète mais profonde, au caractère stable et rassurant.",
  "Bénédicte": "D'origine latine, Bénédicte signifie 'bénie'. Ce prénom porte l'idée d'une personne chérie, protégée par la chance et la bienveillance divine.",
  "Bérenger": "D'origine germanique, Bérenger vient de ber (ours) et ger (lance). Ce prénom évoque un protecteur courageux, à la fois doux et redoutable.",
  "Calixte": "D'origine grecque, Calixte vient de kalos (beau) et xenos (étranger). Ce prénom évoque une personne au charme naturel, accueillante et harmonieuse.",
  "Camille": "D'origine latine, Camille vient de camillus (jeune serviteur des dieux). Ce prénom évoque une jeunesse éternelle, une grâce et une élégance naturelle.",
  "Casimir": "D'origine slave, Casimir vient de kaziti (proclamer) et mir (paix). Ce prénom porte l'idée d'un messager de paix, clair et persuasif.",
  "Catherine": "D'origine grecque, Catherine vient de katharos (pur). Ce prénom évoque une personne intègre, lumineuse et dotée d'une force morale inébranlable.",
  "Charles": "D'origine germanique, Charles vient de karl (homme libre). Ce prénom évoque un leader naturel, généreux et doté d'un charisme rassurant.",
  "Charlotte": "D'origine germanique, Charlotte est la forme féminine de Charles, signifiant 'petite femme libre'. Ce prénom évoque une personne indépendante, douce et pleine de vitalité.",
  "Christine": "D'origine grecque, Christine vient de christos (oint, messie). Ce prénom évoque une personne pieuse, sincère et guidée par une foi profonde.",
  "Christophe": "D'origine grecque, Christophe vient de christos (messie) et phoros (porteur). Ce prénom évoque un guide spirituel, protecteur et porteur d'espoir.",
  "Chély": "D'origine celtique, Chély est une variante de Caelestinus (céleste). Ce prénom évoque une personne lumineuse, rêveuse et en harmonie avec le ciel.",
  "Claire": "D'origine latine, Claire vient de clarus (lumière, clair). Ce prénom évoque une personne transparente, intelligente et rayonnante de vérité.",
  "Claude": "D'origine latine, Claude vient de claudus (boiteux) ou claudere (fermer). Ce prénom évoque une personne discrète, réfléchie et parfois mystérieuse.",
  "Clotilde": "D'origine germanique, Clotilde vient de hlod (gloire) et hild (combat). Ce prénom évoque une femme à la fois glorieuse et combative, pleine de noblesse.",
  "Clémence": "D'origine latine, Clémence vient de clemens (clément, miséricordieux). Ce prénom évoque une personne douce, pardonnante et dotée d'une grande bonté.",
  "Clément": "D'origine latine, Clément vient de clemens (doux, clément). Ce prénom évoque une personne calme, apaisante et naturellement bienveillante envers autrui.",
  "Colette": "D'origine germanique, Colette est une forme diminutive de Nicole, venue de nikê (victoire). Ce prénom évoque une personne victorieuse, joyeuse et pleine d'entrain.",
  "Constant": "D'origine latine, Constant vient de constans (ferme, stable). Ce prénom évoque une personne inébranlable, fiable et toujours égale à elle-même.",
  "Constantin": "D'origine latine, Constantin vient de constans (ferme) et tinus (digne de). Ce prénom évoque un esprit solide, digne et résolument tourné vers l'action.",
  "Corentin": "D'origine celtique, Corentin vient de korentin (rond, courbé). Ce prénom évoque une personne ronde et chaleureuse, au tempérament paisible et accueillant.",
  "Corneille": "D'origine latine, Corneille vient de cornix (corbeau). Ce prénom évoque un esprit vif, observateur et parfois mystérieux, comme l'animal qui le symbolise.",
  "Crépin": "D'origine latine, Crépin vient de crispus (crépu). Ce prénom évoque une personne au caractère bien trempé, parfois rebelle mais toujours authentique.",
  "Crépinien": "D'origine latine, Crépinien est une forme augmentative de Crépin, signifiant 'très crépu'. Ce prénom évoque une personnalité forte, indomptable et pleine de caractère.",
  "Cyprien": "D'origine grecque, Cyprien vient de kupris (ivre, inspiré par la déesse Aphrodite). Ce prénom évoque une personne passionnée, sensuelle et dotée d'un charme envoûtant.",
  "Cyrille": "Du grec Kyrillos, dérivé de kyrios (seigneur). Signifie « celui qui appartient au Seigneur » ou « petit seigneur ».",
  "Cécile": "Du latin Caecilius, lié à caecus (aveugle). Porte le sens de « la bienveillante » ou « celle qui voit clair dans les cœurs ».",
  "Célestin": "Du latin caelestinus, de caelum (ciel). Évoque « celui qui vient du ciel » ou « l’homme céleste ».",
  "Céline": "Du latin caelum (ciel). Signifie « céleste » ou « celle qui est élevée, pure comme le ciel ».",
  "Césaire": "Du latin Caesar, lui-même issu de caesaries (chevelure). Porte le sens de « chevelu » ou « celui qui a une chevelure majestueuse ».",
  "Côme": "Du grec Kosmas, de kosmos (monde, ordre). Signifie « l’orné » ou « celui qui embellit le monde ».",
  "Damase": "Du latin Damasius, dérivé de damnum (dommage). Évoque « celui qui apaise » ou « le réparateur de torts ».",
  "Damien": "Du grec Damianos, de damazô (dompter). Porte le sens de « celui qui dompte » ou « le vainqueur des passions ».",
  "Daniel": "De l’hébreu Daniyyel (Dieu est mon juge). Signifie « Dieu a jugé » ou « justice divine ».",
  "David": "De l’hébreu Dawid (bien-aimé). Évoque « l’élu » ou « celui qui plaît à Dieu ».",
  "Demetrius": "Du grec Dēmētrios, lié à Dēmētēr (déesse Déméter). Porte le sens de « consacré à Déméter » ou « celui qui nourrit la terre ».",
  "Denis": "Du latin Dionysius, grec Dionysios (dieu Dionysos). Signifie « consacré à Dionysos » ou « l’adorateur de Dionysos ».",
  "Denise": "Féminin de Denis, du latin Dionysius. Évoque « celle qui est consacrée à Dionysos » ou « la divine ».",
  "Didier": "Du latin Desiderius, de desiderare (désirer). Porte le sens de « celui qui est désiré » ou « l’objet de désir ».",
  "Dominique": "Du latin Dominicus, de dominus (seigneur). Signifie « consacré au Seigneur » ou « celui qui appartient à Dieu ».",
  "Donatien": "Du latin Donatianus, de donare (donner). Évoque « celui qui est donné » ou « le don de Dieu ».",
  "Désiré": "Du latin Desideratus, participe de desiderare (désirer). Porte le sens de « celui qui est désiré » ou « l’aimé ».",
  "Dévote": "Du latin devotus (consacré, dévoué). Signifie « celle qui se consacre à Dieu » ou « la pieuse ».",
  "Edith": "De l’anglo-saxon Eadgyth, de ead (richesse) et gyth (combat). Évoque « la guerrière riche » ou « celle qui combat pour la prospérité ».",
  "Edmond": "De l’anglo-saxon Eadmund, de ead (richesse) et mund (protection). Porte le sens de « protecteur des richesses » ou « le gardien de la fortune ».",
  "Edouard": "De l’anglo-saxon Eadweard, de ead (richesse) et weard (gardien). Signifie « gardien des richesses » ou « le protecteur des biens ».",
  "Elisabeth": "De l’hébreu Elisheva (Dieu est ma promesse). Évoque « Dieu est ma plénitude » ou « celle qui se consacre à Dieu ».",
  "Elisée": "De l’hébreu Elisha (Dieu est mon salut). Porte le sens de « sauvé par Dieu » ou « le protégé divin ».",
  "Elodie": "Du grec Elodia, peut-être de hēlios (soleil) et ōdē (chant). Signifie « celle qui chante le soleil » ou « la mélodieuse ».",
  "Eloi": "Du latin Eligius, lui-même du germanique ald (ancien) et wig (combat). Évoque « le vieux guerrier » ou « le sage combattant ».",
  "Emeline": "Du germanique Amal (travail) et lin (laine). Porte le sens de « celle qui travaille la laine » ou « l’ouvrière diligente ».",
  "Emmanuel": "De l’hébreu Immanuel (Dieu est avec nous). Signifie « Dieu parmi nous » ou « la présence divine ».",
  "Ephrem": "De l’hébreu Ephraim (fructueux). Évoque « celui qui porte du fruit » ou « le fertile ».",
  "Eric": "Du vieux norrois Eiríkr, de ei (toujours) et ríkr (puissant). Porte le sens de « toujours puissant » ou « le chef invincible ».",
  "Estelle": "Du latin stella (étoile). Signifie « celle qui brille comme une étoile » ou « la lumineuse ».",
  "Etheldrede": "De l’anglo-saxon Æthelthryth, de æthel (noble) et thryth (force). Évoque « la noble force » ou « la puissante noble ».",
  "Etienne": "Du grec Stephanos (couronne). Porte le sens de « celui qui est couronné » ou « le victorieux ».",
  "Eugénie": "Du grec Eugenia, de eu (bien) et gennaô (engendrer). Signifie « bien née » ou « de bonne race ».",
  "Eulalie": "Du grec Eulalia, de eu (bien) et lalein (parler). Évoque « celle qui parle bien » ou « l’éloquente ».",
  "Fabien": "Du latin Fabianus, de faba (fève). Porte le sens de « celui qui cultive les fèves » ou « l’agriculteur ».",
  "Faustine": "Du latin Faustinus, de faustus (heureux). Signifie « celle qui apporte le bonheur » ou « la chanceuse ».",
  "Ferdinand": "Du germanique fridu (paix) et nand (audacieux). Évoque « l’audacieux pacificateur » ou « le guerrier de la paix ».",
  "Fiacre": "Du latin Fiacrius, peut-être d’origine gauloise. Porte le sens de « le solide » ou « le robuste ».",
  "Fidèle": "Du latin fidelis (fidèle). Signifie « celui qui est digne de confiance » ou « le loyal ».",
  "Firmin": "Du latin Firminus, de firmus (ferme, solide). Évoque « le solide » ou « celui qui ne cède pas ».",
  "Flora": "Du latin flos (fleur), ce prénom évoque la nature et la beauté éphémère des fleurs. Il célèbre aussi la déesse romaine des fleurs et du printemps.",
  "Florence": "D'origine latine, Florence vient de florens (florissant). Ce prénom évoque une personne rayonnante, épanouie et pleine de vitalité comme un jardin en fleurs.",
  "Florentin": "D'origine latine, Florentin vient de florens (florissant). Ce prénom évoque une personne joyeuse, en pleine croissance et toujours en harmonie avec la nature.",
  "François": "D'origine latine, Franciscus, signifie 'libre' ou 'homme franc'. Il évoque aussi l'appartenance à la nation franque, symbole de franchise et de loyauté.",
  "François-Xavier": "François vient du latin Franciscus, lié à Francus (franc, libre), et Xavier vient du basque etxe berri (maison neuve). Ensemble, cela signifie libre et maison neuve.",
  "Françoise": "Originaire du latin Franciscus, dérivé de Francus (Franc, peuple germanique), Françoise signifie littéralement femme ou épouse d'un Franc.",
  "Françoise-Xavière": "Le prénom Françoise-Xavière vient du latin Franciscus (libre, franc) et du basque etxe berri (maison neuve) pour Françoise, et du basque etxe berri (maison neuve) associé à Xavier, du basque etxe berri (maison neuve) et etxe berri (maison neuve). Il signifie littéralement libre maison neuve et maison neuve éclatante.",
  "Frédéric": "Le prénom Frédéric vient du germanique Friduric, formé de fridu (paix) et ric (puissant). Il signifie donc littéralement puissant par la paix.",
  "Fulbert": "Fulbert vient du latin Fulbertus, formé de fulgidus (brillant, éclatant) et berht (brillant, illustre). Il signifie donc celui qui est brillant ou illustre.",
  "Félicité": "Le prénom Félicité vient du latin felicitas, lui-même issu de felix, signifiant heureux ou fertile. Il évoque donc la joie, la chance ou la prospérité.",
  "Félix": "Félix vient du latin felix, lui-même issu du grec phelikós, signifiant littéralement heureux ou prospère.",
  "Gabin": "D'origine latine, Gabin vient de Gabinius, un nom de famille romain dérivé de Gabii, une ancienne ville du Latium. Il signifie littéralement celui qui vient de Gabii.",
  "Gabriel": "Gabriel vient de l'hébreu \"Gavri'el\", formé de \"gavri\" (force) et \"El\" (Dieu), ce qui signifie littéralement force de Dieu.",
  "Gaston": "D’origine germanique, Gaston vient de Gast (hôte) et wini (ami), signifiant littéralement l’ami de l’hôte ou l’hôte généreux.",
  "Gatien": "Le prénom Gatien vient du latin Gatianus, dérivé de Catius, un nom d'origine ombrienne (Italie antique). Il signifie littéralement celui qui vient de Catia ou qui en est issu.",
  "Gautier": "Le prénom Gautier vient du germanique waldan (commander) et hari (armée), signifiant littéralement chef de guerre. Il évoque donc la force et le leadership.",
  "Gaétan": "Le prénom Gaétan vient du latin Gaetanus, lui-même dérivé de Caieta, nom d’une ville côtière italienne. Il signifie littéralement habitant de Gaète.",
  "Geneviève": "Le prénom Geneviève vient du germanique Ganewara, composé de gana (race, famille) et weida (voisine, amie), signifiant littéralement compagne de la même famille ou amie du peuple.",
  "Geoffroy": "Issu du germanique Gaufrid, composé de gawi (région, terre) et fridu (paix), Geoffroy signifie littéralement celui qui assure la paix dans son domaine.",
  "Georges": "Le prénom Georges vient du grec Geôrgios, dérivé de geôrgos (γεωργός), signifiant littéralement celui qui travaille la terre, paysan. Il évoque aussi la force et la protection, liée à saint Georges, martyr chrétien.",
  "Germain": "Issu du latin Germanus, ce prénom vient du grec Germanos, signifiant littéralement frère ou vrai frère. Il évoque aussi l'idée d'authenticité ou de parenté proche.",
  "Germaine": "Originaire du latin germen, signifiant germe ou pousse, Germaine évoque la vitalité et la renaissance. Ce prénom féminin célèbre aussi la force et la pureté, souvent associé à la terre fertile.",
  "Gilbert": "D’origine germanique, Gilbert vient de gisel (flèche) et berth (brillant). Il signifie donc celui qui brille comme une flèche.",
  "Gildas": "Le prénom Gildas vient du breton Gweltaz, lui-même issu du vieux breton guil (sacrifice) et tas (fer). Il signifie littéralement celui qui sacrifie ou le guerrier généreux.",
  "Gilles": "Le prénom Gilles vient du grec Aigídios, lui-même issu de aigís (ἀιγίς), la peau de chèvre, attribut de Zeus. Il signifie donc littéralement celui qui porte une peau de chèvre.",
  "Gisèle": "D'origine germanique, issu de gisil (flèche) et hild (combat), ce prénom évoque la force et la précision. Il symbolise aussi la victoire par l'arc, comme dans les sagas nordiques.",
  "Gladys": "D’origine galloise, Gladys vient du vieux gallois Gladus, lui-même dérivé du latin gladios (glaive). Il signifie littéralement brave ou joyeuse.",
  "Gontran": "D'origine germanique, Gontran vient de Gundhram, composé de gund (combat) et hramn (corbeau). Il signifie littéralement celui qui combat avec la sagesse du corbeau.",
  "Grégoire": "Issu du grec ancien Gregórios (Γρηγόριος), dérivé de grēgorein signifiant veiller, être éveillé. Il évoque donc l'idée de vigilance ou de celui qui veille.",
  "Guillaume": "Originaire du germanique Willahelm, composé de wil (volonté) et helm (casque, protection), Guillaume signifie littéralement volonté protectrice.",
  "Guy": "D’origine germanique, Guy vient de Wido, lié à wid (bois) ou witu (forêt). Il signifie littéralement homme de la forêt ou guide.",
  "Guénolé": "D’origine bretonne, Guénolé vient du vieux breton Gwenole, lui-même issu de gwenn (blanc, béni) et haol (ardent, généreux). Il signifie donc littéralement celui qui est pur et ardent.",
  "Gérald": "D'origine germanique, Gérald vient de ger (lance) et wald (règne), signifiant littéralement celui qui commande avec la lance ou le guerrier puissant.",
  "Gérard": "Issu du germanique Gairhard, composé de gair (lance) et hard (fort), Gérard signifie littéralement fort comme une lance.",
  "Géraud": "D'origine germanique, Géraud vient de ger (lance) et wald (gouverneur), signifiant littéralement guide ou chef avec la lance.",
  "Hedwige": "D'origine germanique, Hedwige vient de hadu (combat) et wig (guerre), signifiant littéralement combat ou lutte.",
  "Henri": "Le prénom Henri vient du germanique Haimirich, formé de haim (maison, foyer) et ric (puissant, roi). Il signifie donc littéralement \"maître de la maison\" ou \"souverain du foyer\".",
  "Herbert": "D'origine germanique, Herbert vient de heri (armée) et berht (brillant, illustre), signifiant littéralement celui qui brille par son armée ou son prestige guerrier.",
  "Hervé": "Hervé vient du breton Haerviu, formé de haer (dur, fort) et viu (homme), signifiant littéralement homme fort ou guerrier.",
  "Hilaire": "Hilaire vient du latin hilaris, lui-même issu du grec hilaros, signifiant joyeux ou gai. Ce prénom évoque donc la bonne humeur et la sérénité.",
  "Hildegarde": "D'origine germanique, de hild (combat) et gard (protection), ce prénom signifie \"celle qui protège par la force\". Il évoque une guerrière ou une gardienne au cœur vaillant.",
  "Hippolyte": "Issu du grec ancien, Hippolyte vient de Hippolytos, formé de hippos (cheval) et lytos (délivré). Il signifie littéralement celui qui est libéré par les chevaux.",
  "Honorat": "D'origine latine, Honorat vient de honoratus, signifiant celui qui est honoré ou digne d'honneur. Ce prénom évoque aussi la noblesse et le respect.",
  "Honorine": "Honorine vient du latin honor, qui signifie honneur. Ce prénom évoque donc la dignité, la considération et la noblesse morale.",
  "Honoré": "Du latin honoratus, signifiant 'honoré', 'digne de respect'. Porte l'idée de noblesse morale et de reconnaissance sociale.",
  "Hubert": "Issu du germanique Hugibert, composé de hug (esprit, intelligence) et berht (brillant, illustre), Hubert signifie littéralement celui qui brille par son esprit.",
  "Hugues": "D'origine germanique, Hugues vient de hugu (esprit, intelligence) et hild (combat), signifiant littéralement esprit combatif.",
  "Héloïse": "D’origine germanique, Héloïse vient de Hludwig (composé de hlud, gloire, et wig, combat), signifiant littéralement celle qui est illustre au combat.",
  "Hélène": "D'origine grecque, Hélène vient d'Helene, lié à \"hêlios\" (soleil) ou \"helane\" (rayon lumineux). Il signifie littéralement la lumineuse ou la brillante.",
  "Ida": "D'origine germanique, Ida vient de id signifiant travail ou labeur. Il évoque aussi la fertilité ou la force, comme dans la légende de sainte Ida.",
  "Ignace": "Issu du latin Ignatius, lui-même dérivé du grec ignis (feu), Ignace signifie littéralement celui qui est ardent ou enflammé, évoquant une nature passionnée ou inspirée.",
  "Ildefonse": "D’origine germanique, Ildefonse vient de hild (combat) et funs (prêt, disposé), signifiant littéralement celui qui est prêt au combat. En français, il évoque aussi la force et la détermination.",
  "Ingrid": "D’origine scandinave (vieux norrois), Ingrid signifie littéralement \"celle qui est belle\" ou \"belle comme la déesse Freyja\". Son sens évoque aussi la paix et la force.",
  "Innocent": "Le prénom Innocent vient du latin innocens, formé de in- (négation) et nocens (nuisible), signifiant littéralement celui qui ne fait pas de mal, pur ou sans culpabilité.",
  "Inès": "Inès vient de l'arabe Ayn al-Hasud, signifiant œil de la douceur, mais aussi du latin Innocentia ou du grec hagnè (pure). Il évoque la pureté, l'innocence ou la douceur.",
  "Irène": "Issu du grec ancien Eirēnē, ce prénom signifie paix. Il évoque l'harmonie et la sérénité.",
  "Irénée": "Le prénom Irénée vient du grec ancien Eirēnaios, dérivé de eirēnē (εἰρήνη), qui signifie paix. Il évoque donc la paix et la sérénité.",
  "Isaac": "Origine hébraïque, issu de 'Yitzchaq' signifiant 'il rira'. Symbole de joie et de bénédiction divine dans la tradition biblique.",
  "Isabelle": "Dérivé de l'hébreu 'Elisheba', 'Dieu est ma promesse'. Porté par la reine Isabelle de France, il évoque la noblesse et la fidélité.",
  "Isidore": "Du grec 'Isídoros', composé de 'ísis' (déesse) et 'dôron' (don). Signifie 'don d'Isis', souvent associé à la sagesse et à la protection.",
  "Jacques": "Forme française de 'Jacob', d'origine hébraïque 'Ya'aqov', 'il talonne' ou 'Dieu protège'. Lié à l'apôtre Jacques, symbole de foi et de voyage.",
  "Janvier": "Issu du latin 'Januarius', dérivé de 'Janus', dieu romain des portes et des commencements. Évoque le renouveau et les transitions.",
  "Jean": "D'origine hébraïque 'Yohanan', 'Dieu a fait grâce'. Prénom universel, porté par de nombreux saints, symbole de pureté et de spiritualité.",
  "Jean-Baptiste": "Composé de 'Jean' et 'Baptiste', du grec 'baptistēs', 'celui qui baptise'. Désigne le prophète ayant préparé la venue du Christ.",
  "Jean-Bosco": "Formé de 'Jean' et 'Bosco', du latin 'bos' (bœuf), surnom de saint Jean Bosco, fondateur d'oratoires pour les jeunes défavorisés.",
  "Jean-Damascène": "Associe 'Jean' à 'Damascène', de Damas, ville antique. Saint Jean de Damas, théologien byzantin, symbole de savoir et de foi.",
  "Jean-Eudes": "Composé de 'Jean' et 'Eudes', du germanique 'aud' (richesse) et 'hard' (dur). Saint Jean Eudes, promoteur de la dévotion au Sacré-Cœur.",
  "Jean-François": "Formé de 'Jean' et 'François', du latin 'Franciscus', 'libre' ou 'homme franc'. Porté par saint François d'Assise, symbole de simplicité et de charité.",
  "Jean-Marie": "Associe 'Jean' et 'Marie', figures centrales du christianisme. Symbole d'union entre la force divine et la pureté maternelle.",
  "Jeanne": "Féminin de 'Jean', d'origine hébraïque 'Yohanan', 'Dieu a fait grâce'. Porté par Jeanne d'Arc, symbole de courage et de foi inébranlable.",
  "Jeanne-Françoise": "Composé de 'Jeanne' et 'Françoise', du latin 'Franciscus', 'libre'. Évoque la force et la générosité, comme sainte Jeanne de Chantal.",
  "Joachim": "D'origine hébraïque 'Yehoyaqim', 'Dieu établi'. Père de la Vierge Marie dans la tradition chrétienne, symbole de patience et de bénédiction.",
  "Josaphat": "D'origine hébraïque (יְהוֹשָׁפָט, Yehoshaphat), ce prénom signifie 'Yahvé a jugé'. Il évoque la justice divine et la protection de Dieu.",
  "Joseph": "Le prénom Joseph vient de l'hébreu Yosef, dérivé de la racine \"yasaf\" qui signifie ajouter ou augmenter. Il signifie donc celui qui ajoute ou qui fait prospérer.",
  "Joséphine": "Le prénom Joséphine vient de l'hébreu Yosef, signifiant à l'origine \"Il ajoutera\" ou \"Dieu multipliera\". En français, il évoque la grâce et la beauté, souvent associé à l'élégance.",
  "Jude": "Le prénom Jude vient de l'hébreu Yehudah, signifiant littéralement \"loué\" ou \"celui qui est loué\". Il évoque aussi la gratitude et la reconnaissance.",
  "Judicaël": "D'origine bretonne, Judicaël vient du vieux breton Judhael, formé de iud (seigneur) et hael (généreux). Il signifie littéralement seigneur généreux.",
  "Judith": "Judith vient de l'hébreu Yehudit, signifiant à l'origine femme de Judée. En français, il évoque aussi la femme vertueuse ou la louange.",
  "Jules": "Issu du latin Iulius, ce prénom vient peut-être du grec ioulos (jeune barbe) ou d’un nom romain lié à Jupiter. Il signifie littéralement jeune homme ou descendant de Jules.",
  "Julie": "Le prénom Julie vient du latin Julius, lui-même issu du grec ioulos (jeune, imberbe) ou peut-être de Iupiter (Jupiter). Il signifie littéralement jeune ou celui qui est consacré à Jupiter.",
  "Julienne": "Du latin Julianus, dérivé de Julius (famille romaine Julia), signifiant \"appartenant à Jupiter\" ou \"descendant de Jupiter\". Ce prénom évoque la force et la noblesse, souvent associé à la lumière et à la clarté.",
  "Juliette": "Variante féminine de Julien, issu du latin Julius, lié à Jupiter. Il porte l'idée de jeunesse, de grâce et de charme, avec une touche romantique et poétique.",
  "Justin": "Du latin Justinus, diminutif de Justus (\"juste\", \"équitable\"). Ce prénom incarne l'intégrité, la droiture et l'honnêteté, valeurs chères aux premiers chrétiens.",
  "Justine": "Féminin de Justin, du latin Justina, signifiant \"celle qui est juste\". Il évoque la pureté morale, la sincérité et une nature équilibrée.",
  "Jérémie": "De l'hébreu Yirmeyahu, signifiant \"Dieu élèvera\" ou \"Dieu établira\". Ce prénom porte une dimension prophétique et une force spirituelle, liée à l'espoir et à la résilience.",
  "Jérôme": "Du grec Hieronymos, composé de hieros (\"sacré\") et onoma (\"nom\"). Il signifie \"nom sacré\" et évoque la dévotion, la sagesse et le lien avec le divin.",
  "Karine": "D'origine grecque Karinē, féminin de Karios (\"pur\", \"chaste\"). Ce prénom suggère la pureté, la douceur et une élégance naturelle.",
  "Kateri": "Variante amérindienne (mohawk) de Catherine, signifiant \"celle qui est pure\". Il porte une dimension spirituelle et une résilience historique, liée à la nature et à la foi.",
  "Kevin": "D'origine irlandaise Caoimhín, dérivé de caomh (\"doux\", \"gentil\"). Ce prénom évoque la bienveillance, la gentillesse et une nature paisible.",
  "Landry": "Du germanique Landric, formé de land (\"terre\") et ric (\"puissant\"). Il signifie \"seigneur de la terre\" et porte une image de force, de stabilité et de leadership.",
  "Larissa": "Du grec Larissa, lié à laros (\"doux\", \"agréable\"). Ce prénom évoque la grâce, la douceur et une beauté sereine, inspiré par la mythologie grecque.",
  "Laurent": "Du latin Laurentius, dérivé de Laurus (\"laurier\"). Il symbolise la victoire, la gloire et la pureté, souvent associé à la couronne de laurier des héros.",
  "Lazare": "De l'hébreu El'azar, signifiant \"Dieu a aidé\". Ce prénom porte une dimension de résurrection et d'espoir, lié à la foi en un miracle divin.",
  "Louis": "D'origine germanique Hludwig, composé de hlud (\"célèbre\") et wig (\"combat\"). Il signifie \"guerrier glorieux\" et évoque la force, le pouvoir et la noblesse.",
  "Louise": "Féminin de Louis, du germanique Hludwig. Ce prénom incarne l'élégance, la détermination et une grâce naturelle, avec une touche classique et intemporelle.",
  "Luc": "Du latin Lucas, issu du grec Loukas, signifiant \"lumière\" ou \"celui qui apporte la lumière\". Il évoque la clarté, la connaissance et une nature rayonnante.",
  "Lucie": "Féminin de Luc, du latin Lucia, signifiant \"lumière\". Ce prénom porte une dimension de pureté, de joie et de luminosité, souvent associé à la fête des Lumières.",
  "Lucien": "Du latin Lucianus, dérivé de Lucas (\"lumière\"). Il évoque l'intelligence, la vivacité d'esprit et une nature éclairée, avec une touche antique et raffinée.",
  "Léa": "De l'hébreu Le'ah, signifiant \"fatiguée\" ou \"douce\". Ce prénom porte une douceur naturelle, une simplicité et une beauté discrète, liée à la patience et à la résilience.",
  "Léocadie": "Du grec Leokadia, composé de leos (\"peuple\") et kados (\"pur\"). Il signifie \"pureté du peuple\" et évoque la noblesse, la sincérité et une nature généreuse.",
  "Léon": "Du latin Leo, signifiant \"lion\". Ce prénom incarne la force, le courage et une présence majestueuse, avec une touche royale et protectrice.",
  "Léonard": "Du germanique Leonhard, formé de lewo (\"lion\") et hard (\"fort\"). Il signifie \"fort comme un lion\" et évoque la puissance, la loyauté et une nature protectrice.",
  "Léonce": "Du latin Leontius, dérivé de leo (\"lion\"). Il porte l'image d'un caractère noble, courageux et majestueux, comme un souverain.",
  "Macrine": "Du grec Makrina, féminin de makros (\"grand\", \"illustre\"). Ce prénom évoque la grandeur d'âme, la sagesse et une nature généreuse et bienveillante.",
  "Madeleine-Sophie": "De l'hébreu Magdal-eder (\"tour de David\") pour Madeleine et du grec Sophia (\"sagesse\"). Ce prénom unit la force symbolique et la profondeur intellectuelle, avec une touche mystique.",
  "Marc": "Du latin Marcus, lié à Mars (dieu de la guerre). Il évoque la force, la détermination et une nature dynamique, avec une simplicité antique.",
  "Marcel": "Du latin Marcellus, diminutif de Marcus. Ce prénom porte une image de jeunesse, de vivacité et une touche de noblesse discrète et charmante.",
  "Marcella": "Féminin de Marcellus, du latin Marcus. Il évoque la grâce, l'élégance et une nature à la fois forte et délicate, avec une touche romaine.",
  "Marguerite": "Du grec Margaritēs, signifiant \"perle\". Ce prénom incarne la pureté, la beauté rare et une douceur lumineuse, souvent associé à la fragilité et à la résilience.",
  "Marguerite-Marie": "Combinaison de Marguerite (\"perle\") et Marie (\"celle qui élève\"). Ce prénom unit la pureté, la grâce et une dimension spirituelle profonde et lumineuse.",
  "Maria": "Variante de Marie, de l'hébreu Miriam, signifiant \"celle qui élève\" ou \"goutte de mer\". Il évoque la douceur, la maternité et une présence apaisante et protectrice.",
  "Marie": "De l'hébreu Miriam, signifiant \"celle qui élève\" ou \"goutte de mer\". Ce prénom porte une dimension sacrée, maternelle et universelle, symbole de pureté et de grâce.",
  "Marie-Emilie": "Marie vient de l'hébreu Miryam, signifiant probablement \"celle qui élève\" ou \"goutte de mer\". Emilie, d'origine latine, signifie \"rival\" ou \"émule\". Ensemble, ce prénom évoque une personne à la fois forte et inspirante.",
  "Marie-Hermine": "Associe Marie (\"celle qui élève\") et Hermine (du germanique Hirmin, \"armée\"). Ce prénom évoque la protection divine et une nature à la fois douce et combative.",
  "Marie-Madeleine": "Combinaison de Marie (\"celle qui élève\") et Madeleine (de l'hébreu Magdal-eder, \"tour de David\"). Ce prénom unit la rédemption, la foi et une dimension mystique et profonde.",
  "Marthe": "Du grec Martha, de l'araméen Mārtā, signifiant \"dame\" ou \"maîtresse de maison\". Il évoque la simplicité, la générosité et une nature pratique et chaleureuse.",
  "Martial": "Du latin Martialis, lié à Mars (dieu de la guerre). Ce prénom porte une image de force, de courage et une nature combative et déterminée.",
  "Martin": "Du latin Martinus, dérivé de Mars (dieu de la guerre). Il signifie \"consacré à Mars\" et évoque la bravoure, la loyauté et une nature protectrice.",
  "Martine": "Féminin de Martin, du latin Martinus. Ce prénom incarne la force discrète, la générosité et une élégance naturelle, avec une touche antique.",
  "Martinien": "Du latin Martinianus, dérivé de Martinus. Il évoque la persévérance, la loyauté et une nature à la fois forte et bienveillante, avec une touche historique.",
  "Mathilde": "D'origine germanique (maht = force, hild = combat), ce prénom signifie \"puissante au combat\". Il évoque une personne déterminée et combative.",
  "Matthias": "Le prénom Matthias vient de l'hébreu Mattityahu, signifiant littéralement don de Dieu. En grec, Matthaios, il a gardé cette idée de grâce divine.",
  "Matthieu": "Matthieu vient de l'hébreu Mattityahu, signifiant don de Dieu ou cadeau de Yahvé. En français, il évoque simplement un présent divin.",
  "Maurice": "D'origine latine, Maurice vient de Mauricius, dérivé de Maurus signifiant à l'origine maure ou habitant de Maurétanie. Il évoque ainsi l'idée d'une personne au teint sombre ou d'origine méditerranéenne.",
  "Maxime": "Du latin maximus, superlatif de magnus (grand), ce prénom signifie \"le plus grand\". Il évoque aussi une personne ambitieuse ou d'une intelligence remarquable.",
  "Maximilien": "Maximilien vient du latin Maximus, superlatif de magnus (grand), lui-même issu du grec megas. Ce prénom signifie donc grand ou très grand.",
  "Michel": "Issu de l’hébreu Mikha’el (מִיכָאֵל), Michel signifie littéralement Qui est comme Dieu ?. C’est un prénom biblique porté par l’archange Michel.",
  "Modeste": "Issu du latin modestus, ce prénom signifie littéralement sobre, mesuré ou humble. Il évoque une personne discrète et respectueuse.",
  "Monique": "Du latin monicus, dérivé de monachus (moine), signifiant à l'origine 'celle qui vit en recluse'. Le prénom évoque aussi la solitude ou la piété, souvent associé à sainte Monique, mère de saint Augustin.",
  "Médard": "D'origine germanique, Médard vient de maht (puissance) et hard (dur, fort), signifiant littéralement fort et puissant.",
  "Méthode": "Le prénom Méthode vient du grec Methodios, formé de méthodos, signifiant littéralement voie vers ou recherche méthodique. Il évoque l'idée d'organisation et de rigueur.",
  "Narcisse": "Le prénom Narcisse vient du grec Narkissos, lui-même issu du mot narkê, qui signifie engourdissement. Littéralement, il évoque la torpeur ou l'engourdissement, en référence à la plante du même nom.",
  "Nathalie": "Le prénom Nathalie vient du latin Nathalia, lui-même issu du grec Nathanaēl (Ναθαναήλ), qui signifie littéralement don de Dieu.",
  "Nestor": "Le prénom Nestor vient du grec ancien Néstōr, lié au nom propre Nestor dans l’Iliade, signifiant littéralement celui qui est sage ou qui conseille avec sagesse.",
  "Nicolas": "Le prénom Nicolas vient du grec ancien Nikolaos, formé de nikê (victoire) et laos (peuple). Il signifie donc littéralement victoire du peuple.",
  "Nino": "D’origine italienne, dérivé du latin Ninus ou du grec Ninos, Nino signifie littéralement petit enfant ou jeune garçon. C’est aussi un diminutif affectueux de noms comme Giovanni ou Antonino.",
  "Norbert": "D'origine germanique, Norbert vient de nord (nord) et berth (brillant). Il signifie donc celui qui est brillant au nord.",
  "Noël": "Le prénom Noël vient du latin natalis (naissance), lié à la fête chrétienne de la Nativité. Il signifie littéralement celui qui est né, en référence à la naissance du Christ.",
  "Odette": "Le prénom Odette vient du germanique aud (richesse) et heid (noble), signifiant littéralement noble richesse.",
  "Odile": "Le prénom Odile vient du latin Othilia, lui-même issu du germanique aud (richesse) et hild (combat). Il signifie littéralement celle qui combat pour la richesse ou la prospérité.",
  "Olive": "Le prénom Olive vient du latin oliva, lui-même issu du grec elaia, et désigne littéralement l'olivier ou son fruit. Il évoque la paix et la longévité, symboles souvent associés à cet arbre.",
  "Olivier": "Le prénom Olivier vient du latin olivarius, dérivé d'oliva, qui signifie littéralement olivier. Il évoque donc la paix et la sagesse, symbolisées par l'arbre de l'olivier.",
  "Ombeline": "D’origine germanique, Ombeline vient de Humbeline, formé sur hun (ours) et berht (brillant, illustre). Il signifie donc littéralement brillante comme un ours.",
  "Pacôme": "Du grec Pachomios, dérivé de pakhus (épais) et mêma (mémoire), signifiant à l'origine 'celui qui a une mémoire solide'. Sens courant : 'le patient' ou 'l'endurant'.",
  "Parfait": "Le prénom Parfait vient du latin perfectus, participe passé de perficere (achever, accomplir). Il signifie littéralement celui qui est sans défaut, idéal ou accompli.",
  "Pascal": "Le prénom Pascal vient du latin paschalis, lui-même issu du grec paskha et de l’hébreu pesah, signifiant la fête de Pâques. Il évoque donc celui qui naît ou est célébré pendant cette période.",
  "Patrick": "Le prénom Patrick vient du latin Patricius, lui-même issu du grec patrikios (πᾰτρικῐος), signifiant noble ou patricien. Il évoque donc l'idée de noblesse ou d'appartenance à une classe sociale élevée.",
  "Paul": "D'origine latine, Paul vient du prénom Paulus, dérivé de paulus signifiant petit ou humble. En grec, Pauolos renforce cette idée de modestie.",
  "Paule": "Le prénom Paule vient du latin Paulus, dérivé du grec Παῦλος (Paulos), signifiant à l'origine petit, humble ou faible. Il évoque aussi la simplicité et la modestie.",
  "Paulin": "Issu du latin Paulinus, dérivé de Paulus (petit, humble), ce prénom signifie littéralement celui qui est modeste ou petit. Il évoque aussi une personne paisible et bienveillante.",
  "Perpétue": "Perpétue vient du latin perpetuus, signifiant durable, continu. Ce prénom évoque donc l'idée de permanence, de constance.",
  "Philippe": "Le prénom Philippe vient du grec Philippos, formé de philos (ami) et hippos (cheval), ce qui signifie littéralement ami des chevaux.",
  "Pie": "Pie vient du latin pica, lui-même issu du grec pikos. Ce prénom signifie littéralement pie, l'oiseau noir et blanc.",
  "Pierre": "Le prénom Pierre vient du latin Petrus, lui-même issu du grec Petros, qui signifie littéralement la pierre ou le rocher.",
  "Pierre-Julien": "Pierre vient du grec Pétros, dérivé de pétra (pierre, rocher), et Julien vient du latin Julianus, issu de Julius, lié à Jupiter (dieu romain). Pierre-Julien signifie donc littéralement Pierre et Julien, deux prénoms bibliques et antiques.",
  "Pierre-Marie": "Pierre vient de l’hébreu \"Kefa\" (Pierre) et Marie du latin \"Maria\", dérivé de l’hébreu \"Miryam\". Ensemble, Pierre-Marie signifie littéralement Pierre et Marie, symbolisant la force et la grâce.",
  "Priscille": "Le prénom Priscille vient du latin Priscilla, féminin de Priscillus, diminutif de Priscus, lui-même issu du latin priscus signifiant ancien ou antique. Il évoque donc celle qui est noble ou vénérable par son âge.",
  "Prosper": "Prosper vient du latin prosperus, dérivé de prosperare (faire prospérer), lui-même lié à spes (espoir). Il signifie littéralement celui qui est prospère ou favorisé par la chance.",
  "Prudence": "Du latin prudentia, signifie 'sagesse pratique' ou 'prudence'. Symbole de réflexion avant l'action, souvent associé à la tempérance.",
  "Pélagie": "Du grec pelagios ('de la mer'), lié à pelagos ('mer'). Évoque la liberté et l'immensité, ou la sainte chrétienne protectrice des marins.",
  "Quentin": "Du latin Quintus, signifiant 'cinquième'. Il évoque l'ordre de naissance ou une place privilégiée dans une fratrie.",
  "Ralph": "D'origine germanique Radalf, formé de rad ('conseil') et wolf ('loup'). Signifie 'conseil du loup', symbolisant la ruse et la force.",
  "Raoul": "Variante de Ralph, même origine germanique Radalf. Porte l'idée de 'conseil puissant' ou de protection divine.",
  "Raphaël": "De l'hébreu Rafa'el ('Dieu a guéri'). Signifie 'Dieu guérit' ou 'médecin divin', souvent associé à l'archange bienveillant.",
  "Raymond": "Du germanique Raginmund, de ragin ('conseil') et mund ('protection'). Évoque 'celui qui protège par la sagesse'.",
  "Raïssa": "D'origine hébraïque, ce prénom signifie \"douce\" ou \"agréable\". Il évoque une personne au caractère paisible et bienveillant.",
  "Reine": "Issu du latin regina, il désigne une femme qui règne ou qui est noble. Symbole de pouvoir et de grâce, il porte une connotation majestueuse.",
  "Remi": "Vient du latin Remigius, signifiant \"celui qui rame\" ou \"remueur\". Il évoque aussi l'idée de guidance, comme un guide spirituel ou un protecteur.",
  "René": "Dérivé du latin renatus, il signifie \"renaître\". Il symbolise un renouveau, une seconde chance ou une transformation intérieure.",
  "Richard": "Origine germanique (Ricohard), composé de ric (puissant) et hard (dur). Il désigne un homme fort, courageux et déterminé.",
  "Rita": "Forme féminine de Marguerite, issu du grec margarites (perle). Il évoque la pureté, la douceur et une beauté discrète.",
  "Robert": "D'origine germanique (Hrodebert), composé de hrod (gloire) et berht (brillant). Il signifie \"celui qui brille par sa gloire\".",
  "Rodrigue": "Vient du germanique Hrodric, formé de hrod (gloire) et ric (puissant). Il porte l'idée d'une personne illustre et influente.",
  "Rogatien": "Issu du latin Rogatianus, dérivé de Rogatus (celui qui est prié). Il évoque une personne humble, proche des prières et de la spiritualité.",
  "Roger": "D'origine germanique (Hrodger), formé de hrod (gloire) et ger (lance). Il signifie \"celui qui brandit la gloire comme une lance\".",
  "Romain": "Vient du latin Romanus, signifiant \"originaire de Rome\". Il évoque l'héritage antique, la culture et l'élégance méditerranéenne.",
  "Romaric": "Composé des racines germaniques hrod (gloire) et ric (puissant). Il désigne une personne à la fois illustre et forte.",
  "Romuald": "D'origine germanique (Hrodwald), formé de hrod (gloire) et wald (dirigeant). Il évoque un leader glorieux et respecté.",
  "Rosalie": "Issu du latin rosalia, lié à la rose. Il symbolise la beauté, la douceur et l'épanouissement printanier.",
  "Rose": "Vient du latin rosa, la fleur emblématique. Il évoque la beauté, l'amour et la fragilité délicate.",
  "Rose-Philippine": "Combinaison de Rose (fleur) et Philippine (amie des chevaux). Il unit douceur florale et force noble, comme une guerrière bienveillante.",
  "Rosine": "Diminutif de Rose, issu du latin rosina. Il porte l'idée d'une rose petite et délicate, pleine de charme.",
  "Rupert": "D'origine germanique (Hruodperht), formé de hruod (gloire) et berht (brillant). Il désigne un homme à la fois glorieux et lumineux.",
  "Sabine": "Vient du latin Sabinus, lié au peuple des Sabins. Il évoque une personne simple, naturelle et attachée à ses racines.",
  "Salomon": "Origine hébraïque (Shlomo), signifiant \"paix\". Il évoque la sagesse, l'intelligence et une autorité bienveillante.",
  "Salomé": "D'origine hébraïque (Shlomit), lié à la paix. Elle porte aussi l'idée de grâce et de mystère, comme dans les récits bibliques.",
  "Samson": "Issu de l'hébreu Shimshon, signifiant \"soleil\". Il évoque la force, la puissance et une énergie rayonnante.",
  "Scholastique": "Vient du grec scholastikos, signifiant \"savant\" ou \"studieux\". Il désigne une personne cultivée, réfléchie et attachée au savoir.",
  "Sernin": "D'origine latine (Servinus), lié à servus (serviteur). Il évoque une personne humble, dévouée et proche des valeurs chrétiennes.",
  "Silvain": "Issu du latin Silvanus, dieu des forêts. Il désigne une personne proche de la nature, libre et sauvage comme un esprit des bois.",
  "Silvère": "Vient du latin silva (forêt). Il évoque la force tranquille, la connexion à la nature et une sagesse rustique.",
  "Simon": "D'origine hébraïque (Shimon), signifiant \"Dieu a entendu\". Il porte l'idée d'une écoute divine et d'une réponse favorable.",
  "Solange": "Vient du latin sollemnis (solennel) ou sol (soleil). Elle évoque la lumière, la joie et une présence radieuse.",
  "Stanislas": "D'origine slave (Stanislav), formé de stan (devenir) et slava (gloire). Il signifie \"celui qui devient glorieux\".",
  "Suzanne": "Issu de l'hébreu Shoshannah, signifiant \"lis\" ou \"fleur de lys\". Il évoque la pureté, l'élégance et une beauté délicate.",
  "Sylvain": "Variante de Silvain, issu du latin Silvanus. Il désigne une personne proche de la nature, libre et apaisante comme une forêt.",
  "Sylvestre": "Vient du latin silvestris (qui vit dans les bois). Il évoque la force tranquille, la sagesse et un lien profond avec la nature.",
  "Sébastien": "D'origine grecque (Sebastos), signifiant \"vénérable\" ou \"respecté\". Il porte l'idée d'une personne digne et honorable.",
  "Séverin": "Issu du latin Severus, signifiant \"sévère\" ou \"strict\". Il évoque une personne rigoureuse, sérieuse et déterminée.",
  "Tanguy": "D'origine bretonne, lié à tan (feu) et ki (chien). Il désigne un guerrier ardent, passionné et parfois impulsif.",
  "Tatiana": "Du grec Tatiana, féminin de Tatianus, dérivé de Tatos (signifiant",
  "Thierry": "Du germanique Theudoric, composé de þeudō (peuple) et rīc (puissant), signifiant",
  "Thomas": "De l'araméen Toma (jumeau), popularisé par l'apôtre Thomas dans les Évangiles, signifiant",
  "Théodora": "Du grec Theodōra, féminin de Theodōros, composé de theos (dieu) et dōron (don), signifiant",
  "Théodore": "Du grec Theodōros, composé de theos (dieu) et dōron (don), signifiant",
  "Théophane": "Du grec Theophanes, composé de theos (dieu) et phainein (montrer), signifiant",
  "Thérèse": "Du grec Therasia, féminin de Therasios, signifiant",
  "Timothée": "Du grec Timótheos, composé de timē (honneur) et theos (dieu), signifiant",
  "Toribio": "Du latin Turibius, d'origine celtibère, signifiant",
  "Toussaint": "Du latin Totus Sanctus, signifiant",
  "Ulric": "Du germanique Wulric, composé de wulf (loup) et rīc (puissant), signifiant",
  "Urbain": "Du latin Urbanus, dérivé de urbs (ville), signifiant",
  "Ursule": "Du latin Ursula, diminutif de ursa (ourse), signifiant",
  "Valentin": "Du latin Valentinus, dérivé de valens (fort, valeureux), signifiant",
  "Valérie": "Du latin Valeria, féminin de Valerius, dérivé de valens (fort), signifiant",
  "Venceslas": "Du slave Venceslav, composé de ven (plus) et slava (gloire), signifiant",
  "Victoire": "Du latin Victoria, dérivé de vincere (vaincre), signifiant",
  "Victor": "Du latin Victor, dérivé de vincere (vaincre), signifiant",
  "Vincent": "Du latin Vincentius, dérivé de vincere (vaincre), signifiant",
  "Virgile": "Du latin Virgilius, d'origine incertaine, peut-être lié à virga (branche verte), signifiant",
  "Vivien": "Du latin Vivianus, dérivé de vivus (vivant), signifiant",
  "Véronique": "Du grec Berenikē, composé de pherein (apporter) et nikē (victoire), signifiant",
  "Yves": "Du breton Ivo, d'origine germanique Iwo (if), arbre symbole de vie, signifiant",
  "Zita": "De l'italien Zita, du latin Zita (petite), signifiant",
  "Zéphyrin": "Du grec Zephyrinos, dérivé de Zephyros (vent d'ouest), signifiant",
  "Émile": "Du latin Aemilius, d'origine incertaine, peut-être lié à aemulus (rival), signifiant",
  "Étienne": "Du grec Stephanos, signifiant",
};
