-- Migration 048 : colonnes ton + longueur + remplacement complet des modèles système

ALTER TABLE message_templates
  ADD COLUMN IF NOT EXISTS ton     TEXT CHECK (ton     IN ('tu','vous')),
  ADD COLUMN IF NOT EXISTS longueur TEXT CHECK (longueur IN ('court','moyen','long'));

-- Suppression des anciens modèles système
DELETE FROM message_templates WHERE is_system = true;

-- ─────────────────────────────────────────────────────────────────────────────
-- ANNIVERSAIRE (birthday)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Joyeux anniversaire {prenom} ! 🎉','',true,'birthday','tu','court'),
(NULL,'Modèle 2','Bon anniversaire ! Profite bien de ta journée.','',true,'birthday','tu','court'),
(NULL,'Modèle 3','Joyeux anniversaire ! Que cette journée soit belle.','',true,'birthday','tu','court'),
(NULL,'Modèle 4','Un an de plus, plein de bonheur en plus !','',true,'birthday','tu','court'),
(NULL,'Modèle 5','Très joyeux anniversaire !','',true,'birthday','tu','court'),
(NULL,'Modèle 6','Passe une super journée !','',true,'birthday','tu','court'),
(NULL,'Modèle 7','Joyeux anniversaire ! Plein de belles choses.','',true,'birthday','tu','court'),
(NULL,'Modèle 8','Profite bien de ta journée, c''est la tienne !','',true,'birthday','tu','court'),
(NULL,'Modèle 9','Joyeux anniversaire ! 🎂','',true,'birthday','tu','court'),
(NULL,'Modèle 10','Que cette journée soit pleine de joie !','',true,'birthday','tu','court'),
(NULL,'Modèle 1','Joyeux anniversaire {prenom} ! 🎉 J''espère que ta journée sera remplie de beaux moments. Je te souhaite une année pleine de bonheur.','',true,'birthday','tu','moyen'),
(NULL,'Modèle 2','Bon anniversaire ! Profite bien de cette journée et entoure-toi de ceux que tu aimes. Que cette année t''apporte de belles choses.','',true,'birthday','tu','moyen'),
(NULL,'Modèle 3','Joyeux anniversaire {prenom} ! Une nouvelle année commence, pleine de projets et de moments à savourer. Je te souhaite le meilleur.','',true,'birthday','tu','moyen'),
(NULL,'Modèle 1','Joyeux anniversaire {prenom} ! 🎉 J''espère que cette journée sera à ton image, remplie de joie et de belles surprises. Tu mérites une année pleine de bonheur et de moments précieux. Profite bien de chaque instant.','',true,'birthday','tu','long'),
(NULL,'Modèle 2','Bon anniversaire ! Une nouvelle année commence pour toi, pleine de possibilités. Je te souhaite de réaliser tes projets et de vivre de beaux moments. Passe une excellente journée.','',true,'birthday','tu','long'),
(NULL,'Modèle 3','Joyeux anniversaire {prenom} ! Je te souhaite une année remplie de réussites et de petits bonheurs du quotidien. Que tout ce que tu entreprends te rende heureux(se).','',true,'birthday','tu','long'),
(NULL,'Modèle 1','Joyeux anniversaire {prenom} ! 🎉','',true,'birthday','vous','court'),
(NULL,'Modèle 2','Bon anniversaire !','',true,'birthday','vous','court'),
(NULL,'Modèle 3','Très joyeux anniversaire !','',true,'birthday','vous','court'),
(NULL,'Modèle 4','Je vous souhaite une belle journée.','',true,'birthday','vous','court'),
(NULL,'Modèle 5','Joyeux anniversaire !','',true,'birthday','vous','court'),
(NULL,'Modèle 6','Excellente journée à vous.','',true,'birthday','vous','court'),
(NULL,'Modèle 7','Très bon anniversaire !','',true,'birthday','vous','court'),
(NULL,'Modèle 8','Que cette journée vous soit agréable.','',true,'birthday','vous','court'),
(NULL,'Modèle 9','Joyeux anniversaire 🎂','',true,'birthday','vous','court'),
(NULL,'Modèle 10','Tous mes vœux pour cette journée.','',true,'birthday','vous','court'),
(NULL,'Modèle 1','Joyeux anniversaire {prenom} ! 🎉 Je vous souhaite une très belle journée remplie de moments agréables. Que cette année vous apporte bonheur et réussite.','',true,'birthday','vous','moyen'),
(NULL,'Modèle 2','Bon anniversaire ! Profitez pleinement de cette journée. Je vous souhaite une année riche en projets et en joies.','',true,'birthday','vous','moyen'),
(NULL,'Modèle 3','Joyeux anniversaire {prenom} ! Une nouvelle année s''ouvre à vous, pleine de possibilités. Je vous souhaite le meilleur.','',true,'birthday','vous','moyen'),
(NULL,'Modèle 1','Joyeux anniversaire {prenom} ! 🎉 Je vous souhaite une journée remplie de joie et de beaux moments. Que cette nouvelle année vous apporte bonheur et réussite. Profitez pleinement de cette journée.','',true,'birthday','vous','long'),
(NULL,'Modèle 2','Bon anniversaire ! Cette journée est l''occasion de célébrer tout ce que vous êtes. Je vous souhaite une année pleine de réussites et de sérénité.','',true,'birthday','vous','long'),
(NULL,'Modèle 3','Joyeux anniversaire {prenom} ! Je vous souhaite une année riche en projets et en moments heureux. Que tous vos souhaits se réalisent.','',true,'birthday','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- BONNE FÊTE (nameday)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Bonne fête {prenom} ! 🎉','',true,'nameday','tu','court'),
(NULL,'Modèle 2','Très bonne fête !','',true,'nameday','tu','court'),
(NULL,'Modèle 3','Je pense à toi aujourd''hui 😊','',true,'nameday','tu','court'),
(NULL,'Modèle 4','Passe une belle journée !','',true,'nameday','tu','court'),
(NULL,'Modèle 5','Bonne fête ! Profite bien.','',true,'nameday','tu','court'),
(NULL,'Modèle 6','Une pensée pour toi aujourd''hui.','',true,'nameday','tu','court'),
(NULL,'Modèle 7','Très belle fête !','',true,'nameday','tu','court'),
(NULL,'Modèle 8','Bonne fête 🎂','',true,'nameday','tu','court'),
(NULL,'Modèle 9','Profite bien de ta journée !','',true,'nameday','tu','court'),
(NULL,'Modèle 10','Bonne fête à toi !','',true,'nameday','tu','court'),
(NULL,'Modèle 1','Bonne fête {prenom} ! Je pense bien à toi aujourd''hui. Je te souhaite une belle journée pleine de douceur.','',true,'nameday','tu','moyen'),
(NULL,'Modèle 2','Bonne fête ! Une belle occasion de te dire que je pense à toi. Profite bien de cette journée.','',true,'nameday','tu','moyen'),
(NULL,'Modèle 3','Bonne fête {prenom} ! J''espère que cette journée sera remplie de joie et de beaux moments.','',true,'nameday','tu','moyen'),
(NULL,'Modèle 1','Bonne fête {prenom} ! C''est une belle occasion de te rappeler combien tu comptes. Je te souhaite une journée remplie de douceur et de moments agréables. Profite pleinement de cette journée.','',true,'nameday','tu','long'),
(NULL,'Modèle 2','Bonne fête ! Je te souhaite une journée pleine de joie, de petits bonheurs et de moments précieux. Tu le mérites vraiment.','',true,'nameday','tu','long'),
(NULL,'Modèle 3','Bonne fête {prenom} ! Une journée spéciale pour une personne qui l''est tout autant. Je te souhaite beaucoup de bonheur aujourd''hui.','',true,'nameday','tu','long'),
(NULL,'Modèle 1','Bonne fête {prenom} !','',true,'nameday','vous','court'),
(NULL,'Modèle 2','Très bonne fête !','',true,'nameday','vous','court'),
(NULL,'Modèle 3','Une pensée pour vous aujourd''hui.','',true,'nameday','vous','court'),
(NULL,'Modèle 4','Je vous souhaite une belle journée.','',true,'nameday','vous','court'),
(NULL,'Modèle 5','Bonne fête à vous !','',true,'nameday','vous','court'),
(NULL,'Modèle 6','Excellente journée.','',true,'nameday','vous','court'),
(NULL,'Modèle 7','Bonne fête 🎉','',true,'nameday','vous','court'),
(NULL,'Modèle 8','Très belle fête !','',true,'nameday','vous','court'),
(NULL,'Modèle 9','Profitez bien de cette journée.','',true,'nameday','vous','court'),
(NULL,'Modèle 10','Bonne fête !','',true,'nameday','vous','court'),
(NULL,'Modèle 1','Bonne fête {prenom} ! Je vous souhaite une très belle journée pleine de moments agréables.','',true,'nameday','vous','moyen'),
(NULL,'Modèle 2','Bonne fête ! Une pensée pour vous aujourd''hui. Je vous souhaite une journée agréable.','',true,'nameday','vous','moyen'),
(NULL,'Modèle 3','Bonne fête {prenom} ! J''espère que cette journée vous apportera de la joie.','',true,'nameday','vous','moyen'),
(NULL,'Modèle 1','Bonne fête {prenom} ! Je vous souhaite une journée remplie de douceur et de beaux moments. Profitez pleinement de cette occasion.','',true,'nameday','vous','long'),
(NULL,'Modèle 2','Bonne fête ! Je vous adresse mes meilleurs vœux pour cette journée particulière. Qu''elle soit agréable et sereine.','',true,'nameday','vous','long'),
(NULL,'Modèle 3','Bonne fête {prenom} ! Une belle occasion de vous souhaiter une journée chaleureuse et pleine de bonheur.','',true,'nameday','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- FIANÇAILLES (engagement)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Félicitations pour vos fiançailles ! 💍','',true,'engagement','tu','court'),
(NULL,'Modèle 2','Très heureux(se) pour toi !','',true,'engagement','tu','court'),
(NULL,'Modèle 3','Quelle belle nouvelle !','',true,'engagement','tu','court'),
(NULL,'Modèle 4','Félicitations !','',true,'engagement','tu','court'),
(NULL,'Modèle 5','Plein de bonheur à vous deux !','',true,'engagement','tu','court'),
(NULL,'Modèle 6','Une belle étape commence !','',true,'engagement','tu','court'),
(NULL,'Modèle 7','Félicitations 🎉','',true,'engagement','tu','court'),
(NULL,'Modèle 8','Beaucoup de bonheur !','',true,'engagement','tu','court'),
(NULL,'Modèle 9','Très belle nouvelle !','',true,'engagement','tu','court'),
(NULL,'Modèle 10','Félicitations pour cette belle étape !','',true,'engagement','tu','court'),
(NULL,'Modèle 1','Félicitations pour tes fiançailles {prenom} ! Une très belle étape commence. Je te souhaite beaucoup de bonheur.','',true,'engagement','tu','moyen'),
(NULL,'Modèle 2','Félicitations ! Une nouvelle aventure à deux commence. Profite bien de cette belle période.','',true,'engagement','tu','moyen'),
(NULL,'Modèle 3','Félicitations pour vos fiançailles ! Une belle histoire continue de s''écrire. Je te souhaite le meilleur.','',true,'engagement','tu','moyen'),
(NULL,'Modèle 1','Félicitations pour tes fiançailles {prenom} ! 💍 Une très belle étape commence pour vous deux. Je te souhaite beaucoup de bonheur, de complicité et de beaux projets. Profite pleinement de cette période.','',true,'engagement','tu','long'),
(NULL,'Modèle 2','Félicitations ! Cette belle nouvelle marque le début d''une nouvelle aventure. Je te souhaite une vie remplie d''amour et de moments précieux.','',true,'engagement','tu','long'),
(NULL,'Modèle 3','Félicitations pour vos fiançailles ! Une étape importante et pleine d''émotion. Je te souhaite une relation remplie de bonheur et de projets.','',true,'engagement','tu','long'),
(NULL,'Modèle 1','Félicitations pour vos fiançailles ! 💍','',true,'engagement','vous','court'),
(NULL,'Modèle 2','Très heureux pour vous !','',true,'engagement','vous','court'),
(NULL,'Modèle 3','Quelle belle nouvelle !','',true,'engagement','vous','court'),
(NULL,'Modèle 4','Félicitations !','',true,'engagement','vous','court'),
(NULL,'Modèle 5','Beaucoup de bonheur à vous deux !','',true,'engagement','vous','court'),
(NULL,'Modèle 6','Une belle étape commence !','',true,'engagement','vous','court'),
(NULL,'Modèle 7','Félicitations 🎉','',true,'engagement','vous','court'),
(NULL,'Modèle 8','Tous mes vœux de bonheur !','',true,'engagement','vous','court'),
(NULL,'Modèle 9','Très belle annonce !','',true,'engagement','vous','court'),
(NULL,'Modèle 10','Félicitations pour cette étape !','',true,'engagement','vous','court'),
(NULL,'Modèle 1','Félicitations pour vos fiançailles ! Je vous souhaite beaucoup de bonheur pour cette belle étape.','',true,'engagement','vous','moyen'),
(NULL,'Modèle 2','Félicitations ! Une nouvelle aventure commence pour vous deux. Je vous souhaite le meilleur.','',true,'engagement','vous','moyen'),
(NULL,'Modèle 3','Félicitations pour vos fiançailles ! Une belle histoire se poursuit. Je vous souhaite beaucoup de joie.','',true,'engagement','vous','moyen'),
(NULL,'Modèle 1','Toutes mes félicitations pour vos fiançailles ! 💍 Cette étape marque le début d''une belle aventure. Je vous souhaite beaucoup de bonheur et de moments précieux.','',true,'engagement','vous','long'),
(NULL,'Modèle 2','Félicitations pour vos fiançailles ! Une très belle nouvelle qui annonce de beaux moments à venir. Je vous souhaite une vie remplie d''amour.','',true,'engagement','vous','long'),
(NULL,'Modèle 3','Félicitations pour cette belle annonce ! Je vous souhaite une vie pleine de bonheur, de complicité et de projets partagés.','',true,'engagement','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- NAISSANCE (birth)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Félicitations pour cette naissance ! 👶','',true,'birth','tu','court'),
(NULL,'Modèle 2','Bienvenue à ce petit bout !','',true,'birth','tu','court'),
(NULL,'Modèle 3','Quelle belle nouvelle !','',true,'birth','tu','court'),
(NULL,'Modèle 4','Félicitations !','',true,'birth','tu','court'),
(NULL,'Modèle 5','Plein de bonheur à vous !','',true,'birth','tu','court'),
(NULL,'Modèle 6','Bienvenue à bébé 💛','',true,'birth','tu','court'),
(NULL,'Modèle 7','Une merveilleuse nouvelle !','',true,'birth','tu','court'),
(NULL,'Modèle 8','Félicitations 🎉','',true,'birth','tu','court'),
(NULL,'Modèle 9','Beaucoup de bonheur à vous trois !','',true,'birth','tu','court'),
(NULL,'Modèle 10','Quelle joie !','',true,'birth','tu','court'),
(NULL,'Modèle 1','Félicitations pour cette naissance {prenom} ! Bienvenue à ce petit bout. Je te souhaite beaucoup de bonheur.','',true,'birth','tu','moyen'),
(NULL,'Modèle 2','Quelle belle nouvelle ! Félicitations pour cette naissance. Je te souhaite plein de beaux moments.','',true,'birth','tu','moyen'),
(NULL,'Modèle 3','Félicitations ! Une nouvelle vie commence, pleine de moments précieux. Profite bien de chaque instant.','',true,'birth','tu','moyen'),
(NULL,'Modèle 1','Félicitations pour cette naissance {prenom} ! 👶 Bienvenue à ce petit être qui va remplir votre vie d''amour. Je te souhaite beaucoup de bonheur dans cette nouvelle aventure. Profite de chaque instant.','',true,'birth','tu','long'),
(NULL,'Modèle 2','Quelle magnifique nouvelle ! Félicitations pour cette naissance. Je te souhaite beaucoup de joie, de douceur et de moments précieux avec ton bébé.','',true,'birth','tu','long'),
(NULL,'Modèle 3','Félicitations pour cette naissance ! Un petit être vient agrandir votre famille et apporter encore plus d''amour. Je te souhaite beaucoup de bonheur et de sérénité.','',true,'birth','tu','long'),
(NULL,'Modèle 1','Félicitations pour cette naissance ! 👶','',true,'birth','vous','court'),
(NULL,'Modèle 2','Bienvenue à ce petit être !','',true,'birth','vous','court'),
(NULL,'Modèle 3','Quelle belle nouvelle !','',true,'birth','vous','court'),
(NULL,'Modèle 4','Félicitations !','',true,'birth','vous','court'),
(NULL,'Modèle 5','Beaucoup de bonheur à vous !','',true,'birth','vous','court'),
(NULL,'Modèle 6','Bienvenue à bébé 💛','',true,'birth','vous','court'),
(NULL,'Modèle 7','Une merveilleuse nouvelle !','',true,'birth','vous','court'),
(NULL,'Modèle 8','Félicitations 🎉','',true,'birth','vous','court'),
(NULL,'Modèle 9','Tous mes vœux de bonheur !','',true,'birth','vous','court'),
(NULL,'Modèle 10','Quelle joie !','',true,'birth','vous','court'),
(NULL,'Modèle 1','Toutes mes félicitations pour cette naissance {prenom} ! Je vous souhaite beaucoup de bonheur.','',true,'birth','vous','moyen'),
(NULL,'Modèle 2','Félicitations pour cette belle nouvelle ! Une nouvelle aventure commence. Je vous souhaite beaucoup de joie.','',true,'birth','vous','moyen'),
(NULL,'Modèle 3','Félicitations pour cette naissance ! Une étape importante pleine d''émotion. Je vous souhaite le meilleur.','',true,'birth','vous','moyen'),
(NULL,'Modèle 1','Toutes mes félicitations pour cette naissance {prenom} ! 👶 Bienvenue à ce petit être qui vient enrichir votre famille. Je vous souhaite beaucoup de bonheur dans cette nouvelle aventure.','',true,'birth','vous','long'),
(NULL,'Modèle 2','Félicitations pour cette belle nouvelle ! L''arrivée de votre enfant marque le début d''une nouvelle vie pleine d''émotions. Je vous souhaite beaucoup de joie et de douceur.','',true,'birth','vous','long'),
(NULL,'Modèle 3','Félicitations pour cette naissance ! Un nouveau chapitre commence pour vous. Je vous souhaite beaucoup de bonheur et de moments précieux.','',true,'birth','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- BAPTÊME (baptism)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Félicitations pour ce baptême ✨','',true,'baptism','tu','court'),
(NULL,'Modèle 2','Très belle cérémonie !','',true,'baptism','tu','court'),
(NULL,'Modèle 3','Une belle étape !','',true,'baptism','tu','court'),
(NULL,'Modèle 4','Félicitations !','',true,'baptism','tu','court'),
(NULL,'Modèle 5','Belle journée à toi !','',true,'baptism','tu','court'),
(NULL,'Modèle 6','Un moment précieux !','',true,'baptism','tu','court'),
(NULL,'Modèle 7','Félicitations 🎉','',true,'baptism','tu','court'),
(NULL,'Modèle 8','Très belle occasion !','',true,'baptism','tu','court'),
(NULL,'Modèle 9','Que du bonheur !','',true,'baptism','tu','court'),
(NULL,'Modèle 10','Une journée spéciale !','',true,'baptism','tu','court'),
(NULL,'Modèle 1','Félicitations pour ce baptême {prenom} ! Une très belle étape pleine de sens. Profite bien de cette journée.','',true,'baptism','tu','moyen'),
(NULL,'Modèle 2','Félicitations pour cette belle cérémonie ! Un moment important entouré de tes proches. Je te souhaite beaucoup de joie.','',true,'baptism','tu','moyen'),
(NULL,'Modèle 3','Félicitations pour ce baptême ! Une journée pleine d''émotion et de partage. Profite bien de chaque instant.','',true,'baptism','tu','moyen'),
(NULL,'Modèle 1','Félicitations pour ce baptême {prenom} ✨ Une très belle étape pleine de sens et d''émotion. Je te souhaite une journée remplie de joie et de beaux souvenirs. Profite pleinement de cette occasion.','',true,'baptism','tu','long'),
(NULL,'Modèle 2','Félicitations pour cette belle cérémonie ! Une journée importante entourée de ceux qui comptent. Je te souhaite beaucoup de bonheur et de douceur.','',true,'baptism','tu','long'),
(NULL,'Modèle 3','Félicitations pour ce baptême ! Un moment unique et symbolique. Je te souhaite une journée agréable et pleine de beaux moments.','',true,'baptism','tu','long'),
(NULL,'Modèle 1','Félicitations pour ce baptême ✨','',true,'baptism','vous','court'),
(NULL,'Modèle 2','Très belle cérémonie !','',true,'baptism','vous','court'),
(NULL,'Modèle 3','Une belle étape !','',true,'baptism','vous','court'),
(NULL,'Modèle 4','Félicitations !','',true,'baptism','vous','court'),
(NULL,'Modèle 5','Belle journée à vous !','',true,'baptism','vous','court'),
(NULL,'Modèle 6','Un moment précieux !','',true,'baptism','vous','court'),
(NULL,'Modèle 7','Félicitations 🎉','',true,'baptism','vous','court'),
(NULL,'Modèle 8','Très belle occasion !','',true,'baptism','vous','court'),
(NULL,'Modèle 9','Tous mes vœux !','',true,'baptism','vous','court'),
(NULL,'Modèle 10','Une journée spéciale !','',true,'baptism','vous','court'),
(NULL,'Modèle 1','Toutes mes félicitations pour ce baptême {prenom} ! Je vous souhaite une très belle cérémonie.','',true,'baptism','vous','moyen'),
(NULL,'Modèle 2','Félicitations pour cette belle célébration ! Une étape importante entourée de vos proches. Je vous souhaite beaucoup de joie.','',true,'baptism','vous','moyen'),
(NULL,'Modèle 3','Félicitations pour ce baptême ! Une journée pleine de sens et de partage. Je vous souhaite de très beaux moments.','',true,'baptism','vous','moyen'),
(NULL,'Modèle 1','Toutes mes félicitations pour ce baptême {prenom} ✨ Une belle cérémonie pleine de sens et d''émotion. Je vous souhaite une journée remplie de joie et de beaux souvenirs.','',true,'baptism','vous','long'),
(NULL,'Modèle 2','Félicitations pour cette belle célébration ! Une journée importante entourée de ceux qui comptent. Je vous souhaite beaucoup de bonheur et de sérénité.','',true,'baptism','vous','long'),
(NULL,'Modèle 3','Félicitations pour ce baptême ! Une étape importante dans la vie. Je vous souhaite une très belle journée pleine de moments précieux.','',true,'baptism','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- COMMUNION (communion)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Félicitations pour ta communion ✨','',true,'communion','tu','court'),
(NULL,'Modèle 2','Très belle cérémonie !','',true,'communion','tu','court'),
(NULL,'Modèle 3','Une belle étape !','',true,'communion','tu','court'),
(NULL,'Modèle 4','Félicitations !','',true,'communion','tu','court'),
(NULL,'Modèle 5','Belle journée à toi !','',true,'communion','tu','court'),
(NULL,'Modèle 6','Un moment précieux !','',true,'communion','tu','court'),
(NULL,'Modèle 7','Félicitations 🎉','',true,'communion','tu','court'),
(NULL,'Modèle 8','Très belle occasion !','',true,'communion','tu','court'),
(NULL,'Modèle 9','Que du bonheur !','',true,'communion','tu','court'),
(NULL,'Modèle 10','Une journée spéciale !','',true,'communion','tu','court'),
(NULL,'Modèle 1','Félicitations pour ta communion {prenom} ! Une très belle étape pleine de sens. Profite bien de cette journée.','',true,'communion','tu','moyen'),
(NULL,'Modèle 2','Félicitations pour cette belle célébration ! Un moment important entouré de tes proches. Je te souhaite beaucoup de joie.','',true,'communion','tu','moyen'),
(NULL,'Modèle 3','Félicitations pour cette communion ! Une journée pleine d''émotion et de partage. Profite bien de chaque instant.','',true,'communion','tu','moyen'),
(NULL,'Modèle 1','Félicitations pour ta communion {prenom} ✨ Une très belle étape pleine de sens et d''émotion. Je te souhaite une journée remplie de joie et de beaux souvenirs.','',true,'communion','tu','long'),
(NULL,'Modèle 2','Félicitations pour cette belle célébration ! Une journée importante entourée de ceux qui comptent. Je te souhaite beaucoup de bonheur et de douceur.','',true,'communion','tu','long'),
(NULL,'Modèle 3','Félicitations pour cette communion ! Un moment unique et symbolique. Je te souhaite une journée agréable et pleine de beaux moments.','',true,'communion','tu','long'),
(NULL,'Modèle 1','Félicitations pour cette communion ✨','',true,'communion','vous','court'),
(NULL,'Modèle 2','Très belle cérémonie !','',true,'communion','vous','court'),
(NULL,'Modèle 3','Une belle étape !','',true,'communion','vous','court'),
(NULL,'Modèle 4','Félicitations !','',true,'communion','vous','court'),
(NULL,'Modèle 5','Belle journée à vous !','',true,'communion','vous','court'),
(NULL,'Modèle 6','Un moment précieux !','',true,'communion','vous','court'),
(NULL,'Modèle 7','Félicitations 🎉','',true,'communion','vous','court'),
(NULL,'Modèle 8','Très belle occasion !','',true,'communion','vous','court'),
(NULL,'Modèle 9','Tous mes vœux !','',true,'communion','vous','court'),
(NULL,'Modèle 10','Une journée spéciale !','',true,'communion','vous','court'),
(NULL,'Modèle 1','Toutes mes félicitations pour cette communion {prenom} ! Je vous souhaite une très belle cérémonie.','',true,'communion','vous','moyen'),
(NULL,'Modèle 2','Félicitations pour cette belle célébration ! Une étape importante entourée de vos proches. Je vous souhaite beaucoup de joie.','',true,'communion','vous','moyen'),
(NULL,'Modèle 3','Félicitations pour cette communion ! Une journée pleine de sens et de partage. Je vous souhaite de très beaux moments.','',true,'communion','vous','moyen'),
(NULL,'Modèle 1','Toutes mes félicitations pour cette communion {prenom} ✨ Une belle cérémonie pleine de sens et d''émotion. Je vous souhaite une journée remplie de joie et de beaux souvenirs.','',true,'communion','vous','long'),
(NULL,'Modèle 2','Félicitations pour cette belle célébration ! Une journée importante entourée de ceux qui comptent. Je vous souhaite beaucoup de bonheur et de sérénité.','',true,'communion','vous','long'),
(NULL,'Modèle 3','Félicitations pour cette communion ! Une étape importante dans la vie. Je vous souhaite une très belle journée pleine de moments précieux.','',true,'communion','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- DIPLÔME (graduation)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Félicitations pour ton diplôme ! 🎓','',true,'graduation','tu','court'),
(NULL,'Modèle 2','Bravo pour ta réussite !','',true,'graduation','tu','court'),
(NULL,'Modèle 3','Tu l''as fait, bravo !','',true,'graduation','tu','court'),
(NULL,'Modèle 4','Félicitations !','',true,'graduation','tu','court'),
(NULL,'Modèle 5','Très belle réussite !','',true,'graduation','tu','court'),
(NULL,'Modèle 6','Bravo 🎉','',true,'graduation','tu','court'),
(NULL,'Modèle 7','Une étape franchie !','',true,'graduation','tu','court'),
(NULL,'Modèle 8','Félicitations pour ce succès !','',true,'graduation','tu','court'),
(NULL,'Modèle 9','Tu peux être fier(ère) !','',true,'graduation','tu','court'),
(NULL,'Modèle 10','Bien joué !','',true,'graduation','tu','court'),
(NULL,'Modèle 1','Félicitations pour ton diplôme {prenom} ! 🎓 Tu peux être fier(ère) de toi. Je te souhaite le meilleur pour la suite.','',true,'graduation','tu','moyen'),
(NULL,'Modèle 2','Bravo pour cette belle réussite ! Une étape importante franchie. Que la suite t''apporte encore plein de belles opportunités.','',true,'graduation','tu','moyen'),
(NULL,'Modèle 3','Félicitations pour ton diplôme ! Un bel accomplissement qui ouvre de nouvelles perspectives. Je te souhaite beaucoup de réussite.','',true,'graduation','tu','moyen'),
(NULL,'Modèle 1','Félicitations pour ton diplôme {prenom} ! 🎓 C''est une belle récompense pour tout le travail accompli. Tu peux être fier(ère) de toi. Je te souhaite beaucoup de réussite pour la suite.','',true,'graduation','tu','long'),
(NULL,'Modèle 2','Bravo pour cette réussite ! Cette étape marque un tournant important. Je te souhaite de continuer à réaliser tes projets et de vivre de belles expériences.','',true,'graduation','tu','long'),
(NULL,'Modèle 3','Félicitations pour ton diplôme ! Un accomplissement important qui ouvre la voie à de nouvelles aventures. Je te souhaite beaucoup de succès et de belles opportunités.','',true,'graduation','tu','long'),
(NULL,'Modèle 1','Félicitations pour votre diplôme ! 🎓','',true,'graduation','vous','court'),
(NULL,'Modèle 2','Bravo pour votre réussite !','',true,'graduation','vous','court'),
(NULL,'Modèle 3','Très belle réussite !','',true,'graduation','vous','court'),
(NULL,'Modèle 4','Félicitations !','',true,'graduation','vous','court'),
(NULL,'Modèle 5','Bravo 🎉','',true,'graduation','vous','court'),
(NULL,'Modèle 6','Une étape franchie !','',true,'graduation','vous','court'),
(NULL,'Modèle 7','Félicitations pour ce succès !','',true,'graduation','vous','court'),
(NULL,'Modèle 8','Vous pouvez être fier(ère) !','',true,'graduation','vous','court'),
(NULL,'Modèle 9','Bien joué !','',true,'graduation','vous','court'),
(NULL,'Modèle 10','Tous mes compliments !','',true,'graduation','vous','court'),
(NULL,'Modèle 1','Félicitations pour votre diplôme {prenom} ! 🎓 C''est une belle réussite. Je vous souhaite le meilleur pour la suite.','',true,'graduation','vous','moyen'),
(NULL,'Modèle 2','Bravo pour cette belle réussite ! Une étape importante franchie avec succès. Je vous souhaite de belles opportunités.','',true,'graduation','vous','moyen'),
(NULL,'Modèle 3','Félicitations pour votre diplôme ! Un bel accomplissement qui ouvre de nouvelles perspectives. Je vous souhaite beaucoup de réussite.','',true,'graduation','vous','moyen'),
(NULL,'Modèle 1','Félicitations pour votre diplôme {prenom} ! 🎓 Ce résultat récompense votre travail et votre engagement. Vous pouvez être fier(ère) de ce que vous avez accompli. Je vous souhaite beaucoup de succès.','',true,'graduation','vous','long'),
(NULL,'Modèle 2','Bravo pour cette réussite ! Cette étape marque un moment important de votre parcours. Je vous souhaite de poursuivre vos projets avec succès.','',true,'graduation','vous','long'),
(NULL,'Modèle 3','Félicitations pour votre diplôme ! Un accomplissement qui ouvre la voie à de nouvelles perspectives. Je vous souhaite beaucoup de réussite et de belles opportunités.','',true,'graduation','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- REMERCIEMENTS (thanks)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Merci beaucoup ! 💛','',true,'thanks','tu','court'),
(NULL,'Modèle 2','Un grand merci !','',true,'thanks','tu','court'),
(NULL,'Modèle 3','Merci pour tout !','',true,'thanks','tu','court'),
(NULL,'Modèle 4','Merci infiniment !','',true,'thanks','tu','court'),
(NULL,'Modèle 5','Merci 🙏','',true,'thanks','tu','court'),
(NULL,'Modèle 6','Vraiment merci !','',true,'thanks','tu','court'),
(NULL,'Modèle 7','Merci à toi !','',true,'thanks','tu','court'),
(NULL,'Modèle 8','Merci pour ton aide !','',true,'thanks','tu','court'),
(NULL,'Modèle 9','Merci pour tout 💛','',true,'thanks','tu','court'),
(NULL,'Modèle 10','Merci du fond du cœur !','',true,'thanks','tu','court'),
(NULL,'Modèle 1','Merci beaucoup {prenom} 💛 Ton geste m''a vraiment touché(e). Ça compte beaucoup pour moi.','',true,'thanks','tu','moyen'),
(NULL,'Modèle 2','Un grand merci ! Ce que tu as fait m''a fait très plaisir. Je t''en suis reconnaissant(e).','',true,'thanks','tu','moyen'),
(NULL,'Modèle 3','Merci pour tout ! Ta présence et ton attention ont vraiment compté pour moi.','',true,'thanks','tu','moyen'),
(NULL,'Modèle 1','Merci beaucoup {prenom} 💛 Je voulais vraiment te remercier sincèrement. Ton geste m''a profondément touché(e). Je t''en suis très reconnaissant(e).','',true,'thanks','tu','long'),
(NULL,'Modèle 2','Un grand merci ! Ce que tu as fait m''a vraiment touché(e) et fait plaisir. Ta présence compte beaucoup pour moi.','',true,'thanks','tu','long'),
(NULL,'Modèle 3','Merci pour tout ! Je voulais te dire combien j''ai apprécié ton attention. Cela m''a sincèrement touché(e).','',true,'thanks','tu','long'),
(NULL,'Modèle 1','Merci beaucoup !','',true,'thanks','vous','court'),
(NULL,'Modèle 2','Un grand merci !','',true,'thanks','vous','court'),
(NULL,'Modèle 3','Merci pour tout !','',true,'thanks','vous','court'),
(NULL,'Modèle 4','Merci infiniment !','',true,'thanks','vous','court'),
(NULL,'Modèle 5','Merci 🙏','',true,'thanks','vous','court'),
(NULL,'Modèle 6','Je vous remercie !','',true,'thanks','vous','court'),
(NULL,'Modèle 7','Merci à vous !','',true,'thanks','vous','court'),
(NULL,'Modèle 8','Merci pour votre aide !','',true,'thanks','vous','court'),
(NULL,'Modèle 9','Merci pour tout','',true,'thanks','vous','court'),
(NULL,'Modèle 10','Merci sincèrement !','',true,'thanks','vous','court'),
(NULL,'Modèle 1','Je vous remercie sincèrement {prenom} 💛 Votre geste m''a beaucoup touché(e).','',true,'thanks','vous','moyen'),
(NULL,'Modèle 2','Un grand merci ! Votre attention a été très appréciée. Je vous en suis reconnaissant(e).','',true,'thanks','vous','moyen'),
(NULL,'Modèle 3','Merci pour tout ! Votre présence et votre geste ont beaucoup compté.','',true,'thanks','vous','moyen'),
(NULL,'Modèle 1','Je vous remercie sincèrement {prenom} 💛 Je tenais à vous exprimer toute ma gratitude. Votre geste m''a profondément touché(e).','',true,'thanks','vous','long'),
(NULL,'Modèle 2','Un grand merci ! Votre attention m''a beaucoup touché(e) et fait plaisir. Je vous en suis très reconnaissant(e).','',true,'thanks','vous','long'),
(NULL,'Modèle 3','Merci pour tout ! Je voulais vous dire combien j''ai apprécié votre soutien. Cela m''a sincèrement touché(e).','',true,'thanks','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- NOUVEL AN (newyear)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Bonne année {prenom} ! 🎉','',true,'newyear','tu','court'),
(NULL,'Modèle 2','Très belle année !','',true,'newyear','tu','court'),
(NULL,'Modèle 3','Bonne année !','',true,'newyear','tu','court'),
(NULL,'Modèle 4','Tous mes vœux !','',true,'newyear','tu','court'),
(NULL,'Modèle 5','Excellente année !','',true,'newyear','tu','court'),
(NULL,'Modèle 6','Belle année à toi !','',true,'newyear','tu','court'),
(NULL,'Modèle 7','Bonne année 🎉','',true,'newyear','tu','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'newyear','tu','court'),
(NULL,'Modèle 9','Meilleurs vœux !','',true,'newyear','tu','court'),
(NULL,'Modèle 10','Très bonne année !','',true,'newyear','tu','court'),
(NULL,'Modèle 1','Bonne année {prenom} ! 🎉 Je te souhaite une année pleine de bonheur et de réussite.','',true,'newyear','tu','moyen'),
(NULL,'Modèle 2','Très belle année ! Que cette nouvelle année t''apporte joie et beaux moments.','',true,'newyear','tu','moyen'),
(NULL,'Modèle 3','Bonne année {prenom} ! Une nouvelle page commence. Je te souhaite le meilleur.','',true,'newyear','tu','moyen'),
(NULL,'Modèle 1','Bonne année {prenom} ! 🎉 Je te souhaite une année remplie de bonheur, de réussite et de beaux moments. Que tous tes projets se réalisent.','',true,'newyear','tu','long'),
(NULL,'Modèle 2','Très belle année ! Une nouvelle année commence, pleine de possibilités. Je te souhaite de vivre de beaux moments.','',true,'newyear','tu','long'),
(NULL,'Modèle 3','Bonne année {prenom} ! Je te souhaite une année riche en projets, en réussites et en moments heureux.','',true,'newyear','tu','long'),
(NULL,'Modèle 1','Bonne année {prenom} ! 🎉','',true,'newyear','vous','court'),
(NULL,'Modèle 2','Très belle année !','',true,'newyear','vous','court'),
(NULL,'Modèle 3','Bonne année !','',true,'newyear','vous','court'),
(NULL,'Modèle 4','Tous mes vœux !','',true,'newyear','vous','court'),
(NULL,'Modèle 5','Excellente année !','',true,'newyear','vous','court'),
(NULL,'Modèle 6','Belle année à vous !','',true,'newyear','vous','court'),
(NULL,'Modèle 7','Bonne année 🎉','',true,'newyear','vous','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'newyear','vous','court'),
(NULL,'Modèle 9','Meilleurs vœux !','',true,'newyear','vous','court'),
(NULL,'Modèle 10','Très bonne année !','',true,'newyear','vous','court'),
(NULL,'Modèle 1','Bonne année {prenom} ! 🎉 Je vous souhaite une année pleine de bonheur et de réussite.','',true,'newyear','vous','moyen'),
(NULL,'Modèle 2','Très belle année ! Que cette nouvelle année vous apporte joie et beaux moments.','',true,'newyear','vous','moyen'),
(NULL,'Modèle 3','Bonne année {prenom} ! Une nouvelle page commence. Je vous souhaite le meilleur.','',true,'newyear','vous','moyen'),
(NULL,'Modèle 1','Bonne année {prenom} ! 🎉 Je vous souhaite une année remplie de bonheur, de réussite et de beaux moments.','',true,'newyear','vous','long'),
(NULL,'Modèle 2','Très belle année ! Une nouvelle année commence, pleine de possibilités. Je vous souhaite de beaux projets.','',true,'newyear','vous','long'),
(NULL,'Modèle 3','Bonne année {prenom} ! Je vous souhaite une année riche en réussites et en moments heureux.','',true,'newyear','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- NOËL (christmas)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Joyeux Noël {prenom} ! 🎄','',true,'christmas','tu','court'),
(NULL,'Modèle 2','Très joyeux Noël !','',true,'christmas','tu','court'),
(NULL,'Modèle 3','Belles fêtes !','',true,'christmas','tu','court'),
(NULL,'Modèle 4','Joyeux Noël !','',true,'christmas','tu','court'),
(NULL,'Modèle 5','Profite bien des fêtes !','',true,'christmas','tu','court'),
(NULL,'Modèle 6','Un très beau Noël !','',true,'christmas','tu','court'),
(NULL,'Modèle 7','Joyeuses fêtes 🎄','',true,'christmas','tu','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'christmas','tu','court'),
(NULL,'Modèle 9','Très belles fêtes !','',true,'christmas','tu','court'),
(NULL,'Modèle 10','Passe un bon Noël !','',true,'christmas','tu','court'),
(NULL,'Modèle 1','Joyeux Noël {prenom} ! 🎄 Je te souhaite une journée pleine de douceur et de beaux moments.','',true,'christmas','tu','moyen'),
(NULL,'Modèle 2','Joyeux Noël ! Profite de cette journée entouré(e) de ceux que tu aimes.','',true,'christmas','tu','moyen'),
(NULL,'Modèle 3','Très joyeux Noël {prenom} ! Une belle occasion de partager des moments précieux.','',true,'christmas','tu','moyen'),
(NULL,'Modèle 1','Joyeux Noël {prenom} ! 🎄 Je te souhaite une journée remplie de joie, de douceur et de moments précieux avec ceux que tu aimes.','',true,'christmas','tu','long'),
(NULL,'Modèle 2','Joyeux Noël ! Cette période est idéale pour se retrouver et partager de beaux moments. Je te souhaite beaucoup de bonheur.','',true,'christmas','tu','long'),
(NULL,'Modèle 3','Très joyeux Noël {prenom} ! Que cette journée soit pleine de chaleur, de bonheur et de souvenirs précieux.','',true,'christmas','tu','long'),
(NULL,'Modèle 1','Joyeux Noël {prenom} ! 🎄','',true,'christmas','vous','court'),
(NULL,'Modèle 2','Très joyeux Noël !','',true,'christmas','vous','court'),
(NULL,'Modèle 3','Belles fêtes !','',true,'christmas','vous','court'),
(NULL,'Modèle 4','Joyeux Noël !','',true,'christmas','vous','court'),
(NULL,'Modèle 5','Profitez bien des fêtes !','',true,'christmas','vous','court'),
(NULL,'Modèle 6','Un très beau Noël !','',true,'christmas','vous','court'),
(NULL,'Modèle 7','Joyeuses fêtes 🎄','',true,'christmas','vous','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'christmas','vous','court'),
(NULL,'Modèle 9','Très belles fêtes !','',true,'christmas','vous','court'),
(NULL,'Modèle 10','Passez un bon Noël !','',true,'christmas','vous','court'),
(NULL,'Modèle 1','Je vous souhaite un joyeux Noël {prenom} 🎄 et une belle journée.','',true,'christmas','vous','moyen'),
(NULL,'Modèle 2','Joyeux Noël ! Je vous souhaite de beaux moments entouré(e)(s) de vos proches.','',true,'christmas','vous','moyen'),
(NULL,'Modèle 3','Très joyeux Noël {prenom} ! Une belle occasion de partager des instants précieux.','',true,'christmas','vous','moyen'),
(NULL,'Modèle 1','Je vous souhaite un joyeux Noël {prenom} 🎄 rempli de joie, de douceur et de moments partagés.','',true,'christmas','vous','long'),
(NULL,'Modèle 2','Joyeux Noël ! Que cette période vous apporte bonheur, sérénité et beaux moments.','',true,'christmas','vous','long'),
(NULL,'Modèle 3','Très joyeux Noël {prenom} ! Que cette journée soit pleine de chaleur et de moments précieux.','',true,'christmas','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- PÂQUES (easter)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Joyeuses Pâques {prenom} 🐣','',true,'easter','tu','court'),
(NULL,'Modèle 2','Très joyeuses Pâques !','',true,'easter','tu','court'),
(NULL,'Modèle 3','Bonne fête de Pâques !','',true,'easter','tu','court'),
(NULL,'Modèle 4','Joyeuses Pâques !','',true,'easter','tu','court'),
(NULL,'Modèle 5','Profite bien !','',true,'easter','tu','court'),
(NULL,'Modèle 6','Belle journée !','',true,'easter','tu','court'),
(NULL,'Modèle 7','Pâques 🎉','',true,'easter','tu','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'easter','tu','court'),
(NULL,'Modèle 9','Bonne journée !','',true,'easter','tu','court'),
(NULL,'Modèle 10','Joyeuses Pâques !','',true,'easter','tu','court'),
(NULL,'Modèle 1','Joyeuses Pâques {prenom} 🐣 Je te souhaite une belle journée pleine de douceur.','',true,'easter','tu','moyen'),
(NULL,'Modèle 2','Joyeuses Pâques ! Profite de cette journée agréable et gourmande.','',true,'easter','tu','moyen'),
(NULL,'Modèle 3','Très joyeuses Pâques {prenom} ! Une belle occasion de profiter.','',true,'easter','tu','moyen'),
(NULL,'Modèle 1','Joyeuses Pâques {prenom} 🐣 Je te souhaite une journée remplie de douceur, de joie et de moments agréables.','',true,'easter','tu','long'),
(NULL,'Modèle 2','Joyeuses Pâques ! Une belle journée pour se retrouver et profiter de bons moments.','',true,'easter','tu','long'),
(NULL,'Modèle 3','Très joyeuses Pâques {prenom} ! Que cette journée soit pleine de bonheur et de sérénité.','',true,'easter','tu','long'),
(NULL,'Modèle 1','Joyeuses Pâques {prenom} 🐣','',true,'easter','vous','court'),
(NULL,'Modèle 2','Très joyeuses Pâques !','',true,'easter','vous','court'),
(NULL,'Modèle 3','Bonne fête de Pâques !','',true,'easter','vous','court'),
(NULL,'Modèle 4','Joyeuses Pâques !','',true,'easter','vous','court'),
(NULL,'Modèle 5','Profitez bien !','',true,'easter','vous','court'),
(NULL,'Modèle 6','Belle journée !','',true,'easter','vous','court'),
(NULL,'Modèle 7','Pâques 🎉','',true,'easter','vous','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'easter','vous','court'),
(NULL,'Modèle 9','Bonne journée !','',true,'easter','vous','court'),
(NULL,'Modèle 10','Joyeuses Pâques !','',true,'easter','vous','court'),
(NULL,'Modèle 1','Je vous souhaite de joyeuses Pâques {prenom} 🐣 et une belle journée.','',true,'easter','vous','moyen'),
(NULL,'Modèle 2','Joyeuses Pâques ! Je vous souhaite une journée agréable.','',true,'easter','vous','moyen'),
(NULL,'Modèle 3','Très joyeuses Pâques {prenom} ! Profitez bien de cette journée.','',true,'easter','vous','moyen'),
(NULL,'Modèle 1','Je vous souhaite de joyeuses Pâques {prenom} 🐣 remplies de douceur et de moments agréables.','',true,'easter','vous','long'),
(NULL,'Modèle 2','Joyeuses Pâques ! Une belle journée pour se retrouver et profiter de moments précieux.','',true,'easter','vous','long'),
(NULL,'Modèle 3','Très joyeuses Pâques {prenom} ! Que cette journée soit pleine de sérénité et de bonheur.','',true,'easter','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- SAINT-VALENTIN (valentines)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Joyeuse Saint-Valentin ❤️','',true,'valentines','tu','court'),
(NULL,'Modèle 2','Je pense à toi 💛','',true,'valentines','tu','court'),
(NULL,'Modèle 3','Avec tout mon amour ❤️','',true,'valentines','tu','court'),
(NULL,'Modèle 4','Belle journée à toi !','',true,'valentines','tu','court'),
(NULL,'Modèle 5','Je t''aime ❤️','',true,'valentines','tu','court'),
(NULL,'Modèle 6','Joyeuse Saint-Valentin !','',true,'valentines','tu','court'),
(NULL,'Modèle 7','Une pensée pour toi','',true,'valentines','tu','court'),
(NULL,'Modèle 8','❤️','',true,'valentines','tu','court'),
(NULL,'Modèle 9','Très belle journée','',true,'valentines','tu','court'),
(NULL,'Modèle 10','Pour toi 💛','',true,'valentines','tu','court'),
(NULL,'Modèle 1','Joyeuse Saint-Valentin {prenom} ❤️ Je voulais te dire combien tu comptes pour moi.','',true,'valentines','tu','moyen'),
(NULL,'Modèle 2','Joyeuse Saint-Valentin ! Une belle occasion de te dire que je tiens à toi.','',true,'valentines','tu','moyen'),
(NULL,'Modèle 3','Joyeuse Saint-Valentin {prenom} ! Je te souhaite une journée pleine de douceur.','',true,'valentines','tu','moyen'),
(NULL,'Modèle 1','Joyeuse Saint-Valentin {prenom} ❤️ Je voulais te dire à quel point tu comptes pour moi. Je te souhaite une journée pleine de douceur et d''amour.','',true,'valentines','tu','long'),
(NULL,'Modèle 2','Joyeuse Saint-Valentin ! Une belle occasion de te rappeler combien tu es important(e) pour moi.','',true,'valentines','tu','long'),
(NULL,'Modèle 3','Joyeuse Saint-Valentin {prenom} ! Merci pour tout ce que tu apportes dans ma vie.','',true,'valentines','tu','long'),
(NULL,'Modèle 1','Belle Saint-Valentin ❤️','',true,'valentines','vous','court'),
(NULL,'Modèle 2','Une pensée pour vous','',true,'valentines','vous','court'),
(NULL,'Modèle 3','Très belle journée','',true,'valentines','vous','court'),
(NULL,'Modèle 4','❤️','',true,'valentines','vous','court'),
(NULL,'Modèle 5','Avec toute mon attention','',true,'valentines','vous','court'),
(NULL,'Modèle 6','Bonne Saint-Valentin','',true,'valentines','vous','court'),
(NULL,'Modèle 7','Belle journée à vous','',true,'valentines','vous','court'),
(NULL,'Modèle 8','Très belle fête','',true,'valentines','vous','court'),
(NULL,'Modèle 9','Je pense à vous','',true,'valentines','vous','court'),
(NULL,'Modèle 10','Belle occasion','',true,'valentines','vous','court'),
(NULL,'Modèle 1','Je vous souhaite une belle Saint-Valentin {prenom} ❤️','',true,'valentines','vous','moyen'),
(NULL,'Modèle 2','Joyeuse Saint-Valentin ! Une pensée pour vous aujourd''hui.','',true,'valentines','vous','moyen'),
(NULL,'Modèle 3','Très belle Saint-Valentin {prenom} ! Je vous souhaite une agréable journée.','',true,'valentines','vous','moyen'),
(NULL,'Modèle 1','Je vous souhaite une très belle Saint-Valentin {prenom} ❤️ pleine de douceur et de beaux moments.','',true,'valentines','vous','long'),
(NULL,'Modèle 2','Joyeuse Saint-Valentin ! Une belle occasion de partager des moments agréables.','',true,'valentines','vous','long'),
(NULL,'Modèle 3','Très belle Saint-Valentin {prenom} ! Que cette journée vous apporte joie et sérénité.','',true,'valentines','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- RETRAITE (retirement)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Félicitations pour ta retraite ! 🎉','',true,'retirement','tu','court'),
(NULL,'Modèle 2','Bravo pour cette étape !','',true,'retirement','tu','court'),
(NULL,'Modèle 3','Une nouvelle vie commence !','',true,'retirement','tu','court'),
(NULL,'Modèle 4','Profite bien !','',true,'retirement','tu','court'),
(NULL,'Modèle 5','Félicitations !','',true,'retirement','tu','court'),
(NULL,'Modèle 6','Place au repos !','',true,'retirement','tu','court'),
(NULL,'Modèle 7','Bravo 🎉','',true,'retirement','tu','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'retirement','tu','court'),
(NULL,'Modèle 9','Profite à fond !','',true,'retirement','tu','court'),
(NULL,'Modèle 10','Très belle retraite !','',true,'retirement','tu','court'),
(NULL,'Modèle 1','Félicitations pour ta retraite {prenom} ! Une belle nouvelle étape commence. Profite bien.','',true,'retirement','tu','moyen'),
(NULL,'Modèle 2','Félicitations ! Après tout ce travail, place au plaisir et aux projets.','',true,'retirement','tu','moyen'),
(NULL,'Modèle 3','Félicitations {prenom} ! Une nouvelle aventure commence. Profite bien.','',true,'retirement','tu','moyen'),
(NULL,'Modèle 1','Félicitations pour ta retraite {prenom} ! 🎉 Une belle étape commence après un parcours bien rempli. Profite pleinement de cette nouvelle vie.','',true,'retirement','tu','long'),
(NULL,'Modèle 2','Félicitations ! Il est temps de profiter de chaque moment et de réaliser tes envies.','',true,'retirement','tu','long'),
(NULL,'Modèle 3','Félicitations {prenom} ! Une nouvelle aventure commence. Je te souhaite beaucoup de bonheur.','',true,'retirement','tu','long'),
(NULL,'Modèle 1','Félicitations pour votre retraite ! 🎉','',true,'retirement','vous','court'),
(NULL,'Modèle 2','Bravo pour cette étape !','',true,'retirement','vous','court'),
(NULL,'Modèle 3','Une nouvelle vie commence !','',true,'retirement','vous','court'),
(NULL,'Modèle 4','Profitez bien !','',true,'retirement','vous','court'),
(NULL,'Modèle 5','Félicitations !','',true,'retirement','vous','court'),
(NULL,'Modèle 6','Place au repos !','',true,'retirement','vous','court'),
(NULL,'Modèle 7','Bravo 🎉','',true,'retirement','vous','court'),
(NULL,'Modèle 8','Que du bonheur !','',true,'retirement','vous','court'),
(NULL,'Modèle 9','Profitez à fond !','',true,'retirement','vous','court'),
(NULL,'Modèle 10','Très belle retraite !','',true,'retirement','vous','court'),
(NULL,'Modèle 1','Félicitations pour votre retraite {prenom} ! Une nouvelle étape commence. Profitez pleinement.','',true,'retirement','vous','moyen'),
(NULL,'Modèle 2','Félicitations ! Après votre parcours, place à une nouvelle vie.','',true,'retirement','vous','moyen'),
(NULL,'Modèle 3','Félicitations {prenom} ! Une nouvelle aventure s''ouvre à vous.','',true,'retirement','vous','moyen'),
(NULL,'Modèle 1','Félicitations pour votre retraite {prenom} ! 🎉 Une belle étape commence après un parcours riche. Profitez pleinement de cette nouvelle vie.','',true,'retirement','vous','long'),
(NULL,'Modèle 2','Félicitations ! Il est temps de profiter de chaque moment et de vos projets.','',true,'retirement','vous','long'),
(NULL,'Modèle 3','Félicitations {prenom} ! Une nouvelle aventure commence. Je vous souhaite beaucoup de bonheur.','',true,'retirement','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- SOUTIEN (support)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
(NULL,'Modèle 1','Je pense à toi 💛','',true,'support','tu','court'),
(NULL,'Modèle 2','Courage à toi','',true,'support','tu','court'),
(NULL,'Modèle 3','Je suis là','',true,'support','tu','court'),
(NULL,'Modèle 4','Toutes mes pensées','',true,'support','tu','court'),
(NULL,'Modèle 5','Je pense fort à toi','',true,'support','tu','court'),
(NULL,'Modèle 6','Prends soin de toi','',true,'support','tu','court'),
(NULL,'Modèle 7','Beaucoup de courage','',true,'support','tu','court'),
(NULL,'Modèle 8','Je suis avec toi','',true,'support','tu','court'),
(NULL,'Modèle 9','💛','',true,'support','tu','court'),
(NULL,'Modèle 10','Je t''envoie du soutien','',true,'support','tu','court'),
(NULL,'Modèle 1','Je pense fort à toi {prenom} 💛 Je suis là si tu en as besoin.','',true,'support','tu','moyen'),
(NULL,'Modèle 2','Toutes mes pensées t''accompagnent. Je t''envoie beaucoup de courage.','',true,'support','tu','moyen'),
(NULL,'Modèle 3','Je pense à toi {prenom} dans ce moment difficile. Tu n''es pas seul(e).','',true,'support','tu','moyen'),
(NULL,'Modèle 1','Je pense très fort à toi {prenom} 💛 Je sais que ce n''est pas facile. Je suis là si tu en ressens le besoin.','',true,'support','tu','long'),
(NULL,'Modèle 2','Toutes mes pensées t''accompagnent. Prends le temps qu''il te faut, je suis là.','',true,'support','tu','long'),
(NULL,'Modèle 3','Je pense à toi {prenom} dans cette période difficile. Je t''envoie tout mon soutien.','',true,'support','tu','long'),
(NULL,'Modèle 1','Je pense à vous','',true,'support','vous','court'),
(NULL,'Modèle 2','Courage à vous','',true,'support','vous','court'),
(NULL,'Modèle 3','Toutes mes pensées','',true,'support','vous','court'),
(NULL,'Modèle 4','Je suis avec vous','',true,'support','vous','court'),
(NULL,'Modèle 5','Soutien sincère','',true,'support','vous','court'),
(NULL,'Modèle 6','💛','',true,'support','vous','court'),
(NULL,'Modèle 7','Beaucoup de courage','',true,'support','vous','court'),
(NULL,'Modèle 8','Je vous soutiens','',true,'support','vous','court'),
(NULL,'Modèle 9','Pensées pour vous','',true,'support','vous','court'),
(NULL,'Modèle 10','Prenez soin de vous','',true,'support','vous','court'),
(NULL,'Modèle 1','Je pense à vous {prenom} dans cette période difficile. Je vous adresse tout mon soutien.','',true,'support','vous','moyen'),
(NULL,'Modèle 2','Toutes mes pensées vous accompagnent. Je vous souhaite beaucoup de courage.','',true,'support','vous','moyen'),
(NULL,'Modèle 3','Je pense à vous dans ce moment délicat. Je suis là si besoin.','',true,'support','vous','moyen'),
(NULL,'Modèle 1','Je pense sincèrement à vous {prenom} dans cette période difficile. Je vous adresse tout mon soutien.','',true,'support','vous','long'),
(NULL,'Modèle 2','Toutes mes pensées vous accompagnent. Je vous souhaite beaucoup de courage pour traverser cette épreuve.','',true,'support','vous','long'),
(NULL,'Modèle 3','Je pense à vous {prenom} dans ce moment délicat. Je reste disponible si besoin.','',true,'support','vous','long');
