-- Migration 049 : ajout modèles Halloween + Fête des Mères

-- ─────────────────────────────────────────────────────────────────────────────
-- HALLOWEEN (halloween)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
-- TU / COURT
(NULL,'Modèle 1','Joyeux Halloween {prenom} 🎃','',true,'halloween','tu','court'),
(NULL,'Modèle 2','Bonne soirée d''Halloween !','',true,'halloween','tu','court'),
(NULL,'Modèle 3','Profite bien de cette soirée 🎃','',true,'halloween','tu','court'),
(NULL,'Modèle 4','Joyeux Halloween !','',true,'halloween','tu','court'),
(NULL,'Modèle 5','Une soirée pleine de frissons 😄','',true,'halloween','tu','court'),
(NULL,'Modèle 6','Amuse-toi bien ce soir !','',true,'halloween','tu','court'),
(NULL,'Modèle 7','Happy Halloween 🎃','',true,'halloween','tu','court'),
(NULL,'Modèle 8','Une soirée fun en perspective !','',true,'halloween','tu','court'),
(NULL,'Modèle 9','Profite de cette ambiance 👻','',true,'halloween','tu','court'),
(NULL,'Modèle 10','Passe un super Halloween !','',true,'halloween','tu','court'),
-- TU / MOYEN
(NULL,'Modèle 1','Joyeux Halloween {prenom} 🎃 Profite bien de cette soirée pleine de surprises et de fun.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 2','Bonne soirée d''Halloween ! J''espère qu''elle sera remplie de rires et de bons moments.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 3','Joyeux Halloween ! Une soirée parfaite pour s''amuser et profiter.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 4','Très bon Halloween {prenom} ! Que ta soirée soit agréable et pleine de surprises.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 5','Joyeux Halloween 🎃 Profite bien de cette ambiance unique.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 6','Bonne soirée ! Que ce Halloween soit fun et agréable.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 7','Joyeux Halloween {prenom} ! Passe une excellente soirée.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 8','Une soirée spéciale pour s''amuser ! Joyeux Halloween 🎃','',true,'halloween','tu','moyen'),
(NULL,'Modèle 9','Profite bien de cette soirée pleine de surprises.','',true,'halloween','tu','moyen'),
(NULL,'Modèle 10','Joyeux Halloween ! Passe un très bon moment.','',true,'halloween','tu','moyen'),
-- TU / LONG
(NULL,'Modèle 1','Joyeux Halloween {prenom} 🎃 Je te souhaite une soirée pleine de surprises, de rires et de moments amusants. Profite bien de cette ambiance unique et de tout ce qui rend cette soirée différente.','',true,'halloween','tu','long'),
(NULL,'Modèle 2','Très bon Halloween ! C''est l''occasion parfaite pour s''amuser et passer un bon moment. J''espère que ta soirée sera remplie de rires et de bons souvenirs.','',true,'halloween','tu','long'),
(NULL,'Modèle 3','Joyeux Halloween {prenom} ! Que cette soirée soit à la fois amusante, surprenante et pleine de bons moments à partager.','',true,'halloween','tu','long'),
(NULL,'Modèle 4','Joyeux Halloween 🎃 Une soirée différente pour profiter, s''amuser et lâcher prise. Je te souhaite de passer un excellent moment.','',true,'halloween','tu','long'),
(NULL,'Modèle 5','Très bon Halloween ! Profite de cette soirée pour t''amuser et vivre de bons moments.','',true,'halloween','tu','long'),
(NULL,'Modèle 6','Joyeux Halloween {prenom} ! J''espère que ta soirée sera pleine de surprises et de moments agréables.','',true,'halloween','tu','long'),
(NULL,'Modèle 7','Joyeux Halloween 🎃 Une soirée idéale pour se détendre et profiter.','',true,'halloween','tu','long'),
(NULL,'Modèle 8','Très bon Halloween ! Je te souhaite une soirée fun et pleine de rires.','',true,'halloween','tu','long'),
(NULL,'Modèle 9','Joyeux Halloween {prenom} ! Profite bien de cette ambiance et de cette soirée.','',true,'halloween','tu','long'),
(NULL,'Modèle 10','Joyeux Halloween ! Passe une excellente soirée pleine de bons moments.','',true,'halloween','tu','long'),
-- VOUS / COURT
(NULL,'Modèle 1','Joyeux Halloween {prenom} 🎃','',true,'halloween','vous','court'),
(NULL,'Modèle 2','Bonne soirée d''Halloween !','',true,'halloween','vous','court'),
(NULL,'Modèle 3','Profitez bien de cette soirée 🎃','',true,'halloween','vous','court'),
(NULL,'Modèle 4','Joyeux Halloween !','',true,'halloween','vous','court'),
(NULL,'Modèle 5','Une soirée pleine de surprises','',true,'halloween','vous','court'),
(NULL,'Modèle 6','Très bon Halloween !','',true,'halloween','vous','court'),
(NULL,'Modèle 7','Happy Halloween 🎃','',true,'halloween','vous','court'),
(NULL,'Modèle 8','Passez une belle soirée','',true,'halloween','vous','court'),
(NULL,'Modèle 9','Profitez de cette ambiance 👻','',true,'halloween','vous','court'),
(NULL,'Modèle 10','Excellent Halloween !','',true,'halloween','vous','court'),
-- VOUS / MOYEN
(NULL,'Modèle 1','Joyeux Halloween {prenom} 🎃 Je vous souhaite une soirée pleine de surprises et de bons moments.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 2','Bonne soirée d''Halloween ! J''espère qu''elle sera agréable et festive.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 3','Joyeux Halloween ! Profitez pleinement de cette soirée.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 4','Très bon Halloween {prenom} ! Que votre soirée soit réussie.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 5','Joyeux Halloween 🎃 Profitez bien de cette ambiance unique.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 6','Bonne soirée ! Que ce Halloween soit agréable.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 7','Joyeux Halloween {prenom} ! Passez une excellente soirée.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 8','Une soirée spéciale pour profiter ! Joyeux Halloween 🎃','',true,'halloween','vous','moyen'),
(NULL,'Modèle 9','Profitez bien de cette soirée pleine de surprises.','',true,'halloween','vous','moyen'),
(NULL,'Modèle 10','Joyeux Halloween ! Je vous souhaite un bon moment.','',true,'halloween','vous','moyen'),
-- VOUS / LONG
(NULL,'Modèle 1','Joyeux Halloween {prenom} 🎃 Je vous souhaite une soirée pleine de surprises, de moments agréables et de bonne humeur. Profitez bien de cette ambiance particulière.','',true,'halloween','vous','long'),
(NULL,'Modèle 2','Très bon Halloween ! C''est une belle occasion de passer un moment agréable. Je vous souhaite une excellente soirée.','',true,'halloween','vous','long'),
(NULL,'Modèle 3','Joyeux Halloween {prenom} ! Que cette soirée soit plaisante et pleine de bons moments.','',true,'halloween','vous','long'),
(NULL,'Modèle 4','Joyeux Halloween 🎃 Je vous souhaite une soirée agréable et réussie.','',true,'halloween','vous','long'),
(NULL,'Modèle 5','Très bon Halloween ! Profitez bien de cette soirée.','',true,'halloween','vous','long'),
(NULL,'Modèle 6','Joyeux Halloween {prenom} ! J''espère que votre soirée sera agréable.','',true,'halloween','vous','long'),
(NULL,'Modèle 7','Joyeux Halloween 🎃 Une soirée pour profiter et se détendre.','',true,'halloween','vous','long'),
(NULL,'Modèle 8','Très bon Halloween ! Je vous souhaite une soirée agréable.','',true,'halloween','vous','long'),
(NULL,'Modèle 9','Joyeux Halloween {prenom} ! Profitez bien de ce moment.','',true,'halloween','vous','long'),
(NULL,'Modèle 10','Joyeux Halloween ! Passez une excellente soirée.','',true,'halloween','vous','long');

-- ─────────────────────────────────────────────────────────────────────────────
-- FÊTE DES MÈRES (mothersday)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO message_templates (user_id, title, content, tone, is_system, occasion, ton, longueur) VALUES
-- TU / COURT
(NULL,'Modèle 1','Bonne fête maman 💛','',true,'mothersday','tu','court'),
(NULL,'Modèle 2','Bonne fête {prenom} !','',true,'mothersday','tu','court'),
(NULL,'Modèle 3','Une très belle fête à toi','',true,'mothersday','tu','court'),
(NULL,'Modèle 4','Bonne fête !','',true,'mothersday','tu','court'),
(NULL,'Modèle 5','Je pense à toi aujourd''hui 💛','',true,'mothersday','tu','court'),
(NULL,'Modèle 6','Belle fête des mères','',true,'mothersday','tu','court'),
(NULL,'Modèle 7','Bonne fête maman ❤️','',true,'mothersday','tu','court'),
(NULL,'Modèle 8','Profite bien de ta journée','',true,'mothersday','tu','court'),
(NULL,'Modèle 9','Bonne fête !','',true,'mothersday','tu','court'),
(NULL,'Modèle 10','Une pensée pour toi aujourd''hui','',true,'mothersday','tu','court'),
-- TU / MOYEN
(NULL,'Modèle 1','Bonne fête maman 💛 Je te souhaite une très belle journée remplie de douceur.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 2','Bonne fête {prenom} ! Merci pour tout ce que tu fais au quotidien.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 3','Bonne fête ! Une belle occasion de te dire merci.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 4','Bonne fête maman ❤️ Profite bien de ta journée.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 5','Bonne fête {prenom} ! Je te souhaite beaucoup de bonheur aujourd''hui.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 6','Bonne fête ! Une pensée pour toi en ce jour spécial.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 7','Bonne fête maman 💛 Merci pour ton amour.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 8','Bonne fête {prenom} ! Je te souhaite une journée agréable.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 9','Bonne fête ! Profite bien de ce moment.','',true,'mothersday','tu','moyen'),
(NULL,'Modèle 10','Bonne fête maman ! Je te souhaite plein de beaux moments.','',true,'mothersday','tu','moyen'),
-- TU / LONG
(NULL,'Modèle 1','Bonne fête maman 💛 Je voulais prendre un moment pour te dire combien tu es importante pour moi. Merci pour tout ton amour et tout ce que tu fais. Je te souhaite une journée douce et pleine de bonheur.','',true,'mothersday','tu','long'),
(NULL,'Modèle 2','Bonne fête {prenom} ! C''est une belle occasion de te dire merci pour tout ce que tu apportes. Je te souhaite une très belle journée.','',true,'mothersday','tu','long'),
(NULL,'Modèle 3','Bonne fête ! Une journée spéciale pour te rappeler combien tu comptes. Je te souhaite beaucoup de bonheur.','',true,'mothersday','tu','long'),
(NULL,'Modèle 4','Bonne fête maman ❤️ Merci pour ton soutien et ta présence. Je te souhaite une journée pleine de douceur.','',true,'mothersday','tu','long'),
(NULL,'Modèle 5','Bonne fête {prenom} ! Je te souhaite une journée remplie de moments agréables.','',true,'mothersday','tu','long'),
(NULL,'Modèle 6','Bonne fête ! Une pensée pour toi avec beaucoup d''affection.','',true,'mothersday','tu','long'),
(NULL,'Modèle 7','Bonne fête maman 💛 Je te souhaite beaucoup de bonheur aujourd''hui.','',true,'mothersday','tu','long'),
(NULL,'Modèle 8','Bonne fête {prenom} ! Merci pour tout ce que tu fais.','',true,'mothersday','tu','long'),
(NULL,'Modèle 9','Bonne fête ! Une journée pour te faire plaisir.','',true,'mothersday','tu','long'),
(NULL,'Modèle 10','Bonne fête maman ! Je te souhaite une très belle journée.','',true,'mothersday','tu','long'),
-- VOUS / COURT
(NULL,'Modèle 1','Bonne fête {prenom} !','',true,'mothersday','vous','court'),
(NULL,'Modèle 2','Très belle fête à vous','',true,'mothersday','vous','court'),
(NULL,'Modèle 3','Bonne fête !','',true,'mothersday','vous','court'),
(NULL,'Modèle 4','Une pensée pour vous','',true,'mothersday','vous','court'),
(NULL,'Modèle 5','Belle fête des mères','',true,'mothersday','vous','court'),
(NULL,'Modèle 6','Bonne fête !','',true,'mothersday','vous','court'),
(NULL,'Modèle 7','Je vous souhaite une belle journée','',true,'mothersday','vous','court'),
(NULL,'Modèle 8','Bonne fête {prenom}','',true,'mothersday','vous','court'),
(NULL,'Modèle 9','Profitez bien de cette journée','',true,'mothersday','vous','court'),
(NULL,'Modèle 10','Bonne fête !','',true,'mothersday','vous','court'),
-- VOUS / MOYEN
(NULL,'Modèle 1','Bonne fête {prenom} ! Je vous souhaite une très belle journée.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 2','Bonne fête ! Une pensée pour vous aujourd''hui.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 3','Bonne fête {prenom} ! Merci pour tout ce que vous faites.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 4','Bonne fête ! Je vous souhaite beaucoup de bonheur.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 5','Bonne fête {prenom} ! Profitez bien de cette journée.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 6','Bonne fête ! Je vous souhaite une journée agréable.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 7','Bonne fête {prenom} ! Une belle journée à vous.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 8','Bonne fête ! Je vous adresse mes pensées.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 9','Bonne fête {prenom} ! Je vous souhaite de beaux moments.','',true,'mothersday','vous','moyen'),
(NULL,'Modèle 10','Bonne fête ! Profitez bien de cette journée.','',true,'mothersday','vous','moyen'),
-- VOUS / LONG
(NULL,'Modèle 1','Bonne fête {prenom} ! Je vous souhaite une très belle journée remplie de douceur et de moments agréables. Profitez pleinement de cette occasion.','',true,'mothersday','vous','long'),
(NULL,'Modèle 2','Bonne fête ! Une journée spéciale pour vous dire merci. Je vous souhaite beaucoup de bonheur.','',true,'mothersday','vous','long'),
(NULL,'Modèle 3','Bonne fête {prenom} ! Je vous remercie pour tout ce que vous faites. Je vous souhaite une belle journée.','',true,'mothersday','vous','long'),
(NULL,'Modèle 4','Bonne fête ! Je vous adresse mes pensées en cette journée particulière.','',true,'mothersday','vous','long'),
(NULL,'Modèle 5','Bonne fête {prenom} ! Je vous souhaite de beaux moments aujourd''hui.','',true,'mothersday','vous','long'),
(NULL,'Modèle 6','Bonne fête ! Une belle journée à vous.','',true,'mothersday','vous','long'),
(NULL,'Modèle 7','Bonne fête {prenom} ! Je vous souhaite une journée agréable.','',true,'mothersday','vous','long'),
(NULL,'Modèle 8','Bonne fête ! Profitez bien de cette journée.','',true,'mothersday','vous','long'),
(NULL,'Modèle 9','Bonne fête {prenom} ! Je vous adresse mes meilleurs vœux.','',true,'mothersday','vous','long'),
(NULL,'Modèle 10','Bonne fête ! Je vous souhaite une très belle journée.','',true,'mothersday','vous','long');
