-- Migration 051 : Mariage (wedding) — 60 messages haute qualité

-- tu / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('wedding','tu','court','Félicitations pour votre mariage ! 💍','Félicitations pour votre mariage ! 💍',true),
('wedding','tu','court','Que votre amour soit aussi fort','Que votre amour soit aussi fort que votre engagement aujourd''hui.',true),
('wedding','tu','court','Bonne route à vous deux !','Un grand jour pour une grande histoire. Bonne route à vous deux !',true),
('wedding','tu','court','Le début d''une vie remplie de bonheur','Que ce mariage soit le début d''une vie remplie de bonheur.',true),
('wedding','tu','court','Que votre amour dure à jamais !','Félicitations, et que votre amour dure à jamais !',true),
('wedding','tu','court','L''union de deux cœurs','Un mariage, c''est l''union de deux cœurs… et le début d''une belle aventure !',true),
('wedding','tu','court','Aussi magique que votre amour','Que cette journée soit aussi magique que votre amour.',true),
('wedding','tu','court','Aussi belle que ce jour','Félicitations ! Que votre vie à deux soit aussi belle que ce jour.',true),
('wedding','tu','court','Comme un conte de fées 🏰','Un mariage, c''est comme un conte de fées… mais en vrai ! 🏰',true),
('wedding','tu','court','Votre plus grande force','Que votre amour soit votre plus grande force. Félicitations !',true);

-- tu / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('wedding','tu','moyen','Vous formez un couple magnifique','Félicitations pour votre mariage ! Que cette journée soit le début d''une vie remplie d''amour, de complicité et de bonheur. Vous formez un couple magnifique, et nous vous souhaitons tout le meilleur pour cette nouvelle aventure.',true),
('wedding','tu','moyen','Aussi solide que vos vœux','Que votre amour soit aussi solide que les vœux que vous vous êtes échangés aujourd''hui. Félicitations, et que chaque jour de votre vie commune soit aussi beau que ce moment.',true),
('wedding','tu','moyen','La promesse d''une vie partagée','Un mariage, c''est bien plus qu''une cérémonie : c''est la promesse d''une vie partagée, remplie de rires, de défis et de tendresse. Bonne route à vous deux !',true),
('wedding','tu','moyen','Une histoire d''amour éternelle','Que cette journée reste gravée dans vos mémoires comme le début d''une histoire d''amour éternelle. Félicitations, et que votre vie à deux soit aussi lumineuse que votre sourire aujourd''hui.',true),
('wedding','tu','moyen','Aussi belle que ce jour','Vous avez choisi de partager votre vie, et nous espérons qu''elle sera aussi belle que ce jour. Félicitations pour votre mariage !',true),
('wedding','tu','moyen','Comme un bon vin','Que votre amour grandisse avec le temps, comme un bon vin. Félicitations, et que chaque année soit meilleure que la précédente.',true),
('wedding','tu','moyen','Des chapitres heureux','Un mariage, c''est l''union de deux âmes pour écrire une histoire commune. Nous vous souhaitons une vie remplie de chapitres heureux.',true),
('wedding','tu','moyen','Une aventure merveilleuse','Que cette journée soit aussi joyeuse que votre amour est profond. Félicitations, et que votre vie à deux soit une aventure merveilleuse.',true),
('wedding','tu','moyen','Le monde entier célèbre avec vous','Vous vous êtes dit "oui", et aujourd''hui, le monde entier semble célébrer avec vous. Que votre amour soit aussi infini que votre bonheur.',true),
('wedding','tu','moyen','Amour inconditionnel','Félicitations pour ce grand jour ! Que votre mariage soit le début d''une vie remplie de complicité, de respect et d''amour inconditionnel.',true);

-- tu / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('wedding','tu','long','Vous avez choisi de lier vos vies','Félicitations pour votre mariage ! Aujourd''hui, vous avez choisi de lier vos vies, et nous ne pourrions être plus heureux pour vous. Que cette journée soit le début d''une aventure remplie d''amour, de respect et de complicité. Vous formez un couple incroyable, et nous savons que votre histoire sera aussi belle que ce jour. Que chaque instant de votre vie commune soit une nouvelle raison de sourire, et que votre amour grandisse avec le temps, comme une flamme qui ne s''éteint jamais. Bonne route à vous deux !',true),
('wedding','tu','long','Le point de départ d''une vie à deux','Que votre mariage soit bien plus qu''un simple jour : qu''il soit le point de départ d''une vie à deux aussi riche que vos rêves. Vous avez choisi de partager votre chemin, et nous espérons qu''il sera rempli de joie, de tendresse et de moments inoubliables. Félicitations, et que votre amour soit aussi solide que les vœux que vous vous êtes échangés aujourd''hui.',true),
('wedding','tu','long','Une promesse de bonheur','Aujourd''hui, vous avez dit "oui" l''un à l''autre, et ce mot résonne comme une promesse de bonheur. Que votre mariage soit le début d''une histoire d''amour aussi profonde que votre engagement. Nous vous souhaitons une vie remplie de rires, de défis relevés ensemble, et de cette complicité qui fait des couples comme le vôtre une source d''inspiration. Félicitations !',true),
('wedding','tu','long','Construire un avenir commun','Un mariage, c''est l''union de deux personnes qui décident de construire un avenir commun. Que votre vie à deux soit aussi belle que cette journée, aussi forte que votre amour, et aussi lumineuse que vos sourires. Nous sommes si heureux de faire partie de ce moment si spécial pour vous. Que chaque année qui passe renforce votre lien et vous apporte encore plus de bonheur.',true),
('wedding','tu','long','Une célébration de l''amour','Félicitations pour ce jour si important ! Votre mariage est une célébration de l''amour, de la confiance et de l''engagement. Que votre vie commune soit aussi riche en émotions que cette journée l''a été. Nous vous souhaitons une aventure remplie de succès, de joie et de moments partagés avec ceux qui vous aiment. Que votre amour soit votre guide, et votre bonheur, votre plus grande réussite.',true),
('wedding','tu','long','Une nouvelle page de bonheur','Aujourd''hui, vous avez uni vos vies, et nous savons que cette décision apportera à chacun de vous encore plus de bonheur. Que votre mariage soit le début d''une histoire remplie de tendresse, de respect et de complicité. Félicitations, et que chaque jour de votre vie à deux soit une nouvelle page de bonheur.',true),
('wedding','tu','long','Aussi inspirante que ce moment','Que cette journée reste à jamais gravée dans vos cœurs comme le début d''une vie commune aussi belle que votre amour. Vous formez un couple exceptionnel, et nous espérons que votre histoire sera aussi inspirante que ce moment. Félicitations pour votre mariage, et que votre amour soit aussi éternel que vos souvenirs d''aujourd''hui.',true),
('wedding','tu','long','Vous partez ensemble en voyage','Un mariage, c''est comme un voyage : vous partez ensemble, avec vos rêves, vos espoirs et votre amour comme bagages. Que cette aventure soit aussi passionnante que vous l''imaginez, et que chaque étape vous rapproche encore plus l''un de l''autre. Félicitations, et que votre vie à deux soit aussi magique que ce jour.',true),
('wedding','tu','long','Nous célébrons ce choix avec vous','Vous avez choisi de partager votre vie, et aujourd''hui, nous célébrons ce choix avec vous. Que votre mariage soit le début d''une histoire remplie de bonheur, de succès et de moments précieux. Félicitations, et que votre amour soit aussi fort que les liens qui vous unissent.',true),
('wedding','tu','long','Aussi unique que votre amour','Que votre mariage soit le début d''une vie aussi belle que vos rêves. Vous formez un couple admirable, et nous savons que votre histoire sera aussi unique que votre amour. Félicitations, et que chaque jour de votre vie commune soit une nouvelle raison de célébrer.',true);

-- vous / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('wedding','vous','court','Félicitations pour votre mariage !','Félicitations pour votre mariage !',true),
('wedding','vous','court','Que votre amour soit aussi fort','Que votre amour soit aussi fort que votre engagement aujourd''hui.',true),
('wedding','vous','court','Bonne route à vous deux','Un grand jour pour une grande histoire. Bonne route à vous deux.',true),
('wedding','vous','court','Le début d''une vie remplie de bonheur','Que ce mariage soit le début d''une vie remplie de bonheur.',true),
('wedding','vous','court','Que votre amour dure à jamais','Félicitations, et que votre amour dure à jamais.',true),
('wedding','vous','court','L''union de deux cœurs','Un mariage, c''est l''union de deux cœurs… et le début d''une belle aventure.',true),
('wedding','vous','court','Aussi magique que votre amour','Que cette journée soit aussi magique que votre amour.',true),
('wedding','vous','court','Aussi belle que ce jour','Félicitations ! Que votre vie à deux soit aussi belle que ce jour.',true),
('wedding','vous','court','Un engagement pour la vie','Un mariage, c''est un engagement pour la vie. Nous vous souhaitons tout le bonheur possible.',true),
('wedding','vous','court','Votre plus grande force','Que votre amour soit votre plus grande force. Félicitations !',true);

-- vous / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('wedding','vous','moyen','Vous formez un couple admirable','Félicitations pour votre mariage ! Que cette journée soit le début d''une vie remplie d''amour, de complicité et de bonheur. Vous formez un couple admirable, et nous vous souhaitons tout le meilleur pour cette nouvelle aventure.',true),
('wedding','vous','moyen','Aussi solide que vos vœux','Que votre amour soit aussi solide que les vœux que vous vous êtes échangés aujourd''hui. Félicitations, et que chaque jour de votre vie commune soit aussi beau que ce moment.',true),
('wedding','vous','moyen','La promesse d''une vie partagée','Un mariage, c''est bien plus qu''une cérémonie : c''est la promesse d''une vie partagée, remplie de rires, de défis et de tendresse. Bonne route à vous deux.',true),
('wedding','vous','moyen','Une histoire d''amour éternelle','Que cette journée reste gravée dans vos mémoires comme le début d''une histoire d''amour éternelle. Félicitations, et que votre vie à deux soit aussi lumineuse que votre sourire aujourd''hui.',true),
('wedding','vous','moyen','Aussi belle que ce jour','Vous avez choisi de partager votre vie, et nous espérons qu''elle sera aussi belle que ce jour. Félicitations pour votre mariage.',true),
('wedding','vous','moyen','Comme un trésor précieux','Que votre amour grandisse avec le temps, comme un trésor précieux. Félicitations, et que chaque année soit meilleure que la précédente.',true),
('wedding','vous','moyen','Des chapitres heureux','Un mariage, c''est l''union de deux âmes pour écrire une histoire commune. Nous vous souhaitons une vie remplie de chapitres heureux.',true),
('wedding','vous','moyen','Une aventure merveilleuse','Que cette journée soit aussi joyeuse que votre amour est profond. Félicitations, et que votre vie à deux soit une aventure merveilleuse.',true),
('wedding','vous','moyen','Le monde entier célèbre avec vous','Vous vous êtes dit "oui", et aujourd''hui, le monde entier semble célébrer avec vous. Que votre amour soit aussi infini que votre bonheur.',true),
('wedding','vous','moyen','Amour inconditionnel','Félicitations pour ce grand jour ! Que votre mariage soit le début d''une vie remplie de complicité, de respect et d''amour inconditionnel.',true);

-- vous / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('wedding','vous','long','Vous avez choisi de lier vos vies','Félicitations pour votre mariage ! Aujourd''hui, vous avez choisi de lier vos vies, et nous ne pourrions être plus heureux pour vous. Que cette journée soit le début d''une aventure remplie d''amour, de respect et de complicité. Vous formez un couple admirable, et nous savons que votre histoire sera aussi belle que ce jour. Que chaque instant de votre vie commune soit une nouvelle raison de sourire, et que votre amour grandisse avec le temps, comme une flamme qui ne s''éteint jamais. Bonne route à vous deux !',true),
('wedding','vous','long','Le point de départ d''une vie à deux','Que votre mariage soit bien plus qu''un simple jour : qu''il soit le point de départ d''une vie à deux aussi riche que vos rêves. Vous avez choisi de partager votre chemin, et nous espérons qu''il sera rempli de joie, de tendresse et de moments inoubliables. Félicitations, et que votre amour soit aussi solide que les vœux que vous vous êtes échangés aujourd''hui.',true),
('wedding','vous','long','Une promesse de bonheur','Aujourd''hui, vous avez dit "oui" l''un à l''autre, et ce mot résonne comme une promesse de bonheur. Que votre mariage soit le début d''une histoire d''amour aussi profonde que votre engagement. Nous vous souhaitons une vie remplie de rires, de défis relevés ensemble, et de cette complicité qui fait des couples comme le vôtre une source d''inspiration. Félicitations !',true),
('wedding','vous','long','Construire un avenir commun','Un mariage, c''est l''union de deux personnes qui décident de construire un avenir commun. Que votre vie à deux soit aussi belle que cette journée, aussi forte que votre amour, et aussi lumineuse que vos sourires. Nous sommes si heureux de faire partie de ce moment si spécial pour vous. Que chaque année qui passe renforce votre lien et vous apporte encore plus de bonheur.',true),
('wedding','vous','long','Une célébration de l''amour','Félicitations pour ce jour si important ! Votre mariage est une célébration de l''amour, de la confiance et de l''engagement. Que votre vie commune soit aussi riche en émotions que cette journée l''a été. Nous vous souhaitons une aventure remplie de succès, de joie et de moments partagés avec ceux qui vous aiment. Que votre amour soit votre guide, et votre bonheur, votre plus grande réussite.',true),
('wedding','vous','long','Une nouvelle page de bonheur','Aujourd''hui, vous avez uni vos vies, et nous savons que cette décision apportera à chacun de vous encore plus de bonheur. Que votre mariage soit le début d''une histoire remplie de tendresse, de respect et de complicité. Félicitations, et que chaque jour de votre vie à deux soit une nouvelle page de bonheur.',true),
('wedding','vous','long','Aussi inspirante que ce moment','Que cette journée reste à jamais gravée dans vos cœurs comme le début d''une vie commune aussi belle que votre amour. Vous formez un couple exceptionnel, et nous espérons que votre histoire sera aussi inspirante que ce moment. Félicitations pour votre mariage, et que votre amour soit aussi éternel que vos souvenirs d''aujourd''hui.',true),
('wedding','vous','long','Vous partez ensemble en voyage','Un mariage, c''est comme un voyage : vous partez ensemble, avec vos rêves, vos espoirs et votre amour comme bagages. Que cette aventure soit aussi passionnante que vous l''imaginez, et que chaque étape vous rapproche encore plus l''un de l''autre. Félicitations, et que votre vie à deux soit aussi magique que ce jour.',true),
('wedding','vous','long','Nous célébrons ce choix avec vous','Vous avez choisi de partager votre vie, et aujourd''hui, nous célébrons ce choix avec vous. Que votre mariage soit le début d''une histoire remplie de bonheur, de succès et de moments précieux. Félicitations, et que votre amour soit aussi fort que les liens qui vous unissent.',true),
('wedding','vous','long','Aussi unique que votre amour','Que votre mariage soit le début d''une vie aussi belle que vos rêves. Vous formez un couple admirable, et nous savons que votre histoire sera aussi unique que votre amour. Félicitations, et que chaque jour de votre vie commune soit une nouvelle raison de célébrer.',true);
