-- Migration 054 : Communion + Diplôme + Promotion — 180 messages haute qualité
-- Remplace les templates de base de la migration 048/050

DELETE FROM message_templates WHERE occasion IN ('communion','graduation','promotion') AND is_system = true;

-- ============================================================
-- COMMUNION
-- ============================================================

-- tu / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('communion','tu','court','Félicitations pour ta communion ! 🕯️','Félicitations pour ta communion ! 🕯️',true),
('communion','tu','court','Aussi lumineux que ta foi','Que ce jour soit aussi lumineux que ta foi.',true),
('communion','tu','court','Bienvenue à la table du Seigneur !','Bienvenue à la table du Seigneur !',true),
('communion','tu','court','Une source de grâce et de paix','Que cette communion soit une source de grâce et de paix.',true),
('communion','tu','court','Un jour spécial pour une étape importante','Un jour spécial pour une étape importante. Bravo !',true),
('communion','tu','court','Que ce moment reste gravé dans ton cœur','Que ce moment reste gravé dans ton cœur.',true),
('communion','tu','court','Félicitations pour cette belle célébration !','Félicitations pour cette belle célébration !',true),
('communion','tu','court','L''amour et la foi réunis','La communion, c''est l''amour et la foi réunis.',true),
('communion','tu','court','Que ce jour soit rempli de bénédictions','Que ce jour soit rempli de bénédictions.',true),
('communion','tu','court','Un pas de plus dans ta vie spirituelle','Un pas de plus dans ta vie spirituelle. Félicitations !',true);

-- tu / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('communion','tu','moyen','Rempli de joie, de paix et de grâce','Félicitations pour ta communion ! Que ce jour soit rempli de joie, de paix et de grâce. C''est une étape importante dans ta vie spirituelle, et nous sommes si fiers de toi.',true),
('communion','tu','moyen','Aussi beau que ton cœur','La communion, c''est bien plus qu''une cérémonie : c''est un engagement envers ta foi et ta communauté. Que ce jour soit aussi beau que ton cœur.',true),
('communion','tu','moyen','Aussi riche que ton amour pour Dieu','Que cette communion marque le début d''une vie spirituelle aussi riche que ton amour pour Dieu. Félicitations pour cette belle étape !',true),
('communion','tu','moyen','Le début d''une aventure remplie de lumière','Aujourd''hui, tu as reçu une bénédiction spéciale. Que cette communion soit le début d''une aventure remplie de lumière et de sens.',true),
('communion','tu','moyen','Aussi précieux que ta foi','Un moment sacré pour une personne spéciale. Que ce jour de communion soit aussi précieux que ta foi.',true),
('communion','tu','moyen','Une source de force et de réconfort','Que cette communion soit une source de force et de réconfort pour toi tout au long de ta vie. Félicitations pour cette belle célébration !',true),
('communion','tu','moyen','Aussi joyeux que ton engagement','Bienvenue à la table du Seigneur. Que ce jour soit aussi joyeux que ton engagement envers ta foi.',true),
('communion','tu','moyen','Une lumière sur ton chemin spirituel','Félicitations pour ce moment si important ! Que cette communion soit une lumière sur ton chemin spirituel.',true),
('communion','tu','moyen','Aussi pur que ton cœur','Que ce jour de communion soit aussi lumineux que ton sourire et aussi pur que ton cœur. Toutes nos félicitations !',true),
('communion','tu','moyen','Aussi beau que ton âme','La communion, c''est un engagement envers la foi, l''amour et la communauté. Que ce jour soit aussi beau que ton âme.',true);

-- tu / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('communion','tu','long','Un pas de plus dans ta vie spirituelle','Félicitations pour ta communion ! Aujourd''hui, tu as fait un pas de plus dans ta vie spirituelle, et nous ne pourrions être plus fiers de toi. Que ce jour soit le début d''une aventure remplie de grâce, de paix et de joie. La communion, c''est comme une lumière qui éclaire ton chemin, et nous savons que tu vas continuer à grandir dans la foi et l''amour. Que chaque étape de ta vie spirituelle soit aussi belle que ce moment, et que ton engagement envers Dieu soit aussi fort que ton cœur.',true),
('communion','tu','long','Aussi riche que ton amour pour Dieu','La communion, c''est une journée remplie de sens et d''émotion. Aujourd''hui, tu as choisi de t''engager davantage dans ta foi, et nous espérons que cette étape sera aussi riche que ton amour pour Dieu. Que ce jour reste gravé dans ton cœur comme le début d''une aventure spirituelle aussi inspirante que ta personnalité. Félicitations, et que chaque moment de ta vie soit aussi précieux que cette cérémonie.',true),
('communion','tu','long','Une promesse de grandir dans la foi','Aujourd''hui, tu as reçu une bénédiction qui t''accompagnera toute ta vie. La communion, c''est comme une promesse : celle de grandir dans la foi, l''espoir et l''amour. Que ce jour soit aussi joyeux que ton sourire, aussi pur que ton cœur, et aussi lumineux que ton engagement spirituel. Félicitations pour cette belle étape, et que ta vie soit aussi merveilleuse que tes rêves.',true),
('communion','tu','long','Aimé, protégé et guidé par Dieu','La communion, c''est bien plus qu''une tradition : c''est un acte d''amour et de foi qui marque une étape importante dans ta vie. Que tu grandisses avec la certitude d''être aimé, protégé et guidé par Dieu. Félicitations pour ce moment si spécial, et que chaque jour de ta vie soit une nouvelle raison de célébrer la beauté de la foi.',true),
('communion','tu','long','Une graine plantée dans ton cœur','Aujourd''hui, tu as partagé un moment sacré avec ta communauté, et nous sommes si heureux pour toi. La communion, c''est comme une graine que tu as plantée dans ton cœur : elle grandira avec la foi, l''espoir et l''amour que tu lui donneras. Que ce jour soit aussi lumineux que ton amour pour Dieu, et que ta vie spirituelle soit aussi belle que tes rêves.',true),
('communion','tu','long','La mission de continuer à grandir dans la foi','Félicitations pour ta communion ! Que ce jour soit le début d''une aventure remplie de grâce, de joie et de découvertes spirituelles. Tu as maintenant la mission de continuer à grandir dans la foi, et nous savons que tu seras à la hauteur. Que chaque instant de ta vie spirituelle soit aussi précieux que ce moment, et que ton amour pour Dieu soit aussi fort que ta détermination.',true),
('communion','tu','long','Grandir dans un monde rempli de sens','La communion, c''est un engagement envers la vie, envers l''amour et envers la foi. Aujourd''hui, tu as montré à quel point ta spiritualité compte pour toi, et à quel point tu veux grandir dans un monde rempli de sens. Que ce jour soit aussi beau que ton cœur, et que ta vie spirituelle soit aussi riche que ton amour pour Dieu.',true),
('communion','tu','long','Faire partie d''une communauté aimante','Que cette communion soit une source de force et d''inspiration pour toi tout au long de ta vie. Aujourd''hui, tu as reçu un cadeau précieux : celui de faire partie d''une communauté aimante et bienveillante. Félicitations pour cette belle cérémonie, et que chaque étape de ta vie spirituelle soit aussi lumineuse que ce jour.',true),
('communion','tu','long','Un phare dans la nuit','Aujourd''hui, tu as reçu une bénédiction qui t''accompagnera à jamais. La communion, c''est comme un phare dans la nuit : elle éclaire ton chemin et te rappelle que tu n''es jamais seul. Que ce jour soit aussi joyeux que ton amour pour Dieu, et que ta vie spirituelle soit aussi belle que tes espérances.',true),
('communion','tu','long','Aussi infini que ta joie aujourd''hui','Félicitations pour ce moment si important dans ta vie spirituelle ! La communion, c''est une célébration de l''amour, de la foi et de l''espoir. Que ce jour reste gravé dans ton cœur comme le début d''une aventure aussi belle que ton engagement envers Dieu. Que chaque instant de ta vie spirituelle soit une nouvelle raison de sourire, et que ton amour pour Lui soit aussi infini que ta joie aujourd''hui.',true);

-- vous / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('communion','vous','court','Félicitations pour votre communion !','Félicitations pour votre communion !',true),
('communion','vous','court','Aussi lumineux que votre foi','Que ce jour soit aussi lumineux que votre foi.',true),
('communion','vous','court','Bienvenue à la table du Seigneur','Bienvenue à la table du Seigneur.',true),
('communion','vous','court','Une source de grâce et de paix','Que cette communion soit une source de grâce et de paix.',true),
('communion','vous','court','Un jour spécial pour une étape importante','Un jour spécial pour une étape importante. Bravo.',true),
('communion','vous','court','Que ce moment reste gravé dans votre cœur','Que ce moment reste gravé dans votre cœur.',true),
('communion','vous','court','Félicitations pour cette belle célébration','Félicitations pour cette belle célébration.',true),
('communion','vous','court','L''amour et la foi réunis','La communion, c''est l''amour et la foi réunis.',true),
('communion','vous','court','Que ce jour soit rempli de bénédictions','Que ce jour soit rempli de bénédictions.',true),
('communion','vous','court','Un pas de plus dans votre vie spirituelle','Un pas de plus dans votre vie spirituelle. Félicitations.',true);

-- vous / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('communion','vous','moyen','Rempli de joie, de paix et de grâce','Félicitations pour votre communion ! Que ce jour soit rempli de joie, de paix et de grâce. C''est une étape importante dans votre vie spirituelle, et nous sommes si fiers de vous.',true),
('communion','vous','moyen','Aussi beau que votre cœur','La communion, c''est bien plus qu''une cérémonie : c''est un engagement envers votre foi et votre communauté. Que ce jour soit aussi beau que votre cœur.',true),
('communion','vous','moyen','Aussi riche que votre amour pour Dieu','Que cette communion marque le début d''une vie spirituelle aussi riche que votre amour pour Dieu. Félicitations pour cette belle étape !',true),
('communion','vous','moyen','Le début d''une aventure remplie de lumière','Aujourd''hui, vous avez reçu une bénédiction spéciale. Que cette communion soit le début d''une aventure remplie de lumière et de sens.',true),
('communion','vous','moyen','Aussi précieux que votre foi','Un moment sacré pour une personne spéciale. Que ce jour de communion soit aussi précieux que votre foi.',true),
('communion','vous','moyen','Une source de force et de réconfort','Que cette communion soit une source de force et de réconfort pour vous tout au long de votre vie. Félicitations pour cette belle célébration !',true),
('communion','vous','moyen','Aussi joyeux que votre engagement','Bienvenue à la table du Seigneur. Que ce jour soit aussi joyeux que votre engagement envers votre foi.',true),
('communion','vous','moyen','Une lumière sur votre chemin spirituel','Félicitations pour ce moment si important ! Que cette communion soit une lumière sur votre chemin spirituel.',true),
('communion','vous','moyen','Aussi pur que votre cœur','Que ce jour de communion soit aussi lumineux que votre sourire et aussi pur que votre cœur. Toutes nos félicitations !',true),
('communion','vous','moyen','Aussi beau que votre âme','La communion, c''est un engagement envers la foi, l''amour et la communauté. Que ce jour soit aussi beau que votre âme.',true);

-- vous / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('communion','vous','long','Un pas de plus dans votre vie spirituelle','Félicitations pour votre communion ! Aujourd''hui, vous avez fait un pas de plus dans votre vie spirituelle, et nous ne pourrions être plus fiers de vous. Que ce jour soit le début d''une aventure remplie de grâce, de paix et de joie. La communion, c''est comme une lumière qui éclaire votre chemin, et nous savons que vous allez continuer à grandir dans la foi et l''amour. Que chaque étape de votre vie spirituelle soit aussi belle que ce moment, et que votre engagement envers Dieu soit aussi fort que votre cœur.',true),
('communion','vous','long','Aussi riche que votre amour pour Dieu','La communion, c''est une journée remplie de sens et d''émotion. Aujourd''hui, vous avez choisi de vous engager davantage dans votre foi, et nous espérons que cette étape sera aussi riche que votre amour pour Dieu. Que ce jour reste gravé dans votre cœur comme le début d''une aventure spirituelle aussi inspirante que votre personnalité. Félicitations, et que chaque moment de votre vie soit aussi précieux que cette cérémonie.',true),
('communion','vous','long','Une promesse de grandir dans la foi','Aujourd''hui, vous avez reçu une bénédiction qui vous accompagnera toute votre vie. La communion, c''est comme une promesse : celle de grandir dans la foi, l''espoir et l''amour. Que ce jour soit aussi joyeux que votre sourire, aussi pur que votre cœur, et aussi lumineux que votre engagement spirituel. Félicitations pour cette belle étape, et que votre vie soit aussi merveilleuse que vos rêves.',true),
('communion','vous','long','Aimé, protégé et guidé par Dieu','La communion, c''est bien plus qu''une tradition : c''est un acte d''amour et de foi qui marque une étape importante dans votre vie. Que vous grandissiez avec la certitude d''être aimé, protégé et guidé par Dieu. Félicitations pour ce moment si spécial, et que chaque jour de votre vie soit une nouvelle raison de célébrer la beauté de la foi.',true),
('communion','vous','long','Une graine plantée dans votre cœur','Aujourd''hui, vous avez partagé un moment sacré avec votre communauté, et nous sommes si heureux pour vous. La communion, c''est comme une graine que vous avez plantée dans votre cœur : elle grandira avec la foi, l''espoir et l''amour que vous lui donnerez. Que ce jour soit aussi lumineux que votre amour pour Dieu, et que votre vie spirituelle soit aussi belle que vos rêves.',true),
('communion','vous','long','La mission de continuer à grandir dans la foi','Félicitations pour votre communion ! Que ce jour soit le début d''une aventure remplie de grâce, de joie et de découvertes spirituelles. Vous avez maintenant la mission de continuer à grandir dans la foi, et nous savons que vous serez à la hauteur. Que chaque instant de votre vie spirituelle soit aussi précieux que ce moment, et que votre amour pour Dieu soit aussi fort que votre détermination.',true),
('communion','vous','long','Grandir dans un monde rempli de sens','La communion, c''est un engagement envers la vie, envers l''amour et envers la foi. Aujourd''hui, vous avez montré à quel point votre spiritualité compte pour vous, et à quel point vous voulez grandir dans un monde rempli de sens. Que ce jour soit aussi beau que votre cœur, et que votre vie spirituelle soit aussi riche que votre amour pour Dieu.',true),
('communion','vous','long','Faire partie d''une communauté aimante','Que cette communion soit une source de force et d''inspiration pour vous tout au long de votre vie. Aujourd''hui, vous avez reçu un cadeau précieux : celui de faire partie d''une communauté aimante et bienveillante. Félicitations pour cette belle cérémonie, et que chaque étape de votre vie spirituelle soit aussi lumineuse que ce jour.',true),
('communion','vous','long','Un phare dans la nuit','Aujourd''hui, vous avez reçu une bénédiction qui vous accompagnera à jamais. La communion, c''est comme un phare dans la nuit : elle éclaire votre chemin et vous rappelle que vous n''êtes jamais seul. Que ce jour soit aussi joyeux que votre amour pour Dieu, et que votre vie spirituelle soit aussi belle que vos espérances.',true),
('communion','vous','long','Aussi infini que votre joie aujourd''hui','Félicitations pour ce moment si important dans votre vie spirituelle ! La communion, c''est une célébration de l''amour, de la foi et de l''espoir. Que ce jour reste gravé dans votre cœur comme le début d''une aventure aussi belle que votre engagement envers Dieu. Que chaque instant de votre vie spirituelle soit une nouvelle raison de sourire, et que votre amour pour Lui soit aussi infini que votre joie aujourd''hui.',true);

-- ============================================================
-- DIPLÔME (graduation)
-- ============================================================

-- tu / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('graduation','tu','court','Félicitations pour ton diplôme ! 🎓','Félicitations pour ton diplôme ! 🎓',true),
('graduation','tu','court','Bravo, tu l''as mérité !','Bravo, tu l''as mérité !',true),
('graduation','tu','court','Un pas de plus vers tes rêves','Un pas de plus vers tes rêves. Félicitations !',true),
('graduation','tu','court','Le début d''une belle aventure','Que ce diplôme soit le début d''une belle aventure.',true),
('graduation','tu','court','Tu as réussi !','Tu as réussi ! Félicitations !',true),
('graduation','tu','court','La clé de ton avenir','Le diplôme, c''est la clé de ton avenir. Bravo !',true),
('graduation','tu','court','La première de beaucoup d''autres','Que cette réussite soit la première de beaucoup d''autres.',true),
('graduation','tu','court','Le monde t''attend !','Félicitations, le monde t''attend !',true),
('graduation','tu','court','L''effort récompensé','Un diplôme, c''est l''effort récompensé. Bravo !',true),
('graduation','tu','court','Aussi fier que ton sourire','Que ce jour soit aussi fier que ton sourire.',true);

-- tu / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('graduation','tu','moyen','Aussi passionnant que tes rêves','Félicitations pour ton diplôme ! Que cette réussite soit le début d''une aventure aussi passionnante que tes rêves. Tu as travaillé dur, et aujourd''hui, tu récoltes les fruits de tes efforts.',true),
('graduation','tu','moyen','Tu mérites tout le bonheur du monde','Bravo pour cette belle réussite ! Que ce diplôme soit une porte ouverte vers de nouvelles opportunités et de nouveaux défis. Tu mérites tout le bonheur du monde.',true),
('graduation','tu','moyen','La preuve de ta persévérance','Un diplôme, c''est bien plus qu''un bout de papier : c''est la preuve de ta persévérance, de ton intelligence et de ta détermination. Félicitations !',true),
('graduation','tu','moyen','Le tremplin vers une carrière brillante','Que ce diplôme soit le tremplin vers une carrière aussi brillante que ton avenir. Félicitations pour cette étape importante !',true),
('graduation','tu','moyen','Le travail paie','Tu as montré à tous que le travail paie. Que ce diplôme soit le début d''une vie professionnelle aussi réussie que tes efforts.',true),
('graduation','tu','moyen','Confiance, fierté et opportunités','Félicitations pour ton diplôme ! Que cette réussite t''apporte confiance, fierté et plein de nouvelles opportunités.',true),
('graduation','tu','moyen','Le premier d''une longue série de succès','Aujourd''hui, tu as atteint un objectif important. Que ce diplôme soit le premier d''une longue série de succès.',true),
('graduation','tu','moyen','Une source de motivation','Bravo pour cette belle performance ! Que ce diplôme soit une source de motivation pour la suite de ton parcours.',true),
('graduation','tu','moyen','Ton engagement et ta réussite','Un diplôme, c''est comme une médaille : il symbolise ton engagement et ta réussite. Félicitations pour cette belle étape !',true),
('graduation','tu','moyen','Aussi lumineux que ton avenir','Que ce jour soit aussi lumineux que ton avenir. Félicitations pour ton diplôme !',true);

-- tu / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('graduation','tu','long','La persévérance mène à la réussite','Félicitations pour ton diplôme ! Aujourd''hui, tu as prouvé que la persévérance, le travail et la passion mènent à la réussite. Que ce diplôme soit bien plus qu''un simple bout de papier : qu''il soit le symbole de ton engagement, de ta détermination et de ton intelligence. Tu as surmonté des défis, tu as appris, tu as grandi, et aujourd''hui, tu récoltes les fruits de tes efforts. Que cette réussite soit le début d''une aventure professionnelle aussi passionnante que tes rêves. Nous sommes si fiers de toi, et nous savons que tu vas continuer à briller. Que chaque étape de ta vie soit aussi belle que ce moment, et que ton avenir soit aussi lumineux que ton sourire aujourd''hui.',true),
('graduation','tu','long','Gravir une montagne','Bravo pour cette belle réussite ! Obtenir un diplôme, c''est comme gravir une montagne : ça demande du courage, de la persévérance et une foi inébranlable en soi. Aujourd''hui, tu as atteint le sommet, et la vue est magnifique. Que ce diplôme soit une source de fierté, de confiance et d''inspiration pour la suite de ton parcours. Tu as tout pour réussir, et nous savons que tu vas continuer à te dépasser. Félicitations, et que chaque jour de ta vie professionnelle soit une nouvelle raison de célébrer.',true),
('graduation','tu','long','Des objectifs ambitieux','Un diplôme, c''est bien plus qu''une reconnaissance académique : c''est la preuve que tu es capable de te fixer des objectifs ambitieux et de les atteindre. Aujourd''hui, tu as franchi une étape importante, et nous espérons que ce ne sera que la première d''une longue série. Que ce diplôme soit le tremplin vers une carrière aussi brillante que ton avenir. Félicitations pour cette belle réussite, et que chaque défi que tu relèveras soit aussi gratifiant que ce moment.',true),
('graduation','tu','long','Les fruits de tes efforts','Que ce diplôme soit le début d''une aventure professionnelle aussi passionnante que tes rêves. Tu as travaillé dur, tu as sacrifié du temps, de l''énergie, et aujourd''hui, tu récoltes les fruits de tes efforts. Que cette réussite t''apporte confiance, fierté et plein de nouvelles opportunités. Félicitations pour cette étape importante, et que chaque jour de ta vie soit une nouvelle raison de sourire.',true),
('graduation','tu','long','Tu vas continuer à briller','Aujourd''hui, tu as atteint un objectif qui te rapproche de tes rêves. Que ce diplôme soit le symbole de ta persévérance, de ton intelligence et de ta détermination. Tu as montré à tous que le travail paie, et nous savons que tu vas continuer à briller. Félicitations pour cette belle réussite, et que ton avenir soit aussi lumineux que ton cœur.',true),
('graduation','tu','long','Rien n''est impossible','Félicitations pour ton diplôme ! Tu as prouvé que rien n''est impossible quand on y met tout son cœur. Que ce diplôme soit une source de motivation pour la suite de ton parcours, et que chaque défi que tu relèveras soit aussi gratifiant que cette étape. Nous sommes si fiers de toi, et nous savons que tu vas continuer à réussir. Que chaque instant de ta vie professionnelle soit une nouvelle raison de célébrer.',true),
('graduation','tu','long','Une lumière dans l''obscurité','Obtenir un diplôme, c''est comme allumer une lumière dans l''obscurité : ça éclaire ton chemin et te montre que tout est possible. Aujourd''hui, tu as allumé cette lumière, et nous espérons qu''elle brille de plus en plus fort à chaque étape de ta vie. Félicitations pour cette belle réussite, et que ton avenir soit aussi radieux que ton sourire.',true),
('graduation','tu','long','La persévérance paie','Que ce diplôme soit le début d''une vie professionnelle aussi réussie que tes efforts. Tu as montré à tous que la persévérance paie, et nous savons que tu vas continuer à te dépasser. Félicitations pour cette étape importante, et que chaque jour de ta carrière soit une nouvelle aventure à savourer.',true),
('graduation','tu','long','Aussi lumineux que tes rêves','Aujourd''hui, tu as franchi une étape importante dans ta vie. Que ce diplôme soit le symbole de ton engagement, de ta détermination et de ta passion. Tu as tout pour réussir, et nous savons que tu vas continuer à briller. Félicitations pour cette belle réussite, et que ton avenir soit aussi lumineux que tes rêves.',true),
('graduation','tu','long','Aussi radieux que ton cœur','Bravo pour ton diplôme ! Tu as prouvé que le travail, la persévérance et la passion mènent à la réussite. Que ce diplôme soit une source de fierté, de confiance et d''inspiration pour la suite de ton parcours. Nous sommes si heureux pour toi, et nous savons que tu vas continuer à réussir. Que chaque étape de ta vie professionnelle soit aussi belle que ce moment, et que ton avenir soit aussi radieux que ton cœur.',true);

-- vous / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('graduation','vous','court','Félicitations pour votre diplôme !','Félicitations pour votre diplôme !',true),
('graduation','vous','court','Bravo, vous l''avez mérité','Bravo, vous l''avez mérité.',true),
('graduation','vous','court','Un pas de plus vers vos rêves','Un pas de plus vers vos rêves. Félicitations.',true),
('graduation','vous','court','Le début d''une belle aventure','Que ce diplôme soit le début d''une belle aventure.',true),
('graduation','vous','court','Vous avez réussi !','Vous avez réussi ! Félicitations.',true),
('graduation','vous','court','La clé de votre avenir','Le diplôme, c''est la clé de votre avenir. Bravo.',true),
('graduation','vous','court','La première de beaucoup d''autres','Que cette réussite soit la première de beaucoup d''autres.',true),
('graduation','vous','court','Le monde vous attend','Félicitations, le monde vous attend.',true),
('graduation','vous','court','L''effort récompensé','Un diplôme, c''est l''effort récompensé. Bravo.',true),
('graduation','vous','court','Aussi fier que votre sourire','Que ce jour soit aussi fier que votre sourire.',true);

-- vous / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('graduation','vous','moyen','Aussi passionnant que vos rêves','Félicitations pour votre diplôme ! Que cette réussite soit le début d''une aventure aussi passionnante que vos rêves. Vous avez travaillé dur, et aujourd''hui, vous récoltez les fruits de vos efforts.',true),
('graduation','vous','moyen','Vous méritez tout le bonheur du monde','Bravo pour cette belle réussite ! Que ce diplôme soit une porte ouverte vers de nouvelles opportunités et de nouveaux défis. Vous méritez tout le bonheur du monde.',true),
('graduation','vous','moyen','La preuve de votre persévérance','Un diplôme, c''est bien plus qu''un bout de papier : c''est la preuve de votre persévérance, de votre intelligence et de votre détermination. Félicitations !',true),
('graduation','vous','moyen','Le tremplin vers une carrière brillante','Que ce diplôme soit le tremplin vers une carrière aussi brillante que votre avenir. Félicitations pour cette étape importante !',true),
('graduation','vous','moyen','Le travail paie','Vous avez montré à tous que le travail paie. Que ce diplôme soit le début d''une vie professionnelle aussi réussie que vos efforts.',true),
('graduation','vous','moyen','Confiance, fierté et opportunités','Félicitations pour votre diplôme ! Que cette réussite vous apporte confiance, fierté et plein de nouvelles opportunités.',true),
('graduation','vous','moyen','Le premier d''une longue série de succès','Aujourd''hui, vous avez atteint un objectif important. Que ce diplôme soit le premier d''une longue série de succès.',true),
('graduation','vous','moyen','Une source de motivation','Bravo pour cette belle performance ! Que ce diplôme soit une source de motivation pour la suite de votre parcours.',true),
('graduation','vous','moyen','Votre engagement et votre réussite','Un diplôme, c''est comme une médaille : il symbolise votre engagement et votre réussite. Félicitations pour cette belle étape !',true),
('graduation','vous','moyen','Aussi lumineux que votre avenir','Que ce jour soit aussi lumineux que votre avenir. Félicitations pour votre diplôme !',true);

-- vous / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('graduation','vous','long','La persévérance mène à la réussite','Félicitations pour votre diplôme ! Aujourd''hui, vous avez prouvé que la persévérance, le travail et la passion mènent à la réussite. Que ce diplôme soit bien plus qu''un simple bout de papier : qu''il soit le symbole de votre engagement, de votre détermination et de votre intelligence. Vous avez surmonté des défis, vous avez appris, vous avez grandi, et aujourd''hui, vous récoltez les fruits de vos efforts. Que cette réussite soit le début d''une aventure professionnelle aussi passionnante que vos rêves. Nous sommes si fiers de vous, et nous savons que vous allez continuer à briller. Que chaque étape de votre vie soit aussi belle que ce moment, et que votre avenir soit aussi lumineux que votre sourire aujourd''hui.',true),
('graduation','vous','long','Gravir une montagne','Bravo pour cette belle réussite ! Obtenir un diplôme, c''est comme gravir une montagne : ça demande du courage, de la persévérance et une foi inébranlable en soi. Aujourd''hui, vous avez atteint le sommet, et la vue est magnifique. Que ce diplôme soit une source de fierté, de confiance et d''inspiration pour la suite de votre parcours. Vous avez tout pour réussir, et nous savons que vous allez continuer à vous dépasser. Félicitations, et que chaque jour de votre vie professionnelle soit une nouvelle raison de célébrer.',true),
('graduation','vous','long','Des objectifs ambitieux','Un diplôme, c''est bien plus qu''une reconnaissance académique : c''est la preuve que vous êtes capable de vous fixer des objectifs ambitieux et de les atteindre. Aujourd''hui, vous avez franchi une étape importante, et nous espérons que ce ne sera que la première d''une longue série. Que ce diplôme soit le tremplin vers une carrière aussi brillante que votre avenir. Félicitations pour cette belle réussite, et que chaque défi que vous relèverez soit aussi gratifiant que ce moment.',true),
('graduation','vous','long','Les fruits de vos efforts','Que ce diplôme soit le début d''une aventure professionnelle aussi passionnante que vos rêves. Vous avez travaillé dur, vous avez sacrifié du temps, de l''énergie, et aujourd''hui, vous récoltez les fruits de vos efforts. Que cette réussite vous apporte confiance, fierté et plein de nouvelles opportunités. Félicitations pour cette étape importante, et que chaque jour de votre vie soit une nouvelle raison de sourire.',true),
('graduation','vous','long','Vous allez continuer à briller','Aujourd''hui, vous avez atteint un objectif qui vous rapproche de vos rêves. Que ce diplôme soit le symbole de votre persévérance, de votre intelligence et de votre détermination. Vous avez montré à tous que le travail paie, et nous savons que vous allez continuer à briller. Félicitations pour cette belle réussite, et que votre avenir soit aussi lumineux que votre cœur.',true),
('graduation','vous','long','Rien n''est impossible','Félicitations pour votre diplôme ! Vous avez prouvé que rien n''est impossible quand on y met tout son cœur. Que ce diplôme soit une source de motivation pour la suite de votre parcours, et que chaque défi que vous relèverez soit aussi gratifiant que cette étape. Nous sommes si fiers de vous, et nous savons que vous allez continuer à réussir. Que chaque instant de votre vie professionnelle soit une nouvelle raison de célébrer.',true),
('graduation','vous','long','Une lumière dans l''obscurité','Obtenir un diplôme, c''est comme allumer une lumière dans l''obscurité : ça éclaire votre chemin et vous montre que tout est possible. Aujourd''hui, vous avez allumé cette lumière, et nous espérons qu''elle brille de plus en plus fort à chaque étape de votre vie. Félicitations pour cette belle réussite, et que votre avenir soit aussi radieux que votre sourire.',true),
('graduation','vous','long','La persévérance paie','Que ce diplôme soit le début d''une vie professionnelle aussi réussie que vos efforts. Vous avez montré à tous que la persévérance paie, et nous savons que vous allez continuer à vous dépasser. Félicitations pour cette étape importante, et que chaque jour de votre carrière soit une nouvelle aventure à savourer.',true),
('graduation','vous','long','Aussi lumineux que vos rêves','Aujourd''hui, vous avez franchi une étape importante dans votre vie. Que ce diplôme soit le symbole de votre engagement, de votre détermination et de votre passion. Vous avez tout pour réussir, et nous savons que vous allez continuer à briller. Félicitations pour cette belle réussite, et que votre avenir soit aussi lumineux que vos rêves.',true),
('graduation','vous','long','Aussi radieux que votre cœur','Bravo pour votre diplôme ! Vous avez prouvé que le travail, la persévérance et la passion mènent à la réussite. Que ce diplôme soit une source de fierté, de confiance et d''inspiration pour la suite de votre parcours. Nous sommes si heureux pour vous, et nous savons que vous allez continuer à réussir. Que chaque étape de votre vie professionnelle soit aussi belle que ce moment, et que votre avenir soit aussi radieux que votre cœur.',true);

-- ============================================================
-- PROMOTION
-- ============================================================

-- tu / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('promotion','tu','court','Félicitations pour ta promotion ! 🎉','Félicitations pour ta promotion ! 🎉',true),
('promotion','tu','court','Bravo, tu l''as méritée !','Bravo, tu l''as méritée !',true),
('promotion','tu','court','Une nouvelle étape, un nouveau défi','Une nouvelle étape, un nouveau défi. Félicitations !',true),
('promotion','tu','court','Le début d''une belle aventure','Que cette promotion soit le début d''une belle aventure.',true),
('promotion','tu','court','Tu as gravi un échelon !','Tu as gravi un échelon. Bravo !',true),
('promotion','tu','court','La reconnaissance de ton travail','La promotion, c''est la reconnaissance de ton travail. Félicitations !',true),
('promotion','tu','court','La première de beaucoup d''autres','Que cette réussite soit la première de beaucoup d''autres.',true),
('promotion','tu','court','Le succès te sourit !','Félicitations, le succès te sourit !',true),
('promotion','tu','court','Un pas en avant dans ta carrière','Un pas en avant dans ta carrière. Bravo !',true),
('promotion','tu','court','Aussi fier que ton sourire','Que ce jour soit aussi fier que ton sourire.',true);

-- tu / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('promotion','tu','moyen','Aussi passionnant que tes rêves','Félicitations pour ta promotion ! Que cette nouvelle étape soit aussi passionnante que tes rêves. Tu as travaillé dur, et aujourd''hui, tu récoltes les fruits de tes efforts.',true),
('promotion','tu','moyen','Tu mérites tout le bonheur du monde','Bravo pour cette belle réussite ! Que cette promotion soit une porte ouverte vers de nouvelles opportunités et de nouveaux défis. Tu mérites tout le bonheur du monde.',true),
('promotion','tu','moyen','La preuve de ta persévérance','Une promotion, c''est bien plus qu''un simple changement de poste : c''est la preuve de ta persévérance, de ton intelligence et de ta détermination. Félicitations !',true),
('promotion','tu','moyen','Le tremplin vers une carrière brillante','Que cette promotion soit le tremplin vers une carrière aussi brillante que ton avenir. Félicitations pour cette étape importante !',true),
('promotion','tu','moyen','Le travail paie','Tu as montré à tous que le travail paie. Que cette promotion soit le début d''une vie professionnelle aussi réussie que tes efforts.',true),
('promotion','tu','moyen','Confiance, fierté et opportunités','Félicitations pour ta promotion ! Que cette réussite t''apporte confiance, fierté et plein de nouvelles opportunités.',true),
('promotion','tu','moyen','Le premier d''une longue série de succès','Aujourd''hui, tu as atteint un objectif important. Que cette promotion soit le premier d''une longue série de succès.',true),
('promotion','tu','moyen','Une source de motivation','Bravo pour cette belle performance ! Que cette promotion soit une source de motivation pour la suite de ton parcours.',true),
('promotion','tu','moyen','Ton engagement et ta réussite','Une promotion, c''est comme une médaille : elle symbolise ton engagement et ta réussite. Félicitations pour cette belle étape !',true),
('promotion','tu','moyen','Aussi lumineux que ton avenir','Que ce jour soit aussi lumineux que ton avenir. Félicitations pour ta promotion !',true);

-- tu / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('promotion','tu','long','La persévérance mène à la réussite','Félicitations pour ta promotion ! Aujourd''hui, tu as prouvé que la persévérance, le travail et la passion mènent à la réussite. Que cette promotion soit bien plus qu''un simple changement de poste : qu''elle soit le symbole de ton engagement, de ta détermination et de ton intelligence. Tu as surmonté des défis, tu as appris, tu as grandi, et aujourd''hui, tu récoltes les fruits de tes efforts. Que cette réussite soit le début d''une aventure professionnelle aussi passionnante que tes rêves. Nous sommes si fiers de toi, et nous savons que tu vas continuer à briller. Que chaque étape de ta carrière soit aussi belle que ce moment, et que ton avenir soit aussi lumineux que ton sourire aujourd''hui.',true),
('promotion','tu','long','Gravir un nouveau sommet','Bravo pour cette belle réussite ! Obtenir une promotion, c''est comme gravir une montagne : ça demande du courage, de la persévérance et une foi inébranlable en soi. Aujourd''hui, tu as atteint un nouveau sommet, et la vue est magnifique. Que cette promotion soit une source de fierté, de confiance et d''inspiration pour la suite de ton parcours. Tu as tout pour réussir, et nous savons que tu vas continuer à te dépasser. Félicitations, et que chaque jour de ta vie professionnelle soit une nouvelle raison de célébrer.',true),
('promotion','tu','long','Des objectifs ambitieux','Une promotion, c''est bien plus qu''une reconnaissance professionnelle : c''est la preuve que tu es capable de te fixer des objectifs ambitieux et de les atteindre. Aujourd''hui, tu as franchi une étape importante, et nous espérons que ce ne sera que la première d''une longue série. Que cette promotion soit le tremplin vers une carrière aussi brillante que ton avenir. Félicitations pour cette belle réussite, et que chaque défi que tu relèveras soit aussi gratifiant que ce moment.',true),
('promotion','tu','long','Les fruits de tes efforts','Que cette promotion soit le début d''une aventure professionnelle aussi passionnante que tes rêves. Tu as travaillé dur, tu as sacrifié du temps, de l''énergie, et aujourd''hui, tu récoltes les fruits de tes efforts. Que cette réussite t''apporte confiance, fierté et plein de nouvelles opportunités. Félicitations pour cette étape importante, et que chaque jour de ta vie soit une nouvelle raison de sourire.',true),
('promotion','tu','long','Tu vas continuer à briller','Aujourd''hui, tu as atteint un objectif qui te rapproche de tes rêves. Que cette promotion soit le symbole de ta persévérance, de ton intelligence et de ta détermination. Tu as montré à tous que le travail paie, et nous savons que tu vas continuer à briller. Félicitations pour cette belle réussite, et que ton avenir soit aussi lumineux que ton cœur.',true),
('promotion','tu','long','Rien n''est impossible','Félicitations pour ta promotion ! Tu as prouvé que rien n''est impossible quand on y met tout son cœur. Que cette promotion soit une source de motivation pour la suite de ton parcours, et que chaque défi que tu relèveras soit aussi gratifiant que cette étape. Nous sommes si fiers de toi, et nous savons que tu vas continuer à réussir. Que chaque instant de ta vie professionnelle soit une nouvelle raison de célébrer.',true),
('promotion','tu','long','Une lumière dans l''obscurité','Obtenir une promotion, c''est comme allumer une lumière dans l''obscurité : ça éclaire ton chemin et te montre que tout est possible. Aujourd''hui, tu as allumé cette lumière, et nous espérons qu''elle brille de plus en plus fort à chaque étape de ta vie. Félicitations pour cette belle réussite, et que ton avenir soit aussi radieux que ton sourire.',true),
('promotion','tu','long','La persévérance paie','Que cette promotion soit le début d''une vie professionnelle aussi réussie que tes efforts. Tu as montré à tous que la persévérance paie, et nous savons que tu vas continuer à te dépasser. Félicitations pour cette étape importante, et que chaque jour de ta carrière soit une nouvelle aventure à savourer.',true),
('promotion','tu','long','Aussi lumineux que tes rêves','Aujourd''hui, tu as franchi une étape importante dans ta vie. Que cette promotion soit le symbole de ton engagement, de ta détermination et de ta passion. Tu as tout pour réussir, et nous savons que tu vas continuer à briller. Félicitations pour cette belle réussite, et que ton avenir soit aussi lumineux que tes rêves.',true),
('promotion','tu','long','Aussi radieux que ton cœur','Bravo pour ta promotion ! Tu as prouvé que le travail, la persévérance et la passion mènent à la réussite. Que cette promotion soit une source de fierté, de confiance et d''inspiration pour la suite de ton parcours. Nous sommes si heureux pour toi, et nous savons que tu vas continuer à réussir. Que chaque étape de ta vie professionnelle soit aussi belle que ce moment, et que ton avenir soit aussi radieux que ton cœur.',true);

-- vous / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('promotion','vous','court','Félicitations pour votre promotion !','Félicitations pour votre promotion !',true),
('promotion','vous','court','Bravo, vous l''avez méritée','Bravo, vous l''avez méritée.',true),
('promotion','vous','court','Une nouvelle étape, un nouveau défi','Une nouvelle étape, un nouveau défi. Félicitations.',true),
('promotion','vous','court','Le début d''une belle aventure','Que cette promotion soit le début d''une belle aventure.',true),
('promotion','vous','court','Vous avez gravi un échelon','Vous avez gravi un échelon. Bravo.',true),
('promotion','vous','court','La reconnaissance de votre travail','La promotion, c''est la reconnaissance de votre travail. Félicitations.',true),
('promotion','vous','court','La première de beaucoup d''autres','Que cette réussite soit la première de beaucoup d''autres.',true),
('promotion','vous','court','Le succès vous sourit','Félicitations, le succès vous sourit.',true),
('promotion','vous','court','Un pas en avant dans votre carrière','Un pas en avant dans votre carrière. Bravo.',true),
('promotion','vous','court','Aussi fier que votre sourire','Que ce jour soit aussi fier que votre sourire.',true);

-- vous / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('promotion','vous','moyen','Aussi passionnant que vos rêves','Félicitations pour votre promotion ! Que cette nouvelle étape soit aussi passionnante que vos rêves. Vous avez travaillé dur, et aujourd''hui, vous récoltez les fruits de vos efforts.',true),
('promotion','vous','moyen','Vous méritez tout le bonheur du monde','Bravo pour cette belle réussite ! Que cette promotion soit une porte ouverte vers de nouvelles opportunités et de nouveaux défis. Vous méritez tout le bonheur du monde.',true),
('promotion','vous','moyen','La preuve de votre persévérance','Une promotion, c''est bien plus qu''un simple changement de poste : c''est la preuve de votre persévérance, de votre intelligence et de votre détermination. Félicitations !',true),
('promotion','vous','moyen','Le tremplin vers une carrière brillante','Que cette promotion soit le tremplin vers une carrière aussi brillante que votre avenir. Félicitations pour cette étape importante !',true),
('promotion','vous','moyen','Le travail paie','Vous avez montré à tous que le travail paie. Que cette promotion soit le début d''une vie professionnelle aussi réussie que vos efforts.',true),
('promotion','vous','moyen','Confiance, fierté et opportunités','Félicitations pour votre promotion ! Que cette réussite vous apporte confiance, fierté et plein de nouvelles opportunités.',true),
('promotion','vous','moyen','Le premier d''une longue série de succès','Aujourd''hui, vous avez atteint un objectif important. Que cette promotion soit le premier d''une longue série de succès.',true),
('promotion','vous','moyen','Une source de motivation','Bravo pour cette belle performance ! Que cette promotion soit une source de motivation pour la suite de votre parcours.',true),
('promotion','vous','moyen','Votre engagement et votre réussite','Une promotion, c''est comme une médaille : elle symbolise votre engagement et votre réussite. Félicitations pour cette belle étape !',true),
('promotion','vous','moyen','Aussi lumineux que votre avenir','Que ce jour soit aussi lumineux que votre avenir. Félicitations pour votre promotion !',true);

-- vous / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('promotion','vous','long','La persévérance mène à la réussite','Félicitations pour votre promotion ! Aujourd''hui, vous avez prouvé que la persévérance, le travail et la passion mènent à la réussite. Que cette promotion soit bien plus qu''un simple changement de poste : qu''elle soit le symbole de votre engagement, de votre détermination et de votre intelligence. Vous avez surmonté des défis, vous avez appris, vous avez grandi, et aujourd''hui, vous récoltez les fruits de vos efforts. Que cette réussite soit le début d''une aventure professionnelle aussi passionnante que vos rêves. Nous sommes si fiers de vous, et nous savons que vous allez continuer à briller. Que chaque étape de votre carrière soit aussi belle que ce moment, et que votre avenir soit aussi lumineux que votre sourire aujourd''hui.',true),
('promotion','vous','long','Gravir un nouveau sommet','Bravo pour cette belle réussite ! Obtenir une promotion, c''est comme gravir une montagne : ça demande du courage, de la persévérance et une foi inébranlable en soi. Aujourd''hui, vous avez atteint un nouveau sommet, et la vue est magnifique. Que cette promotion soit une source de fierté, de confiance et d''inspiration pour la suite de votre parcours. Vous avez tout pour réussir, et nous savons que vous allez continuer à vous dépasser. Félicitations, et que chaque jour de votre vie professionnelle soit une nouvelle raison de célébrer.',true),
('promotion','vous','long','Des objectifs ambitieux','Une promotion, c''est bien plus qu''une reconnaissance professionnelle : c''est la preuve que vous êtes capable de vous fixer des objectifs ambitieux et de les atteindre. Aujourd''hui, vous avez franchi une étape importante, et nous espérons que ce ne sera que la première d''une longue série. Que cette promotion soit le tremplin vers une carrière aussi brillante que votre avenir. Félicitations pour cette belle réussite, et que chaque défi que vous relèverez soit aussi gratifiant que ce moment.',true),
('promotion','vous','long','Les fruits de vos efforts','Que cette promotion soit le début d''une aventure professionnelle aussi passionnante que vos rêves. Vous avez travaillé dur, vous avez sacrifié du temps, de l''énergie, et aujourd''hui, vous récoltez les fruits de vos efforts. Que cette réussite vous apporte confiance, fierté et plein de nouvelles opportunités. Félicitations pour cette étape importante, et que chaque jour de votre vie soit une nouvelle raison de sourire.',true),
('promotion','vous','long','Vous allez continuer à briller','Aujourd''hui, vous avez atteint un objectif qui vous rapproche de vos rêves. Que cette promotion soit le symbole de votre persévérance, de votre intelligence et de votre détermination. Vous avez montré à tous que le travail paie, et nous savons que vous allez continuer à briller. Félicitations pour cette belle réussite, et que votre avenir soit aussi lumineux que votre cœur.',true),
('promotion','vous','long','Rien n''est impossible','Félicitations pour votre promotion ! Vous avez prouvé que rien n''est impossible quand on y met tout son cœur. Que cette promotion soit une source de motivation pour la suite de votre parcours, et que chaque défi que vous relèverez soit aussi gratifiant que cette étape. Nous sommes si fiers de vous, et nous savons que vous allez continuer à réussir. Que chaque instant de votre vie professionnelle soit une nouvelle raison de célébrer.',true),
('promotion','vous','long','Une lumière dans l''obscurité','Obtenir une promotion, c''est comme allumer une lumière dans l''obscurité : ça éclaire votre chemin et vous montre que tout est possible. Aujourd''hui, vous avez allumé cette lumière, et nous espérons qu''elle brille de plus en plus fort à chaque étape de votre vie. Félicitations pour cette belle réussite, et que votre avenir soit aussi radieux que votre sourire.',true),
('promotion','vous','long','La persévérance paie','Que cette promotion soit le début d''une vie professionnelle aussi réussie que vos efforts. Vous avez montré à tous que la persévérance paie, et nous savons que vous allez continuer à vous dépasser. Félicitations pour cette étape importante, et que chaque jour de votre carrière soit une nouvelle aventure à savourer.',true),
('promotion','vous','long','Aussi lumineux que vos rêves','Aujourd''hui, vous avez franchi une étape importante dans votre vie. Que cette promotion soit le symbole de votre engagement, de votre détermination et de votre passion. Vous avez tout pour réussir, et nous savons que vous allez continuer à briller. Félicitations pour cette belle réussite, et que votre avenir soit aussi lumineux que vos rêves.',true),
('promotion','vous','long','Aussi radieux que votre cœur','Bravo pour votre promotion ! Vous avez prouvé que le travail, la persévérance et la passion mènent à la réussite. Que cette promotion soit une source de fierté, de confiance et d''inspiration pour la suite de votre parcours. Nous sommes si heureux pour vous, et nous savons que vous allez continuer à réussir. Que chaque étape de votre vie professionnelle soit aussi belle que ce moment, et que votre avenir soit aussi radieux que votre cœur.',true);
