-- Migration 058 : Halloween — 60 messages haute qualité avec {annee}
-- Remplace les templates de base de la migration 049

DELETE FROM message_templates WHERE occasion = 'halloween' AND is_system = true;

-- tu / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('halloween','tu','court','Joyeux Halloween {annee} ! 🎃','Joyeux Halloween {annee} ! 🎃',true),
('halloween','tu','court','Aussi effrayante que ton rire !','Que cette Halloween {annee} soit aussi effrayante que ton rire !',true),
('halloween','tu','court','Rempli de frissons et de bonbons','Passe un Halloween {annee} rempli de frissons et de bonbons.',true),
('halloween','tu','court','Une Halloween inoubliable','Que {annee} t''apporte une Halloween inoubliable.',true),
('halloween','tu','court','Se faire peur… et s''amuser !','Halloween {annee} : l''occasion de se faire peur… et de s''amuser !',true),
('halloween','tu','court','Aussi magique que ton déguisement','Que cette Halloween {annee} soit aussi magique que ton déguisement.',true),
('halloween','tu','court','Que les fantômes te sourient','Joyeux Halloween {annee} ! Que les fantômes te sourient.',true),
('halloween','tu','court','Un jour pour jouer avec la peur','Halloween {annee} : un jour pour jouer avec la peur.',true),
('halloween','tu','court','Rempli de surprises','Que {annee} soit un Halloween rempli de surprises.',true),
('halloween','tu','court','Douce… ou effrayante !','Joyeux Halloween {annee} ! Que la nuit soit douce… ou effrayante !',true);

-- tu / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('halloween','tu','moyen','Aussi effrayant que ton déguisement','Joyeux Halloween {annee} ! Que cette soirée soit remplie de frissons, de rires et de bonbons. Que chaque moment soit aussi effrayant que ton déguisement et aussi amusant que ton sourire.',true),
('halloween','tu','moyen','Autant de surprises que de bonbons','Que cette Halloween {annee} t''apporte autant de surprises que de bonbons dans ton sac. Que chaque instant soit aussi magique que la nuit du 31 octobre.',true),
('halloween','tu','moyen','S''amuser sans limites','Halloween {annee}, c''est l''occasion de jouer avec la peur et de s''amuser sans limites. Que cette soirée soit aussi inoubliable que tes rires.',true),
('halloween','tu','moyen','Effrayant… mais toujours amusant','Que cette Halloween {annee} soit remplie de magie, de mystère et de moments effrayants… mais toujours amusants. Que chaque frisson soit aussi doux que ton cœur.',true),
('halloween','tu','moyen','Aussi lumineuse que les citrouilles','Joyeux Halloween {annee} ! Que cette nuit soit aussi lumineuse que les citrouilles et aussi effrayante que les histoires que tu racontes.',true),
('halloween','tu','moyen','Se déguiser, rire et se faire peur','Halloween {annee}, c''est le moment de se déguiser, de rire et de se faire peur. Que chaque instant soit une nouvelle aventure à vivre.',true),
('halloween','tu','moyen','Aussi précieux que ton sourire','Que cette Halloween {annee} soit une source de joie, de surprises et de bonbons. Que chaque moment soit aussi précieux que ton sourire.',true),
('halloween','tu','moyen','Aussi mystérieuse que la lune','Joyeux Halloween {annee} ! Que cette soirée soit aussi mystérieuse que la lune et aussi joyeuse que tes rires.',true),
('halloween','tu','moyen','Les bonbons aussi !','Halloween {annee} : un jour pour célébrer la peur… et les bonbons ! Que chaque instant soit aussi amusant que toi.',true),
('halloween','tu','moyen','Aussi spécial que cette nuit','Que {annee} soit un Halloween rempli de magie, de frissons et de souvenirs inoubliables. Que chaque moment soit aussi spécial que cette nuit.',true);

-- tu / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('halloween','tu','long','La magie de la nuit et les frissons','Joyeux Halloween {annee} ! Aujourd''hui, c''est le moment de célébrer la magie de la nuit, les frissons des histoires effrayantes et la joie des bonbons. Que cette soirée soit aussi inoubliable que ton sourire, aussi mystérieuse que ton déguisement, et aussi amusante que tes rires. Que chaque instant passé avec ceux que tu aimes soit une nouvelle raison de croire en la magie d''Halloween. Que {annee} t''apporte tout ce que tu désires : des frissons, des rires et des souvenirs précieux. Que chaque moment soit aussi spécial que cette nuit unique, et que chaque bonbon soit aussi doux que ton cœur.',true),
('halloween','tu','long','Le symbole de tout ce qui rend cette fête magique','Que cette Halloween {annee} soit bien plus qu''une simple soirée : qu''elle soit le symbole de tout ce qui rend cette fête magique. Que chaque moment soit rempli de surprises, de frissons et de joie. Que cette nuit te rappelle à quel point il est amusant de jouer avec la peur, et que chaque instant soit aussi précieux que les bonbons que tu récoltes. Joyeux Halloween, et que cette année soit aussi effrayante et amusante que ton imagination.',true),
('halloween','tu','long','Te déguiser et rire avec ceux que tu aimes','Halloween {annee}, c''est l''occasion de te déguiser, de rire et de te faire peur avec ceux que tu aimes. Que cette soirée soit aussi joyeuse que tes rires, aussi mystérieuse que la nuit, et aussi lumineuse que les citrouilles qui brillent. Que chaque instant soit une nouvelle aventure à vivre, et que chaque frisson soit aussi doux que ton cœur. Joyeux Halloween, et que cette année t''apporte tout ce que tu mérites.',true),
('halloween','tu','long','Tout ce qui rend cette fête unique','Aujourd''hui, c''est Halloween {annee}, et avec elle, l''occasion de célébrer tout ce qui rend cette fête unique. Que cette soirée soit remplie de moments inoubliables, de rires et de surprises. Que chaque instant soit une nouvelle preuve de la magie qui t''entoure. Joyeux Halloween, et que cette année soit aussi exceptionnelle que toi.',true),
('halloween','tu','long','Aussi précieux que l''or','Que cette Halloween {annee} soit le début d''une nuit remplie de joie, de mystère et de bonbons. Que chaque moment passé avec ceux que tu aimes soit aussi précieux que l''or, et que chaque rire soit aussi lumineux que les étoiles. Joyeux Halloween, et que cette fête soit aussi magique que tes rêves.',true),
('halloween','tu','long','Un conte qui prend vie','Halloween {annee}, c''est comme un conte qui prend vie : les déguisements, les bonbons et les frissons. Que cette soirée soit aussi douce que tes rêves, aussi effrayante que les histoires que tu aimes, et aussi joyeuse que tes rires. Que chaque instant soit une nouvelle raison de croire en la magie d''Halloween. Joyeux Halloween, et que cette année t''apporte tout ce que tu désires.',true),
('halloween','tu','long','Remplie de lumière, de mystère et de joie','Que cette Halloween {annee} soit remplie de lumière, de mystère et de joie. Que chaque moment soit une nouvelle aventure à partager avec ceux qui comptent pour toi. Que cette soirée soit aussi belle que ton âme, et que chaque instant soit aussi précieux que ton cœur. Joyeux Halloween !',true),
('halloween','tu','long','Ce qui rend cette nuit spéciale','Aujourd''hui, c''est Halloween {annee}, et c''est l''occasion de célébrer tout ce qui rend cette nuit spéciale. Que cette soirée soit aussi joyeuse que tes rires, aussi mystérieuse que la lune, et aussi douce que tes rêves. Que chaque instant soit une nouvelle raison de sourire, et que cette année soit aussi exceptionnelle que toi.',true),
('halloween','tu','long','Des souvenirs aussi beaux','Que cette Halloween {annee} soit une fête remplie de magie, de frissons et de moments précieux. Que chaque instant soit aussi beau que les souvenirs que tu crées, et que chaque moment soit une nouvelle preuve de la joie qui t''entoure. Joyeux Halloween, et que cette année soit aussi belle que ton cœur.',true),
('halloween','tu','long','La magie de cette nuit','Halloween {annee}, c''est le moment de te retrouver, de partager et de célébrer la magie de cette nuit. Que cette soirée soit aussi chaleureuse que ton cœur, aussi lumineuse que ton sourire, et aussi douce que tes rêves. Que chaque instant soit une nouvelle raison de croire en la beauté de la vie. Joyeux Halloween !',true);

-- vous / court
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('halloween','vous','court','Joyeux Halloween {annee} !','Joyeux Halloween {annee} !',true),
('halloween','vous','court','Aussi effrayante que votre rire !','Que cette Halloween {annee} soit aussi effrayante que votre rire !',true),
('halloween','vous','court','Rempli de frissons et de bonbons','Passez un Halloween {annee} rempli de frissons et de bonbons.',true),
('halloween','vous','court','Une Halloween inoubliable','Que {annee} vous apporte une Halloween inoubliable.',true),
('halloween','vous','court','Se faire peur… et s''amuser !','Halloween {annee} : l''occasion de se faire peur… et de s''amuser !',true),
('halloween','vous','court','Aussi magique que votre déguisement','Que cette Halloween {annee} soit aussi magique que votre déguisement.',true),
('halloween','vous','court','Que les fantômes vous sourient','Joyeux Halloween {annee} ! Que les fantômes vous sourient.',true),
('halloween','vous','court','Un jour pour jouer avec la peur','Halloween {annee} : un jour pour jouer avec la peur.',true),
('halloween','vous','court','Rempli de surprises','Que {annee} soit un Halloween rempli de surprises.',true),
('halloween','vous','court','Douce… ou effrayante !','Joyeux Halloween {annee} ! Que la nuit soit douce… ou effrayante !',true);

-- vous / moyen
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('halloween','vous','moyen','Aussi effrayant que votre déguisement','Joyeux Halloween {annee} ! Que cette soirée soit remplie de frissons, de rires et de bonbons. Que chaque moment soit aussi effrayant que votre déguisement et aussi amusant que votre sourire.',true),
('halloween','vous','moyen','Autant de surprises que de bonbons','Que cette Halloween {annee} vous apporte autant de surprises que de bonbons dans votre sac. Que chaque instant soit aussi magique que la nuit du 31 octobre.',true),
('halloween','vous','moyen','S''amuser sans limites','Halloween {annee}, c''est l''occasion de jouer avec la peur et de vous amuser sans limites. Que cette soirée soit aussi inoubliable que vos rires.',true),
('halloween','vous','moyen','Effrayant… mais toujours amusant','Que cette Halloween {annee} soit remplie de magie, de mystère et de moments effrayants… mais toujours amusants. Que chaque frisson soit aussi doux que votre cœur.',true),
('halloween','vous','moyen','Aussi lumineuse que les citrouilles','Joyeux Halloween {annee} ! Que cette nuit soit aussi lumineuse que les citrouilles et aussi effrayante que les histoires que vous racontez.',true),
('halloween','vous','moyen','Se déguiser, rire et se faire peur','Halloween {annee}, c''est le moment de vous déguiser, de rire et de vous faire peur. Que chaque instant soit une nouvelle aventure à vivre.',true),
('halloween','vous','moyen','Aussi précieux que votre sourire','Que cette Halloween {annee} soit une source de joie, de surprises et de bonbons. Que chaque moment soit aussi précieux que votre sourire.',true),
('halloween','vous','moyen','Aussi mystérieuse que la lune','Joyeux Halloween {annee} ! Que cette soirée soit aussi mystérieuse que la lune et aussi joyeuse que vos rires.',true),
('halloween','vous','moyen','Les bonbons aussi !','Halloween {annee} : un jour pour célébrer la peur… et les bonbons ! Que chaque instant soit aussi amusant que vous.',true),
('halloween','vous','moyen','Aussi spécial que cette nuit','Que {annee} soit un Halloween rempli de magie, de frissons et de souvenirs inoubliables. Que chaque moment soit aussi spécial que cette nuit.',true);

-- vous / long
INSERT INTO message_templates (occasion, ton, longueur, title, content, is_system) VALUES
('halloween','vous','long','La magie de la nuit et les frissons','Joyeux Halloween {annee} ! Aujourd''hui, c''est le moment de célébrer la magie de la nuit, les frissons des histoires effrayantes et la joie des bonbons. Que cette soirée soit aussi inoubliable que votre sourire, aussi mystérieuse que votre déguisement, et aussi amusante que vos rires. Que chaque instant passé avec ceux que vous aimez soit une nouvelle raison de croire en la magie d''Halloween. Que {annee} vous apporte tout ce que vous désirez : des frissons, des rires et des souvenirs précieux. Que chaque moment soit aussi spécial que cette nuit unique, et que chaque bonbon soit aussi doux que votre cœur.',true),
('halloween','vous','long','Le symbole de tout ce qui rend cette fête magique','Que cette Halloween {annee} soit bien plus qu''une simple soirée : qu''elle soit le symbole de tout ce qui rend cette fête magique. Que chaque moment soit rempli de surprises, de frissons et de joie. Que cette nuit vous rappelle à quel point il est amusant de jouer avec la peur, et que chaque instant soit aussi précieux que les bonbons que vous récoltez. Joyeux Halloween, et que cette année soit aussi effrayante et amusante que votre imagination.',true),
('halloween','vous','long','Vous déguiser et rire avec ceux que vous aimez','Halloween {annee}, c''est l''occasion de vous déguiser, de rire et de vous faire peur avec ceux que vous aimez. Que cette soirée soit aussi joyeuse que vos rires, aussi mystérieuse que la nuit, et aussi lumineuse que les citrouilles qui brillent. Que chaque instant soit une nouvelle aventure à vivre, et que chaque frisson soit aussi doux que votre cœur. Joyeux Halloween, et que cette année vous apporte tout ce que vous méritez.',true),
('halloween','vous','long','Tout ce qui rend cette fête unique','Aujourd''hui, c''est Halloween {annee}, et avec elle, l''occasion de célébrer tout ce qui rend cette fête unique. Que cette soirée soit remplie de moments inoubliables, de rires et de surprises. Que chaque instant soit une nouvelle preuve de la magie qui vous entoure. Joyeux Halloween, et que cette année soit aussi exceptionnelle que vous.',true),
('halloween','vous','long','Aussi précieux que l''or','Que cette Halloween {annee} soit le début d''une nuit remplie de joie, de mystère et de bonbons. Que chaque moment passé avec ceux que vous aimez soit aussi précieux que l''or, et que chaque rire soit aussi lumineux que les étoiles. Joyeux Halloween, et que cette fête soit aussi magique que vos rêves.',true),
('halloween','vous','long','Un conte qui prend vie','Halloween {annee}, c''est comme un conte qui prend vie : les déguisements, les bonbons et les frissons. Que cette soirée soit aussi douce que vos rêves, aussi effrayante que les histoires que vous aimez, et aussi joyeuse que vos rires. Que chaque instant soit une nouvelle raison de croire en la magie d''Halloween. Joyeux Halloween, et que cette année vous apporte tout ce que vous désirez.',true),
('halloween','vous','long','Remplie de lumière, de mystère et de joie','Que cette Halloween {annee} soit remplie de lumière, de mystère et de joie. Que chaque moment soit une nouvelle aventure à partager avec ceux qui comptent pour vous. Que cette soirée soit aussi belle que votre âme, et que chaque instant soit aussi précieux que votre cœur. Joyeux Halloween !',true),
('halloween','vous','long','Ce qui rend cette nuit spéciale','Aujourd''hui, c''est Halloween {annee}, et c''est l''occasion de célébrer tout ce qui rend cette nuit spéciale. Que cette soirée soit aussi joyeuse que vos rires, aussi mystérieuse que la lune, et aussi douce que vos rêves. Que chaque instant soit une nouvelle raison de sourire, et que cette année soit aussi exceptionnelle que vous.',true),
('halloween','vous','long','Des souvenirs aussi beaux','Que cette Halloween {annee} soit une fête remplie de magie, de frissons et de moments précieux. Que chaque instant soit aussi beau que les souvenirs que vous créez, et que chaque moment soit une nouvelle preuve de la joie qui vous entoure. Joyeux Halloween, et que cette année soit aussi belle que votre cœur.',true),
('halloween','vous','long','La magie de cette nuit','Halloween {annee}, c''est le moment de vous retrouver, de partager et de célébrer la magie de cette nuit. Que cette soirée soit aussi chaleureuse que votre cœur, aussi lumineuse que votre sourire, et aussi douce que vos rêves. Que chaque instant soit une nouvelle raison de croire en la beauté de la vie. Joyeux Halloween !',true);
